crawlserv++: crawlservpp::Wrapper::TidyDoc Class Reference
crawlservpp::Wrapper::TidyDoc Class Reference
RAII wrapper for documents used by the tidy-html5 API.
#include <TidyDoc.hpp>
Classes
class Exception
Class for tidy-html5 document exceptions.
Construction and Destruction
TidyDoc ()
Constructor creating an empty tidy-html5 document.
virtual ~TidyDoc ()
Destructor releasing the underlying tidy-html5 document.
Getter
std::string getOutput (std::queue< std::string > &warningsTo)
Gets the processed text from the tidy-html5 document.
Setters
void setOption (TidyOptionId option, bool value)
Sets a boolean option.
void setOption (TidyOptionId option, int value)
Sets an integer option.
void setOption (TidyOptionId option, ulong value)
Sets a ulong option.
void setOption (TidyOptionId option, const std::string &value)
Sets a string option.
Parsing and Cleanup
void parse (const std::string &in, std::queue< std::string > &warningsTo)
Parses the given markup.
void cleanAndRepair (std::queue< std::string > &warningsTo)
Cleans and repairs the previously parsed content of the underlying tidy-html5 document.
Copy and Move
The class neither copyable, nor moveable.
TidyDoc (TidyDoc &)=delete
Deleted copy constructor.
TidyDoc & operator= (TidyDoc &)=delete
Deleted copy assignment operator.
TidyDoc (TidyDoc &&)=delete
Deleted move constructor.
TidyDoc & operator= (TidyDoc &&)=delete
Deleted move assignment operator.
Detailed Description
RAII wrapper for documents used by the tidy-html5 API.
Creates a Tidy document on construction and automatically releases it on destruction, avoiding memory leaks.
The class encapsulates functionality to configure the API, to parse, clean and repair markup and to retrieve a stringified copy of the resulting tree inside the underlying document.
At the moment, this class is used exclusively by Parsing::HTML::tidyAndConvert().
For more information about the tidy-html5 API, see its GitHub repository.
Constructor & Destructor Documentation
TidyDoc() [1/3]
crawlservpp::Wrapper::TidyDoc::TidyDoc () inline
Constructor creating an empty tidy-html5 document.
Also sets the internal error buffer of the newly created document.
Exceptions
TidyDoc::Exception if the error buffer could not be set.
References crawlservpp::Wrapper::TidyBuffer::get().
~TidyDoc()
crawlservpp::Wrapper::TidyDoc::~TidyDoc () inline virtual
Destructor releasing the underlying tidy-html5 document.
TidyDoc() [2/3]
crawlservpp::Wrapper::TidyDoc::TidyDoc (TidyDoc &) delete
Deleted copy constructor.
TidyDoc() [3/3]
crawlservpp::Wrapper::TidyDoc::TidyDoc (TidyDoc &&) delete
Deleted move constructor.
Member Function Documentation
cleanAndRepair()
void crawlservpp::Wrapper::TidyDoc::cleanAndRepair (std::queue< std::string > & warningsTo) inline
Cleans and repairs the previously parsed content of the underlying tidy-html5 document.
The parsed content will be cleaned and repaired according to the options that have previously been set by calls to the different setOption() functions.
The result will be stored in the underlying document and can be accessed via the getOutput() function. The raw output from the parsing process will be overwritten.
An exception will only be thrown when a fatal error occured.
Note
If no input has been parsed, the function will have no effect.
Parameters
warningsTo The reference to a queue of strings into which to push errors and warnings that occured while cleaning and repairing.
Exceptions
TidyDoc::Exception if the parsed markup could not be cleaned and repaired.
References crawlservpp::Wrapper::TidyBuffer::clear(), crawlservpp::Wrapper::TidyBuffer::getString(), crawlservpp::Helper::Strings::splitToQueue(), and crawlservpp::Wrapper::TidyBuffer::valid().
Referenced by crawlservpp::Parsing::HTML::tidyAndConvert().
getOutput()
std::string crawlservpp::Wrapper::TidyDoc::getOutput (std::queue< std::string > & warningsTo) inline
Gets the processed text from the tidy-html5 document.
If the buffer received from the underlying document is invalid (or empty), an empty string will be returned.
An exception will only be thrown when a fatal error occured.
Note
All warnings and errors will be discarded once they have been received by calling this function.
Parameters
warningsTo The reference to a queue of strings into which to push errors and warnings that occured while saving the output.
Returns
A copy of the text inside the underlying document.
Exceptions
TidyDoc::Exception if writing to the output buffer failed.
See also
parse, cleanAndRepair
References crawlservpp::Wrapper::TidyBuffer::clear(), crawlservpp::Wrapper::TidyBuffer::empty(), crawlservpp::Wrapper::TidyBuffer::get(), crawlservpp::Wrapper::TidyBuffer::getString(), crawlservpp::Helper::Strings::splitToQueue(), and crawlservpp::Wrapper::TidyBuffer::valid().
Referenced by crawlservpp::Parsing::HTML::tidyAndConvert().
operator=() [1/2]
TidyDoc& crawlservpp::Wrapper::TidyDoc::operator= (TidyDoc &&) delete
Deleted move assignment operator.
operator=() [2/2]
TidyDoc& crawlservpp::Wrapper::TidyDoc::operator= (TidyDoc &) delete
Deleted copy assignment operator.
parse()
void crawlservpp::Wrapper::TidyDoc::parse (const std::string & in, std::queue< std::string > & warningsTo) inline
Parses the given markup.
The given markup will be parsed according to the options that have previously been set by calls to the different setOption() functions.
The underlying API will correct syntax errors while parsing.
The result will be stored in the underlying document for possible further processing and can be accessed via the getOutput() function. Any previous output will be overwritten.
An exception will only be thrown when a fatal error occured.
Note
A string view cannot be used, because the underlying API required a null-terminated string.
Parameters
in A const reference to the string containing the markup to be parsed.
warningsTo The reference to a queue of strings into which to push errors and warnings that occured while parsing the given input.
Exceptions
TidyDoc::Exception if the given markup could not be parsed.
References crawlservpp::Wrapper::TidyBuffer::clear(), crawlservpp::Wrapper::TidyBuffer::getString(), crawlservpp::Helper::Strings::splitToQueue(), and crawlservpp::Wrapper::TidyBuffer::valid().
Referenced by crawlservpp::Parsing::HTML::tidyAndConvert().
setOption() [1/4]
void crawlservpp::Wrapper::TidyDoc::setOption (TidyOptionId option, bool value) inline
Sets a boolean option.
Once successfully set, it will take effect for all subsequent parsing, cleaning and repairing of any given input.
Warning
An invalid option or the wrong type will lead to a failing assertion inside the API, which cannot be catched via exception.
Parameters
option The ID of the option to be set.
value The value which the option will be set to.
Exceptions
TidyDoc::Exception if the option could not be set.
See also
parse, cleanAndRepair, Options Quick Reference
Referenced by crawlservpp::Parsing::HTML::tidyAndConvert().
setOption() [2/4]
void crawlservpp::Wrapper::TidyDoc::setOption (TidyOptionId option, const std::string & value) inline
Sets a string option.
Once successfully set, it will take effect for all subsequent parsing, cleaning and repairing of any given input.
Warning
An invalid option or the wrong type will lead to a failing assertion inside the API, which cannot be catched via exception.
Parameters
option The ID of the option to be set.
value The value which the option will be set to.
Exceptions
TidyDoc::Exception if the option could not be set.
See also
parse, cleanAndRepair, Options Quick Reference
setOption() [3/4]
void crawlservpp::Wrapper::TidyDoc::setOption (TidyOptionId option, int value) inline
Sets an integer option.
Once successfully set, it will take effect for all subsequent parsing, cleaning and repairing of any given input.
Warning
An invalid option or the wrong type will lead to a failing assertion inside the API, which cannot be catched via exception.
Parameters
option The ID of the option to be set.
value The value which the option will be set to.
Exceptions
TidyDoc::Exception if the option could not be set.
See also
parse, cleanAndRepair, Options Quick Reference
setOption() [4/4]
void crawlservpp::Wrapper::TidyDoc::setOption (TidyOptionId option, ulong value) inline
Sets a ulong option.
Once successfully set, it will take effect for all subsequent parsing, cleaning and repairing of any given input.
Warning
An invalid option or the wrong type will lead to a failing assertion inside the API, which cannot be catched via exception.
Parameters
option The ID of the option to be set.
value The value which the option will be set to.
Exceptions
TidyDoc::Exception if the option could not be set.
See also
parse, cleanAndRepair, Options Quick Reference
The documentation for this class was generated from the following file:
Wrapper/TidyDoc.hpp