crawlserv++: crawlservpp::Wrapper::URI Class Reference
crawlservpp::Wrapper::URI Class Reference
RAII wrapper for the RFC 3986 URI structure used by uriparser.
#include <URI.hpp>
Construction and Destruction
URI ()=default
Default constructor.
virtual ~URI ()
Destructor freeing the URI if necessary.
Getters
UriUriA * get () noexcept
Gets a pointer to the underlying URI structure.
const UriUriA * getc () const noexcept
Gets a const pointer to the underlying URI structure.
bool valid () const noexcept
Checks whether the URI is valid.
Creation and Cleanup
void create ()
Creates a new and empty URI.
void clear ()
Frees the current URI.
Copy and Move
The class is not copyable, only moveable.
URI (URI &)=delete
Deleted copy constructor.
URI & operator= (URI &)=delete
Deleted copy assignment operator.
URI (URI &&other)=default
Default move constructor.
URI & operator= (URI &&other)=default
Default move assignment operator.
Detailed Description
RAII wrapper for the RFC 3986 URI structure used by uriparser.
Creates a uriparser structure on request and automatically frees it on destruction, avoiding memory leaks.
At the moment, this class is used exclusively by Parsing::URI.
For more information about the uriparser API, see its GitHub repository.
Constructor & Destructor Documentation
URI() [1/3]
crawlservpp::Wrapper::URI::URI () default
Default constructor.
~URI()
crawlservpp::Wrapper::URI::~URI () inline virtual
Destructor freeing the URI if necessary.
Has no effect if no URI has been created.
References clear().
URI() [2/3]
crawlservpp::Wrapper::URI::URI (URI &) delete
Deleted copy constructor.
URI() [3/3]
crawlservpp::Wrapper::URI::URI (URI && other) default
Default move constructor.
Member Function Documentation
clear()
void crawlservpp::Wrapper::URI::clear () inline
Frees the current URI.
Frees and resets the underlying URI structure.
Has no effect if no URI has been created.
Referenced by create(), crawlservpp::Parsing::URI::parseLink(), and ~URI().
create()
void crawlservpp::Wrapper::URI::create () inline
Creates a new and empty URI.
Frees the underlying URI structure beforehand, if necessary.
References clear().
Referenced by crawlservpp::Parsing::URI::makeAbsolute(), crawlservpp::Parsing::URI::parseLink(), and crawlservpp::Parsing::URI::setCurrentOrigin().
get()
UriUriA * crawlservpp::Wrapper::URI::get () inline noexcept
Gets a pointer to the underlying URI structure.
Returns
Pointer to the underlying URI structure.
Referenced by crawlservpp::Parsing::URI::makeAbsolute(), crawlservpp::Parsing::URI::parseLink(), and crawlservpp::Parsing::URI::setCurrentOrigin().
getc()
const UriUriA * crawlservpp::Wrapper::URI::getc () const inline noexcept
Gets a const pointer to the underlying URI structure.
Returns
Pointer to the underlying URI structure.
Referenced by crawlservpp::Parsing::URI::getSubUri(), crawlservpp::Parsing::URI::isSameDomain(), crawlservpp::Parsing::URI::makeAbsolute(), and crawlservpp::Parsing::URI::parseLink().
operator=() [1/2]
URI& crawlservpp::Wrapper::URI::operator= (URI && other) default
Default move assignment operator.
operator=() [2/2]
URI& crawlservpp::Wrapper::URI::operator= (URI &) delete
Deleted copy assignment operator.
valid()
bool crawlservpp::Wrapper::URI::valid () const inline noexcept
Checks whether the URI is valid.
Returns
True, if the underlying URI structure is valid. False otherwise.
Referenced by crawlservpp::Parsing::URI::getSubUri(), and crawlservpp::Parsing::URI::isSameDomain().
The documentation for this class was generated from the following file:
Wrapper/URI.hpp