crawlserv++: crawlservpp::Main::Database::Transaction Class Reference
crawlservpp::Main::Database::Transaction Class Reference
Wrapper class for in-scope transactions.
#include <Database.hpp>
Construction and Destruction
Transaction (Main::Database &db, const std::string &isolationLevel)
Constructor starting the transaction using the specified isolation level.
Transaction (Main::Database &db)
Constructor starting the transaction using the default isolation level.
virtual ~Transaction ()
Destructor committing the transaction on success.
Setter
void success ()
Sets the state of the transaction to successful.
Copy and Move
The class is neither copyable, nor moveable.
Transaction (Transaction &)=delete
Deleted copy constructor.
Transaction & operator= (Transaction &)=delete
Deleted copy assignment operator.
Transaction (Transaction &&)=delete
Deleted move constructor.
Transaction & operator= (Transaction &&)=delete
Deleted move assignment operator.
Detailed Description
Wrapper class for in-scope transactions.
Constructor & Destructor Documentation
Transaction() [1/4]
crawlservpp::Main::Database::Transaction::Transaction (Main::Database & db, const std::string & isolationLevel) inline
Constructor starting the transaction using the specified isolation level.
Parameters
db Reference to the database connection to be used.
isolationLevel Constant reference to a string containing the isolation level to be used.
References crawlservpp::Main::Database::startTransaction().
Transaction() [2/4]
crawlservpp::Main::Database::Transaction::Transaction (Main::Database & db) inline explicit
Constructor starting the transaction using the default isolation level.
Parameters
db Reference to the database connection to be used.
References crawlservpp::Main::Database::startTransaction().
~Transaction()
virtual crawlservpp::Main::Database::Transaction::~Transaction () inline virtual
Destructor committing the transaction on success.
References crawlservpp::Main::Database::endTransaction().
Transaction() [3/4]
crawlservpp::Main::Database::Transaction::Transaction (Transaction &) delete
Deleted copy constructor.
Transaction() [4/4]
crawlservpp::Main::Database::Transaction::Transaction (Transaction &&) delete
Deleted move constructor.
Member Function Documentation
operator=() [1/2]
Transaction& crawlservpp::Main::Database::Transaction::operator= (Transaction &&) delete
Deleted move assignment operator.
operator=() [2/2]
Transaction& crawlservpp::Main::Database::Transaction::operator= (Transaction &) delete
Deleted copy assignment operator.
success()
void crawlservpp::Main::Database::Transaction::success () inline
Sets the state of the transaction to successful.
The transaction will be committed on destruction.
Referenced by crawlservpp::Main::Database::moveWebsite().
The documentation for this class was generated from the following file:
Main/Database.hpp