crawlserv++: crawlservpp::Main::WebServer Class Reference
crawlservpp::Main::WebServer Class Reference final
Embedded web server class using the mongoose library.
#include <WebServer.hpp>
Classes
class Exception
Class for web server exceptions.
Construction and Destruction
WebServer (std::string_view fileCacheDirectory)
Constructor setting the file cache and initializing the web server.
virtual ~WebServer ()
Destructor freeing the web server.
@name Initialization
void initHTTP (const std::string &port)
Initializes the web server for usage over HTTP.
Setters
void setCORS (const std::string &allowed)
Configures cross-origin resource sharing (CORS).
void setAcceptCallback (AcceptCallback callback)
Sets callback function for accepted connections.
void setRequestCallback (RequestCallback callback)
Sets callback function for HTTP requests.
Networking
void poll (int timeOut)
Polls the web server.
void send (ConnectionPtr connection, uint16_t code, const std::string &type, const std::string &content)
Sends a HTTP reply to a previously established connection.
void sendFile (ConnectionPtr connection, const std::string &fileName, void *data)
Sends a file located in the file cache.
static void sendError (ConnectionPtr connection, const std::string &error)
Sends an internal server error (HTTP code 500) with a custom message and closes the connection.
static void close (ConnectionPtr connection)
Closes a connection immediately.
Static Helper
static std::string getIP (ConnectionPtr connection)
Static helper function retrieving the client IP from a connection.
Copy and Move
The class is neither copyable, nor movable.
WebServer (WebServer &)=delete
Deleted copy constructor.
WebServer & operator= (WebServer &)=delete
Deleted copy assignment operator.
WebServer (WebServer &&)=delete
Deleted move constructor.
WebServer & operator= (WebServer &&)=delete
Deleted move assignment operator.
Detailed Description
Embedded web server class using the mongoose library.
For more information about the mongoose library, see its GitHub repository.
Warning
The web server does one final poll on destruction. When used inside classes, it should therefore declared last, i.e. destroyed first, in case it uses other member data when polled.
Constructor & Destructor Documentation
WebServer() [1/3]
crawlservpp::Main::WebServer::WebServer (std::string_view fileCacheDirectory) explicit
Constructor setting the file cache and initializing the web server.
Parameters
fileCacheDirectory View of the directory in which to temporarily save files uploaded to the server.
~WebServer()
crawlservpp::Main::WebServer::~WebServer () virtual
Destructor freeing the web server.
Warning
The web server does one final poll on destruction. When used inside classes, it should therefore declared last, i.e. destroyed first, in case it uses other member data when polled.
WebServer() [2/3]
crawlservpp::Main::WebServer::WebServer (WebServer &) delete
Deleted copy constructor.
WebServer() [3/3]
crawlservpp::Main::WebServer::WebServer (WebServer &&) delete
Deleted move constructor.
Member Function Documentation
close()
void crawlservpp::Main::WebServer::close (ConnectionPtr connection) static
Closes a connection immediately.
Parameters
connection Pointer to the connection that will closed immediately.
Exceptions
WebServer::Connection if no connection has been specified, i.e. the pointer to the connection is nullptr.
Referenced by sendError().
getIP()
std::string crawlservpp::Main::WebServer::getIP (ConnectionPtr connection) static
Static helper function retrieving the client IP from a connection.
Parameters
connection Pointer to the connection from which to retrieve the IP address of the connected client.
Returns
The IP address of the connected client as string.
Exceptions
WebServer::Connection if no connection has been specified, i.e. the pointer to the connection is nullptr.
initHTTP()
void crawlservpp::Main::WebServer::initHTTP (const std::string & port)
Initializes the web server for usage over HTTP.
Todo:
The HTTPS protocol is not supported yet.
Binds the web server to its port, sets user data and the protocol.
Parameters
port Constant reference to a string containing the port to be used by the web server.
Exceptions
WebServer::Exception if the server could not be bound to the given port.
Referenced by crawlservpp::Main::Server::Server().
operator=() [1/2]
WebServer& crawlservpp::Main::WebServer::operator= (WebServer &&) delete
Deleted move assignment operator.
operator=() [2/2]
WebServer& crawlservpp::Main::WebServer::operator= (WebServer &) delete
Deleted copy assignment operator.
poll()
void crawlservpp::Main::WebServer::poll (int timeOut)
Polls the web server.
Parameters
timeOut The number of milliseconds after which polling the web server times out.
Referenced by crawlservpp::Main::Server::tick().
send()
void crawlservpp::Main::WebServer::send (ConnectionPtr connection, uint16_t code, const std::string & type, const std::string & content)
Sends a HTTP reply to a previously established connection.
Parameters
connection Pointer to the connection which will be used for sending the HTTP reply.
code HTTP status code to be send at the beginning of the response.
type Constant reference to a string containing the content type to be sent.
content Constant reference to a string containing the content to be sent.
Exceptions
WebServer::Connection if no connection has been specified, i.e. the pointer to the connection is nullptr.
sendError()
void crawlservpp::Main::WebServer::sendError (ConnectionPtr connection, const std::string & error) static
Sends an internal server error (HTTP code 500) with a custom message and closes the connection.
Parameters
connection Pointer to the connection which will be used for sending the error and which will closed afterwards.
error Constant reference to a string containing the custom error message sent via the given connection before closing it.
Exceptions
WebServer::Connection if no connection has been specified, i.e. the pointer to the connection is nullptr.
References close().
Referenced by sendFile().
sendFile()
void crawlservpp::Main::WebServer::sendFile (ConnectionPtr connection, const std::string & fileName, void * data)
Sends a file located in the file cache.
The file might be a relative path, but must be located in the file cache. If the path to the file is invalid, an internal server error (HTTP code 500) will be sent instead of the file.
Files can only be sent in response to a HTTP message received by the callback function set via setRequestCallback.
Parameters
connection Pointer to the connection which will be used for sending the file.
fileName Constant reference to a string containing name of the file to be sent.
data Pointer to the HTTP message requesting the file, as retrieved by the callback function set via setRequestCallback.
Exceptions
WebServer::Connection if no connection has been specified, i.e. the pointer to the connection is nullptr.
See also
setRequestCallback
References crawlservpp::Helper::FileSystem::contains(), crawlservpp::Helper::FileSystem::getPathSeparator(), and sendError().
setAcceptCallback()
void crawlservpp::Main::WebServer::setAcceptCallback (AcceptCallback callback)
Sets callback function for accepted connections.
Parameters
callback A callback function that will be called when a connection got accepted.
Referenced by crawlservpp::Main::Server::Server().
setCORS()
void crawlservpp::Main::WebServer::setCORS (const std::string & allowed)
Configures cross-origin resource sharing (CORS).
Parameters
allowed Constant reference to a string containing the origins from which access is allowed via CORS.
Referenced by crawlservpp::Main::Server::Server().
setRequestCallback()
void crawlservpp::Main::WebServer::setRequestCallback (RequestCallback callback)
Sets callback function for HTTP requests.
Parameters
callback A callback function that will be called when a HTTP request has been received.
Referenced by crawlservpp::Main::Server::Server().
The documentation for this class was generated from the following files:
Main/WebServer.hpp
Main/WebServer.cpp