crawlserv++: crawlservpp::Module::Crawler::Thread Class Reference
crawlservpp::Module::Crawler::Thread Class Reference
Crawler thread.
#include <Thread.hpp>
Classes
class Exception
Class for crawler exceptions.
Construction
Thread (Main::Database &dbBase, std::string_view cookieDirectory, const ThreadOptions &threadOptions, const NetworkSettings &networkSettings, const ThreadStatus &threadStatus)
Constructor initializing a previously interrupted crawler thread.
Thread (Main::Database &dbBase, std::string_view cookieDirectory, const ThreadOptions &threadOptions, const NetworkSettings &networkSettings)
Constructor initializing a new crawler thread.
Database Connection
Database database
Database connection for the crawler thread.
Networking
const NetworkSettings networkOptions
Network settings for the crawler thread.
Network::Curl networking
Networking for the crawler thread.
Network::TorControl torControl
TOR control for the crawler thread.
Implemented Thread Functions
void onInit () override
Initializes the crawler.
void onTick () override
Performs a crawler tick.
void onPause () override
Pauses the crawler.
void onUnpause () override
Unpauses the crawler.
void onClear () override
Clears the crawler.
Getters
std::uint64_t getId () const
Gets the ID of the thread.
std::uint64_t getWebsite () const
Gets the ID of the website used by the thread.
std::uint64_t getUrlList () const
Gets the ID of the URL list used by the thread.
std::uint64_t getConfig () const
Gets the ID of the configuration used by the thread.
bool isShutdown () const
Checks whether the thread is shutting down or has shut down.
bool isRunning () const
Checks whether the thread is still supposed to run.
bool isFinished () const
Checks whether the shutdown of the thread has been finished.
bool isPaused () const
Checks whether the thread has been paused.
Thread Control
void end ()
Waits for the thread until shutdown is completed.
Time Travel
void warpTo (std::uint64_t target)
Jumps to the specified target ID ("time travel").
Configuration
std::string websiteNamespace
Namespace of the website used by the thread.
std::string urlListNamespace
Namespace of the URL list used by the thread.
std::string configuration
JSON string of the configuration used by the thread.
Protected Getters
bool isInterrupted () const
Checks whether the thread has been interrupted.
std::string getStatusMessage () const
Gets the current status message.
std::uint64_t getLast () const
Gets the valud of the last ID processed by the thread.
std::int64_t getWarpedOverAndReset ()
Gets the number of IDs that have been jumped over, and resets them.
Protected Setters
void setStatusMessage (const std::string &statusMessage)
Sets the status message of the thread.
void setProgress (float progress)
Sets the progress of the thread.
void setLast (std::uint64_t lastId)
Sets the last ID processed by the thread.
void incrementLast ()
Increments the last ID processed by the thread.
Protected Thread Control
void sleep (std::uint64_t ms) const
Lets the thread sleep for the specified number of milliseconds.
void allowPausing ()
Allows the thread to be paused.
void disallowPausing ()
Disallows the thread to be paused.
void pauseByThread ()
Forces the thread to pause.
Logging
bool isLogLevel (std::uint8_t level) const
Checks whether a certain logging level is enabled.
void log (std::uint8_t level, const std::string &logEntry)
Adds a thread-specific log entry to the database, if the current logging level is high enough.
void log (std::uint8_t level, std::queue< std::string > &logEntries)
Adds multiple thread-specific log entries to the database, if the current logging level is high enough.
Detailed Description
Crawler thread.
Constructor & Destructor Documentation
Thread() [1/2]
crawlservpp::Module::Crawler::Thread::Thread (Main::Database & dbBase, std::string_view cookieDirectory, const ThreadOptions & threadOptions, const NetworkSettings & networkSettings, const ThreadStatus & threadStatus)
Constructor initializing a previously interrupted crawler thread.
Parameters
dbBase Reference to the main database connection.
cookieDirectory View of a string containing the (sub-)directory for storing cookie files.
threadOptions Constant reference to a structure containing the options for the thread.
networkSettings Network settings.
threadStatus Constant reference to a structure containing the last known status of the thread.
Thread() [2/2]
crawlservpp::Module::Crawler::Thread::Thread (Main::Database & dbBase, std::string_view cookieDirectory, const ThreadOptions & threadOptions, const NetworkSettings & networkSettings)
Constructor initializing a new crawler thread.
Member Function Documentation
allowPausing()
void crawlservpp::Module::Thread::allowPausing () protected inherited
Allows the thread to be paused.
Threads are pausable by default. Use this function if pausing has been disallowed via disallowPausing().
Thread-safe: Can be used by both the module and the main thread.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit().
disallowPausing()
void crawlservpp::Module::Thread::disallowPausing () protected inherited
Disallows the thread to be paused.
Thread-safe: Can be used by both the module and the main thread.
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::CorpusGenerator(), crawlservpp::Module::Analyzer::Algo::MarkovText::MarkovText(), and crawlservpp::Module::Analyzer::Algo::MarkovTweet::MarkovTweet().
end()
void crawlservpp::Module::Thread::end () inherited
Waits for the thread until shutdown is completed.
Note
Either stop() or interrupt() must have been called before calling this function.
Warning
May not be used by the thread itself!
References crawlservpp::Main::Database::deleteThread().
getConfig()
std::uint64_t crawlservpp::Module::Thread::getConfig () const inherited
Gets the ID of the configuration used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used configuration in the database.
References crawlservpp::Struct::ThreadOptions::config.
Referenced by crawlservpp::Module::Thread::Thread().
getId()
std::uint64_t crawlservpp::Module::Thread::getId () const inherited
Gets the ID of the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the thread in the database.
getLast()
std::uint64_t crawlservpp::Module::Thread::getLast () const protected inherited
Gets the valud of the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
Returns
The ID last processed by the thread, or zero if no ID has been processed yet.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), and crawlservpp::Module::Extractor::Thread::onTick().
getStatusMessage()
std::string crawlservpp::Module::Thread::getStatusMessage () const protected inherited
Gets the current status message.
Thread-safe: Can be used by both the module and the main thread.
Returns
A copy of the current status message.
Referenced by crawlservpp::Module::Parser::Thread::onClear(), and crawlservpp::Module::Extractor::Thread::onClear().
getUrlList()
std::uint64_t crawlservpp::Module::Thread::getUrlList () const inherited
Gets the ID of the URL list used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used URL list in the database.
References crawlservpp::Struct::ThreadOptions::urlList.
Referenced by crawlservpp::Module::Thread::Thread().
getWarpedOverAndReset()
std::int64_t crawlservpp::Module::Thread::getWarpedOverAndReset () protected inherited
Gets the number of IDs that have been jumped over, and resets them.
Resets the number of IDs jumped over to zero.
Warning
May only be used by the thread itself, not by the main thread!
Returns
The number of IDs that have been jumped over due to a call to warpTo(), or zero if no IDs have been jumped over, at least not since the last call to getWarpedOverAndReset(). The result might be negative, if warpTo() resulted in a jump to a previous ID.
Referenced by crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), and onTick().
getWebsite()
std::uint64_t crawlservpp::Module::Thread::getWebsite () const inherited
Gets the ID of the website used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used website in the database.
References crawlservpp::Struct::ThreadOptions::website.
Referenced by onInit(), and crawlservpp::Module::Thread::Thread().
incrementLast()
void crawlservpp::Module::Thread::incrementLast () protected inherited
Increments the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
See also
setLast, Main::Database::setThreadLast
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadLast().
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick().
isFinished()
bool crawlservpp::Module::Thread::isFinished () const inherited
Checks whether the shutdown of the thread has been finished.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread has been completely shut down. False otherwise.
isInterrupted()
bool crawlservpp::Module::Thread::isInterrupted () const protected inherited
Checks whether the thread has been interrupted.
Thread-safe: Can be used by both the module and the main thread.
Returns
True if the thread has been interrupted. False otherwise.
isLogLevel()
bool crawlservpp::Module::Thread::isLogLevel (std::uint8_t level) const protected inherited
Checks whether a certain logging level is enabled.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
level The logging level to be checked for.
Returns
True, if the current logging level is at least as high as the given level. False, if the current logging level is lower than the given one.
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::isLogLevel().
Referenced by crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), and onTick().
isPaused()
bool crawlservpp::Module::Thread::isPaused () const inherited
Checks whether the thread has been paused.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread has been paused. False otherwise.
isRunning()
bool crawlservpp::Module::Thread::isRunning () const inherited
Checks whether the thread is still supposed to run.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread is has not been cancelled, even when it is paused. False, if the thread is not supposed to run any longer.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and onInit().
isShutdown()
bool crawlservpp::Module::Thread::isShutdown () const inherited
Checks whether the thread is shutting down or has shut down.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread is shutting down or has been shut down. False, if the thread is continuing to run.
See also
Thread::isFinished
log() [1/2]
void crawlservpp::Module::Thread::log (std::uint8_t level, const std::string & logEntry) protected inherited
Adds a thread-specific log entry to the database, if the current logging level is high enough.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entry will be written to the logging file as well.
The log entry will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entry. The entry will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntry Constant reference to a string containing the log entry.
See also
Module::Database::log(std::uint8_t, const std::string&)
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::log().
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::Empty::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onClear(), crawlservpp::Module::Extractor::Thread::onClear(), onClear(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), onInit(), crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), and onTick().
log() [2/2]
void crawlservpp::Module::Thread::log (std::uint8_t level, std::queue< std::string > & logEntries) protected inherited
Adds multiple thread-specific log entries to the database, if the current logging level is high enough.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entries will be written to the logging file as well.
The log entries will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entries. The entries will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntries Reference to a queue of strings containing the log entries to be written. It will be emptied regardless whether the log entries will be written to the database.
See also
Module::Database::log(std::uint8_t, std::queue<std::string>&)
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::log().
onClear()
void crawlservpp::Module::Crawler::Thread::onClear () override protected virtual
Clears the crawler.
Implements crawlservpp::Module::Thread.
References crawlservpp::Query::Container::clearQueries(), crawlservpp::Module::Crawler::crawlerLoggingDefault, crawlservpp::Module::Thread::log(), and crawlservpp::Helper::DateTime::now().
onInit()
void crawlservpp::Module::Crawler::Thread::onInit () override protected virtual
Initializes the crawler.
Exceptions
Module::Crawler::Thread::Exception if no query for link extraction has been specified.
Implements crawlservpp::Module::Thread.
References crawlservpp::Module::Crawler::Config::config, crawlservpp::Module::Crawler::Config::Entries::crawlerArchives, crawlservpp::Module::Crawler::Config::Entries::crawlerLogging, crawlservpp::Module::Crawler::crawlerLoggingDefault, crawlservpp::Module::Crawler::crawlerLoggingExtended, crawlservpp::Module::Crawler::crawlerLoggingVerbose, crawlservpp::Module::Crawler::Config::Entries::crawlerQueriesLinks, crawlservpp::Module::Crawler::Config::Entries::crawlerReCrawl, crawlservpp::Module::Crawler::Config::Entries::crawlerRepairCData, crawlservpp::Module::Crawler::Config::Entries::crawlerRepairComments, crawlservpp::Module::Crawler::Config::Entries::crawlerSleepMySql, crawlservpp::Module::Crawler::Config::Entries::crawlerTidyWarnings, crawlservpp::Module::Crawler::Config::Entries::crawlerUrlCaseSensitive, crawlservpp::Module::Crawler::Config::Entries::crawlerUrlDebug, crawlservpp::Module::Crawler::Config::Entries::crawlerUrlStartupCheck, database, crawlservpp::Wrapper::Database::getConfiguration(), crawlservpp::Module::Thread::getWebsite(), crawlservpp::Wrapper::Database::getWebsiteDomain(), crawlservpp::Wrapper::DatabaseTryLock< DB >::isActive(), crawlservpp::Module::Thread::isRunning(), crawlservpp::Module::Config::loadConfig(), crawlservpp::Module::Thread::log(), networking, networkOptions, crawlservpp::Helper::DateTime::now(), crawlservpp::Module::Crawler::Database::prepare(), crawlservpp::Network::Config::resetTorAfter, crawlservpp::Network::Config::resetTorOnlyAfter, crawlservpp::Network::Curl::setConfigGlobal(), crawlservpp::Module::Crawler::Config::setCrossDomain(), crawlservpp::Wrapper::Database::setLogging(), crawlservpp::Network::TorControl::setNewIdentityMax(), crawlservpp::Network::TorControl::setNewIdentityMin(), crawlservpp::Module::Crawler::Database::setRecrawl(), crawlservpp::Query::Container::setRepairCData(), crawlservpp::Query::Container::setRepairComments(), crawlservpp::Wrapper::Database::setSleepOnError(), crawlservpp::Module::Thread::setStatusMessage(), crawlservpp::Query::Container::setTidyErrorsAndWarnings(), crawlservpp::Module::Crawler::Database::setUrlCaseSensitive(), crawlservpp::Module::Crawler::Database::setUrlDebug(), crawlservpp::Module::Crawler::Database::setUrlStartupCheck(), torControl, crawlservpp::Module::Crawler::Database::urlDuplicationCheck(), crawlservpp::Module::Crawler::Database::urlEmptyCheck(), crawlservpp::Module::Crawler::Database::urlHashCheck(), crawlservpp::Module::Thread::urlListNamespace, crawlservpp::Module::Thread::websiteNamespace, and crawlservpp::Module::Crawler::wwwString.
onPause()
void crawlservpp::Module::Crawler::Thread::onPause () override protected virtual
Pauses the crawler.
Stores the current time for keeping track of the time, the crawler is paused.
Implements crawlservpp::Module::Thread.
References crawlservpp::Helper::DateTime::now().
onTick()
void crawlservpp::Module::Crawler::Thread::onTick () override protected virtual
Performs a crawler tick.
If successful, this will crawl one URL. If not, the URL will either be skipped, or retried in the next tick.
Implements crawlservpp::Module::Thread.
References crawlservpp::Network::TorControl::active(), crawlservpp::Query::Container::clearQueryTarget(), crawlservpp::Module::Crawler::Config::config, crawlservpp::Module::Crawler::Config::Entries::crawlerArchives, crawlservpp::Module::Crawler::crawlerLoggingDefault, crawlservpp::Module::Crawler::crawlerLoggingExtended, crawlservpp::Module::Crawler::Config::Entries::crawlerSleepIdle, crawlservpp::Module::Crawler::Config::Entries::crawlerTiming, database, crawlservpp::Module::Thread::getWarpedOverAndReset(), crawlservpp::Module::Thread::isLogLevel(), crawlservpp::Module::Thread::log(), crawlservpp::Helper::DateTime::now(), crawlservpp::Module::Thread::sleep(), crawlservpp::Timer::StartStop::start(), crawlservpp::Timer::StartStop::stop(), crawlservpp::Network::TorControl::tick(), torControl, crawlservpp::Timer::StartStop::totalStr(), and crawlservpp::Module::Crawler::Database::unLockUrlIfOk().
onUnpause()
void crawlservpp::Module::Crawler::Thread::onUnpause () override protected virtual
Unpauses the crawler.
Calculates the time, the crawler was paused.
Implements crawlservpp::Module::Thread.
References crawlservpp::Helper::DateTime::now().
pauseByThread()
void crawlservpp::Module::Thread::pauseByThread () protected inherited
Forces the thread to pause.
Warning
May only be used by the thread itself, not by the main thread!
References crawlservpp::Module::Thread::database, and crawlservpp::Main::Database::setThreadStatus().
Referenced by crawlservpp::Module::Analyzer::Thread::pause().
setLast()
void crawlservpp::Module::Thread::setLast (std::uint64_t lastId) protected inherited
Sets the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
lastId The last ID processed by the thread.
See also
incrementLast, Main::Database::setThreadLast
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadLast().
setProgress()
void crawlservpp::Module::Thread::setProgress (float progress) protected inherited
Sets the progress of the thread.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
progress The new progress of the thread, between 0.f (0%) and 1.f (100%).
See also
Main::Database::setThreadProgress
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadProgress().
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), and crawlservpp::Module::Extractor::Thread::onTick().
setStatusMessage()
void crawlservpp::Module::Thread::setStatusMessage (const std::string & statusMessage) protected inherited
Sets the status message of the thread.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
statusMessage Constant reference to a string containing the new status message to be set.
See also
Main::Database::setThreadStatus
References crawlservpp::Module::Thread::database, and crawlservpp::Main::Database::setThreadStatus().
Referenced by crawlservpp::Module::Analyzer::Thread::finished(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onClear(), crawlservpp::Module::Extractor::Thread::onClear(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), onInit(), crawlservpp::Module::Parser::Thread::onTick(), and crawlservpp::Module::Extractor::Thread::onTick().
sleep()
void crawlservpp::Module::Thread::sleep (std::uint64_t ms) const protected inherited
Lets the thread sleep for the specified number of milliseconds.
The sleep will be interrupted if the thread is stopped.
Thread-safe: Can be used by both the module and the main thread.
Parameters
ms The number of milliseconds for the thread to sleep, if it is not stopped.
References crawlservpp::Module::sleepMs.
Referenced by crawlservpp::Module::Analyzer::Thread::finished(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), and onTick().
warpTo()
void crawlservpp::Module::Thread::warpTo (std::uint64_t target) inherited
Jumps to the specified target ID ("time travel").
Skips the normal process of determining the next ID once the current ID has been processed.
Thread-safe: Can be used by both the module and the main thread.
Parameters
target The target ID that should be processed next.
Exceptions
Module::Thread::Exception if no target is specified, i.e. the target ID is zero.
See also
getWarpedOverAndReset
Member Data Documentation
configuration
std::string crawlservpp::Module::Thread::configuration protected inherited
JSON string of the configuration used by the thread.
See also
Main::Database::getConfiguration
Referenced by crawlservpp::Module::Thread::Thread().
database
Database crawlservpp::Module::Crawler::Thread::database protected
Database connection for the crawler thread.
Referenced by onInit(), and onTick().
networking
Network::Curl crawlservpp::Module::Crawler::Thread::networking protected
Networking for the crawler thread.
Referenced by onInit().
networkOptions
const NetworkSettings crawlservpp::Module::Crawler::Thread::networkOptions protected
Network settings for the crawler thread.
Referenced by onInit().
torControl
Network::TorControl crawlservpp::Module::Crawler::Thread::torControl protected
TOR control for the crawler thread.
Referenced by onInit(), and onTick().
urlListNamespace
std::string crawlservpp::Module::Thread::urlListNamespace protected inherited
Namespace of the URL list used by the thread.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), onInit(), and crawlservpp::Module::Thread::Thread().
websiteNamespace
std::string crawlservpp::Module::Thread::websiteNamespace protected inherited
Namespace of the website used by the thread.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), onInit(), and crawlservpp::Module::Thread::Thread().
The documentation for this class was generated from the following files:
Module/Crawler/Thread.hpp
Module/Crawler/Thread.cpp