crawlserv++: crawlservpp::Query::Container Class Reference
crawlservpp::Query::Container Class Reference abstract
Query container.
#include <Container.hpp>
Classes
class Exception
Class for query container exceptions.
Construction and Destruction
Container ()=default
Default constructor.
virtual ~Container ()=default
Default destructor.
Copy and move
The class is not copyable, only (default) moveable.
Container (const Container &)=delete
Deleted copy constructor.
Container & operator= (const Container &)=delete
Deleted copy assignment operator.
Container (Container &&)=default
Default move constructor.
Container & operator= (Container &&)=default
Default move assignment operator.
Setters
void setRepairCData (bool isRepairCData)
Sets whether to try to repair CData when parsing XML.
void setRepairComments (bool isRepairComments)
Sets whether to try to repair broken HTML/XML comments.
void setMinimizeMemory (bool isMinimizeMemory)
Sets whether to minimize memory usage.
void setTidyErrorsAndWarnings (bool warnings, std::uint32_t numOfErrors)
Sets how tidy-html5 reports errors and warnings.
void setQueryTarget (const std::string &content, const std::string &source)
Sets the content to use the managed queries on.
Getters
std::size_t getNumberOfSubSets () const
Gets the number of subsets currently acquired.
bool getTarget (std::string &targetTo)
Gets the current query target, if available, and writes it to the given string.
bool getXml (std::string &resultTo, std::queue< std::string > &warningsTo)
Parses the current query target as tidied XML and writes it to the given string.
Initialization
virtual void initQueries ()=0
Pure virtual function initializing queries.
Queries
QueryStruct addQuery (const QueryProperties &properties)
Adds a query with the given query properties to the container.
void clearQueries ()
Clears all queries currently managed by the container and frees the associated memory.
void clearQueryTarget ()
Clears the current query target and frees the associated memory.
Subsets
bool nextSubSet ()
Requests the next subset for all subsequent queries.
Results
bool getBoolFromRegEx (const QueryStruct &query, const std::string &target, bool &resultTo, std::queue< std::string > &warningsTo) const
Gets a boolean result from a RegEx query on a separate string.
bool getSingleFromRegEx (const QueryStruct &query, const std::string &target, std::string &resultTo, std::queue< std::string > &warningsTo) const
Gets a single result from a RegEx query on a separate string.
bool getMultiFromRegEx (const QueryStruct &query, const std::string &target, std::vector< std::string > &resultTo, std::queue< std::string > &warningsTo) const
Gets multiple results from a RegEx query on a separate string.
bool getBoolFromQuery (const QueryStruct &query, bool &resultTo, std::queue< std::string > &warningsTo)
Gets a boolean result from a query of any type on the current query target.
bool getBoolFromQueryOnSubSet (const QueryStruct &query, bool &resultTo, std::queue< std::string > &warningsTo)
Gets a boolean result from a query of any type on the current subset.
bool getSingleFromQuery (const QueryStruct &query, std::string &resultTo, std::queue< std::string > &warningsTo)
Gets a single result from a query of any type on the current query target.
bool getSingleFromQueryOnSubSet (const QueryStruct &query, std::string &resultTo, std::queue< std::string > &warningsTo)
Gets a single result from a query of any type on the current subset.
bool getMultiFromQuery (const QueryStruct &query, std::vector< std::string > &resultTo, std::queue< std::string > &warningsTo)
Gets multiple results from a query of any type on the current query target.
bool getMultiFromQueryOnSubSet (const QueryStruct &query, std::vector< std::string > &resultTo, std::queue< std::string > &warningsTo)
Gets multiple results from a query of any type on the current subset.
bool setSubSetsFromQuery (const QueryStruct &query, std::queue< std::string > &warningsTo)
Sets subsets for subsequent queries using a query of any type.
bool addSubSetsFromQueryOnSubSet (const QueryStruct &query, std::queue< std::string > &warningsTo)
Inserts more subsets after the current one based on a query on the current subset.
Memory
void reserveForSubSets (const QueryStruct &query, std::size_t n)
Reserves memory for a specific number of subsets.
Detailed Description
Query container.
Abstract class to be inherited by module thread classes managing their queries.
Most member functions of the container are protected, as they will only be used from inside its child classes.
Constructor & Destructor Documentation
Container() [1/3]
crawlservpp::Query::Container::Container () default
Default constructor.
~Container()
virtual crawlservpp::Query::Container::~Container () virtual default
Default destructor.
Container() [2/3]
crawlservpp::Query::Container::Container (const Container &) delete
Deleted copy constructor.
Container() [3/3]
crawlservpp::Query::Container::Container (Container &&) default
Default move constructor.
Member Function Documentation
addQuery()
Struct::QueryStruct crawlservpp::Query::Container::addQuery (const QueryProperties & properties) inline protected
Adds a query with the given query properties to the container.
Parameters
properties Constant reference to the properties of the query to add to the container.
Returns
A structure to be used to identify the added query, including the index of the query inside the container.
Exceptions
Container::Exception if an error occured while creating a query with the given properties or the specified type of the query is unknown.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Struct::QueryProperties::resultBool, crawlservpp::Struct::QueryStruct::resultBool, crawlservpp::Struct::QueryProperties::resultMulti, crawlservpp::Struct::QueryStruct::resultMulti, crawlservpp::Struct::QueryProperties::resultSingle, crawlservpp::Struct::QueryStruct::resultSingle, crawlservpp::Struct::QueryProperties::resultSubSets, crawlservpp::Struct::QueryStruct::resultSubSets, crawlservpp::Struct::QueryProperties::text, crawlservpp::Struct::QueryProperties::textOnly, crawlservpp::Struct::QueryProperties::type, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
addSubSetsFromQueryOnSubSet()
bool crawlservpp::Query::Container::addSubSetsFromQueryOnSubSet (const QueryStruct & query, std::queue< std::string > & warningsTo) inline protected
Inserts more subsets after the current one based on a query on the current subset.
This function is used for recursive extracting.
Parameters
query A constant reference to a structure identifying the query that will be performed to acquire the subset.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if new subsets have been added. False, if the execution of the query failed or did not see any results.
Exceptions
Container::Exception if no query target or no subset has been specified, the current subset is invalid, or the given query is of an unknown type.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Helper::Json::parseCons(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::QueryStruct::resultSubSets, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
clearQueries()
void crawlservpp::Query::Container::clearQueries () inline protected
Clears all queries currently managed by the container and frees the associated memory.
Referenced by crawlservpp::Module::Parser::Thread::onClear(), crawlservpp::Module::Extractor::Thread::onClear(), and crawlservpp::Module::Crawler::Thread::onClear().
clearQueryTarget()
void crawlservpp::Query::Container::clearQueryTarget () inline protected
Clears the current query target and frees the associated memory.
References crawlservpp::Parsing::XML::clear().
Referenced by crawlservpp::Module::Crawler::Thread::onTick(), and setQueryTarget().
getBoolFromQuery()
bool crawlservpp::Query::Container::getBoolFromQuery (const QueryStruct & query, bool & resultTo, std::queue< std::string > & warningsTo) inline protected
Gets a boolean result from a query of any type on the current query target.
Parameters
query A constant reference to a structure identifying the query that will be performed.
resultTo A reference to a boolean variable which will be set according to the result of the query.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the execution of the query failed.
Exceptions
Container::Exception if no query target has been specified or the query is of an unknown type.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Helper::Json::parseCons(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::QueryStruct::resultBool, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
getBoolFromQueryOnSubSet()
bool crawlservpp::Query::Container::getBoolFromQueryOnSubSet (const QueryStruct & query, bool & resultTo, std::queue< std::string > & warningsTo) inline protected
Gets a boolean result from a query of any type on the current subset.
Parameters
query A constant reference to a structure identifying the query that will be performed.
resultTo A reference to a boolean variable which will be set according to the result of the query.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the execution of the query failed.
Exceptions
Container::Exception if no query target or no subset has been specified, the current subset is invalid, or the given query is of an unknown type.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Helper::Json::parseCons(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::QueryStruct::resultBool, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
getBoolFromRegEx()
bool crawlservpp::Query::Container::getBoolFromRegEx (const QueryStruct & query, const std::string & target, bool & resultTo, std::queue< std::string > & warningsTo) const inline protected
Gets a boolean result from a RegEx query on a separate string.
Parameters
query A constant reference to a structure identifying the RegEx query that will be performed.
target A constant reference to a string containing the target on which the query will be performed.
resultTo A reference to a boolean variable which will be set according to the result of the query.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the query is of a different type or its execution failed.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Struct::QueryStruct::resultBool, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, and crawlservpp::Main::Exception::view().
getMultiFromQuery()
bool crawlservpp::Query::Container::getMultiFromQuery (const QueryStruct & query, std::vector< std::string > & resultTo, std::queue< std::string > & warningsTo) inline protected
Gets multiple results from a query of any type on the current query target.
Parameters
query A constant reference to a structure identifying the query that will be performed.
resultTo A reference to a vector to which the results of the query will be appended.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the execution of the query failed.
Exceptions
Container::Exception if no query target has been specified or the query is of an unknown type.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Helper::Json::parseCons(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::QueryStruct::resultMulti, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
getMultiFromQueryOnSubSet()
bool crawlservpp::Query::Container::getMultiFromQueryOnSubSet (const QueryStruct & query, std::vector< std::string > & resultTo, std::queue< std::string > & warningsTo) inline protected
Gets multiple results from a query of any type on the current subset.
Parameters
query A constant reference to a structure identifying the query that will be performed.
resultTo A reference to a vector to which the results of the query will be appended.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the execution of the query failed.
Exceptions
Container::Exception if no query target or no subset has been specified, the current subset is invalid, or the given query is of an unknown type.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Helper::Json::parseCons(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::QueryStruct::resultMulti, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
getMultiFromRegEx()
bool crawlservpp::Query::Container::getMultiFromRegEx (const QueryStruct & query, const std::string & target, std::vector< std::string > & resultTo, std::queue< std::string > & warningsTo) const inline protected
Gets multiple results from a RegEx query on a separate string.
Parameters
query A constant reference to a structure identifying the RegEx query that will be performed.
target A constant reference to a string containing the target on which the query will be performed.
resultTo A reference to a vector to which the results of the query will be appended.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the query is of a different type or its execution failed.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Struct::QueryStruct::resultMulti, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, and crawlservpp::Main::Exception::view().
getNumberOfSubSets()
std::size_t crawlservpp::Query::Container::getNumberOfSubSets () const inline protected
Gets the number of subsets currently acquired.
Returns
The number of subsets generated by the last query that generated subsets as its result.
getSingleFromQuery()
bool crawlservpp::Query::Container::getSingleFromQuery (const QueryStruct & query, std::string & resultTo, std::queue< std::string > & warningsTo) inline protected
Gets a single result from a query of any type on the current query target.
Parameters
query A constant reference to a structure identifying the query that will be performed.
resultTo A reference to a string to which the result of the query will be written.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the execution of the query failed.
Exceptions
Container::Exception if no query target has been specified or the query is of an unknown type.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Helper::Json::parseCons(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::QueryStruct::resultSingle, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
getSingleFromQueryOnSubSet()
bool crawlservpp::Query::Container::getSingleFromQueryOnSubSet (const QueryStruct & query, std::string & resultTo, std::queue< std::string > & warningsTo) inline protected
Gets a single result from a query of any type on the current subset.
Parameters
query A constant reference to a structure identifying the query that will be performed.
resultTo A reference to a string to which the result of the query will be written.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the execution of the query failed.
Exceptions
Container::Exception if no query target or no subset has been specified, the current subset is invalid, or the given query is of an unknown type.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Helper::Json::parseCons(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::QueryStruct::resultSingle, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
getSingleFromRegEx()
bool crawlservpp::Query::Container::getSingleFromRegEx (const QueryStruct & query, const std::string & target, std::string & resultTo, std::queue< std::string > & warningsTo) const inline protected
Gets a single result from a RegEx query on a separate string.
Parameters
query A constant reference to a structure identifying the RegEx query that will be performed.
target A constant reference to a string containing the target on which the query will be performed.
resultTo A reference to a string to which the result of the query will be written.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the query is of a different type or its execution failed.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Struct::QueryStruct::resultSingle, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, and crawlservpp::Main::Exception::view().
getTarget()
bool crawlservpp::Query::Container::getTarget (std::string & targetTo) inline protected
Gets the current query target, if available, and writes it to the given string.
Parameters
targetTo Reference to a string the query target will be written to, if one is available. Its content will not be changed if no query target is available.
Returns
True, if a query target was available and has been written to the referenced string. Returns false, if no query target was available and the referenced string has not been changed.
getXml()
bool crawlservpp::Query::Container::getXml (std::string & resultTo, std::queue< std::string > & warningsTo) inline protected
Parses the current query target as tidied XML and writes it to the given string.
Parameters
resultTo Reference to a string the parsed query target will be written to.
warningsTo Reference to a vector of strings to which warnings that occured during parsing will be appended.
Returns
True, if the parsing was successful and the tidied XML was written to the given string. False, if the parsing was not successful and the given string has not been changed.
References crawlservpp::Parsing::XML::getContent().
initQueries()
virtual void crawlservpp::Query::Container::initQueries () protected pure virtual
Pure virtual function initializing queries.
This function needs to be implemented by the child classes of the container, so that children need to initialize their queries on their own.
nextSubSet()
bool crawlservpp::Query::Container::nextSubSet () inline protected
Requests the next subset for all subsequent queries.
Returns
True, if another subset existed that will be used by subsequent queries. False, if no more subsets exist.
Exceptions
Container::Exception if an invalid subset had previously been selected.
References crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, and crawlservpp::Struct::QueryStruct::typeXPath.
operator=() [1/2]
Container& crawlservpp::Query::Container::operator= (const Container &) delete
Deleted copy assignment operator.
operator=() [2/2]
Container& crawlservpp::Query::Container::operator= (Container &&) default
Default move assignment operator.
reserveForSubSets()
void crawlservpp::Query::Container::reserveForSubSets (const QueryStruct & query, std::size_t n) inline protected
Reserves memory for a specific number of subsets.
Parameters
query A constant reference to a structure identifying the query for whose type memory will be specifically reserved.
n The number of subsets for which memory will be reserved.
References crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, and crawlservpp::Struct::QueryStruct::typeXPathJsonPointer.
setMinimizeMemory()
void crawlservpp::Query::Container::setMinimizeMemory (bool isMinimizeMemory) inline protected
Sets whether to minimize memory usage.
Note
Setting memory minimization to true might negatively affect performance.
Parameters
isMinimizeMemory Set whether to minimize memory usage, prioritizing memory usage over performance.
Referenced by crawlservpp::Module::Extractor::Thread::onInit().
setQueryTarget()
void crawlservpp::Query::Container::setQueryTarget (const std::string & content, const std::string & source) inline protected
Sets the content to use the managed queries on.
The old query target referencing the old content will be cleared.
Warning
Pointers to the strings will be saved in-class. Make sure the strings remain valid as long as they are used!
Parameters
content Constant reference to a string containing the content to use the managed queries on.
source Constant reference to a string containing the source (URL) of the content. It will be used for logging and error reporting purposes only.
References clearQueryTarget().
setRepairCData()
void crawlservpp::Query::Container::setRepairCData (bool isRepairCData) inline protected
Sets whether to try to repair CData when parsing XML.
Parameters
isRepairCData Set whether to try to repair CData when parsing XML.
Referenced by crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
setRepairComments()
void crawlservpp::Query::Container::setRepairComments (bool isRepairComments) inline protected
Sets whether to try to repair broken HTML/XML comments.
Parameters
isRepairComments Set whether to try to repair broken HTML/XML comments.
Referenced by crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
setSubSetsFromQuery()
bool crawlservpp::Query::Container::setSubSetsFromQuery (const QueryStruct & query, std::queue< std::string > & warningsTo) inline protected
Sets subsets for subsequent queries using a query of any type.
The subsets resulting from the query will be saved in-class. Previous subsets will be overwritten.
Parameters
query A constant reference to a structure identifying the query that will be performed to acquire the subset.
warningsTo A reference to a vector of strings to which all warnings will be appended that occur during the execution of the query.
Returns
True, if the query was successful. False, if the execution of the query failed.
Exceptions
Container::Exception if no query target has been specified or the query is of an unknown type.
References crawlservpp::Struct::QueryStruct::index, crawlservpp::Helper::Json::parseCons(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::QueryStruct::resultSubSets, crawlservpp::Struct::QueryStruct::type, crawlservpp::Struct::QueryStruct::typeJsonPath, crawlservpp::Struct::QueryStruct::typeJsonPointer, crawlservpp::Struct::QueryStruct::typeNone, crawlservpp::Struct::QueryStruct::typeRegEx, crawlservpp::Struct::QueryStruct::typeXPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPath, crawlservpp::Struct::QueryStruct::typeXPathJsonPointer, and crawlservpp::Main::Exception::view().
setTidyErrorsAndWarnings()
void crawlservpp::Query::Container::setTidyErrorsAndWarnings (bool warnings, std::uint32_t numOfErrors) inline protected
Sets how tidy-html5 reports errors and warnings.
The reporting of both errors and warnings is deactivated by default.
For more information about tidy-html5, see its GitHub repository.
Parameters
warnings Specify whether to report simple warnings.
numOfErrors Set the number of errors to be reported. Set to zero to deactivate error reporting.
References crawlservpp::Parsing::XML::setOptions().
Referenced by crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
The documentation for this class was generated from the following file:
Query/Container.hpp