crawlserv++: crawlservpp::Main::Exception Class Reference
crawlservpp::Main::Exception Class Reference
Base class for all exceptions thrown by the application.
#include <Exception.hpp>
Construction and Destruction
Exception (const std::string &description)
Constructor for creating a new exception.
~Exception () override=default
Default destructor.
Getter
std::string_view view () const noexcept
Gets the description of the exception as a view to the underlying string.
Copy and Move
The class is both copyable and moveable.
Exception (const Exception &other)=default
Default copy constructor.
Exception & operator= (const Exception &other)=default
Default copy assignment operator.
Exception (Exception &&other)=default
Default move constructor.
Exception & operator= (Exception &&other)=default
Default move assignment operator.
Detailed Description
Base class for all exceptions thrown by the application.
Possesses a view into the string describing the exception.
Use MAIN_EXCEPTION_CLASS() for adding child classes of Main::Exception for general exceptions to another class.
Use MAIN_EXCEPTION_SUBCLASS(NAME) for adding children for specific types of exceptions to such a class.
Constructor & Destructor Documentation
Exception() [1/3]
crawlservpp::Main::Exception::Exception (const std::string & description) inline explicit
Constructor for creating a new exception.
The string will be handled by the std::runtime_error parent class.
An extra view into the string will be stored inside the class.
Note
An appropriate child class should be used when throwing an exception.
Use MAIN_EXCEPTION_CLASS() for adding child classes of Main::Exception to another class.
Use MAIN_EXCEPTION_SUBCLASS(NAME) for adding children to those classes for specific types of exceptions.
Parameters
description A const reference to a string describing the exception.
~Exception()
crawlservpp::Main::Exception::~Exception () override default
Default destructor.
Exception() [2/3]
crawlservpp::Main::Exception::Exception (const Exception & other) default
Default copy constructor.
Exception() [3/3]
crawlservpp::Main::Exception::Exception (Exception && other) default
Default move constructor.
Member Function Documentation
operator=() [1/2]
Exception& crawlservpp::Main::Exception::operator= (const Exception & other) default
Default copy assignment operator.
operator=() [2/2]
Exception& crawlservpp::Main::Exception::operator= (Exception && other) default
Default move assignment operator.
view()
std::string_view crawlservpp::Main::Exception::view () const inline noexcept
Gets the description of the exception as a view to the underlying string.
Returns
A view to the string containing the description of the exception.
Referenced by crawlservpp::Query::Container::addQuery(), crawlservpp::Query::Container::addSubSetsFromQueryOnSubSet(), crawlservpp::Main::Database::duplicateWebsite(), crawlservpp::Query::Container::getBoolFromQuery(), crawlservpp::Query::Container::getBoolFromQueryOnSubSet(), crawlservpp::Query::Container::getBoolFromRegEx(), crawlservpp::Module::Analyzer::Database::getCorpus(), crawlservpp::Query::Container::getMultiFromQuery(), crawlservpp::Query::Container::getMultiFromQueryOnSubSet(), crawlservpp::Query::Container::getMultiFromRegEx(), crawlservpp::Network::Curl::getPublicIp(), crawlservpp::Query::Container::getSingleFromQuery(), crawlservpp::Query::Container::getSingleFromQueryOnSubSet(), crawlservpp::Query::Container::getSingleFromRegEx(), crawlservpp::Module::Config::loadConfig(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Parsing::XML::parse(), crawlservpp::Main::Server::Server(), crawlservpp::Query::Container::setSubSetsFromQuery(), crawlservpp::Main::Server::tick(), and crawlservpp::Main::Server::~Server().
The documentation for this class was generated from the following file:
Main/Exception.hpp