crawlserv++: crawlservpp::Module::Database Class Reference
crawlservpp::Module::Database Class Reference
Class handling database access for threads.
#include <Database.hpp>
Classes
class Exception
Class for Module::Database exceptions.
Friends
class Wrapper::Database
Allows access to module threads.
Setters
void setSleepOnError (std::uint64_t seconds)
Sets the number of seconds to sleep before trying to reconnect after connection loss.
void setTimeOut (std::uint64_t milliseconds)
Sets the maximum execution time for MySQL queries, in milliseconds.
Getters
const DatabaseSettings & getSettings () const
Gets the settings of the database.
const std::string & getMysqlVersion () const
Gets the MySQL version string.
const std::string & getDataDir () const
Gets the default data directory.
std::uint64_t getMaxAllowedPacketSize () const
Gets the maximum allowed packet size for communicating with the MySQL server.
std::uint64_t getConnectionId () const
Gets the connection ID.
Initialization and Update
void connect ()
Establishes a connection to the database and retrieves information about the server and the connection.
void initializeSql ()
Runs initializing SQL commands by processing all .sql files in the SQL (sub-)folder.
void update ()
Updates the tables with language and version information in the database.
Logging
void log (const std::string &logEntry)
Adds a log entry to the database for the current module.
void log (const std::string &logModule, const std::string &logEntry)
Adds a log entry to the database for any module.
std::uint64_t getNumberOfLogEntries (const std::string &logModule)
Gets the number of log entries from the database.
void clearLogs (const std::string &logModule)
Removes log entries from the database.
Threads
std::vector< ThreadDatabaseEntry > getThreads ()
Gets information about all threads from the database.
std::uint64_t addThread (const ThreadOptions &threadOptions)
Adds information about a new thread to the database and returns its ID.
std::uint64_t getThreadRunTime (std::uint64_t threadId)
Gets the run time of a thread from the database.
std::uint64_t getThreadPauseTime (std::uint64_t threadId)
Gets the pause time of a thread from the database.
void setThreadStatus (std::uint64_t threadId, bool threadPaused, const std::string &threadStatusMessage)
Updates the status of a thread in the database.
void setThreadStatus (std::uint64_t threadId, const std::string &threadStatusMessage)
Updates the status of a thread in the database without changing the pause state of the thread.
void setThreadRunTime (std::uint64_t threadId, std::uint64_t threadRunTime)
Updates the run time of a thread in the database.
void setThreadPauseTime (std::uint64_t threadId, std::uint64_t threadPauseTime)
Updates the pause time of a thread in the database.
void deleteThread (std::uint64_t threadId)
Removes a thread from the database.
Websites
std::uint64_t addWebsite (const WebsiteProperties &websiteProperties)
Adds a new website to the database and returns its ID.
std::string getWebsiteDomain (std::uint64_t id)
Gets the domain of a website from the database.
std::string getWebsiteNamespace (std::uint64_t websiteId)
Gets the namespace of a website from the database.
IdString getWebsiteNamespaceFromUrlList (std::uint64_t listId)
Gets the ID and the namespace of the website associated with a URL list from the database.
IdString getWebsiteNamespaceFromConfig (std::uint64_t configId)
Gets the ID and the namespace of the website associated with a configuration from the database.
IdString getWebsiteNamespaceFromTargetTable (const std::string &type, std::uint64_t tableId)
Gets the ID and the namespace of the website associated with a target table from the database.
bool isWebsiteNamespace (const std::string &nameSpace)
Checks whether a website namespace exists in the database.
std::string duplicateWebsiteNamespace (const std::string &websiteNamespace)
Gets a new name for a website namespace to duplicate.
std::string getWebsiteDataDirectory (std::uint64_t websiteId)
Gets the data directory used by a website.
std::uint64_t getChangedUrlsByWebsiteUpdate (std::uint64_t websiteId, const WebsiteProperties &websiteProperties)
Gets the number of URLs that will be modified by updating a website from the database.
std::uint64_t getLostUrlsByWebsiteUpdate (std::uint64_t websiteId, const WebsiteProperties &websiteProperties)
Gets the number of URLs that will be lost by updating a website from the database.
void updateWebsite (std::uint64_t websiteId, const WebsiteProperties &websiteProperties)
Updates a website and all associated tables in the database.
void deleteWebsite (std::uint64_t websiteId)
Deletes a website and all associated data from the database.
std::uint64_t duplicateWebsite (std::uint64_t websiteId, const Queries &queries)
Duplicates a website, its URL lists, queries, and configurations in the database.
void moveWebsite (std::uint64_t websiteId, const WebsiteProperties &websiteProperties)
Moves a website and all associated data to another data directory in the database.
URL Lists
std::uint64_t addUrlList (std::uint64_t websiteId, const UrlListProperties &listProperties)
Adds a new URL list to the database and returns its ID.
std::queue< IdString > getUrlLists (std::uint64_t websiteId)
Gets all URL lists associated with a website from the database.
std::size_t mergeUrls (std::uint64_t listId, std::queue< std::string > &urls)
Inserts URLs that do not already exist into a URL list in the database, returns the number of added URLs.
std::queue< std::string > getUrls (std::uint64_t listId)
Gets all URLs from a URL list in the database.
std::queue< IdString > getUrlsWithIds (std::uint64_t listId)
Gets all URLs and their IDs from a URL list in the database.
std::string getUrlListNamespace (std::uint64_t listId)
Gets the namespace of a URL list from the database.
IdString getUrlListNamespaceFromTargetTable (const std::string &type, std::uint64_t tableId)
Gets the namespace of a URL list from the database by using a target table.
bool isUrlListNamespace (std::uint64_t websiteId, const std::string &nameSpace)
Checks whether a URL list namespace for a specific website exists in the database.
void updateUrlList (std::uint64_t listId, const UrlListProperties &listProperties)
Updates a URL list and all associated tables in the database.
void deleteUrlList (std::uint64_t listId)
Deletes a URL list and all associated data from the database.
std::size_t deleteUrls (std::uint64_t listId, std::queue< uint64_t > &urlIds)
Deletes URLs from a URL list in the database and returns the number of deleted URLs.
void resetParsingStatus (std::uint64_t listId)
Resets the parsing status of all URLs in a URL list in the database.
void resetExtractingStatus (std::uint64_t listId)
Resets the extracting status of all URLs in a URL list in the database.
void resetAnalyzingStatus (std::uint64_t listId)
Resets the analyzing status of all URLs in a URL list in the database.
Queries
std::uint64_t addQuery (std::uint64_t websiteId, const QueryProperties &queryProperties)
Adds a new query to the database and returns its ID.
void getQueryProperties (std::uint64_t queryId, QueryProperties &queryPropertiesTo)
Gets the properties of a query from the database.
void updateQuery (std::uint64_t queryId, const QueryProperties &queryProperties)
Updates a query in the database.
void moveQuery (std::uint64_t queryId, std::uint64_t toWebsiteId)
Moves a query to another website in the database.
void deleteQuery (std::uint64_t queryId)
Deletes a query from the database.
std::uint64_t duplicateQuery (std::uint64_t queryId)
Duplicates a query in the database.
Configurations
std::uint64_t addConfiguration (std::uint64_t websiteId, const ConfigProperties &configProperties)
Adds a new configuration to the database and returns its ID.
std::string getConfiguration (std::uint64_t configId)
Gets a configuration from the database.
void updateConfiguration (std::uint64_t configId, const ConfigProperties &configProperties)
Updates a configuration in the database.
void deleteConfiguration (std::uint64_t configId)
Deletes a configuration from the database.
std::uint64_t duplicateConfiguration (std::uint64_t configId)
Duplicates a configuration in the database.
Target Tables
std::uint64_t addTargetTable (const TargetTableProperties &properties)
Adds a new target table or updates an existing target table in the database.
std::queue< IdString > getTargetTables (const std::string &type, std::uint64_t listId)
Gets the target tables of the specified type for a URL list from the database.
std::uint64_t getTargetTableId (const std::string &type, std::uint64_t listId, const std::string &tableName)
Gets the ID of a target table from the database.
std::string getTargetTableName (const std::string &type, std::uint64_t tableId)
Gets the name of a target table from the database.
void deleteTargetTable (const std::string &type, std::uint64_t tableId)
Deletes a target table from the database.
Validation
void checkConnection ()
Checks whether the connection to the database is still valid and tries to reconnect if necessary.
bool isWebsite (std::uint64_t websiteId)
Checks whether a website ID is valid.
bool isUrlList (std::uint64_t urlListId)
Checks whether a URL list ID is valid.
bool isUrlList (std::uint64_t websiteId, std::uint64_t urlListId)
Checks whether a URL list ID is valid for a specific website.
bool isQuery (std::uint64_t queryId)
Checks whether a query ID is valid.
bool isQuery (std::uint64_t websiteId, std::uint64_t queryId)
Checks whether a query ID is valid for a specific website.
bool isConfiguration (std::uint64_t configId)
Checks whether a configuration ID is valid.
bool isConfiguration (std::uint64_t websiteId, std::uint64_t configId)
Checks whether a configuration ID is valid for a specific website.
bool checkDataDir (const std::string &dir)
Checks whether a data directory is known to the database.
Locking
void beginNoLock ()
Disables database locking by starting a new SQL transaction.
void endNoLock ()
Re-enables database locking by ending the previous SQL transaction.
Tables
bool isTableEmpty (const std::string &tableName)
Checks whether a table in the database is empty.
bool isTableExists (const std::string &tableName)
Checks whether a table exists in the database.
bool isColumnExists (const std::string &tableName, const std::string &columnName)
Checks whether a table in the database contains a specific column.
std::string getColumnType (const std::string &tableName, const std::string &columnName)
Gets the type of a specific table column from the database.
void lockTables (std::queue< TableNameWriteAccess > &tableLocks)
Locks tables in the database.
void unlockTables ()
Unlocks all previously locked tables in the database.
void startTransaction (const std::string &isolationLevel)
Starts a new transaction with the database using a specific isolation level.
void endTransaction (bool success)
Ends the current transaction with the database, committing the commands on success.
Custom Data
void getCustomData (Data::GetValue &data)
Gets a custom value from one column from a table row in the database.
void getCustomData (Data::GetFields &data)
Gets custom values from multiple columns of the same type from a table row.
void getCustomData (Data::GetFieldsMixed &data)
Gets custom values from multiple columns of different types from a table row.
void getCustomData (Data::GetColumn &data)
Gets custom values from a table column in the database.
void getCustomData (Data::GetColumns &data)
Gets custom values from multiple table columns of the same type.
void getCustomData (Data::GetColumnsMixed &data)
Gets custom values from multiple table columns of different types.
void insertCustomData (const Data::InsertValue &data)
Inserts a custom value into a table row in the database.
void insertCustomData (const Data::InsertFields &data)
Inserts custom values into multiple table columns of the same type.
void insertCustomData (const Data::InsertFieldsMixed &data)
Inserts custom values into multiple table columns of different types.
void updateCustomData (const Data::UpdateValue &data)
Updates a custom value in a table row.
void updateCustomData (const Data::UpdateFields &data)
Updates custom values in multiple table columns of the same type.
void updateCustomData (const Data::UpdateFieldsMixed &data)
Updates custom values in multiple table columns of different types.
Request Counter
static std::uint64_t getRequestCounter ()
Gets the number of SQL requests performed since the start of the application.
Shared Connection Information
std::unique_ptr< sql::Connection > connection
Database connection.
static sql::Driver * driver {nullptr}
Pointer to the MySQL database driver.
Helper Functions for Prepared SQL Statements
void reserveForPreparedStatements (std::size_t n)
Reserves memory for a specific number of additional prepared SQL statements.
std::size_t addPreparedStatement (const std::string &sqlQuery)
Prepares an additional SQL statement and returns its ID.
sql::PreparedStatement & getPreparedStatement (std::size_t id)
Gets a reference to a prepared SQL statement.
Database Helper Functions
std::uint64_t getLastInsertedId ()
Gets the last inserted ID from the database.
void resetAutoIncrement (const std::string &tableName)
Resets the auto-increment value of an empty table in the database.
void checkDirectory (const std::string &dir)
Checks access to an external data directory in the database.
static void addDatabaseLock (const std::string &name, const IsRunningCallback &isRunningCallback)
Adds a lock to the database class, blocking execution.
static bool tryDatabaseLock (const std::string &name)
Tries to add a lock to the database class, not blocking execution.
static void removeDatabaseLock (const std::string &name)
Removes a lock from the database class.
Table Helper Functions
void createTable (const TableProperties &properties)
Adds a table to the database.
void dropTable (const std::string &name)
Deletes a table from the database.
void addColumn (const std::string &tableName, const TableColumn &column)
Adds a column to a table in the database.
void compressTable (const std::string &tableName)
Compresses a table in the database.
std::queue< std::string > cloneTable (const std::string &tableName, const std::string &destDir)
Clones a table into another data directory, without copying data or constraints.
URL List Helper Functions
bool isUrlListCaseSensitive (std::uint64_t listId)
Gets whether the specified URL list is case-sensitive.
void setUrlListCaseSensitive (std::uint64_t listId, bool isCaseSensitive)
Sets whether the specified URL list is case-sensitive.
Exception Helper Function
static void sqlException (const std::string &function, const sql::SQLException &e)
Catches a SQL exception and re-throws it as a specific or a generic Database::Exception.
Helper Functions for Executing SQL Queries
template<class T , class... Args>
static bool sqlExecute (T &statement, Args... args)
Template function for executing a SQL query.
template<class T , class... Args>
static bool sqlExecute (std::unique_ptr< T > &statement, Args... args)
Template function for executing a SQL query by unique pointer.
template<class T , class... Args>
static sql::ResultSet * sqlExecuteQuery (T &statement, Args... args)
Template function for executing a SQL query and returning the resulting set.
template<class T , class... Args>
static sql::ResultSet * sqlExecuteQuery (std::unique_ptr< T > &statement, Args... args)
Template function for executing a SQL query by unique pointer and returning the resulting set.
template<class T , class... Args>
static int sqlExecuteUpdate (T &statement, Args... args)
Template function for executing a SQL query and returning the number of affected rows.
template<class T , class... Args>
static int sqlExecuteUpdate (std::unique_ptr< T > &statement, Args... args)
Template function for executing a SQL query by unique pointer and returning the number of affected rows.
Construction and Destruction
Database (const DatabaseSettings &dbSettings, const std::string &dbModule)
Constructor setting database settings and the module.
~Database () override
Destructor clearing the thread.
Setters (Module)
void setOptions (const ModuleOptions &moduleOptions)
Sets general options for the module.
void setThreadId (std::uint64_t id)
Sets the ID of the thread.
void setLogging (std::uint8_t level, std::uint8_t min, std::uint8_t verbose)
Sets the current, minimal, and verbose logging levels.
Preparation (Module)
void prepare ()
Prepares SQL statements for basic thread management.
Logging (Module)
void log (std::uint8_t level, const std::string &logEntry)
Writes a thread-specific log entry to the database.
void log (std::uint8_t level, std::queue< std::string > &logEntries)
Writes multiple thread-specific log entries to the database.
bool isLogLevel (uint8_t level) const
Checks whether a certain logging level is active.
Threads (Module)
void setThreadStatusMessage (std::uint64_t threadId, bool threadPaused, const std::string &threadStatusMessage)
Saves the current status of a thread to the database.
void setThreadProgress (std::uint64_t threadId, float threadProgress, std::uint64_t threadRunTime)
Saves the current progress and runtime of a thread to the database.
void setThreadLast (std::uint64_t threadId, std::uint64_t threadLast)
Saves the last ID processed by the thread to the database.
Copy and Move
The class is neither copyable, nor movable.
Database (Database &)=delete
Deleted copy constructor.
Database & operator= (Database &)=delete
Deleted copy assignment operator.
Database (Database &&)=delete
Deleted move constructor.
Database & operator= (Database &&)=delete
Deleted move assignment operator.
Detailed Description
Class handling database access for threads.
Only implements module-independent functionality. For module-specific functionality, use the child classes of Wrapper::Database instead.
Constructor & Destructor Documentation
Database() [1/3]
crawlservpp::Module::Database::Database (const DatabaseSettings & dbSettings, const std::string & dbModule)
Constructor setting database settings and the module.
Parameters
dbSettings Constant reference to a structure containing the database settings.
dbModule Constant reference to a string containing the name of the module of the current thread.
Exceptions
Module::Database::Exception if the MySQL driver has not been loaded.
See also
Struct::DatabaseSettings
References crawlservpp::Main::Database::driver.
~Database()
crawlservpp::Module::Database::~Database () override virtual
Destructor clearing the thread.
Also closes the logging file, if debug logging via file had been active.
Reimplemented from crawlservpp::Main::Database.
References crawlservpp::Main::Database::driver.
Database() [2/3]
crawlservpp::Module::Database::Database (Database &) delete
Deleted copy constructor.
Database() [3/3]
crawlservpp::Module::Database::Database (Database &&) delete
Deleted move constructor.
Member Function Documentation
addColumn()
void crawlservpp::Main::Database::addColumn (const std::string & tableName, const TableColumn & column) protected inherited
Adds a column to a table in the database.
Parameters
tableName Constant reference to a string containing the name of the table to which the column will be added.
column Constant reference to a structure containing the properties of the column to be added to the table.
Exceptions
Main::Database::Exception if no table, no column, or no column type is specified, i.e. if one of the strings containing the name of the table, the name of the column, and the type of the column is empty, or if a column reference is incomplete.
Main::Database::Exception if a MySQL error occured while adding the column to the given table in the database.
See also
Struct::TableColumn
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::TableColumn::name, crawlservpp::Struct::TableColumn::referenceColumn, crawlservpp::Struct::TableColumn::referenceTable, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), and crawlservpp::Struct::TableColumn::type.
Referenced by crawlservpp::Wrapper::Database::addColumn(), and crawlservpp::Main::Database::addTargetTable().
addConfiguration()
std::uint64_t crawlservpp::Main::Database::addConfiguration (std::uint64_t websiteId, const ConfigProperties & configProperties) inherited
Adds a new configuration to the database and returns its ID.
Parameters
websiteId The ID of the website to which the new query will be added, or zero for adding a global configuration to the database.
configProperties Constant reference to the properties of the new configuration.
Returns
A unique ID identifying the new configuration in the database.
Exceptions
Main::Database::Exception if no module, name, or configuration has been specfied in the given properties of the new configuration.
Main::Database::Exception if a MySQL error occured while adding the new configuration to the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Struct::ConfigProperties::config, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Struct::ConfigProperties::module, crawlservpp::Struct::ConfigProperties::name, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::sqlArg4, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Database::duplicateConfiguration(), and crawlservpp::Main::Database::duplicateWebsite().
addDatabaseLock()
void crawlservpp::Main::Database::addDatabaseLock (const std::string & name, const IsRunningCallback & isRunningCallback) static protected inherited
Adds a lock to the database class, blocking execution.
If a lock with the same name already exists, the function will block execution until this lock has been released, or the specified callback function returns false.
Parameters
name Constant reference to a string containing the name of the lock to be waited for and added to the database class.
isRunningCallback Constant reference to a function that will be regularly called during a block, to enquire whether the thread (or application) is still running. As soon as this function returns false, execution will no longer be blocked, even if the lock could not be added.
References crawlservpp::Main::sleepOnLockMs.
Referenced by crawlservpp::Wrapper::Database::addDatabaseLock().
addPreparedStatement()
std::size_t crawlservpp::Main::Database::addPreparedStatement (const std::string & sqlQuery) protected inherited
Prepares an additional SQL statement and returns its ID.
Parameters
sqlQuery Constant reference to a string containing the SQL query for the prepared SQL statement.
Returns
A unique ID identifying the prepared SQL query in-class.
Exceptions
Main::Database::Exception if a MySQL error occured while preparing and adding the SQL statement.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, and crawlservpp::Main::Database::sqlException().
Referenced by crawlservpp::Wrapper::Database::addPreparedStatement(), prepare(), and crawlservpp::Main::Database::prepare().
addQuery()
std::uint64_t crawlservpp::Main::Database::addQuery (std::uint64_t websiteId, const QueryProperties & queryProperties) inherited
Adds a new query to the database and returns its ID.
Parameters
websiteId The ID of the website to which the new query will be added, or zero for adding a global query to the database.
queryProperties Constant reference to the properties of the new query.
Returns
A unique ID identifying the new query in the database.
Exceptions
Main::Database::Exception if no query name, text, or type has been specfied in the given properties of the new query.
Main::Database::Exception if a MySQL error occured while adding the new query to the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Struct::QueryProperties::name, crawlservpp::Struct::QueryProperties::resultBool, crawlservpp::Struct::QueryProperties::resultMulti, crawlservpp::Struct::QueryProperties::resultSingle, crawlservpp::Struct::QueryProperties::resultSubSets, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::sqlArg4, crawlservpp::Main::sqlArg5, crawlservpp::Main::sqlArg6, crawlservpp::Main::sqlArg7, crawlservpp::Main::sqlArg8, crawlservpp::Main::sqlArg9, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Struct::QueryProperties::text, crawlservpp::Struct::QueryProperties::textOnly, and crawlservpp::Struct::QueryProperties::type.
Referenced by crawlservpp::Main::Database::duplicateQuery(), and crawlservpp::Main::Database::duplicateWebsite().
addTargetTable()
std::uint64_t crawlservpp::Main::Database::addTargetTable (const TargetTableProperties & properties) inherited
Adds a new target table or updates an existing target table in the database.
Parameters
properties Constant reference to the properties of the new target table, or the existing target table to be updated.
Returns
If no target table with the specified type and name already exists, a unique ID identifying the new target table in the database. The ID of the new table is, however, only unique among all target tables of the same type. If a target table with the specified type and name already exists, its ID will be returned instead.
Exceptions
Main::Database::Exception if no type, website, URL list, name, or columns have been specfied in the given properties of the new target table, or if a column of the already existing target table cannot be overwritten due to incompatibilities between the respective data types.
Main::Database::Exception if a MySQL error occured while adding the new target table, or updating the existing target table in the database.
References crawlservpp::Main::Database::addColumn(), crawlservpp::Main::Database::checkConnection(), crawlservpp::Struct::TargetTableProperties::columns, crawlservpp::Struct::TargetTableProperties::compressed, crawlservpp::Main::Database::compressTable(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::createTable(), crawlservpp::Struct::TargetTableProperties::fullName, crawlservpp::Main::Database::getColumnType(), crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Main::Database::getWebsiteDataDirectory(), crawlservpp::Main::Database::isColumnExists(), crawlservpp::Main::Database::isTableExists(), crawlservpp::Struct::TargetTableProperties::name, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Struct::TargetTableProperties::type, crawlservpp::Struct::TargetTableProperties::urlList, and crawlservpp::Struct::TargetTableProperties::website.
Referenced by crawlservpp::Wrapper::Database::addTargetTable().
addThread()
std::uint64_t crawlservpp::Main::Database::addThread (const ThreadOptions & threadOptions) inherited
Adds information about a new thread to the database and returns its ID.
Parameters
threadOptions Constant reference to the options for the new thread.
Returns
A unique ID identifying the new thread in the database.
Exceptions
Main::Database::Exception if the module of the thread is empty, or if no module, no website, no URL list, or no configuration has been specified in the given options for the thread.
Main::Database::Exception if a MySQL error occured while adding information about the new thread to the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Struct::ThreadOptions::config, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Struct::ThreadOptions::module, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::sqlArg4, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Struct::ThreadOptions::urlList, and crawlservpp::Struct::ThreadOptions::website.
Referenced by crawlservpp::Module::Thread::Thread().
addUrlList()
std::uint64_t crawlservpp::Main::Database::addUrlList (std::uint64_t websiteId, const UrlListProperties & listProperties) inherited
Adds a new URL list to the database and returns its ID.
Parameters
websiteId The ID of the website to which the new URL list will be added.
listProperties Constant reference to the properties of the new URL list.
Returns
A unique ID identifying the new URL list in the database.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero, no namespace or name has been specfied in the given properties of the new URL list, or if the specified URL list namespace already exists in the database.
Main::Database::Exception if a MySQL error occured while adding the new URL list to the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::createTable(), crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Main::Database::getWebsiteDataDirectory(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::Database::isUrlListNamespace(), crawlservpp::Struct::UrlListProperties::name, crawlservpp::Struct::UrlListProperties::nameSpace, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Database::addWebsite(), and crawlservpp::Main::Database::duplicateWebsite().
addWebsite()
std::uint64_t crawlservpp::Main::Database::addWebsite (const WebsiteProperties & websiteProperties) inherited
Adds a new website to the database and returns its ID.
Parameters
websiteProperties Constant reference to the properties of the new website.
Returns
A unique ID identifying the new website in the database.
Exceptions
Main::Database::Exception if the namespace or the name of the new website is empty, its namespace already exists, or the specified data directory does not exist.
Main::Database::Exception if a MySQL error occured while adding the new website to the database.
References crawlservpp::Main::Database::addUrlList(), crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::deleteWebsite(), crawlservpp::Struct::WebsiteProperties::dir, crawlservpp::Struct::WebsiteProperties::domain, crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Helper::FileSystem::isValidDirectory(), crawlservpp::Main::Database::isWebsiteNamespace(), crawlservpp::Struct::WebsiteProperties::name, crawlservpp::Struct::WebsiteProperties::nameSpace, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::sqlArg4, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Database::duplicateWebsite().
beginNoLock()
void crawlservpp::Main::Database::beginNoLock () inherited
Disables database locking by starting a new SQL transaction.
Exceptions
Main::Database::Exception if a MySQL error occured while starting a new SQL transaction in the database.
References crawlservpp::Main::Database::connection, and crawlservpp::Main::Database::sqlException().
Referenced by crawlservpp::Wrapper::Database::beginNoLock().
checkConnection()
void crawlservpp::Main::Database::checkConnection () inherited
Checks whether the connection to the database is still valid and tries to reconnect if necessary.
Warning
Afterwards, old references to prepared SQL statements might be invalid, because the connection to the database might have been reset.
Exceptions
Main::Database::Exception if the MySQL driver is not initialized.
Main::Database::Exception if a MySQL error occured while attempting to reconnect to the database.
References crawlservpp::Main::Database::connect(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::driver, crawlservpp::Main::Database::log(), crawlservpp::Main::reconnectAfterIdleMs, crawlservpp::Helper::DateTime::secondsToString(), crawlservpp::Main::secToMs, crawlservpp::Main::Database::sqlException(), and crawlservpp::Timer::Simple::tick().
Referenced by crawlservpp::Main::Database::addColumn(), crawlservpp::Main::Database::addConfiguration(), crawlservpp::Main::Database::addPreparedStatement(), crawlservpp::Main::Database::addQuery(), crawlservpp::Main::Database::addTargetTable(), crawlservpp::Main::Database::addThread(), crawlservpp::Main::Database::addUrlList(), crawlservpp::Main::Database::addWebsite(), crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Main::Database::checkDirectory(), crawlservpp::Main::Database::clearLogs(), crawlservpp::Main::Database::cloneTable(), crawlservpp::Main::Database::compressTable(), crawlservpp::Main::Database::createTable(), crawlservpp::Main::Database::deleteConfiguration(), crawlservpp::Main::Database::deleteQuery(), crawlservpp::Main::Database::deleteTargetTable(), crawlservpp::Main::Database::deleteThread(), crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Main::Database::deleteUrls(), crawlservpp::Main::Database::deleteWebsite(), crawlservpp::Main::Database::dropTable(), crawlservpp::Main::Database::duplicateConfiguration(), crawlservpp::Main::Database::duplicateQuery(), crawlservpp::Main::Database::duplicateWebsite(), crawlservpp::Main::Database::endTransaction(), crawlservpp::Main::Database::getChangedUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getColumnType(), crawlservpp::Main::Database::getConfiguration(), crawlservpp::Main::Database::getCustomData(), crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Main::Database::getLostUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getNumberOfLogEntries(), crawlservpp::Main::Database::getQueryProperties(), crawlservpp::Main::Database::getTargetTableId(), crawlservpp::Main::Database::getTargetTableName(), crawlservpp::Main::Database::getTargetTables(), crawlservpp::Main::Database::getThreadPauseTime(), crawlservpp::Main::Database::getThreadRunTime(), crawlservpp::Main::Database::getThreads(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getUrlListNamespaceFromTargetTable(), crawlservpp::Main::Database::getUrlLists(), crawlservpp::Main::Database::getUrls(), crawlservpp::Main::Database::getUrlsWithIds(), crawlservpp::Main::Database::getWebsiteDataDirectory(), crawlservpp::Main::Database::getWebsiteDomain(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromConfig(), crawlservpp::Main::Database::getWebsiteNamespaceFromTargetTable(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::insertCustomData(), crawlservpp::Main::Database::isColumnExists(), crawlservpp::Main::Database::isConfiguration(), crawlservpp::Main::Database::isQuery(), crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::isTableExists(), crawlservpp::Main::Database::isUrlList(), crawlservpp::Main::Database::isUrlListCaseSensitive(), crawlservpp::Main::Database::isUrlListNamespace(), crawlservpp::Main::Database::isWebsite(), crawlservpp::Main::Database::isWebsiteNamespace(), crawlservpp::Main::Database::log(), crawlservpp::Main::Database::mergeUrls(), crawlservpp::Main::Database::moveQuery(), crawlservpp::Main::Database::moveWebsite(), prepare(), crawlservpp::Main::Database::resetAnalyzingStatus(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::Database::resetExtractingStatus(), crawlservpp::Main::Database::resetParsingStatus(), setThreadLast(), crawlservpp::Main::Database::setThreadPauseTime(), setThreadProgress(), crawlservpp::Main::Database::setThreadRunTime(), crawlservpp::Main::Database::setThreadStatus(), setThreadStatusMessage(), crawlservpp::Main::Database::setTimeOut(), crawlservpp::Main::Database::setUrlListCaseSensitive(), crawlservpp::Main::Database::startTransaction(), crawlservpp::Main::Server::tick(), crawlservpp::Main::Database::update(), crawlservpp::Main::Database::updateConfiguration(), crawlservpp::Main::Database::updateCustomData(), crawlservpp::Main::Database::updateQuery(), crawlservpp::Main::Database::updateUrlList(), and crawlservpp::Main::Database::updateWebsite().
checkDataDir()
bool crawlservpp::Main::Database::checkDataDir (const std::string & dir) inherited
Checks whether a data directory is known to the database.
Parameters
dir Constant reference to a string containing the data directory to be checked.
Returns
True, if the exact data directory is known to the database. False otherwise.
checkDirectory()
void crawlservpp::Main::Database::checkDirectory (const std::string & dir) protected inherited
Checks access to an external data directory in the database.
Adds and removes a test table to check access to the given data directory.
Parameters
dir Constant reference to a string containing the data directory to be checked.
Exceptions
Main::Database::Exception if no data directory is specified, i.e. the string containing the directory is empty.
Main::Database::Exception if a MySQL error occured while checking access to the data directory in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
clearLogs()
void crawlservpp::Main::Database::clearLogs (const std::string & logModule) inherited
Removes log entries from the database.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
logModule Constant reference to a string containing the name of the module, whose log entries will be removed, or to an empty string for all log entries to be removed.
Exceptions
Main::Database::Exception if a MySQL error occured while removing log entries from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
cloneTable()
std::queue< std::string > crawlservpp::Main::Database::cloneTable (const std::string & tableName, const std::string & destDir) protected inherited
Clones a table into another data directory, without copying data or constraints.
Warning
The table <tablename>_tmp may not exist already in the database!
Parameters
tableName Const reference to a string containing the name of the table to be cloned.
destDir Const reference to a string containing the data directory into which the table will be cloned.
Returns
A queue containing the constraints that have been dropped during the cloning of the table.
Exceptions
Main::Database::Exception if no table is specified, i.e. if the string containing the name of the table is empty, or if the properties of a table could not be retrieved.
Main::Database::Exception if a MySQL error occured while cloning the table into the other data directory.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlConstraint, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Main::Database::sqlExecuteQuery(), and crawlservpp::Helper::Strings::trim().
Referenced by crawlservpp::Main::Database::moveWebsite().
compressTable()
void crawlservpp::Main::Database::compressTable (const std::string & tableName) protected inherited
Compresses a table in the database.
The function will have no effect om the table, if the table is already compressed.
Parameters
tableName Constant reference to a string containing the name of the table to be compressed.
Exceptions
Main::Database::Exception if no table is specified, i.e. if the string containing the name of the table is empty, or if a row format could not be determined.
Main::Database::Exception if a MySQL error occured while compressing the table in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::DatabaseSettings::name, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addTargetTable(), and crawlservpp::Wrapper::Database::compressTable().
connect()
void crawlservpp::Main::Database::connect () inherited
Establishes a connection to the database and retrieves information about the server and the connection.
Exceptions
Main::Database::Exception if the MySQL driver could not be loaded, a connection to the MySQL database could not be established, the connection to the database is invalid, a SQL statement could not be created, a server variable could not be retrieved or has an invalid value, or the connection ID could not be retrieved.
Main::Database::Exception if a MySQL error occured while connecting to the MySQL server, or while retrieving information about the server and the connection.
References crawlservpp::Struct::DatabaseSettings::compression, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::driver, crawlservpp::Helper::FileSystem::getPathSeparator(), crawlservpp::Struct::DatabaseSettings::host, crawlservpp::Main::lockTimeOutSec, crawlservpp::Main::maxContentSize, crawlservpp::Struct::DatabaseSettings::name, crawlservpp::Struct::DatabaseSettings::password, crawlservpp::Struct::DatabaseSettings::port, crawlservpp::Helper::Strings::split(), crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Helper::Strings::trim(), and crawlservpp::Struct::DatabaseSettings::user.
Referenced by crawlservpp::Main::Database::checkConnection(), and crawlservpp::Main::Server::Server().
createTable()
void crawlservpp::Main::Database::createTable (const TableProperties & properties) protected inherited
Adds a table to the database.
Note
A column for the primary key named id will be created automatically.
Parameters
properties Constant reference to a structure containing the properties of the table to be created.
Exceptions
Main::Database::Exception if no name or columns are specified in the given properties structure, if one of the columns defined there is missing its name or data type, or if a column reference is incomplete.
Main::Database::Exception if a MySQL error occured while adding the table to the database.
See also
Struct::TableProperties
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Struct::TableProperties::columns, crawlservpp::Struct::TableProperties::compressed, crawlservpp::Main::Database::connection, crawlservpp::Struct::TableProperties::dataDirectory, crawlservpp::Struct::TableProperties::name, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Database::addTargetTable(), crawlservpp::Main::Database::addUrlList(), crawlservpp::Wrapper::Database::createTable(), and crawlservpp::Main::Database::update().
deleteConfiguration()
void crawlservpp::Main::Database::deleteConfiguration (std::uint64_t configId) inherited
Deletes a configuration from the database.
Parameters
configId The ID of the configuration that will be deleted from the database.
Exceptions
Main::Database::Exception if no configuration has been specified, i.e. the configuration ID is zero.
Main::Database::Exception if a MySQL error occured while deleting the configuration from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
deleteQuery()
void crawlservpp::Main::Database::deleteQuery (std::uint64_t queryId) inherited
Deletes a query from the database.
Parameters
queryId The ID of the query that will be deleted from the database.
Exceptions
Main::Database::Exception if no query has been specified, i.e. the query ID is zero.
Main::Database::Exception if a MySQL error occured while deleting the query from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
deleteTargetTable()
void crawlservpp::Main::Database::deleteTargetTable (const std::string & type, std::uint64_t tableId) inherited
Deletes a target table from the database.
Parameters
type Constant reference to a string containing the type of the target table to be deleted
tableId The ID of the target table to be deleted.
Exceptions
Main::Database::Exception if no target table has been specified, i.e. the string containing the type is empty or the target table ID is zero.
Main::Database::Exception if a MySQL error occured while deleting the target table from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getTargetTableName(), crawlservpp::Main::Database::getUrlListNamespaceFromTargetTable(), crawlservpp::Main::Database::getWebsiteNamespaceFromTargetTable(), crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Wrapper::Database::deleteTargetTable(), and crawlservpp::Main::Database::deleteUrlList().
deleteThread()
void crawlservpp::Main::Database::deleteThread (std::uint64_t threadId) inherited
Removes a thread from the database.
Parameters
threadId The ID of the thread to be removed from the database.
Exceptions
Main::Database::Exception if no thread has been specified, i.e. the thread ID is zero.
Main::Database::Exception if a MySQL error occured while deleting the thread from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Module::Thread::end().
deleteUrlList()
void crawlservpp::Main::Database::deleteUrlList (std::uint64_t listId) inherited
Deletes a URL list and all associated data from the database.
Warning
All associated data will be removed alongside the URL list.
Parameters
listId The ID of the URL list that will be deleted from the database.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while getting the namespace of the URL list, deleting all associated tables, or deleting the URL list from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::deleteTargetTable(), crawlservpp::Main::Database::dropTable(), crawlservpp::Main::Database::getTargetTables(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Database::deleteWebsite().
deleteUrls()
std::size_t crawlservpp::Main::Database::deleteUrls (std::uint64_t listId, std::queue< uint64_t > & urlIds) inherited
Deletes URLs from a URL list in the database and returns the number of deleted URLs.
Parameters
listId The ID of the URL list that will be deleted from the database.
urlIds Reference to a queue containing the IDs of the URLs to be deleted. It will be cleared while deleting the URLs, so that the referenced queue will be empty when the deletion succeeds.
Returns
The number of URLs deleted from the given URL list in the database. It might differ from the number of URLs given, as duplicates and non-existing URLs will not be counted.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while deleting the URLs from the given URL list in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getMaxAllowedPacketSize(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), and crawlservpp::Main::Database::sqlException().
deleteWebsite()
void crawlservpp::Main::Database::deleteWebsite (std::uint64_t websiteId) inherited
Deletes a website and all associated data from the database.
Warning
All associated URL lists will also be removed.
Parameters
websiteId The ID of the website that will be deleted from the database.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero.
Main::Database::Exception if a MySQL error occured while getting the namespace of the website, deleting all associated URL lists, or deleting the website from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Main::Database::getUrlLists(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Database::addWebsite().
dropTable()
void crawlservpp::Main::Database::dropTable (const std::string & tableName) protected inherited
Deletes a table from the database.
If the table does not exist in the database, the database will not be changed.
Parameters
tableName Constant reference to a string containing the name of the table to be deleted, if it exists.
Exceptions
Main::Database::Exception if no table is specified, i.e. if the string containing the name of the table is empty.
Main::Database::Exception if a MySQL error occured while removing the table from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Wrapper::Database::dropTable(), crawlservpp::Main::Database::moveWebsite(), and crawlservpp::Main::Database::update().
duplicateConfiguration()
std::uint64_t crawlservpp::Main::Database::duplicateConfiguration (std::uint64_t configId) inherited
Duplicates a configuration in the database.
Parameters
configId The ID of the configuration that will be duplicated in the database.
Exceptions
Main::Database::Exception if no configuration has been specified, i.e. the configuration ID is zero.
Main::Database::Exception if a MySQL error occured while duplicating the configuration in the database.
References crawlservpp::Main::Database::addConfiguration(), crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
duplicateQuery()
std::uint64_t crawlservpp::Main::Database::duplicateQuery (std::uint64_t queryId) inherited
Duplicates a query in the database.
Parameters
queryId The ID of the query that will be duplicated in the database.
Exceptions
Main::Database::Exception if no query has been specified, i.e. the query ID is zero.
Main::Database::Exception if a MySQL error occured while duplicating the query in the database.
References crawlservpp::Main::Database::addQuery(), crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
duplicateWebsite()
std::uint64_t crawlservpp::Main::Database::duplicateWebsite (std::uint64_t websiteId, const Queries & queries) inherited
Duplicates a website, its URL lists, queries, and configurations in the database.
A namespace for the new website will automatically be created by using duplicateWebsiteNamespace.
A name for the new website will automatically be created by adding " (copy)" to the name of the duplicated website.
Note
No retrieved data (i.e. target tables) will be duplicated alongside the website, its URL lists, queries, and configurations.
Parameters
websiteId The ID of the website to duplicate in the database.
queries Constant reference to a vector containing pairs of all module names with their queries (i.e. vectors with key, value pairs including the "cat" and "name" keys). This vector will be used to update the queries inside the duplicated configurations.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero, or if an error occured while parsing the duplicated configurations.
Main::Database::Exception if a MySQL error occured while getting information about the website, creating the new namespace of the website, or duplicating the website, its URL lists, queries, and configurations.
References crawlservpp::Main::Database::addConfiguration(), crawlservpp::Main::Database::addQuery(), crawlservpp::Main::Database::addUrlList(), crawlservpp::Main::Database::addWebsite(), crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::duplicateWebsiteNamespace(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Helper::Json::stringify(), and crawlservpp::Main::Exception::view().
duplicateWebsiteNamespace()
std::string crawlservpp::Main::Database::duplicateWebsiteNamespace (const std::string & websiteNamespace) inherited
Gets a new name for a website namespace to duplicate.
Adds a number to the end of the namespace. If the namespace already ends on a number, this number will be increased until the new name does not already exist.
Parameters
websiteNamespace Const reference to a string containing the name of the website namespace to duplicate.
Returns
A copy of a string containing the new name for the duplicated website namespace.
Exceptions
Main::Database::Exception if no namespace has been specified, i.e. the string containing the name of the namespace is empty, or if a conversion from string to number failed.
Main::Database::Exception if a MySQL error occured while checking the existence of the website namespace in the database.
References crawlservpp::Main::Database::isWebsiteNamespace().
Referenced by crawlservpp::Main::Database::duplicateWebsite().
endNoLock()
void crawlservpp::Main::Database::endNoLock () inherited
Re-enables database locking by ending the previous SQL transaction.
Exceptions
Main::Database::Exception if a MySQL error occured while ending the previous SQL transaction by committing the changes to the database.
References crawlservpp::Main::Database::connection, and crawlservpp::Main::Database::sqlException().
Referenced by crawlservpp::Wrapper::Database::endNoLock().
endTransaction()
void crawlservpp::Main::Database::endTransaction (bool success) inherited
Ends the current transaction with the database, committing the commands on success.
Rolls back the commands if the transaction was not successful.
Parameters
success Specifies whether the transaction was successful and the commands should be committed.
Exceptions
Main::Database::Exception if a MySQL error occured while starting the SQL transaction.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, and crawlservpp::Main::Database::sqlException().
Referenced by crawlservpp::Main::Database::Transaction::~Transaction().
getChangedUrlsByWebsiteUpdate()
std::uint64_t crawlservpp::Main::Database::getChangedUrlsByWebsiteUpdate (std::uint64_t websiteId, const WebsiteProperties & websiteProperties) inherited
Gets the number of URLs that will be modified by updating a website from the database.
Note
URLs will only be modified if the type of the domain changes from using a specific domain to cross-domain, or vice versa, because the name of the domain is saved as part of the URLs if the website is cross-domain.
Parameters
websiteId The ID of the website for which the number of URLs that will be modified will be retrieved from the database.
websiteProperties A constant reference to the new website properties.
Returns
The number of URLs that will be modified by replacing the current properties of the website with the given ones.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero, or if no website namespace or name has been specified in the provided website options.
Main::Database::Exception if a MySQL error occured while retrieving the number of URLs that will be modified from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::WebsiteProperties::domain, crawlservpp::Main::Database::getUrlLists(), crawlservpp::Main::Database::getWebsiteDomain(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Struct::WebsiteProperties::name, crawlservpp::Struct::WebsiteProperties::nameSpace, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), and crawlservpp::Main::wwwPrefix.
getColumnType()
std::string crawlservpp::Main::Database::getColumnType (const std::string & tableName, const std::string & columnName) inherited
Gets the type of a specific table column from the database.
Parameters
tableName Constant reference to a string containing the name of the table in the database from which the type of the column will be retrieved.
columnName Constant reference to a string containing the name of the column whose type will be retrieved.
Returns
A copy of the name of the given table column's data type.
Exceptions
Main::Database::Exception if no table or column name has been specified, i.e. one of the strings containing the name and the column is empty.
Main::Database::Exception if a MySQL error occured while retrieving the type of the given column, e.g. if the specified table does not exist.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::DatabaseSettings::name, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addTargetTable(), and crawlservpp::Wrapper::Database::getColumnType().
getConfiguration()
std::string crawlservpp::Main::Database::getConfiguration (std::uint64_t configId) inherited
Gets a configuration from the database.
Parameters
configId The ID of the configuration to be retrieved from the database.
Returns
A copy of the configuration's JSON string as stored in the database, or an empty string if the given configuration does not exist in the database.
Exceptions
Main::Database::Exception if no configuration has been specified, i.e. the configuration ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the configuration from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Wrapper::Database::getConfiguration(), crawlservpp::Main::Server::Server(), and crawlservpp::Module::Thread::Thread().
getConnectionId()
std::uint64_t crawlservpp::Main::Database::getConnectionId () const inherited
Gets the connection ID.
Returns
The ID of the current connection to the MySQL server or zero if not connected to the database.
getCustomData() [1/6]
void crawlservpp::Main::Database::getCustomData (Data::GetColumn & data) inherited
Gets custom values from a table column in the database.
Parameters
data Reference to the data structure that identifies the column, and to which the result will be written.
Exceptions
Main::Database::Exception if no column or column type is specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetColumn
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Data::_unknown, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::GetColumn::column, crawlservpp::Data::GetColumn::condition, crawlservpp::Main::Database::connection, crawlservpp::Data::GetColumn::order, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Data::GetColumn::table, crawlservpp::Data::GetColumn::type, and crawlservpp::Data::GetColumn::values.
getCustomData() [2/6]
void crawlservpp::Main::Database::getCustomData (Data::GetColumns & data) inherited
Gets custom values from multiple table columns of the same type.
Parameters
data Reference to the data structure that identifies the columns, and to which the result will be written.
Exceptions
Main::Database::Exception if no column or column type is specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetColumns
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Data::_unknown, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::GetColumns::columns, crawlservpp::Data::GetColumns::condition, crawlservpp::Main::Database::connection, crawlservpp::Data::GetColumns::order, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Data::GetColumns::table, crawlservpp::Data::GetColumns::type, and crawlservpp::Data::GetColumns::values.
getCustomData() [3/6]
void crawlservpp::Main::Database::getCustomData (Data::GetColumnsMixed & data) inherited
Gets custom values from multiple table columns of different types.
Parameters
data Reference to the data structure that identifies the columns and their types, and to which the result will be written.
Exceptions
Main::Database::Exception if no columns have been specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetColumnsMixed
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::GetColumnsMixed::columns_types, crawlservpp::Data::GetColumnsMixed::condition, crawlservpp::Main::Database::connection, crawlservpp::Data::GetColumnsMixed::order, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Data::GetColumnsMixed::table, and crawlservpp::Data::GetColumnsMixed::values.
getCustomData() [4/6]
void crawlservpp::Main::Database::getCustomData (Data::GetFields & data) inherited
Gets custom values from multiple columns of the same type from a table row.
Parameters
data Reference to the data structure that identifies the columns, and to which the result will be written.
Exceptions
Main::Database::Exception if no column names or no column type are specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetFields
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Data::_unknown, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::GetFields::columns, crawlservpp::Data::GetFields::condition, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Data::GetFields::table, crawlservpp::Data::GetFields::type, and crawlservpp::Data::GetFields::values.
getCustomData() [5/6]
void crawlservpp::Main::Database::getCustomData (Data::GetFieldsMixed & data) inherited
Gets custom values from multiple columns of different types from a table row.
Parameters
data Reference to the data structure that identifies the columns and their types, and to which the result will be written.
Exceptions
Main::Database::Exception if no columns are specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetFieldsMixed
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::GetFieldsMixed::columns_types, crawlservpp::Data::GetFieldsMixed::condition, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Data::GetFieldsMixed::table, and crawlservpp::Data::GetFieldsMixed::values.
getCustomData() [6/6]
void crawlservpp::Main::Database::getCustomData (Data::GetValue & data) inherited
Gets a custom value from one column from a table row in the database.
Parameters
data Reference to the data structure that identifies the column, and to which the result will be written.
Exceptions
Main::Database::Exception if no column name or no column type is specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetValue
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Data::_unknown, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::GetValue::column, crawlservpp::Data::GetValue::condition, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Data::GetValue::table, crawlservpp::Data::GetValue::type, and crawlservpp::Data::GetValue::value.
Referenced by crawlservpp::Wrapper::Database::getCustomData().
getDataDir()
const std::string & crawlservpp::Main::Database::getDataDir () const inherited
Gets the default data directory.
Returns
A constant reference to the string containing the default data directory for the MySQL server or an empty string if not connected to the database.
getLastInsertedId()
std::uint64_t crawlservpp::Main::Database::getLastInsertedId () protected inherited
Gets the last inserted ID from the database.
Returns
The last inserted ID from the database.
Exceptions
Main::Database::Exception if the prepared SQL statement for retrieving the last inserted ID from the database is missing.
Main::Database::Exception if a MySQL error occured while retrieving the last inserted ID from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getPreparedStatement(), crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addConfiguration(), crawlservpp::Main::Database::addQuery(), crawlservpp::Main::Database::addTargetTable(), crawlservpp::Main::Database::addThread(), crawlservpp::Main::Database::addUrlList(), crawlservpp::Main::Database::addWebsite(), and crawlservpp::Wrapper::Database::getLastInsertedId().
getLostUrlsByWebsiteUpdate()
std::uint64_t crawlservpp::Main::Database::getLostUrlsByWebsiteUpdate (std::uint64_t websiteId, const WebsiteProperties & websiteProperties) inherited
Gets the number of URLs that will be lost by updating a website from the database.
Note
URLs might only be lost if the type of the domain changes from cross-domain to using a specific domain, because in this case, all URLs that do not contain the newly specified domain name, will be lost.
Parameters
websiteId The ID of the website for which the number of URLs that will be lost will be retrieved from the database.
websiteProperties A constant reference to the new website properties.
Returns
The number of URLs that will be lost by replacing the current properties of the website with the given ones.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero, or if no website namespace or name has been specified in the provided website options.
Main::Database::Exception if a MySQL error occured while retrieving the number of URLs that will be lost from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::WebsiteProperties::domain, crawlservpp::Main::Database::getUrlLists(), crawlservpp::Main::Database::getWebsiteDomain(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Struct::WebsiteProperties::name, crawlservpp::Struct::WebsiteProperties::nameSpace, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecuteQuery(), and crawlservpp::Main::wwwPrefix.
getMaxAllowedPacketSize()
std::uint64_t crawlservpp::Main::Database::getMaxAllowedPacketSize () const inherited
Gets the maximum allowed packet size for communicating with the MySQL server.
Returns
The maximum allowed packet size for communicating with the MySQL server, in bytes, or zero if not connected to the database.
Referenced by crawlservpp::Main::Database::deleteUrls(), crawlservpp::Wrapper::Database::getMaxAllowedPacketSize(), crawlservpp::Main::Database::insertCustomData(), and crawlservpp::Main::Database::updateCustomData().
getMysqlVersion()
const std::string & crawlservpp::Main::Database::getMysqlVersion () const inherited
Gets the MySQL version string.
Returns
A constant reference to the string containing the version of the MySQL driver.
Referenced by crawlservpp::Main::Server::Server().
getNumberOfLogEntries()
std::uint64_t crawlservpp::Main::Database::getNumberOfLogEntries (const std::string & logModule) inherited
Gets the number of log entries from the database.
The number can be retrieved for a specific module or for all modules at once.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
logModule Constant reference to a string containing the name of the module, for which the number of log entries will be retrieved, or to an empty string for all log entries to be retrieved.
Returns
The number of log entries for the specified module in the database, or the total number of log entries, if logModule references an empty string.
Exceptions
Main::Database::Exception if a MySQL error occured while getting the number of log entries from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
getPreparedStatement()
sql::PreparedStatement & crawlservpp::Main::Database::getPreparedStatement (std::size_t id) protected inherited
Gets a reference to a prepared SQL statement.
Warning
Do not run checkConnection while using this reference, because the references will be invalidated when reconnecting to the database!
Parameters
id The ID of the prepared SQL statement to retrieve.
Returns
A reference to the prepared SQL statement.
Exceptions
Main::Database::Exception if a MySQL error occured while retrieving the prepared SQL statement.
References crawlservpp::Main::Database::sqlException().
Referenced by crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Main::Database::log(), setThreadLast(), setThreadProgress(), crawlservpp::Main::Database::setThreadStatus(), and setThreadStatusMessage().
getQueryProperties()
void crawlservpp::Main::Database::getQueryProperties (std::uint64_t queryId, QueryProperties & queryPropertiesTo) inherited
Gets the properties of a query from the database.
Parameters
queryId The ID of the query for which the properties will be retrieved from the database.
queryPropertiesTo Reference to the structure to which the retrieved properties of the query will be written.
Exceptions
Main::Database::Exception if no query ID has been specfied, i.e. the query ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the properties of the given query from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Wrapper::Database::getQueryProperties().
getRequestCounter()
static std::uint64_t crawlservpp::Main::Database::getRequestCounter () inline static inherited
Gets the number of SQL requests performed since the start of the application.
Note
By default, the request counter should be deactivated and the function always return zero.
Returns
The number of SQL requests performed since the start of the application or zero, if the request counter had not been activated on compilation.
Referenced by crawlservpp::Wrapper::Database::getRequestCounter(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Main::Database::sqlExecuteUpdate(), and crawlservpp::Main::Database::~Database().
getSettings()
const Database::DatabaseSettings & crawlservpp::Main::Database::getSettings () const inherited
Gets the settings of the database.
Returns
A constant reference to the settings of the database.
getTargetTableId()
std::uint64_t crawlservpp::Main::Database::getTargetTableId (const std::string & type, std::uint64_t listId, const std::string & tableName) inherited
Gets the ID of a target table from the database.
Parameters
type Constant reference to a string containing the type of the target table for which to retrieve its ID.
listId The ID of the URL list associated with the target table for which to retrieve its ID.
tableName Const reference to a string containing the name of the target table for which to retrieve its ID.
Returns
The ID of the specified target table as stored in the database.
Exceptions
Main::Database::Exception if no target table or URL list has been specified, i.e. if the string containing the type is empty, or the target table or the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the ID of the target table from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Wrapper::Database::getTargetTableId().
getTargetTableName()
std::string crawlservpp::Main::Database::getTargetTableName (const std::string & type, std::uint64_t tableId) inherited
Gets the name of a target table from the database.
Parameters
type Constant reference to a string containing the type of the target table for which to retrieve its name.
tableId The ID of the target table for which to retrieve its name.
Returns
A copy of the name of the specified target table as stored in the database.
Exceptions
Main::Database::Exception if no target table has been specified, i.e. the string containing the type is empty or the target table ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the name of the target table from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::deleteTargetTable(), and crawlservpp::Wrapper::Database::getTargetTableName().
getTargetTables()
std::queue< Database::IdString > crawlservpp::Main::Database::getTargetTables (const std::string & type, std::uint64_t listId) inherited
Gets the target tables of the specified type for a URL list from the database.
Parameters
type Constant reference to a string containing the type of the target tables to retrieve.
listId The ID of the URL list for which to retrieve the target tables.
Returns
A queue containing the IDs and names of the target tables of the given type for the specified URL list.
Exceptions
Main::Database::Exception if no target table has been specified, i.e. the string containing the type is empty or the target table ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the target tables from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Wrapper::Database::getTargetTables(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Main::Database::updateUrlList(), and crawlservpp::Main::Database::updateWebsite().
getThreadPauseTime()
std::uint64_t crawlservpp::Main::Database::getThreadPauseTime (std::uint64_t threadId) inherited
Gets the pause time of a thread from the database.
Parameters
threadId The ID of the thread for which the pause time will be retrieved from the database.
Returns
The total number of seconds the given thread has been paused.
Exceptions
Main::Database::Exception if no thread has been specified, i.e. the thread ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the pause time of the thread from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
getThreadRunTime()
std::uint64_t crawlservpp::Main::Database::getThreadRunTime (std::uint64_t threadId) inherited
Gets the run time of a thread from the database.
Parameters
threadId The ID of the thread for which the run time will be retrieved from the database.
Returns
The total number of seconds the given thread has been running, and not been paused.
Exceptions
Main::Database::Exception if no thread has been specified, i.e. the thread ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the run time of the thread from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
getThreads()
std::vector< Database::ThreadDatabaseEntry > crawlservpp::Main::Database::getThreads () inherited
Gets information about all threads from the database.
Returns
A vector containing information about all threads that have been saved in the database.
Exceptions
Main::Database::Exception if a MySQL error occured while getting information about the threads from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Server::Server().
getUrlListNamespace()
std::string crawlservpp::Main::Database::getUrlListNamespace (std::uint64_t listId) inherited
Gets the namespace of a URL list from the database.
Parameters
listId The ID of the URL list whose namespace will be retrieved.
Returns
A copy of the namespace of the given URL list.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the list ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the namespace of the URL list.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Main::Database::deleteUrls(), crawlservpp::Main::Database::getUrlListNamespaceFromTargetTable(), crawlservpp::Main::Database::getUrls(), crawlservpp::Main::Database::getUrlsWithIds(), crawlservpp::Main::Database::mergeUrls(), crawlservpp::Main::Database::resetAnalyzingStatus(), crawlservpp::Main::Database::resetExtractingStatus(), crawlservpp::Main::Database::resetParsingStatus(), crawlservpp::Module::Thread::Thread(), and crawlservpp::Main::Database::updateUrlList().
getUrlListNamespaceFromTargetTable()
Database::IdString crawlservpp::Main::Database::getUrlListNamespaceFromTargetTable (const std::string & type, std::uint64_t tableId) inherited
Gets the namespace of a URL list from the database by using a target table.
Parameters
type Constant reference to a string containing the type of the target table whose URL list's namespace will be retrieved.
tableId The ID of the target table whose URL list's namespace will be retrieved.
Returns
A copy of the namespace of the URL list associated with the given target table.
Exceptions
Main::Database::Exception if no target table type has been specified, i.e. the type is empty, or no target table has been specified, i.e. the string containing the type is empty or the target table ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the namespace of the URL list.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::deleteTargetTable().
getUrlLists()
std::queue< Database::IdString > crawlservpp::Main::Database::getUrlLists (std::uint64_t websiteId) inherited
Gets all URL lists associated with a website from the database.
Parameters
websiteId The ID of the website for which the associated URL lists will be retrieved.
Returns
A queue with pairs containing the IDs and the namespaces of the URL lists associated with the given website.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the URL lists from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::deleteWebsite(), crawlservpp::Main::Database::getChangedUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getLostUrlsByWebsiteUpdate(), crawlservpp::Main::Database::moveWebsite(), and crawlservpp::Main::Database::updateWebsite().
getUrls()
std::queue< std::string > crawlservpp::Main::Database::getUrls (std::uint64_t listId) inherited
Gets all URLs from a URL list in the database.
Parameters
listId The ID of the URL list from which the URLs will be retrieved.
Returns
A queue of strings containing all URLs in the given URL list.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the list ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the URLs from the given URL list in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
getUrlsWithIds()
std::queue< Database::IdString > crawlservpp::Main::Database::getUrlsWithIds (std::uint64_t listId) inherited
Gets all URLs and their IDs from a URL list in the database.
Parameters
listId The ID of the URL list from which the URLs and their IDs will be retrieved.
Returns
A queue of pairs containing the IDs of all URLs in the given URL list and the URLs themselves.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the list ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the URLs and their IDs from the given URL list in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
getWebsiteDataDirectory()
std::string crawlservpp::Main::Database::getWebsiteDataDirectory (std::uint64_t websiteId) inherited
Gets the data directory used by a website.
Parameters
websiteId The ID of the website for which the data directory will be retrieved from the database.
Returns
A copy of the data directory of the given website or an empty string if the default data directory is used.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the data directory of the website from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addTargetTable(), crawlservpp::Main::Database::addUrlList(), and crawlservpp::Main::Database::updateWebsite().
getWebsiteDomain()
std::string crawlservpp::Main::Database::getWebsiteDomain (std::uint64_t websiteId) inherited
Gets the domain of a website from the database.
Parameters
websiteId The ID of the website for which the domain will be retrieved from the database.
Returns
A copy of the domain name of the given website.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the domain name of the given website from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::getChangedUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getLostUrlsByWebsiteUpdate(), crawlservpp::Wrapper::Database::getWebsiteDomain(), and crawlservpp::Main::Database::updateWebsite().
getWebsiteNamespace()
std::string crawlservpp::Main::Database::getWebsiteNamespace (std::uint64_t websiteId) inherited
Gets the namespace of a website from the database.
Parameters
websiteId The ID of the website for which the namespace will be retrieved from the database.
Returns
A copy of the namespace of the given website.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the namespace of the given website from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addUrlList(), crawlservpp::Main::Database::deleteWebsite(), crawlservpp::Main::Database::getChangedUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getLostUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getWebsiteNamespaceFromConfig(), crawlservpp::Main::Database::getWebsiteNamespaceFromTargetTable(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Module::Thread::Thread(), and crawlservpp::Main::Database::updateWebsite().
getWebsiteNamespaceFromConfig()
Database::IdString crawlservpp::Main::Database::getWebsiteNamespaceFromConfig (std::uint64_t configId) inherited
Gets the ID and the namespace of the website associated with a configuration from the database.
Parameters
configId The ID of the configuration for which the ID and namespace of the associated website will be retrieved from the database.
Returns
A pair containing the ID and the namespace of the website associated with the given configuration.
Exceptions
Main::Database::Exception if no configuration has been specified, i.e. the configuration ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the ID and namespace of the website associated with the given configuration from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
getWebsiteNamespaceFromTargetTable()
Database::IdString crawlservpp::Main::Database::getWebsiteNamespaceFromTargetTable (const std::string & type, std::uint64_t tableId) inherited
Gets the ID and the namespace of the website associated with a target table from the database.
Parameters
type Constant reference to a string containing the type of the target table for which the ID and namespace of the associated website will be retrieved from the database.
tableId The ID of the target table for which the ID and namespace of the associated website will be retrieved from the database.
Returns
A pair containing the ID and the namespace of the website associated with the given target table.
Exceptions
Main::Database::Exception if no target table has been specified, i.e. the string containing the type is empty or the target table ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the ID and namespace of the website associated with the given target table from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::deleteTargetTable().
getWebsiteNamespaceFromUrlList()
Database::IdString crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList (std::uint64_t listId) inherited
Gets the ID and the namespace of the website associated with a URL list from the database.
Parameters
listId The ID of the URL list for which the ID and namespace of the associated website will be retrieved from the database.
Returns
A pair containing the ID and the namespace of the website associated with the given URL list.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the ID and namespace of the website associated with the given URL list from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Main::Database::deleteUrls(), crawlservpp::Main::Database::getUrls(), crawlservpp::Main::Database::getUrlsWithIds(), crawlservpp::Main::Database::mergeUrls(), crawlservpp::Main::Database::resetAnalyzingStatus(), crawlservpp::Main::Database::resetExtractingStatus(), crawlservpp::Main::Database::resetParsingStatus(), and crawlservpp::Main::Database::updateUrlList().
initializeSql()
void crawlservpp::Main::Database::initializeSql () inherited
Runs initializing SQL commands by processing all .sql files in the SQL (sub-)folder.
Exceptions
Main::Database::Exception if no SQL statement could be created or a .sql file could not be opened for reading.
Main::Database::Exception if a MySQL error occured while executing the commands inside the .sql files.
References crawlservpp::Helper::FileSystem::listFilesInPath(), crawlservpp::Main::sqlDir, and crawlservpp::Main::sqlExtension.
Referenced by crawlservpp::Main::Server::Server().
insertCustomData() [1/3]
void crawlservpp::Main::Database::insertCustomData (const Data::InsertFields & data) inherited
Inserts custom values into multiple table columns of the same type.
Parameters
data Constant reference to a structure containing the data to be inserted.
Exceptions
Main::Database::Exception if no columns or no column type are specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while inserting the data.
See also
Data::InsertFields
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Data::_unknown, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::InsertFields::columns_values, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getMaxAllowedPacketSize(), crawlservpp::Main::maxContentSize, crawlservpp::Main::maxContentSizeString, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Data::InsertFields::table, and crawlservpp::Data::InsertFields::type.
insertCustomData() [2/3]
void crawlservpp::Main::Database::insertCustomData (const Data::InsertFieldsMixed & data) inherited
Inserts custom values into multiple table columns of different types.
Parameters
data Constant reference to a structure containing the data to be inserted.
Exceptions
Main::Database::Exception if no columns are specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while inserting the data.
See also
Data::InsertFieldsMixed
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::InsertFieldsMixed::columns_types_values, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getMaxAllowedPacketSize(), crawlservpp::Main::maxContentSize, crawlservpp::Main::maxContentSizeString, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), and crawlservpp::Data::InsertFieldsMixed::table.
insertCustomData() [3/3]
void crawlservpp::Main::Database::insertCustomData (const Data::InsertValue & data) inherited
Inserts a custom value into a table row in the database.
Parameters
data Constant reference to a structure containing the data to be inserted.
Exceptions
Main::Database::Exception if no column name or no column type is specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while inserting the data.
See also
Data::InsertValue
References crawlservpp::Data::Value::_b, crawlservpp::Data::_bool, crawlservpp::Data::Value::_d, crawlservpp::Data::_double, crawlservpp::Data::Value::_i32, crawlservpp::Data::Value::_i64, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::Value::_isnull, crawlservpp::Data::Value::_s, crawlservpp::Data::_string, crawlservpp::Data::Value::_ui32, crawlservpp::Data::Value::_ui64, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Data::_unknown, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::InsertValue::column, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getMaxAllowedPacketSize(), crawlservpp::Main::maxContentSize, crawlservpp::Main::maxContentSizeString, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Data::InsertValue::table, crawlservpp::Data::InsertValue::type, and crawlservpp::Data::InsertValue::value.
Referenced by crawlservpp::Wrapper::Database::insertCustomData().
isColumnExists()
bool crawlservpp::Main::Database::isColumnExists (const std::string & tableName, const std::string & columnName) inherited
Checks whether a table in the database contains a specific column.
Parameters
tableName Constant reference to a string containing the name of the table in the database in which the existence of the column will be checked.
columnName Constant reference to a string containing the name of the column to be checked for in the given table.
Returns
True, if the given column exists in the specified table. False otherwise.
Exceptions
Main::Database::Exception if no table or column name has been specified, i.e. one of the strings containing the name and the column is empty.
Main::Database::Exception if a MySQL error occured while checking the existence of the given column, e.g. if the specified table does not exist.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::DatabaseSettings::name, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addTargetTable(), crawlservpp::Module::Analyzer::Database::checkSource(), and crawlservpp::Wrapper::Database::isColumnExists().
isConfiguration() [1/2]
bool crawlservpp::Main::Database::isConfiguration (std::uint64_t configId) inherited
Checks whether a configuration ID is valid.
Parameters
configId The configuration ID to be checked for in the database.
Returns
True, if a configuration with the given ID exists in the database. False otherwise.
Exceptions
Main::Database::Exception if no configuration has been specified, i.e. the configuration ID is zero.
Main::Database::Exception if a MySQL error occured while checking the validity of the given configuration ID in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
isConfiguration() [2/2]
bool crawlservpp::Main::Database::isConfiguration (std::uint64_t websiteId, std::uint64_t configId) inherited
Checks whether a configuration ID is valid for a specific website.
Parameters
websiteId The ID of the website to which the configuration should belong.
configId The configuration ID to be checked for in the database.
Returns
True, if a configuration with the given ID exists in the database and belongs to the specified website. False otherwise.
Exceptions
Main::Database::Exception if no website or no configuration has been specified, i.e. the website ID or the configuration ID is zero.
Main::Database::Exception if a MySQL error occured while checking the validity of the given configuration ID in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
isLogLevel()
bool crawlservpp::Module::Database::isLogLevel (uint8_t level) const
Checks whether a certain logging level is active.
Parameters
level The logging level to be checked for.
Returns
True, if given logging level is active, i.e. if the current logging level larger or equal to the given logging level. False otherwise.
Referenced by crawlservpp::Module::Thread::isLogLevel().
isQuery() [1/2]
bool crawlservpp::Main::Database::isQuery (std::uint64_t queryId) inherited
Checks whether a query ID is valid.
Parameters
queryId The query ID to be checked for in the database.
Returns
True, if a query with the given ID exists in the database. False otherwise.
Exceptions
Main::Database::Exception if no query has been specified, i.e. the query ID is zero.
Main::Database::Exception if a MySQL error occured while checking the validity of the given query ID in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
isQuery() [2/2]
bool crawlservpp::Main::Database::isQuery (std::uint64_t websiteId, std::uint64_t queryId) inherited
Checks whether a query ID is valid for a specific website.
Parameters
websiteId The ID of the website to which the query should belong.
queryId The query ID to be checked for in the database.
Returns
True, if a query with the given ID exists in the database and belongs to the specified website. False otherwise.
Exceptions
Main::Database::Exception if no website or no query has been specified, i.e. the website ID or the query ID is zero.
Main::Database::Exception if a MySQL error occured while checking the validity of the given query ID in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
isTableEmpty()
bool crawlservpp::Main::Database::isTableEmpty (const std::string & tableName) inherited
Checks whether a table in the database is empty.
Parameters
tableName Constant reference to a string containing the name of the table whose contents will be checked in the database.
Returns
True, if the given table is empty. False if it contains data.
Exceptions
Main::Database::Exception if no table name has been specified, i.e. the string containing the name is empty.
Main::Database::Exception if a MySQL error occured while checking the content of the given table in the database, e.g. if the table does not exist.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::clearLogs(), crawlservpp::Main::Database::deleteConfiguration(), crawlservpp::Main::Database::deleteQuery(), crawlservpp::Main::Database::deleteTargetTable(), crawlservpp::Main::Database::deleteThread(), crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Main::Database::deleteWebsite(), and crawlservpp::Wrapper::Database::isTableEmpty().
isTableExists()
bool crawlservpp::Main::Database::isTableExists (const std::string & tableName) inherited
Checks whether a table exists in the database.
Parameters
tableName Constant reference to a string containing the name of the table whose existence in the database will be checked.
Returns
True, if the given table exists in the database. False otherwise.
Exceptions
Main::Database::Exception if no table name has been specified, i.e. the string containing the name is empty.
Main::Database::Exception if a MySQL error occured while checking the existence of the given table in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::DatabaseSettings::name, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addTargetTable(), crawlservpp::Module::Analyzer::Database::checkSource(), and crawlservpp::Wrapper::Database::isTableExists().
isUrlList() [1/2]
bool crawlservpp::Main::Database::isUrlList (std::uint64_t urlListId) inherited
Checks whether a URL list ID is valid.
Parameters
urlListId The URL list ID to be checked for in the database.
Returns
True, if a URL list with the given ID exists in the database. False otherwise.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while checking the validity of the given URL list ID in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
isUrlList() [2/2]
bool crawlservpp::Main::Database::isUrlList (std::uint64_t websiteId, std::uint64_t urlListId) inherited
Checks whether a URL list ID is valid for a specific website.
Parameters
websiteId The ID of the website to which the URL list should belong.
urlListId The URL list ID to be checked for in the database.
Returns
True, if a URL list with the given ID exists in the database and belongs to the specified website. False otherwise.
Exceptions
Main::Database::Exception if no website or no URL list has been specified, i.e. the website ID or the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while checking the validity of the given URL list ID in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
isUrlListCaseSensitive()
bool crawlservpp::Main::Database::isUrlListCaseSensitive (std::uint64_t listId) protected inherited
Gets whether the specified URL list is case-sensitive.
Parameters
listId The ID of the URL list to be checked for case-sensitivity.
Returns
True, if the given URL list is case-sensitive. False otherwise.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the case-sensitivity of the URL list from the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::mergeUrls().
isUrlListNamespace()
bool crawlservpp::Main::Database::isUrlListNamespace (std::uint64_t websiteId, const std::string & nameSpace) inherited
Checks whether a URL list namespace for a specific website exists in the database.
Parameters
websiteId The ID of the website for which the URL list namespace will be checked.
nameSpace Constant reference to a string containing the URL list namespace to be checked.
Returns
True, if the given URL list namespace for the given website already exists in the database. False otherwise.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero, or no URL list namespace has been specified, i.e. the namespace is empty.
Main::Database::Exception if a MySQL error occured while checking the existence of the URL list namespace in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addUrlList(), and crawlservpp::Main::Database::updateUrlList().
isWebsite()
bool crawlservpp::Main::Database::isWebsite (std::uint64_t websiteId) inherited
Checks whether a website ID is valid.
Parameters
websiteId The website ID to be checked for in the database.
Returns
True, if a website with the given ID exists in the database. False otherwise.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero.
Main::Database::Exception if a MySQL error occured while checking the validity of the given website ID in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
isWebsiteNamespace()
bool crawlservpp::Main::Database::isWebsiteNamespace (const std::string & nameSpace) inherited
Checks whether a website namespace exists in the database.
Parameters
nameSpace Constant reference to a string containing the namespace whose existence will be checked in the database.
Returns
True, if a namespace with the given name exists in the database. False otherwise.
Exceptions
Main::Database::Exception if no namespace has been specified, i.e. the string containing the name of the namespace is empty.
Main::Database::Exception if a MySQL error occured while checking the existence of the website namespace in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Main::Database::addWebsite(), crawlservpp::Main::Database::duplicateWebsiteNamespace(), and crawlservpp::Main::Database::updateWebsite().
lockTables()
void crawlservpp::Main::Database::lockTables (std::queue< TableNameWriteAccess > & tableLocks) inherited
Locks tables in the database.
Parameters
tableLocks Reference to a queue of string-bool pairs containing the table names and whether to grant write access to each table.
Exceptions
Main::Database::Exception if a MySQL error occured while locking the given tables, e.g. if another table lock is active.
References crawlservpp::Main::Database::connection, and crawlservpp::Main::Database::sqlException().
log() [1/4]
void crawlservpp::Main::Database::log (const std::string & logEntry) inherited
Adds a log entry to the database for the current module.
Removes invalid UTF-8 characters if necessary.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
logEntry Constant reference to a string containing the log entry to be added to the database.
Exceptions
Main::Database::Exception if a MySQL error occured while adding the log entry to the database. If such an exception is thrown, the log entry will be written to stdout instead.
Referenced by crawlservpp::Main::Database::checkConnection(), log(), crawlservpp::Main::Server::Server(), crawlservpp::Main::Server::tick(), crawlservpp::Main::Database::~Database(), and crawlservpp::Main::Server::~Server().
log() [2/4]
void crawlservpp::Main::Database::log (const std::string & logModule, const std::string & logEntry) inherited
Adds a log entry to the database for any module.
Removes invalid UTF-8 characters if necessary. If characters needed to be removed, a note will be included in the log entry that will be added to the database.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
logModule Constant reference to a string containing the name of the module from which the log entry is added to the database.
logEntry Constant reference to a string containing the log entry to be added to the database.
Exceptions
Main::Database::Exception if the prepared SQL statement for adding a log entry is missing.
Main::Database::Exception if a MySQL error occured while adding the log entry to the database. If such an exception is thrown, the log entry will be written to stdout instead.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getPreparedStatement(), crawlservpp::Helper::Utf8::repairUtf8(), crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
log() [3/4]
void crawlservpp::Module::Database::log (std::uint8_t level, const std::string & logEntry)
Writes a thread-specific log entry to the database.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entry will be written to the logging file as well.
The log entry will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entry. The entry will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntry Constant reference to a string containing the log entry.
References crawlservpp::Main::Database::log(), crawlservpp::Helper::DateTime::now(), and crawlservpp::Helper::Utf8::repairUtf8().
Referenced by crawlservpp::Wrapper::Database::log(), and crawlservpp::Module::Thread::log().
log() [4/4]
void crawlservpp::Module::Database::log (std::uint8_t level, std::queue< std::string > & logEntries)
Writes multiple thread-specific log entries to the database.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entries will be written to the logging file as well.
The log entries will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entries. The entries will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntries Reference to a queue of strings containing the log entries to be written. It will be emptied regardless whether the log entries will be written to the database.
References crawlservpp::Main::Database::log(), and crawlservpp::Helper::Utf8::repairUtf8().
mergeUrls()
std::size_t crawlservpp::Main::Database::mergeUrls (std::uint64_t listId, std::queue< std::string > & urls) inherited
Inserts URLs that do not already exist into a URL list in the database, returns the number of added URLs.
Parameters
listId The ID of the URL list to which those URLs will be added that the list does not already contain.
urls Reference to a queue containing the URLs to be inserted, if they do not already exist in the given URL list. The queue will be emptied, even if URLs will not be added, because they already exist in the URL list.
Returns
The number of URLs actually added.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the list ID is zero.
Main::Database::Exception if a MySQL error occured while checking the existence of the URLs and adding the non-existing URLs to the URL list.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::isUrlListCaseSensitive(), crawlservpp::Main::nAtOnce1000, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::sqlArg4, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecuteUpdate().
moveQuery()
void crawlservpp::Main::Database::moveQuery (std::uint64_t queryId, std::uint64_t toWebsiteId) inherited
Moves a query to another website in the database.
Parameters
queryId The ID of the query that will be moved to another website in the database.
toWebsiteId The ID of the website to which the query will be moved in the database, or zero to change the query into a global query.
Exceptions
Main::Database::Exception if no query has been specified, i.e. the query ID is zero.
Main::Database::Exception if a MySQL error occured while moving the query in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
moveWebsite()
void crawlservpp::Main::Database::moveWebsite (std::uint64_t websiteId, const WebsiteProperties & websiteProperties) inherited
Moves a website and all associated data to another data directory in the database.
Creates temporary copies of all tables first, enough memory needs therefore to be available if both data directories are located on the same physical device.
Warning
Disables the checking of constraints in the database while copying and moving the tables.
Parameters
websiteId The ID of the website that will be moved to another data directory in the database.
websiteProperties Constant reference to the properties of the website to be moved, including the new data directory.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero.
Main::Database::Exception if a MySQL error occured while moving the website and all associated data to another data directory in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::cloneTable(), crawlservpp::Main::Database::connection, crawlservpp::Struct::WebsiteProperties::dir, crawlservpp::Main::Database::dropTable(), crawlservpp::Main::Database::getTargetTables(), crawlservpp::Main::Database::getUrlLists(), crawlservpp::Struct::WebsiteProperties::name, crawlservpp::Struct::DatabaseSettings::name, crawlservpp::Struct::WebsiteProperties::nameSpace, crawlservpp::Main::nAtOnce10, crawlservpp::Main::nAtOnce100, crawlservpp::Main::numUrlListTables, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Main::Database::sqlExecuteQuery(), crawlservpp::Main::Database::Transaction::success(), crawlservpp::Timer::Simple::tickStr(), and crawlservpp::Main::Exception::view().
Referenced by crawlservpp::Main::Database::updateWebsite().
operator=() [1/2]
Database& crawlservpp::Module::Database::operator= (Database &&) delete
Deleted move assignment operator.
operator=() [2/2]
Database& crawlservpp::Module::Database::operator= (Database &) delete
Deleted copy assignment operator.
prepare()
void crawlservpp::Module::Database::prepare ()
Prepares SQL statements for basic thread management.
References crawlservpp::Main::Database::addPreparedStatement(), crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::prepare(), and crawlservpp::Main::Database::reserveForPreparedStatements().
removeDatabaseLock()
void crawlservpp::Main::Database::removeDatabaseLock (const std::string & name) static protected inherited
Removes a lock from the database class.
Does nothing if a lock with the given name does not exist in the database class.
Parameters
name Constant reference to a string containing the name of the lock to be removed from the database class.
Referenced by crawlservpp::Wrapper::Database::removeDatabaseLock().
reserveForPreparedStatements()
void crawlservpp::Main::Database::reserveForPreparedStatements (std::size_t n) protected inherited
Reserves memory for a specific number of additional prepared SQL statements.
Parameters
n Number of prepared SQL statements for which memory should be reserved.
Referenced by prepare(), crawlservpp::Main::Database::prepare(), and crawlservpp::Wrapper::Database::reserveForPreparedStatements().
resetAnalyzingStatus()
void crawlservpp::Main::Database::resetAnalyzingStatus (std::uint64_t listId) inherited
Resets the analyzing status of all URLs in a URL list in the database.
Parameters
listId The ID of the URL list for which the analyzing status will be reset.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while resetting the analyzing state of all URLs in the given URL list.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), and crawlservpp::Main::Database::sqlException().
resetAutoIncrement()
void crawlservpp::Main::Database::resetAutoIncrement (const std::string & tableName) protected inherited
Resets the auto-increment value of an empty table in the database.
Parameters
tableName Const reference to a string containing the name of the table whose auto-increment value will be reset.
Exceptions
Main::Database::Exception if no table is specified, i.e. the string containing the name of the table is empty. *
Main::Database::Exception if a MySQL error occured while resetting the auto-increment value of the table in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Database::clearLogs(), crawlservpp::Main::Database::deleteConfiguration(), crawlservpp::Main::Database::deleteQuery(), crawlservpp::Main::Database::deleteTargetTable(), crawlservpp::Main::Database::deleteThread(), crawlservpp::Main::Database::deleteUrlList(), and crawlservpp::Main::Database::deleteWebsite().
resetExtractingStatus()
void crawlservpp::Main::Database::resetExtractingStatus (std::uint64_t listId) inherited
Resets the extracting status of all URLs in a URL list in the database.
Parameters
listId The ID of the URL list for which the extracting status will be reset.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while resetting the extracting state of all URLs in the given URL list.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), and crawlservpp::Main::Database::sqlException().
resetParsingStatus()
void crawlservpp::Main::Database::resetParsingStatus (std::uint64_t listId) inherited
Resets the parsing status of all URLs in a URL list in the database.
Parameters
listId The ID of the URL list for which the parsing status will be reset.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while resetting the parsing state of all URLs in the given URL list.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), and crawlservpp::Main::Database::sqlException().
setLogging()
void crawlservpp::Module::Database::setLogging (std::uint8_t level, std::uint8_t min, std::uint8_t verbose)
Sets the current, minimal, and verbose logging levels.
Initializes debug logging via logging file if necessary.
Parameters
level The current logging level.
min The minimum logging level.
verbose The verbose logging level.
Exceptions
Module::Database::Exception if the logging file could not be opened for writing.
References crawlservpp::Helper::FileSystem::getPathSeparator().
Referenced by crawlservpp::Wrapper::Database::setLogging().
setOptions()
void crawlservpp::Module::Database::setOptions (const ModuleOptions & moduleOptions)
Sets general options for the module.
Also converts all IDs to strings for easier usage later on.
Parameters
moduleOptions Constant reference to a structure containing the options for the current module.
See also
Struct::ModuleOptions
References crawlservpp::Struct::ModuleOptions::threadId, crawlservpp::Struct::ModuleOptions::urlListId, and crawlservpp::Struct::ModuleOptions::websiteId.
Referenced by crawlservpp::Module::Thread::Thread().
setSleepOnError()
void crawlservpp::Main::Database::setSleepOnError (std::uint64_t seconds) inherited
Sets the number of seconds to sleep before trying to reconnect after connection loss.
Parameters
seconds The number of seconds to wait before trying to reconnect to the MySQL server after the connection got lost.
Referenced by crawlservpp::Main::Server::Server(), and crawlservpp::Wrapper::Database::setSleepOnError().
setThreadId()
void crawlservpp::Module::Database::setThreadId (std::uint64_t threadId)
Sets the ID of the thread.
Also converts it to a string for easier use later on.
Parameters
threadId Sets the ID of the thread.
Exceptions
Module::Database::Exception if no thread ID has been specified, i.e. the given thread ID is zero.
References crawlservpp::Struct::ModuleOptions::threadId.
Referenced by crawlservpp::Module::Thread::Thread().
setThreadLast()
void crawlservpp::Module::Database::setThreadLast (std::uint64_t threadId, std::uint64_t threadLast)
Saves the last ID processed by the thread to the database.
Parameters
threadId The ID of the thread for which the last processed ID will be written to the database.
threadLast The last ID processed by the thread.
Exceptions
Module::Database::Exception if the prepared SQL statement for setting the last ID is missing.
Main::Database::Exception if a MySQL error occured while saving the last ID processed by the thread to the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getPreparedStatement(), crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Module::Thread::incrementLast(), and crawlservpp::Module::Thread::setLast().
setThreadPauseTime()
void crawlservpp::Main::Database::setThreadPauseTime (std::uint64_t threadId, std::uint64_t threadPauseTime) inherited
Updates the pause time of a thread in the database.
Parameters
threadId The ID of the thread for which the pause time will be updated in the database.
threadPauseTime The total number of seconds the given thread has been paused.
Exceptions
Main::Database::Exception if no thread has been specified, i.e. the thread ID is zero.
Main::Database::Exception if a MySQL error occured while updating the pause time of the thread in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
setThreadProgress()
void crawlservpp::Module::Database::setThreadProgress (std::uint64_t threadId, float threadProgress, std::uint64_t threadRunTime)
Saves the current progress and runtime of a thread to the database.
Parameters
threadId The ID of the thread for which progress and runtime will be written to the database.
threadProgress The current progress of the thread between 0.f (0%) and 1.f (100%).
threadRunTime The current runtime of the thread in seconds.
Exceptions
Module::Database::Exception if the prepared SQL statement for setting the progress is missing.
Main::Database::Exception if a MySQL error occured while saving the progress of the thread to the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getPreparedStatement(), crawlservpp::Module::sqlArg1, crawlservpp::Module::sqlArg2, crawlservpp::Module::sqlArg3, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Module::Thread::setProgress().
setThreadRunTime()
void crawlservpp::Main::Database::setThreadRunTime (std::uint64_t threadId, std::uint64_t threadRunTime) inherited
Updates the run time of a thread in the database.
Parameters
threadId The ID of the thread for which the run time will be updated in the database.
threadRunTime The total number of seconds the given thread has been running, and not been paused.
Exceptions
Main::Database::Exception if no thread has been specified, i.e. the thread ID is zero.
Main::Database::Exception if a MySQL error occured while updating the run time of the thread in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
setThreadStatus() [1/2]
void crawlservpp::Main::Database::setThreadStatus (std::uint64_t threadId, bool threadPaused, const std::string & threadStatusMessage) inherited
Updates the status of a thread in the database.
Adds the pause state to the status message if necessary.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
threadId The ID of the thread for which the status will be updated in the database.
threadPaused Specifies whether the thread is currently paused.
threadStatusMessage Constant reference to a string containing the current status of the thread.
Exceptions
Main::Database::Exception if no thread has been specified, i.e. the thread ID is zero, or the prepared SQL statement for setting the thread status is missing.
Main::Database::Exception if a MySQL error occured while updating the status of the thread in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getPreparedStatement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Module::Thread::pause(), crawlservpp::Module::Thread::pauseByThread(), crawlservpp::Module::Thread::setStatusMessage(), crawlservpp::Module::Thread::Thread(), and crawlservpp::Module::Thread::unpause().
setThreadStatus() [2/2]
void crawlservpp::Main::Database::setThreadStatus (std::uint64_t threadId, const std::string & threadStatusMessage) inherited
Updates the status of a thread in the database without changing the pause state of the thread.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
threadId The ID of the thread for which the status will be updated in the database.
threadStatusMessage Constant reference to a string containing the current status of the thread.
Exceptions
Main::Database::Exception if no thread has been specified, i.e. the thread ID is zero, or the prepared SQL statement for setting the thread status is missing.
Main::Database::Exception if a MySQL error occured while updating the status of the thread in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getPreparedStatement(), crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
setThreadStatusMessage()
void crawlservpp::Module::Database::setThreadStatusMessage (std::uint64_t threadId, bool threadPaused, const std::string & threadStatusMessage)
Saves the current status of a thread to the database.
Adds the pause state if necessary.
Parameters
threadId The ID of the thread for which status message and pause state will be written to the database.
threadPaused Specified whether the thread is currently paused.
threadStatusMessage Constant reference to a string containing the current status of the thread.
Exceptions
Module::Database::Exception if the prepared SQL statement for setting the status is missing.
Main::Database::Exception if a MySQL error occured while saving the status of the thread to the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::getPreparedStatement(), crawlservpp::Module::sqlArg1, crawlservpp::Module::sqlArg2, crawlservpp::Module::sqlArg3, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
setTimeOut()
void crawlservpp::Main::Database::setTimeOut (std::uint64_t milliseconds) inherited
Sets the maximum execution time for MySQL queries, in milliseconds.
Note
The database connection needs to be estanblished before setting the time out.
Parameters
milliseconds The number of milliseconds for a MySQL query to run before it gets cancelled, or zero to disable the time-out for MySQL queries.
Exceptions
Main::Database::Exception if a MySQL error occurs while setting the execution time.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Wrapper::Database::setTimeOut().
setUrlListCaseSensitive()
void crawlservpp::Main::Database::setUrlListCaseSensitive (std::uint64_t listId, bool isCaseSensitive) protected inherited
Sets whether the specified URL list is case-sensitive.
Warning
The case-sensitivity should not be changed once URLs have been retrieved!
Parameters
listId The ID of the URL list whose case-sensitivity will be changed.
isCaseSensitive Specify whether URLs in the given URL list will be case-sensitive or not.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while setting the case-sensitivity of the URL list.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Wrapper::Database::setUrlListCaseSensitive().
sqlException()
void crawlservpp::Main::Database::sqlException (const std::string & function, const sql::SQLException & e) static protected inherited
Catches a SQL exception and re-throws it as a specific or a generic Database::Exception.
Note
Always throws an exception.
Parameters
function Constant reference to a string containing the name of the function in which the exception has been thrown.
e Constant reference to the SQL exception that has been thrown.
Exceptions
Main::Database::ConnectionException
Main::Database::StorageEngineException
Main::Database::PrivilegesException
Main::Database::WrongArgumentsException
Main::Database::IncorrectPathException
Main::Database::Exception depending on the SQL exception thrown.
References crawlservpp::Main::sqlAbortedConnection, crawlservpp::Main::sqlBadHandShake, crawlservpp::Main::sqlCannotConnectToServer, crawlservpp::Main::sqlCannotConnectToServerThroughSocket, crawlservpp::Main::sqlCannotCreateIPSocket, crawlservpp::Main::sqlCannotGetHostName, crawlservpp::Main::sqlClientErrorConnectingToMaster, crawlservpp::Main::sqlClientErrorConnectingToSlave, crawlservpp::Main::sqlCouldNotUncompressPackets, crawlservpp::Main::sqlErrorInServerHandshake, crawlservpp::Main::sqlErrorReadingPackets, crawlservpp::Main::sqlErrorWritingPackets, crawlservpp::Main::sqlForcingCloseOfThread, crawlservpp::Main::sqlGotSignal, crawlservpp::Main::sqlIncorrectPath, crawlservpp::Main::sqlInsufficientPrivileges, crawlservpp::Main::sqlInvalidConnectionHandle, crawlservpp::Main::sqlLockWaitTimeOutExceeded, crawlservpp::Main::sqlLostConnectionDuringQuery, crawlservpp::Main::sqlMalformedPacket, crawlservpp::Main::sqlMoreThanMaxUserConnections, crawlservpp::Main::sqlNetErrorReadingFromMaster, crawlservpp::Main::sqlNetErrorWritingToMaster, crawlservpp::Main::sqlNewAbortedConnection, crawlservpp::Main::sqlNormalShutdown, crawlservpp::Main::sqlNumOfLocksExceedsLockTableSize, crawlservpp::Main::sqlPacketsOutOfOrder, crawlservpp::Main::sqlQueryExecutionInterrupted, crawlservpp::Main::sqlReadErrorFromConnectionPipe, crawlservpp::Main::sqlServerErrorConnectingToMaster, crawlservpp::Main::sqlServerHasGoneAway, crawlservpp::Main::sqlServerShutDown, crawlservpp::Main::sqlShutDownComplete, crawlservpp::Main::sqlSortAborted, crawlservpp::Main::sqlSSLConnectionError, crawlservpp::Main::sqlStorageEngineError, crawlservpp::Main::sqlTCPError, crawlservpp::Main::sqlTimeOutReadingPackets, crawlservpp::Main::sqlTimeOutWritingPackets, crawlservpp::Main::sqlTooManyConnections, crawlservpp::Main::sqlUnableToConnectToForeignDataSource, crawlservpp::Main::sqlUnknownServerHost, and crawlservpp::Main::sqlWrongArguments.
Referenced by crawlservpp::Main::Database::addColumn(), crawlservpp::Main::Database::addConfiguration(), crawlservpp::Main::Database::addPreparedStatement(), crawlservpp::Main::Database::addQuery(), crawlservpp::Main::Database::addTargetTable(), crawlservpp::Main::Database::addThread(), crawlservpp::Main::Database::addUrlList(), crawlservpp::Main::Database::addWebsite(), crawlservpp::Main::Database::beginNoLock(), crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::checkDirectory(), crawlservpp::Main::Database::clearLogs(), crawlservpp::Main::Database::cloneTable(), crawlservpp::Main::Database::compressTable(), crawlservpp::Main::Database::connect(), crawlservpp::Main::Database::createTable(), crawlservpp::Main::Database::deleteConfiguration(), crawlservpp::Main::Database::deleteQuery(), crawlservpp::Main::Database::deleteTargetTable(), crawlservpp::Main::Database::deleteThread(), crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Main::Database::deleteUrls(), crawlservpp::Main::Database::deleteWebsite(), crawlservpp::Main::Database::dropTable(), crawlservpp::Main::Database::duplicateConfiguration(), crawlservpp::Main::Database::duplicateQuery(), crawlservpp::Main::Database::duplicateWebsite(), crawlservpp::Main::Database::endNoLock(), crawlservpp::Main::Database::endTransaction(), crawlservpp::Main::Database::getChangedUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getColumnType(), crawlservpp::Main::Database::getConfiguration(), crawlservpp::Main::Database::getCustomData(), crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Main::Database::getLostUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getNumberOfLogEntries(), crawlservpp::Main::Database::getPreparedStatement(), crawlservpp::Main::Database::getQueryProperties(), crawlservpp::Main::Database::getTargetTableId(), crawlservpp::Main::Database::getTargetTableName(), crawlservpp::Main::Database::getTargetTables(), crawlservpp::Main::Database::getThreadPauseTime(), crawlservpp::Main::Database::getThreadRunTime(), crawlservpp::Main::Database::getThreads(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getUrlListNamespaceFromTargetTable(), crawlservpp::Main::Database::getUrlLists(), crawlservpp::Main::Database::getUrls(), crawlservpp::Main::Database::getUrlsWithIds(), crawlservpp::Main::Database::getWebsiteDataDirectory(), crawlservpp::Main::Database::getWebsiteDomain(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromConfig(), crawlservpp::Main::Database::getWebsiteNamespaceFromTargetTable(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::insertCustomData(), crawlservpp::Main::Database::isColumnExists(), crawlservpp::Main::Database::isConfiguration(), crawlservpp::Main::Database::isQuery(), crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::isTableExists(), crawlservpp::Main::Database::isUrlList(), crawlservpp::Main::Database::isUrlListCaseSensitive(), crawlservpp::Main::Database::isUrlListNamespace(), crawlservpp::Main::Database::isWebsite(), crawlservpp::Main::Database::isWebsiteNamespace(), crawlservpp::Main::Database::lockTables(), crawlservpp::Main::Database::log(), crawlservpp::Main::Database::mergeUrls(), crawlservpp::Main::Database::moveQuery(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Main::Database::prepare(), crawlservpp::Main::Database::resetAnalyzingStatus(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::Database::resetExtractingStatus(), crawlservpp::Main::Database::resetParsingStatus(), setThreadLast(), crawlservpp::Main::Database::setThreadPauseTime(), setThreadProgress(), crawlservpp::Main::Database::setThreadRunTime(), crawlservpp::Main::Database::setThreadStatus(), setThreadStatusMessage(), crawlservpp::Main::Database::setTimeOut(), crawlservpp::Main::Database::setUrlListCaseSensitive(), crawlservpp::Wrapper::Database::sqlException(), crawlservpp::Main::Database::startTransaction(), crawlservpp::Main::Database::unlockTables(), crawlservpp::Main::Database::update(), crawlservpp::Main::Database::updateConfiguration(), crawlservpp::Main::Database::updateCustomData(), crawlservpp::Main::Database::updateQuery(), crawlservpp::Main::Database::updateUrlList(), and crawlservpp::Main::Database::updateWebsite().
sqlExecute() [1/2]
template<class T , class... Args> static bool crawlservpp::Main::Database::sqlExecute (std::unique_ptr< T > & statement, Args... args) inline static protected inherited
Template function for executing a SQL query by unique pointer.
Parameters
statement Reference to the unique pointer. to the SQL statement.
args Optional arguments to the underlying function executing the query. When a sql::Statement is used, this should be a null- terminated string containing the text of the SQL query.
Returns
True, if the query returned a result set. False, if the query returned nothing or an update count.
References crawlservpp::Main::Database::sqlExecute().
sqlExecute() [2/2]
template<class T , class... Args> static bool crawlservpp::Main::Database::sqlExecute (T & statement, Args... args) inline static protected inherited
Template function for executing a SQL query.
Parameters
statement Reference to the SQL statement. Can be either a prepared statement or a sql::Statement.
args Optional arguments to the underlying function executing the query. When a sql::Statement is used, this should be a null- terminated string containing the text of the SQL query.
Returns
True, if the query returned a result set. False, if the query returned nothing or an update count.
References crawlservpp::Main::Database::getRequestCounter(), crawlservpp::Main::sleepOnDeadLockMs, and crawlservpp::Main::sqlDeadLock.
Referenced by crawlservpp::Main::Database::addColumn(), crawlservpp::Main::Database::addConfiguration(), crawlservpp::Main::Database::addQuery(), crawlservpp::Main::Database::addTargetTable(), crawlservpp::Main::Database::addThread(), crawlservpp::Main::Database::addUrlList(), crawlservpp::Main::Database::addWebsite(), crawlservpp::Main::Database::checkDirectory(), crawlservpp::Main::Database::clearLogs(), crawlservpp::Main::Database::cloneTable(), crawlservpp::Main::Database::compressTable(), crawlservpp::Main::Database::connect(), crawlservpp::Main::Database::createTable(), crawlservpp::Main::Database::deleteConfiguration(), crawlservpp::Main::Database::deleteQuery(), crawlservpp::Main::Database::deleteTargetTable(), crawlservpp::Main::Database::deleteThread(), crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Main::Database::deleteWebsite(), crawlservpp::Main::Database::dropTable(), crawlservpp::Main::Database::insertCustomData(), crawlservpp::Main::Database::log(), crawlservpp::Main::Database::moveQuery(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Main::Database::resetAutoIncrement(), setThreadLast(), crawlservpp::Main::Database::setThreadPauseTime(), setThreadProgress(), crawlservpp::Main::Database::setThreadRunTime(), crawlservpp::Main::Database::setThreadStatus(), setThreadStatusMessage(), crawlservpp::Main::Database::setTimeOut(), crawlservpp::Main::Database::setUrlListCaseSensitive(), crawlservpp::Wrapper::Database::sqlExecute(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Main::Database::update(), crawlservpp::Main::Database::updateConfiguration(), crawlservpp::Main::Database::updateCustomData(), crawlservpp::Main::Database::updateQuery(), crawlservpp::Main::Database::updateUrlList(), and crawlservpp::Main::Database::updateWebsite().
sqlExecuteQuery() [1/2]
template<class T , class... Args> static sql::ResultSet* crawlservpp::Main::Database::sqlExecuteQuery (std::unique_ptr< T > & statement, Args... args) inline static protected inherited
Template function for executing a SQL query by unique pointer and returning the resulting set.
Parameters
statement Reference to the unique pointer. to the SQL statement.
args Optional arguments to the underlying function executing the query. When a sql::Statement is used, this should be a null- terminated string containing the text of the SQL query.
Returns
A pointer to the result set retrieved by executing the SQL query.
References crawlservpp::Main::Database::sqlExecuteQuery().
sqlExecuteQuery() [2/2]
template<class T , class... Args> static sql::ResultSet* crawlservpp::Main::Database::sqlExecuteQuery (T & statement, Args... args) inline static protected inherited
Template function for executing a SQL query and returning the resulting set.
Parameters
statement Reference to the SQL statement. Can be either a prepared statement or a sql::Statement.
args Optional arguments to the underlying function executing the query. When a sql::Statement is used, this should be a null- terminated string containing the text of the SQL query.
Returns
A pointer to the result set retrieved by executing the SQL query.
References crawlservpp::Main::Database::getRequestCounter(), crawlservpp::Main::sleepOnDeadLockMs, and crawlservpp::Main::sqlDeadLock.
Referenced by crawlservpp::Main::Database::addTargetTable(), crawlservpp::Main::Database::cloneTable(), crawlservpp::Main::Database::compressTable(), crawlservpp::Main::Database::connect(), crawlservpp::Main::Database::duplicateConfiguration(), crawlservpp::Main::Database::duplicateQuery(), crawlservpp::Main::Database::duplicateWebsite(), crawlservpp::Main::Database::getChangedUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getColumnType(), crawlservpp::Main::Database::getConfiguration(), crawlservpp::Main::Database::getCustomData(), crawlservpp::Main::Database::getLastInsertedId(), crawlservpp::Main::Database::getLostUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getNumberOfLogEntries(), crawlservpp::Main::Database::getQueryProperties(), crawlservpp::Main::Database::getTargetTableId(), crawlservpp::Main::Database::getTargetTableName(), crawlservpp::Main::Database::getTargetTables(), crawlservpp::Main::Database::getThreadPauseTime(), crawlservpp::Main::Database::getThreadRunTime(), crawlservpp::Main::Database::getThreads(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getUrlListNamespaceFromTargetTable(), crawlservpp::Main::Database::getUrlLists(), crawlservpp::Main::Database::getUrls(), crawlservpp::Main::Database::getUrlsWithIds(), crawlservpp::Main::Database::getWebsiteDataDirectory(), crawlservpp::Main::Database::getWebsiteDomain(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromConfig(), crawlservpp::Main::Database::getWebsiteNamespaceFromTargetTable(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::isColumnExists(), crawlservpp::Main::Database::isConfiguration(), crawlservpp::Main::Database::isQuery(), crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::isTableExists(), crawlservpp::Main::Database::isUrlList(), crawlservpp::Main::Database::isUrlListCaseSensitive(), crawlservpp::Main::Database::isUrlListNamespace(), crawlservpp::Main::Database::isWebsite(), crawlservpp::Main::Database::isWebsiteNamespace(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Wrapper::Database::sqlExecuteQuery(), and crawlservpp::Main::Database::sqlExecuteQuery().
sqlExecuteUpdate() [1/2]
template<class T , class... Args> static int crawlservpp::Main::Database::sqlExecuteUpdate (std::unique_ptr< T > & statement, Args... args) inline static protected inherited
Template function for executing a SQL query by unique pointer and returning the number of affected rows.
Parameters
statement Reference to the unique pointer. to the SQL statement.
args Optional arguments to the underlying function executing the query. When a sql::Statement is used, this should be a null- terminated string containing the text of the SQL query.
Returns
The number of rows affected by the SQL query.
References crawlservpp::Main::Database::sqlExecuteUpdate().
sqlExecuteUpdate() [2/2]
template<class T , class... Args> static int crawlservpp::Main::Database::sqlExecuteUpdate (T & statement, Args... args) inline static protected inherited
Template function for executing a SQL query and returning the number of affected rows.
Parameters
statement Reference to the SQL statement. Can be either a prepared statement or a sql::Statement.
args Optional arguments to the underlying function executing the query. When a sql::Statement is used, this should be a null- terminated string containing the text of the query.
Returns
The number of rows affected by the SQL query.
References crawlservpp::Main::Database::getRequestCounter(), crawlservpp::Main::sleepOnDeadLockMs, and crawlservpp::Main::sqlDeadLock.
Referenced by crawlservpp::Main::Database::mergeUrls(), crawlservpp::Wrapper::Database::sqlExecuteUpdate(), and crawlservpp::Main::Database::sqlExecuteUpdate().
startTransaction()
void crawlservpp::Main::Database::startTransaction (const std::string & isolationLevel) inherited
Starts a new transaction with the database using a specific isolation level.
Parameters
isolationLevel Constant reference to a string containing the isolation level to be used, or to an empty string if the default isolation level should be used.
Exceptions
Main::Database::Exception if a MySQL error occured while starting the SQL transaction.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, and crawlservpp::Main::Database::sqlException().
Referenced by crawlservpp::Main::Database::Transaction::Transaction().
tryDatabaseLock()
bool crawlservpp::Main::Database::tryDatabaseLock (const std::string & name) static protected inherited
Tries to add a lock to the database class, not blocking execution.
If a lock with the same name already exists, the function will not add a lock and return false instead.
Parameters
name Constant reference to a string containing the name of the lock to be added to the database class if a lock with the same name does not exist already.
Returns
True, if a lock with the same name did not exist already and the lock has been added. False, if a lock with the same name already exists and no lock has been added.
Referenced by crawlservpp::Wrapper::Database::tryDatabaseLock().
unlockTables()
void crawlservpp::Main::Database::unlockTables () inherited
Unlocks all previously locked tables in the database.
Exceptions
Main::Database::Exception if a MySQL error occured while unlocking all previously locked tables.
References crawlservpp::Main::Database::connection, and crawlservpp::Main::Database::sqlException().
update()
void crawlservpp::Main::Database::update () inherited
Updates the tables with language and version information in the database.
Creates the tables if they do not exist yet.
Exceptions
Main::Database::Exception if a MySQL error occured while creating or updating those tables.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::createTable(), crawlservpp::Main::Database::dropTable(), crawlservpp::Helper::Portability::enumLocales(), crawlservpp::Helper::Versions::getLibraryVersions(), crawlservpp::Main::Version::getString(), crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Main::Server::Server().
updateConfiguration()
void crawlservpp::Main::Database::updateConfiguration (std::uint64_t configId, const ConfigProperties & configProperties) inherited
Updates a configuration in the database.
Note
The name of the module will not be updated.
Parameters
configId The ID of the configuration to be updated in the database.
configProperties Constant reference to the new properties of the configuration. The name of the module specified in these properties will be ignored.
Exceptions
Main::Database::Exception if no configuration has been specified, i.e. the configuration ID is zero, or if no name or configuration has been specified in the given properties of the configuration.
Main::Database::Exception if a MySQL error occured while updating the configuration in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Struct::ConfigProperties::config, crawlservpp::Main::Database::connection, crawlservpp::Struct::ConfigProperties::name, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
updateCustomData() [1/3]
void crawlservpp::Main::Database::updateCustomData (const Data::UpdateFields & data) inherited
Updates custom values in multiple table columns of the same type.
Parameters
data Constant reference to a structure containing the data to be updated.
Exceptions
Main::Database::Exception if no columns or no column type are specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while updating the data.
See also
Data::UpdateFields
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Data::_unknown, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::UpdateFields::columns_values, crawlservpp::Data::UpdateFields::condition, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getMaxAllowedPacketSize(), crawlservpp::Main::maxContentSize, crawlservpp::Main::maxContentSizeString, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Data::UpdateFields::table, and crawlservpp::Data::UpdateFields::type.
updateCustomData() [2/3]
void crawlservpp::Main::Database::updateCustomData (const Data::UpdateFieldsMixed & data) inherited
Updates custom values in multiple table columns of different types.
Parameters
data Constant reference to a structure containing the data to be updated.
Exceptions
Main::Database::Exception if no columns are specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while updating the data.
See also
Data::UpdateFieldsMixed
References crawlservpp::Data::_bool, crawlservpp::Data::_double, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::_string, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::UpdateFieldsMixed::columns_types_values, crawlservpp::Data::UpdateFieldsMixed::condition, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getMaxAllowedPacketSize(), crawlservpp::Main::maxContentSize, crawlservpp::Main::maxContentSizeString, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), and crawlservpp::Data::UpdateFieldsMixed::table.
updateCustomData() [3/3]
void crawlservpp::Main::Database::updateCustomData (const Data::UpdateValue & data) inherited
Updates a custom value in a table row.
Parameters
data Constant reference to a structure containing the data to be updated.
Exceptions
Main::Database::Exception if no column name or no column type is specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while updating the data.
See also
Data::UpdateValue
References crawlservpp::Data::Value::_b, crawlservpp::Data::_bool, crawlservpp::Data::Value::_d, crawlservpp::Data::_double, crawlservpp::Data::Value::_i32, crawlservpp::Data::Value::_i64, crawlservpp::Data::_int32, crawlservpp::Data::_int64, crawlservpp::Data::Value::_isnull, crawlservpp::Data::Value::_s, crawlservpp::Data::_string, crawlservpp::Data::Value::_ui32, crawlservpp::Data::Value::_ui64, crawlservpp::Data::_uint32, crawlservpp::Data::_uint64, crawlservpp::Data::_unknown, crawlservpp::Main::Database::checkConnection(), crawlservpp::Data::UpdateValue::column, crawlservpp::Data::UpdateValue::condition, crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getMaxAllowedPacketSize(), crawlservpp::Main::maxContentSize, crawlservpp::Main::maxContentSizeString, crawlservpp::Main::sqlArg1, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Data::UpdateValue::table, crawlservpp::Data::UpdateValue::type, and crawlservpp::Data::UpdateValue::value.
Referenced by crawlservpp::Wrapper::Database::updateCustomData().
updateQuery()
void crawlservpp::Main::Database::updateQuery (std::uint64_t queryId, const QueryProperties & queryProperties) inherited
Updates a query in the database.
Replaces the current query properties with the given ones.
Parameters
queryId The ID of the query that will be updated in the database.
queryProperties A constant reference to the new query properties.
Exceptions
Main::Database::Exception if no query has been specified, i.e. the query ID is zero, or if no name, namespace or text has been specified in the provided query properties.
Main::Database::Exception if a MySQL error occured while updating the query in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::QueryProperties::name, crawlservpp::Struct::QueryProperties::resultBool, crawlservpp::Struct::QueryProperties::resultMulti, crawlservpp::Struct::QueryProperties::resultSingle, crawlservpp::Struct::QueryProperties::resultSubSets, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::sqlArg4, crawlservpp::Main::sqlArg5, crawlservpp::Main::sqlArg6, crawlservpp::Main::sqlArg7, crawlservpp::Main::sqlArg8, crawlservpp::Main::sqlArg9, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), crawlservpp::Struct::QueryProperties::text, crawlservpp::Struct::QueryProperties::textOnly, and crawlservpp::Struct::QueryProperties::type.
updateUrlList()
void crawlservpp::Main::Database::updateUrlList (std::uint64_t listId, const UrlListProperties & listProperties) inherited
Updates a URL list and all associated tables in the database.
Replaces the current URL list properties with the given ones.
Changing the namespace will result in the renaming of all associated tables.
Parameters
listId The ID of the URL list that will be updated in the database.
listProperties A constant reference to the new URL list properties.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero, if no URL list namespace or name has been specified in the provided website options, or if the new namespace already exists in the database.
Main::Database::Exception if a MySQL error occured while updating the URL list and all associated tables in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Main::Database::getTargetTables(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::isUrlListNamespace(), crawlservpp::Struct::UrlListProperties::name, crawlservpp::Struct::UrlListProperties::nameSpace, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::Database::sqlException(), and crawlservpp::Main::Database::sqlExecute().
updateWebsite()
void crawlservpp::Main::Database::updateWebsite (std::uint64_t websiteId, const WebsiteProperties & websiteProperties) inherited
Updates a website and all associated tables in the database.
Replaces the current website properties with the given ones.
Changing the namespace will result in the renaming of all associated tables.
URLs will be changed, if the type of the domain changes from using a specific domain to cross-domain, or vice versa, because the name of the domain is saved as part of the URLs if the website is cross-domain.
Warning
URLs might be lost if the type of the domain changes from cross-domain to using a specific domain, because in this case, all URLs that do not contain the newly specified domain name, will be lost.
Parameters
websiteId The ID of the website that will be updated in the database.
websiteProperties A constant reference to the new website properties.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero, if no website namespace or name has been specified in the provided website options, or if the new namespace already exists in the database.
Main::Database::Exception if a MySQL error occured while updating the website, its URLs and all associated tables in the database.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connection, crawlservpp::Struct::WebsiteProperties::dir, crawlservpp::Struct::WebsiteProperties::domain, crawlservpp::Main::Database::getTargetTables(), crawlservpp::Main::Database::getUrlLists(), crawlservpp::Main::Database::getWebsiteDataDirectory(), crawlservpp::Main::Database::getWebsiteDomain(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::Database::isWebsiteNamespace(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Struct::WebsiteProperties::name, crawlservpp::Struct::WebsiteProperties::nameSpace, crawlservpp::Main::sqlArg1, crawlservpp::Main::sqlArg2, crawlservpp::Main::sqlArg3, crawlservpp::Main::sqlArg4, crawlservpp::Main::Database::sqlException(), crawlservpp::Main::Database::sqlExecute(), and crawlservpp::Main::wwwPrefix.
Friends And Related Function Documentation
Wrapper::Database
friend class Wrapper::Database friend
Allows access to module threads.
Member Data Documentation
connection
std::unique_ptr<sql::Connection> crawlservpp::Main::Database::connection protected inherited
Database connection.
Referenced by crawlservpp::Main::Database::addColumn(), crawlservpp::Main::Database::addConfiguration(), crawlservpp::Main::Database::addPreparedStatement(), crawlservpp::Main::Database::addQuery(), crawlservpp::Main::Database::addTargetTable(), crawlservpp::Main::Database::addThread(), crawlservpp::Main::Database::addUrlList(), crawlservpp::Main::Database::addWebsite(), crawlservpp::Main::Database::beginNoLock(), crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::checkDirectory(), crawlservpp::Main::Database::clearLogs(), crawlservpp::Main::Database::cloneTable(), crawlservpp::Main::Database::compressTable(), crawlservpp::Main::Database::connect(), crawlservpp::Main::Database::createTable(), crawlservpp::Main::Database::deleteConfiguration(), crawlservpp::Main::Database::deleteQuery(), crawlservpp::Main::Database::deleteTargetTable(), crawlservpp::Main::Database::deleteThread(), crawlservpp::Main::Database::deleteUrlList(), crawlservpp::Main::Database::deleteWebsite(), crawlservpp::Main::Database::dropTable(), crawlservpp::Main::Database::duplicateConfiguration(), crawlservpp::Main::Database::duplicateQuery(), crawlservpp::Main::Database::duplicateWebsite(), crawlservpp::Main::Database::endNoLock(), crawlservpp::Main::Database::endTransaction(), crawlservpp::Main::Database::getChangedUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getColumnType(), crawlservpp::Main::Database::getConfiguration(), crawlservpp::Main::Database::getCustomData(), crawlservpp::Main::Database::getLostUrlsByWebsiteUpdate(), crawlservpp::Main::Database::getNumberOfLogEntries(), crawlservpp::Main::Database::getQueryProperties(), crawlservpp::Main::Database::getTargetTableId(), crawlservpp::Main::Database::getTargetTableName(), crawlservpp::Main::Database::getTargetTables(), crawlservpp::Main::Database::getThreadPauseTime(), crawlservpp::Main::Database::getThreadRunTime(), crawlservpp::Main::Database::getThreads(), crawlservpp::Main::Database::getUrlListNamespace(), crawlservpp::Main::Database::getUrlListNamespaceFromTargetTable(), crawlservpp::Main::Database::getUrlLists(), crawlservpp::Main::Database::getUrls(), crawlservpp::Main::Database::getUrlsWithIds(), crawlservpp::Main::Database::getWebsiteDataDirectory(), crawlservpp::Main::Database::getWebsiteDomain(), crawlservpp::Main::Database::getWebsiteNamespace(), crawlservpp::Main::Database::getWebsiteNamespaceFromConfig(), crawlservpp::Main::Database::getWebsiteNamespaceFromTargetTable(), crawlservpp::Main::Database::getWebsiteNamespaceFromUrlList(), crawlservpp::Main::Database::insertCustomData(), crawlservpp::Main::Database::isColumnExists(), crawlservpp::Main::Database::isConfiguration(), crawlservpp::Main::Database::isQuery(), crawlservpp::Main::Database::isTableEmpty(), crawlservpp::Main::Database::isTableExists(), crawlservpp::Main::Database::isUrlList(), crawlservpp::Main::Database::isUrlListCaseSensitive(), crawlservpp::Main::Database::isUrlListNamespace(), crawlservpp::Main::Database::isWebsite(), crawlservpp::Main::Database::isWebsiteNamespace(), crawlservpp::Main::Database::lockTables(), crawlservpp::Main::Database::mergeUrls(), crawlservpp::Main::Database::moveQuery(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Main::Database::resetAutoIncrement(), crawlservpp::Main::Database::setThreadPauseTime(), crawlservpp::Main::Database::setThreadRunTime(), crawlservpp::Main::Database::setTimeOut(), crawlservpp::Main::Database::setUrlListCaseSensitive(), crawlservpp::Main::Database::startTransaction(), crawlservpp::Main::Database::unlockTables(), crawlservpp::Main::Database::update(), crawlservpp::Main::Database::updateConfiguration(), crawlservpp::Main::Database::updateCustomData(), crawlservpp::Main::Database::updateQuery(), crawlservpp::Main::Database::updateUrlList(), crawlservpp::Main::Database::updateWebsite(), and crawlservpp::Main::Database::~Database().
driver
sql::Driver * crawlservpp::Main::Database::driver {nullptr} static protected inherited
Pointer to the MySQL database driver.
Referenced by crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::connect(), Database(), crawlservpp::Main::Database::Database(), and ~Database().
The documentation for this class was generated from the following files:
Module/Database.hpp
Module/Database.cpp