crawlserv++: crawlservpp::Parsing::XML Class Reference
crawlservpp::Parsing::XML Class Reference
Parses HTML markup into clean XML.
#include <XML.hpp>
Classes
class Exception
Class for XML exceptions.
Friends
class Query::XPath
Construction and Destruction
XML ()=default
Default constructor.
XML (const pugi::xml_node &node)
Constructor creating a new XML document from an existing XML node.
virtual ~XML ()
Destructor clearing the underlying XML document.
Getters
bool valid () const
Returns whether the underlying document is valid.
void getContent (std::string &resultTo) const
Gets the stringified content inside the underlying document.
Setter
void setOptions (bool showWarnings, std::uint32_t numOfErrors) noexcept
Sets logging options.
Parsing
void parse (std::string_view content, bool repairCData, bool repairComments, std::queue< std::string > &warningsTo)
Parses the given HTML markup into the underlying XML document.
Cleanup
void clear ()
Clears the content of the underlying XML document.
Copy and Move
The class is not copyable, only moveable.
XML (const XML &)=delete
Deleted copy constructor.
XML (XML &&) noexcept=default
Default move constructor.
XML & operator= (const XML &)=delete
Deleted copy assignment operator.
XML & operator= (XML &&) noexcept=default
Default move assignment operator.
Detailed Description
Parses HTML markup into clean XML.
Uses the tidy-html5 via Parsing::HTML and the pugixml library to parse, tidy up and clean the given HTML markup and to convert it into clean XML markup.
For more information about pugixml, see its GitHub repository.
Constructor & Destructor Documentation
XML() [1/4]
crawlservpp::Parsing::XML::XML () default
Default constructor.
XML() [2/4]
crawlservpp::Parsing::XML::XML (const pugi::xml_node & node) inline explicit
Constructor creating a new XML document from an existing XML node.
Parameters
node The node which should be added as root node to the new XML document.
~XML()
crawlservpp::Parsing::XML::~XML () inline virtual
Destructor clearing the underlying XML document.
References clear().
XML() [3/4]
crawlservpp::Parsing::XML::XML (const XML &) delete
Deleted copy constructor.
XML() [4/4]
crawlservpp::Parsing::XML::XML (XML &&) default noexcept
Default move constructor.
Member Function Documentation
clear()
void crawlservpp::Parsing::XML::clear () inline
Clears the content of the underlying XML document.
Does not have any effect if no content has been parsed.
Referenced by crawlservpp::Query::Container::clearQueryTarget(), and ~XML().
getContent()
void crawlservpp::Parsing::XML::getContent (std::string & resultTo) const inline
Gets the stringified content inside the underlying document.
The result will be intended with tabs (\t).
The output string will be overwritten, if no exception is thrown.
Warning
Should only be called if XML markup has been successfully parsed.
Parameters
resultTo A reference to the string that will be replaced with the content from the underlying document.
Exceptions
XML::Exception if no content is available.
Referenced by crawlservpp::Query::Container::getXml().
operator=() [1/2]
XML& crawlservpp::Parsing::XML::operator= (const XML &) delete
Deleted copy assignment operator.
operator=() [2/2]
XML& crawlservpp::Parsing::XML::operator= (XML &&) default noexcept
Default move assignment operator.
parse()
void crawlservpp::Parsing::XML::parse (std::string_view content, bool repairCData, bool repairComments, std::queue< std::string > & warningsTo) inline
Parses the given HTML markup into the underlying XML document.
A copy of the given markup will be created and ASCII whitespaces at the beginning of the input will be removed.
Parameters
content A view into the HTML markup to be parsed.
repairCData Specify whether the class should try to repair broken CDATA elements in the input.
repairComments Specify whether the class should try to replace broken comments in the input.
warningsTo A reference to a queue of strings to which warnings and errors will be added according to the specified options.
Exceptions
XML::Exception if a HTML::Exception has been thrown.
See also
setOptions, getContent
References crawlservpp::Parsing::numDebugCharacters, crawlservpp::Parsing::HTML::tidyAndConvert(), crawlservpp::Main::Exception::view(), and crawlservpp::Parsing::xmlBegin.
setOptions()
void crawlservpp::Parsing::XML::setOptions (bool showWarnings, std::uint32_t numOfErrors) inline noexcept
Sets logging options.
Forwards the given values to the underlying Parsing::HTML document.
Parameters
showWarnings Specify whether to report simple warnings. The default is false.
numOfErrors Set the number of errors to be reported. The default is zero.
See also
Parsing::HTML::tidyAndConvert
Referenced by crawlservpp::Query::Container::setTidyErrorsAndWarnings().
valid()
bool crawlservpp::Parsing::XML::valid () const inline
Returns whether the underlying document is valid.
Returns
True, if the underlying document is valid, i.e. XML content has been sucessfully parsed. False otherwise.
Friends And Related Function Documentation
Query::XPath
friend class Query::XPath friend
The documentation for this class was generated from the following file:
Parsing/XML.hpp