crawlserv++: crawlservpp::Data::Compression::Zlib::Exception Class Reference
crawlservpp::Data::Compression::Zlib::Exception Class Reference
Class for zlib exceptions.
#include <Zlib.hpp>
Public Member Functions
Exception (const std::string &description)
Getter
std::string_view view () const noexcept
Gets the description of the exception as a view to the underlying string.
Detailed Description
Class for zlib exceptions.
This exception is being thrown when
zlib compression could not be initialized
zlib decompression could not be initialized
compressing content using zlib failed
decompressing zlib-compressed content failed
See also
compress, decompress
Constructor & Destructor Documentation
Exception()
crawlservpp::Data::Compression::Zlib::Exception::Exception (const std::string & description) inline explicit
Member Function Documentation
view()
std::string_view crawlservpp::Main::Exception::view () const inline noexcept inherited
Gets the description of the exception as a view to the underlying string.
Returns
A view to the string containing the description of the exception.
Referenced by crawlservpp::Query::Container::addQuery(), crawlservpp::Query::Container::addSubSetsFromQueryOnSubSet(), crawlservpp::Main::Database::duplicateWebsite(), crawlservpp::Query::Container::getBoolFromQuery(), crawlservpp::Query::Container::getBoolFromQueryOnSubSet(), crawlservpp::Query::Container::getBoolFromRegEx(), crawlservpp::Module::Analyzer::Database::getCorpus(), crawlservpp::Query::Container::getMultiFromQuery(), crawlservpp::Query::Container::getMultiFromQueryOnSubSet(), crawlservpp::Query::Container::getMultiFromRegEx(), crawlservpp::Network::Curl::getPublicIp(), crawlservpp::Query::Container::getSingleFromQuery(), crawlservpp::Query::Container::getSingleFromQueryOnSubSet(), crawlservpp::Query::Container::getSingleFromRegEx(), crawlservpp::Module::Config::loadConfig(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Parsing::XML::parse(), crawlservpp::Main::Server::Server(), crawlservpp::Query::Container::setSubSetsFromQuery(), crawlservpp::Main::Server::tick(), and crawlservpp::Main::Server::~Server().
The documentation for this class was generated from the following file:
Data/Compression/Zlib.hpp