crawlserv++: crawlservpp::Main::App Class Reference
crawlservpp::Main::App Class Reference final
Main application.
#include <App.hpp>
Construction and Destruction
App (const std::vector< std::string > &args) noexcept
Constructor.
virtual ~App ()
Destructor waiting for active threads before cleaning up the application.
Execution
int run () noexcept
Runs the application.
Signal Handling
static volatile std::sig_atomic_t interruptionSignal {0}
Received signal, or zero if none has been received.
void shutdown ()
In-class signal handler shutting down the application.
static void signal (int signalNumber)
Static signal handler forwarding a signal to the class.
Copy and Move
The class is neither copyable, nor moveable.
App (App &)=delete
Deleted copy constructor.
App & operator= (App &)=delete
Deleted copy assignment operator.
App (App &&)=delete
Deleted move constructor.
App & operator= (App &&)=delete
Deleted move assignment operator.
Detailed Description
Main application.
This class
writes default output to stdout
checks the program arguments
loads the configuration file
runs the command-and-control server
handles signals by the operating system
Constructor & Destructor Documentation
App() [1/3]
crawlservpp::Main::App::App (const std::vector< std::string > & args) explicit noexcept
Constructor.
Writes the application header to stdout, checks the program arguments, loads the configuration from the configuration file, gets the database password from the user (i.e. stdin), initializes and finally runs the command-and-control server.
Parameters
args Constant reference to a vector contining the program arguments passed to the application, e.g. via the command line.
References signal().
~App()
crawlservpp::Main::App::~App () virtual
Destructor waiting for active threads before cleaning up the application.
References crawlservpp::Helper::DateTime::secondsToString().
App() [2/3]
crawlservpp::Main::App::App (App &) delete
Deleted copy constructor.
App() [3/3]
crawlservpp::Main::App::App (App &&) delete
Deleted move constructor.
Member Function Documentation
operator=() [1/2]
App& crawlservpp::Main::App::operator= (App &&) delete
Deleted move assignment operator.
operator=() [2/2]
App& crawlservpp::Main::App::operator= (App &) delete
Deleted copy assignment operator.
run()
int crawlservpp::Main::App::run () noexcept
Runs the application.
References interruptionSignal, and shutdown().
Referenced by main().
shutdown()
void crawlservpp::Main::App::shutdown ()
In-class signal handler shutting down the application.
References interruptionSignal, and signal().
Referenced by run().
signal()
void crawlservpp::Main::App::signal (int signalNumber) static
Static signal handler forwarding a signal to the class.
References interruptionSignal.
Referenced by App(), and shutdown().
Member Data Documentation
interruptionSignal
volatile std::sig_atomic_t crawlservpp::Main::App::interruptionSignal {0} static
Received signal, or zero if none has been received.
Referenced by run(), shutdown(), and signal().
The documentation for this class was generated from the following files:
Main/App.hpp
Main/App.cpp