crawlserv++: crawlservpp::Timer::StartStopHR Class Reference
crawlservpp::Timer::StartStopHR Class Reference
A simple start/stop watch with high resolution.
#include <StartStopHR.hpp>
Construction
StartStopHR ()
Constructor initializing the values.
Control functions
void start ()
Starts the timer.
void stop ()
Stops the timer.
void reset ()
Resets the timer.
Getter
std::string totalStr ()
Gets the total duration as formatted string.
Internal state
std::chrono::high_resolution_clock::time_point timePoint
(Time) point of start.
std::chrono::high_resolution_clock::duration duration
Duration of previous runs.
Detailed Description
A simple start/stop watch with high resolution.
Accumulates the number of passed microseconds while runnning.
Note
This timer needs to be started manually.
Constructor & Destructor Documentation
StartStopHR()
crawlservpp::Timer::StartStopHR::StartStopHR () inline
Constructor initializing the values.
Note
Other than Timer::Simple and Timer::SimpleHR, this timer will not be started automatically on creation.
See also
start
Member Function Documentation
reset()
void crawlservpp::Timer::StartStopHR::reset () inline
Resets the timer.
Warning
The number of microseconds stored internally will be lost.
References duration, and timePoint.
start()
void crawlservpp::Timer::StartStopHR::start () inline
Starts the timer.
Microseconds will be accumulated starting from now on.
If the timer is already running, it will first be stopped, i.e. the number of microseconds stored internally will be refreshed.
See also
stop
References crawlservpp::Helper::DateTime::now(), stop(), and timePoint.
stop()
void crawlservpp::Timer::StartStopHR::stop () inline
Stops the timer.
The number of microseconds stored internally will be refreshed.
See also
start
References duration, crawlservpp::Helper::DateTime::now(), and timePoint.
Referenced by start(), and totalStr().
totalStr()
std::string crawlservpp::Timer::StartStopHR::totalStr () inline
Gets the total duration as formatted string.
If the timer is currenty running, it will first be stopped, i.e. the number of microseconds passed will be refreshed.
Returns
The number of microseconds stored internally, formatted as string.
See also
Helper::DateTime::microsecondsToString
References duration, crawlservpp::Helper::DateTime::microsecondsToString(), stop(), and timePoint.
Member Data Documentation
duration
std::chrono::high_resolution_clock::duration crawlservpp::Timer::StartStopHR::duration protected
Duration of previous runs.
Equals std::chrono::high_resolution_clock::duration::zero() if no time has been measured yet (excluding the current run).
Referenced by reset(), stop(), and totalStr().
timePoint
std::chrono::high_resolution_clock::time_point crawlservpp::Timer::StartStopHR::timePoint protected
(Time) point of start.
Equals std::chrono::high_resolution_clock::time_point::min() if the timer has not been started yet or is currently stopped.
Referenced by reset(), start(), stop(), and totalStr().
The documentation for this class was generated from the following file:
Timer/StartStopHR.hpp