crawlserv++: crawlservpp::Module::Analyzer::Algo::MarkovTweet Class Reference
crawlservpp::Module::Analyzer::Algo::MarkovTweet Class Reference
Algorithm generate random tweet texts from a text corpus.
#include <MarkovTweet.hpp>
Construction
MarkovTweet (Main::Database &dbBase, const ThreadOptions &threadOptions, const ThreadStatus &threadStatus)
Continues a previously interrupted algorithm run.
MarkovTweet (Main::Database &dbBase, const ThreadOptions &threadOptions)
Starts a new algorithm run.
Implemented Algorithm Functions
void onAlgoInit () override
Initializes the algorithm and processes its input.
void onAlgoTick () override
Generates the requested texts.
void onAlgoPause () override
Does nothing.
void onAlgoUnpause () override
Does nothing.
void onAlgoClear () override
Does nothing.
Implemented Configuration Functions
void parseAlgoOption () override
Parses a configuration option for the algorithm.
void checkAlgoOptions () override
Checks the configuration options for the algorithm.
Configuration
struct crawlservpp::Module::Analyzer::Config::Entries config
Configuration of the analyzer.
Analyzer-Specific Configuration Parsing
void parseOption () override
Parses an analyzer-specific configuration option.
void checkOptions () override
Checks the analyzer-specific configuration options.
Database Connection
Database database
Database connection for the analyzer thread.
Implemented Thread Functions
void onInit () override
Initializes the analyzer, and the algorithm.
void onTick () override
Performs an algorithm tick.
void onPause () override
Pauses the analyzer.
void onUnpause () override
Unpauses the analyzer.
void onClear () override
Clears the algorithm.
Thread Control for Algorithms
void finished ()
Sets the status of the analyzer to finished, and sleeps.
void pause ()
Pauses the thread.
Configuration Loader
void loadConfig (const std::string &configJson, LogQueue &warningsTo)
Loads a configuration.
Parsing Options
enum StringParsingOption { Default = 0, SQL, SubURL, URL }
Options for parsing strings.
enum CharParsingOption { FromNumber = 0, FromString }
Options for parsing char's.
Configuration Parsing
void category (const std::string &category)
Sets the category of the subsequent configuration items to be checked for.
void option (const std::string &name, bool &target)
Checks for a configuration option of type bool.
void option (const std::string &name, std::vector< bool > &target)
Checks for a configuration option of type array of bool's.
void option (const std::string &name, char &target, CharParsingOption opt)
Checks for a configuration option of type char.
void option (const std::string &name, std::vector< char > &target, CharParsingOption opt)
Checks for a configuration option of type array of char's.
void option (const std::string &name, std::int16_t &target)
Checks for a configuration option of type 16-bit integer.
void option (const std::string &name, std::vector< std::int16_t > &target)
Checks for a configuration option of type array of 16-bit integers.
void option (const std::string &name, std::int32_t &target)
Checks for a configuration option of type 32-bit integer.
void option (const std::string &name, std::vector< std::int32_t > &target)
Checks for a configuration option of type array of 32-bit integers.
void option (const std::string &name, std::int64_t &target)
Checks for a configuration option of type 64-bit integer.
void option (const std::string &name, std::vector< std::int64_t > &target)
Checks for a configuration option of type array of 64-bit integers.
void option (const std::string &name, std::uint8_t &target)
Checks for a configuration option of type unsigned 8-bit integer.
void option (const std::string &name, std::vector< std::uint8_t > &target)
Checks for a configuration option of type array of unsigned 8-bit integers.
void option (const std::string &name, std::uint16_t &target)
Checks for a configuration option of type unsigned 16-bit integer.
void option (const std::string &name, std::vector< std::uint16_t > &target)
Checks for a configuration option of type array of unsigned 16-bit integers.
void option (const std::string &name, std::uint32_t &target)
Checks for a configuration option of type unsigned 32-bit integer.
void option (const std::string &name, std::vector< std::uint32_t > &target)
Checks for a configuration option of type array of unsigned 32-bit integers.
void option (const std::string &name, std::uint64_t &target)
Checks for a configuration option of type unsigned 64-bit integer.
void option (const std::string &name, std::vector< std::uint64_t > &target)
Checks for a configuration option of type array of unsigned 64-bit integers.
void option (const std::string &name, std::string &target, StringParsingOption opt=Default)
Checks for a configuration option of type string.
void option (const std::string &name, std::vector< std::string > &target, StringParsingOption opt=Default)
Checks for a configuration option of type array of strings.
void warning (const std::string &warning)
Adds a warning to the logging queue.
Module-specific Configuration Parsing
virtual void parseBasicOption ()
Parses a basic option.
Getters
std::uint64_t getId () const
Gets the ID of the thread.
std::uint64_t getWebsite () const
Gets the ID of the website used by the thread.
std::uint64_t getUrlList () const
Gets the ID of the URL list used by the thread.
std::uint64_t getConfig () const
Gets the ID of the configuration used by the thread.
bool isShutdown () const
Checks whether the thread is shutting down or has shut down.
bool isRunning () const
Checks whether the thread is still supposed to run.
bool isFinished () const
Checks whether the shutdown of the thread has been finished.
bool isPaused () const
Checks whether the thread has been paused.
Thread Control
void end ()
Waits for the thread until shutdown is completed.
Time Travel
void warpTo (std::uint64_t target)
Jumps to the specified target ID ("time travel").
Configuration
std::string websiteNamespace
Namespace of the website used by the thread.
std::string urlListNamespace
Namespace of the URL list used by the thread.
std::string configuration
JSON string of the configuration used by the thread.
Protected Getters
bool isInterrupted () const
Checks whether the thread has been interrupted.
std::string getStatusMessage () const
Gets the current status message.
std::uint64_t getLast () const
Gets the valud of the last ID processed by the thread.
std::int64_t getWarpedOverAndReset ()
Gets the number of IDs that have been jumped over, and resets them.
Protected Setters
void setStatusMessage (const std::string &statusMessage)
Sets the status message of the thread.
void setProgress (float progress)
Sets the progress of the thread.
void setLast (std::uint64_t lastId)
Sets the last ID processed by the thread.
void incrementLast ()
Increments the last ID processed by the thread.
Protected Thread Control
void sleep (std::uint64_t ms) const
Lets the thread sleep for the specified number of milliseconds.
void allowPausing ()
Allows the thread to be paused.
void disallowPausing ()
Disallows the thread to be paused.
void pauseByThread ()
Forces the thread to pause.
Logging
bool isLogLevel (std::uint8_t level) const
Checks whether a certain logging level is enabled.
void log (std::uint8_t level, const std::string &logEntry)
Adds a thread-specific log entry to the database, if the current logging level is high enough.
void log (std::uint8_t level, std::queue< std::string > &logEntries)
Adds multiple thread-specific log entries to the database, if the current logging level is high enough.
Detailed Description
Algorithm generate random tweet texts from a text corpus.
This is a semi-serious proof-of-concept class for the crawlserv++ Analyzer module.
The implementation of the algorithm itself is done by the slightly modified rawr class, originally by Kelly Rauchenberger see the GitHub repository.
Warning
This algorithm may use A LOT of memory when parsing large corpora, adjust your swap size accordingly to prevent the server from being killed by the operating system!
Member Enumeration Documentation
CharParsingOption
enum crawlservpp::Module::Config::CharParsingOption protected inherited
Options for parsing char's.
Enumerator
FromNumber
Get char by its numeric value.
FromString
Get char from the beginning of a string.
Also supports certain escaped characters.
See also
Helper::Strings::getFirstOrEscapeChar
StringParsingOption
enum crawlservpp::Module::Config::StringParsingOption protected inherited
Options for parsing strings.
Enumerator
Default
Uses a string as it is.
SQL
Requires a SQL-compatible string.
SubURL
Converts a string to a sub-URL.
URL
Converts a string to a URL (without the protocol).
Constructor & Destructor Documentation
MarkovTweet() [1/2]
crawlservpp::Module::Analyzer::Algo::MarkovTweet::MarkovTweet (Main::Database & dbBase, const ThreadOptions & threadOptions, const ThreadStatus & threadStatus)
Continues a previously interrupted algorithm run.
Parameters
dbBase Reference to the main database connection.
threadOptions Constant reference to a structure containing the options for the thread.
threadStatus Constant reference to a structure containing the last known status of the thread.
References crawlservpp::Module::Thread::disallowPausing().
MarkovTweet() [2/2]
crawlservpp::Module::Analyzer::Algo::MarkovTweet::MarkovTweet (Main::Database & dbBase, const ThreadOptions & threadOptions)
Starts a new algorithm run.
Parameters
dbBase Reference to the main database connection.
threadOptions Constant reference to a structure containing the options for the thread.
References crawlservpp::Module::Thread::disallowPausing().
Member Function Documentation
allowPausing()
void crawlservpp::Module::Thread::allowPausing () protected inherited
Allows the thread to be paused.
Threads are pausable by default. Use this function if pausing has been disallowed via disallowPausing().
Thread-safe: Can be used by both the module and the main thread.
Referenced by onAlgoInit(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit().
category()
void crawlservpp::Module::Config::category (const std::string & category) inline protected inherited
Sets the category of the subsequent configuration items to be checked for.
Parameters
category Constant reference to a string containing the name of the category.
References crawlservpp::Struct::ConfigItem::category.
Referenced by parseAlgoOption(), crawlservpp::Module::Analyzer::Algo::MarkovText::parseAlgoOption(), crawlservpp::Network::Config::parseBasicOption(), crawlservpp::Module::Analyzer::Config::parseOption(), crawlservpp::Module::Parser::Config::parseOption(), crawlservpp::Module::Crawler::Config::parseOption(), and crawlservpp::Module::Extractor::Config::parseOption().
checkAlgoOptions()
void crawlservpp::Module::Analyzer::Algo::MarkovTweet::checkAlgoOptions () override virtual
Checks the configuration options for the algorithm.
Exceptions
Module::Analyzer::Thread::Exception if no input sources or no target table are provided, if the given dimension parameter is zero, or the length of the texts to generate is zero.
Implements crawlservpp::Module::Analyzer::Config.
References crawlservpp::Module::Analyzer::Config::config, crawlservpp::Module::Analyzer::Config::Entries::generalInputFields, and crawlservpp::Module::Analyzer::Config::Entries::generalTargetTable.
checkOptions()
void crawlservpp::Module::Analyzer::Config::checkOptions () inline override protected virtual inherited
Checks the analyzer-specific configuration options.
Implements crawlservpp::Module::Config.
References crawlservpp::Module::Analyzer::Config::checkAlgoOptions(), crawlservpp::Module::Analyzer::Config::config, crawlservpp::Module::Analyzer::defaultPercentageCorpusSlices, crawlservpp::Module::Analyzer::Config::Entries::generalCorpusSlicing, crawlservpp::Module::Analyzer::Config::Entries::generalInputFields, crawlservpp::Module::Analyzer::Config::Entries::generalInputSources, crawlservpp::Module::Analyzer::Config::Entries::generalInputTables, crawlservpp::Module::Analyzer::maxPercentageCorpusSlices, crawlservpp::Module::Analyzer::minPercentageCorpusSlices, and crawlservpp::Module::Config::warning().
disallowPausing()
void crawlservpp::Module::Thread::disallowPausing () protected inherited
Disallows the thread to be paused.
Thread-safe: Can be used by both the module and the main thread.
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::CorpusGenerator(), crawlservpp::Module::Analyzer::Algo::MarkovText::MarkovText(), and MarkovTweet().
end()
void crawlservpp::Module::Thread::end () inherited
Waits for the thread until shutdown is completed.
Note
Either stop() or interrupt() must have been called before calling this function.
Warning
May not be used by the thread itself!
References crawlservpp::Main::Database::deleteThread().
finished()
void crawlservpp::Module::Analyzer::Thread::finished () protected inherited
Sets the status of the analyzer to finished, and sleeps.
Call this function when the algorithm has finished.
References crawlservpp::Module::Analyzer::Config::config, crawlservpp::Module::Analyzer::Config::Entries::generalSleepWhenFinished, crawlservpp::Module::Thread::setStatusMessage(), and crawlservpp::Module::Thread::sleep().
Referenced by onAlgoTick(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick().
getConfig()
std::uint64_t crawlservpp::Module::Thread::getConfig () const inherited
Gets the ID of the configuration used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used configuration in the database.
References crawlservpp::Struct::ThreadOptions::config.
Referenced by crawlservpp::Module::Thread::Thread().
getId()
std::uint64_t crawlservpp::Module::Thread::getId () const inherited
Gets the ID of the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the thread in the database.
getLast()
std::uint64_t crawlservpp::Module::Thread::getLast () const protected inherited
Gets the valud of the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
Returns
The ID last processed by the thread, or zero if no ID has been processed yet.
Referenced by onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), and crawlservpp::Module::Extractor::Thread::onTick().
getStatusMessage()
std::string crawlservpp::Module::Thread::getStatusMessage () const protected inherited
Gets the current status message.
Thread-safe: Can be used by both the module and the main thread.
Returns
A copy of the current status message.
Referenced by crawlservpp::Module::Parser::Thread::onClear(), and crawlservpp::Module::Extractor::Thread::onClear().
getUrlList()
std::uint64_t crawlservpp::Module::Thread::getUrlList () const inherited
Gets the ID of the URL list used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used URL list in the database.
References crawlservpp::Struct::ThreadOptions::urlList.
Referenced by crawlservpp::Module::Thread::Thread().
getWarpedOverAndReset()
std::int64_t crawlservpp::Module::Thread::getWarpedOverAndReset () protected inherited
Gets the number of IDs that have been jumped over, and resets them.
Resets the number of IDs jumped over to zero.
Warning
May only be used by the thread itself, not by the main thread!
Returns
The number of IDs that have been jumped over due to a call to warpTo(), or zero if no IDs have been jumped over, at least not since the last call to getWarpedOverAndReset(). The result might be negative, if warpTo() resulted in a jump to a previous ID.
Referenced by crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), and crawlservpp::Module::Crawler::Thread::onTick().
getWebsite()
std::uint64_t crawlservpp::Module::Thread::getWebsite () const inherited
Gets the ID of the website used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used website in the database.
References crawlservpp::Struct::ThreadOptions::website.
Referenced by crawlservpp::Module::Crawler::Thread::onInit(), and crawlservpp::Module::Thread::Thread().
incrementLast()
void crawlservpp::Module::Thread::incrementLast () protected inherited
Increments the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
See also
setLast, Main::Database::setThreadLast
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadLast().
Referenced by onAlgoTick(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick().
isFinished()
bool crawlservpp::Module::Thread::isFinished () const inherited
Checks whether the shutdown of the thread has been finished.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread has been completely shut down. False otherwise.
isInterrupted()
bool crawlservpp::Module::Thread::isInterrupted () const protected inherited
Checks whether the thread has been interrupted.
Thread-safe: Can be used by both the module and the main thread.
Returns
True if the thread has been interrupted. False otherwise.
isLogLevel()
bool crawlservpp::Module::Thread::isLogLevel (std::uint8_t level) const protected inherited
Checks whether a certain logging level is enabled.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
level The logging level to be checked for.
Returns
True, if the current logging level is at least as high as the given level. False, if the current logging level is lower than the given one.
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::isLogLevel().
Referenced by crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), and crawlservpp::Module::Crawler::Thread::onTick().
isPaused()
bool crawlservpp::Module::Thread::isPaused () const inherited
Checks whether the thread has been paused.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread has been paused. False otherwise.
isRunning()
bool crawlservpp::Module::Thread::isRunning () const inherited
Checks whether the thread is still supposed to run.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread is has not been cancelled, even when it is paused. False, if the thread is not supposed to run any longer.
Referenced by onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
isShutdown()
bool crawlservpp::Module::Thread::isShutdown () const inherited
Checks whether the thread is shutting down or has shut down.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread is shutting down or has been shut down. False, if the thread is continuing to run.
See also
Thread::isFinished
loadConfig()
void crawlservpp::Module::Config::loadConfig (const std::string & configJson, LogQueue & warningsTo) inline inherited
Loads a configuration.
Parameters
configJson Constant reference to a string containing the configuration as JSON.
warningsTo Reference to a queue to which warnings will be added that occur during the parsing of the configuration, also known as the "logging queue".
Exceptions
Module::Config::Exception if the configuration JSON cannot be parsed.
References crawlservpp::Struct::ConfigItem::category, crawlservpp::Module::Config::checkOptions(), crawlservpp::Struct::ConfigItem::name, crawlservpp::Module::Config::parseBasicOption(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::ConfigItem::str(), crawlservpp::Struct::ConfigItem::value, and crawlservpp::Main::Exception::view().
Referenced by crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
log() [1/2]
void crawlservpp::Module::Thread::log (std::uint8_t level, const std::string & logEntry) protected inherited
Adds a thread-specific log entry to the database, if the current logging level is high enough.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entry will be written to the logging file as well.
The log entry will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entry. The entry will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntry Constant reference to a string containing the log entry.
See also
Module::Database::log(std::uint8_t, const std::string&)
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::log().
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), onAlgoInit(), crawlservpp::Module::Analyzer::Algo::Empty::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onClear(), crawlservpp::Module::Extractor::Thread::onClear(), crawlservpp::Module::Crawler::Thread::onClear(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), crawlservpp::Module::Crawler::Thread::onInit(), crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), and crawlservpp::Module::Crawler::Thread::onTick().
log() [2/2]
void crawlservpp::Module::Thread::log (std::uint8_t level, std::queue< std::string > & logEntries) protected inherited
Adds multiple thread-specific log entries to the database, if the current logging level is high enough.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entries will be written to the logging file as well.
The log entries will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entries. The entries will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntries Reference to a queue of strings containing the log entries to be written. It will be emptied regardless whether the log entries will be written to the database.
See also
Module::Database::log(std::uint8_t, std::queue<std::string>&)
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::log().
onAlgoClear()
void crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoClear () override virtual
Does nothing.
Implements crawlservpp::Module::Analyzer::Thread.
onAlgoInit()
void crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit () override virtual
Initializes the algorithm and processes its input.
Note
In the case of this algorithm, most of the work will be done during initialization which therefore may take a while.
Exceptions
Module::Analyzer::Thread::Exception if the compilation of the text corpus to be used as source failed.
Implements crawlservpp::Module::Analyzer::Thread.
References crawlservpp::Module::Thread::allowPausing(), crawlservpp::Module::Analyzer::Database::checkSources(), crawlservpp::Module::Analyzer::Config::config, crawlservpp::Module::Analyzer::Thread::database, crawlservpp::Module::Analyzer::Config::Entries::filterDateEnable, crawlservpp::Module::Analyzer::Config::Entries::filterDateFrom, crawlservpp::Module::Analyzer::Config::Entries::filterDateTo, crawlservpp::Module::Analyzer::Config::Entries::generalCorpusChecks, crawlservpp::Module::Analyzer::Config::Entries::generalInputSources, crawlservpp::Module::Analyzer::generalLoggingExtended, crawlservpp::Module::Analyzer::generalLoggingVerbose, crawlservpp::Data::Corpus::getcCorpus(), crawlservpp::Module::Analyzer::Database::getCorpus(), crawlservpp::Module::Analyzer::Database::initTargetTable(), crawlservpp::Module::Thread::isRunning(), crawlservpp::Module::Thread::log(), crawlservpp::Module::Thread::setProgress(), crawlservpp::Module::Thread::setStatusMessage(), and crawlservpp::Module::Analyzer::Database::setTargetFields().
onAlgoPause()
void crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoPause () override virtual
Does nothing.
Implements crawlservpp::Module::Analyzer::Thread.
onAlgoTick()
void crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick () override virtual
Generates the requested texts.
Implements crawlservpp::Module::Analyzer::Thread.
References crawlservpp::Data::_string, crawlservpp::Data::InsertFieldsMixed::columns_types_values, crawlservpp::Module::Analyzer::Config::config, crawlservpp::Module::Analyzer::Thread::database, crawlservpp::Module::Analyzer::Thread::finished(), crawlservpp::Module::Analyzer::Config::Entries::generalTargetTable, crawlservpp::Module::Thread::getLast(), crawlservpp::Data::getTypeOfSizeT(), crawlservpp::Module::Thread::incrementLast(), crawlservpp::Wrapper::Database::insertCustomData(), crawlservpp::Module::Thread::setProgress(), crawlservpp::Module::Thread::setStatusMessage(), crawlservpp::Module::Thread::sleep(), crawlservpp::Data::InsertFieldsMixed::table, crawlservpp::Module::Thread::urlListNamespace, and crawlservpp::Module::Thread::websiteNamespace.
onAlgoUnpause()
void crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoUnpause () override virtual
Does nothing.
Implements crawlservpp::Module::Analyzer::Thread.
onClear()
void crawlservpp::Module::Analyzer::Thread::onClear () override protected virtual inherited
Clears the algorithm.
See also
onAlgoClear()
Implements crawlservpp::Module::Thread.
References crawlservpp::Module::Analyzer::Thread::onAlgoClear().
onInit()
void crawlservpp::Module::Analyzer::Thread::onInit () override protected virtual inherited
Initializes the analyzer, and the algorithm.
See also
onAlgoInit
Implements crawlservpp::Module::Thread.
References crawlservpp::Module::Analyzer::Config::config, crawlservpp::Module::Analyzer::Thread::database, crawlservpp::Module::Analyzer::Config::Entries::generalCorpusSlicing, crawlservpp::Module::Analyzer::Config::Entries::generalLogging, crawlservpp::Module::Analyzer::generalLoggingDefault, crawlservpp::Module::Analyzer::generalLoggingVerbose, crawlservpp::Module::Analyzer::Config::Entries::generalSleepMySql, crawlservpp::Module::Analyzer::Config::Entries::generalTargetTable, crawlservpp::Wrapper::Database::getConfiguration(), crawlservpp::Module::Thread::isRunning(), crawlservpp::Module::Config::loadConfig(), crawlservpp::Module::Thread::log(), crawlservpp::Module::Analyzer::Thread::onAlgoInit(), crawlservpp::Module::Analyzer::Database::prepare(), crawlservpp::Module::Analyzer::Database::setCorpusSlicing(), crawlservpp::Module::Analyzer::Database::setIsRunningCallback(), crawlservpp::Wrapper::Database::setLogging(), crawlservpp::Wrapper::Database::setSleepOnError(), crawlservpp::Module::Thread::setStatusMessage(), and crawlservpp::Module::Analyzer::Database::setTargetTable().
onPause()
void crawlservpp::Module::Analyzer::Thread::onPause () override protected virtual inherited
Pauses the analyzer.
See also
onAlgoPause
Implements crawlservpp::Module::Thread.
References crawlservpp::Module::Analyzer::Thread::onAlgoPause().
onTick()
void crawlservpp::Module::Analyzer::Thread::onTick () override protected virtual inherited
Performs an algorithm tick.
See also
onAlgoTick
Implements crawlservpp::Module::Thread.
References crawlservpp::Module::Analyzer::Thread::onAlgoTick().
onUnpause()
void crawlservpp::Module::Analyzer::Thread::onUnpause () override protected virtual inherited
Unpauses the analyzer.
See also
onAlgoUnpause
Implements crawlservpp::Module::Thread.
References crawlservpp::Module::Analyzer::Thread::onAlgoUnpause().
option() [1/20]
void crawlservpp::Module::Config::option (const std::string & name, bool & target) inline protected inherited
Checks for a configuration option of type bool.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a boolean variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
Referenced by parseAlgoOption(), crawlservpp::Module::Analyzer::Algo::MarkovText::parseAlgoOption(), crawlservpp::Network::Config::parseBasicOption(), crawlservpp::Module::Analyzer::Config::parseOption(), crawlservpp::Module::Parser::Config::parseOption(), crawlservpp::Module::Crawler::Config::parseOption(), and crawlservpp::Module::Extractor::Config::parseOption().
option() [2/20]
void crawlservpp::Module::Config::option (const std::string & name, char & target, CharParsingOption opt) inline protected inherited
Checks for a configuration option of type char.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable of the type char into which the value of the configuration entry will be written if it is encountered.
opt Parsing options used for the configuration option.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Module::Config::FromNumber, crawlservpp::Module::Config::FromString, crawlservpp::Helper::Strings::getFirstOrEscapeChar(), crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [3/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int16_t & target) inline protected inherited
Checks for a configuration option of type 16-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [4/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int32_t & target) inline protected inherited
Checks for a configuration option of type 32-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [5/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int64_t & target) inline protected inherited
Checks for a configuration option of type 64-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [6/20]
void crawlservpp::Module::Config::option (const std::string & name, std::string & target, StringParsingOption opt = Default) inline protected inherited
Checks for a configuration option of type string.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a string into which the value of the configuration entry will be stored if it is encountered.
opt Parsing option for the configuration entry.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Helper::Strings::checkSQLName(), crawlservpp::Module::Config::Default, crawlservpp::Struct::ConfigItem::name, crawlservpp::Module::Config::SQL, crawlservpp::Struct::ConfigItem::str(), crawlservpp::Module::Config::SubURL, crawlservpp::Module::Config::URL, and crawlservpp::Struct::ConfigItem::value.
option() [7/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint16_t & target) inline protected inherited
Checks for a configuration option of type unsigned 16-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [8/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint32_t & target) inline protected inherited
Checks for a configuration option of type unsigned 32-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [9/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint64_t & target) inline protected inherited
Checks for a configuration option of type unsigned 64-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [10/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint8_t & target) inline protected inherited
Checks for a configuration option of type unsigned 8-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [11/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< bool > & target) inline protected inherited
Checks for a configuration option of type array of bool's.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector of bool's into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [12/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< char > & target, CharParsingOption opt) inline protected inherited
Checks for a configuration option of type array of char's.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector of char's into which the value of the configuration entry will be written if it is encountered.
opt Parsing options used for the configuration option.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Module::Config::FromNumber, crawlservpp::Module::Config::FromString, crawlservpp::Helper::Strings::getFirstOrEscapeChar(), crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [13/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int16_t > & target) inline protected inherited
Checks for a configuration option of type array of 16-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [14/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int32_t > & target) inline protected inherited
Checks for a configuration option of type array of 32-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [15/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int64_t > & target) inline protected inherited
Checks for a configuration option of type array of 64-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [16/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::string > & target, StringParsingOption opt = Default) inline protected inherited
Checks for a configuration option of type array of strings.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
opt Parsing option for the configuration entry.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Helper::Strings::checkSQLName(), crawlservpp::Module::Config::Default, crawlservpp::Struct::ConfigItem::name, crawlservpp::Module::Config::SQL, crawlservpp::Struct::ConfigItem::str(), crawlservpp::Module::Config::SubURL, crawlservpp::Module::Config::URL, and crawlservpp::Struct::ConfigItem::value.
option() [17/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint16_t > & target) inline protected inherited
Checks for a configuration option of type array of unsigned 16-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [18/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint32_t > & target) inline protected inherited
Checks for a configuration option of type array of unsigned 32-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [19/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint64_t > & target) inline protected inherited
Checks for a configuration option of type array of unsigned 64-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [20/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint8_t > & target) inline protected inherited
Checks for a configuration option of type array of unsigned 8-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
parseAlgoOption()
void crawlservpp::Module::Analyzer::Algo::MarkovTweet::parseAlgoOption () override virtual
Parses a configuration option for the algorithm.
Implements crawlservpp::Module::Analyzer::Config.
References crawlservpp::Module::Config::category(), and crawlservpp::Module::Config::option().
parseBasicOption()
void crawlservpp::Module::Config::parseBasicOption () inline protected virtual inherited
Parses a basic option.
Might be overridden by child classes.
Can be used by abstract classes to add additional configuration entries without being the final implementation, as in Network::Config.
Warning
Any reimplementation needs to call parseOption() for the configuration to work properly.
See also
Network::Config::parseBasicOption
Reimplemented in crawlservpp::Network::Config.
References crawlservpp::Module::Config::parseOption().
Referenced by crawlservpp::Module::Config::loadConfig().
parseOption()
void crawlservpp::Module::Analyzer::Config::parseOption () inline override protected virtual inherited
Parses an analyzer-specific configuration option.
Implements crawlservpp::Module::Config.
References crawlservpp::Module::Config::category(), crawlservpp::Module::Analyzer::Config::config, crawlservpp::Module::Analyzer::Config::Entries::filterDateEnable, crawlservpp::Module::Analyzer::Config::Entries::filterDateFrom, crawlservpp::Module::Analyzer::Config::Entries::filterDateTo, crawlservpp::Module::Analyzer::Config::Entries::generalCorpusChecks, crawlservpp::Module::Analyzer::Config::Entries::generalCorpusSlicing, crawlservpp::Module::Analyzer::Config::Entries::generalInputFields, crawlservpp::Module::Analyzer::Config::Entries::generalInputSources, crawlservpp::Module::Analyzer::Config::Entries::generalInputTables, crawlservpp::Module::Analyzer::Config::Entries::generalLogging, crawlservpp::Module::Analyzer::Config::Entries::generalSleepMySql, crawlservpp::Module::Analyzer::Config::Entries::generalSleepWhenFinished, crawlservpp::Module::Analyzer::Config::Entries::generalTargetTable, crawlservpp::Module::Config::option(), and crawlservpp::Module::Analyzer::Config::parseAlgoOption().
pause()
void crawlservpp::Module::Analyzer::Thread::pause () protected inherited
Pauses the thread.
Shadows Module::Thread::pause(), which should not be used by the thread.
See also
pauseByThread
References crawlservpp::Module::Thread::pauseByThread().
pauseByThread()
void crawlservpp::Module::Thread::pauseByThread () protected inherited
Forces the thread to pause.
Warning
May only be used by the thread itself, not by the main thread!
References crawlservpp::Module::Thread::database, and crawlservpp::Main::Database::setThreadStatus().
Referenced by crawlservpp::Module::Analyzer::Thread::pause().
setLast()
void crawlservpp::Module::Thread::setLast (std::uint64_t lastId) protected inherited
Sets the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
lastId The last ID processed by the thread.
See also
incrementLast, Main::Database::setThreadLast
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadLast().
setProgress()
void crawlservpp::Module::Thread::setProgress (float progress) protected inherited
Sets the progress of the thread.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
progress The new progress of the thread, between 0.f (0%) and 1.f (100%).
See also
Main::Database::setThreadProgress
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadProgress().
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), onAlgoInit(), onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), and crawlservpp::Module::Extractor::Thread::onTick().
setStatusMessage()
void crawlservpp::Module::Thread::setStatusMessage (const std::string & statusMessage) protected inherited
Sets the status message of the thread.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
statusMessage Constant reference to a string containing the new status message to be set.
See also
Main::Database::setThreadStatus
References crawlservpp::Module::Thread::database, and crawlservpp::Main::Database::setThreadStatus().
Referenced by crawlservpp::Module::Analyzer::Thread::finished(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoTick(), onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onClear(), crawlservpp::Module::Extractor::Thread::onClear(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), crawlservpp::Module::Crawler::Thread::onInit(), crawlservpp::Module::Parser::Thread::onTick(), and crawlservpp::Module::Extractor::Thread::onTick().
sleep()
void crawlservpp::Module::Thread::sleep (std::uint64_t ms) const protected inherited
Lets the thread sleep for the specified number of milliseconds.
The sleep will be interrupted if the thread is stopped.
Thread-safe: Can be used by both the module and the main thread.
Parameters
ms The number of milliseconds for the thread to sleep, if it is not stopped.
References crawlservpp::Module::sleepMs.
Referenced by crawlservpp::Module::Analyzer::Thread::finished(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoTick(), onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), and crawlservpp::Module::Crawler::Thread::onTick().
warning()
void crawlservpp::Module::Config::warning (const std::string & warning) inline protected inherited
Adds a warning to the logging queue.
Warning
Should not be used outside of Config::loadConfig!
Parameters
warning Constant reference to a string containing the warning.
Exceptions
Module::Config::Exception if no log queue is active.
Referenced by crawlservpp::Module::Analyzer::Config::checkOptions(), crawlservpp::Module::Parser::Config::checkOptions(), crawlservpp::Module::Crawler::Config::checkOptions(), crawlservpp::Module::Extractor::Config::checkOptions(), and crawlservpp::Network::Config::parseBasicOption().
warpTo()
void crawlservpp::Module::Thread::warpTo (std::uint64_t target) inherited
Jumps to the specified target ID ("time travel").
Skips the normal process of determining the next ID once the current ID has been processed.
Thread-safe: Can be used by both the module and the main thread.
Parameters
target The target ID that should be processed next.
Exceptions
Module::Thread::Exception if no target is specified, i.e. the target ID is zero.
See also
getWarpedOverAndReset
Member Data Documentation
config
struct crawlservpp::Module::Analyzer::Config::Entries crawlservpp::Module::Analyzer::Config::config inherited
Configuration of the analyzer.
Referenced by checkAlgoOptions(), crawlservpp::Module::Analyzer::Algo::MarkovText::checkAlgoOptions(), crawlservpp::Module::Analyzer::Config::checkOptions(), crawlservpp::Module::Analyzer::Thread::finished(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Analyzer::Thread::onInit(), and crawlservpp::Module::Analyzer::Config::parseOption().
configuration
std::string crawlservpp::Module::Thread::configuration protected inherited
JSON string of the configuration used by the thread.
See also
Main::Database::getConfiguration
Referenced by crawlservpp::Module::Thread::Thread().
database
Database crawlservpp::Module::Analyzer::Thread::database protected inherited
Database connection for the analyzer thread.
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), and crawlservpp::Module::Analyzer::Thread::onInit().
urlListNamespace
std::string crawlservpp::Module::Thread::urlListNamespace protected inherited
Namespace of the URL list used by the thread.
Referenced by onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), crawlservpp::Module::Crawler::Thread::onInit(), and crawlservpp::Module::Thread::Thread().
websiteNamespace
std::string crawlservpp::Module::Thread::websiteNamespace protected inherited
Namespace of the website used by the thread.
Referenced by onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), crawlservpp::Module::Crawler::Thread::onInit(), and crawlservpp::Module::Thread::Thread().
The documentation for this class was generated from the following files:
Module/Analyzer/Algo/MarkovTweet.hpp
Module/Analyzer/Algo/MarkovTweet.cpp