crawlserv++: crawlservpp::Data::Corpus Class Reference
crawlservpp::Data::Corpus Class Reference
Class representing a text corpus.
#include <Corpus.hpp>
Classes
class Exception
Class for corpus exceptions.
Construction
Corpus (bool consistencyChecks)
Constructor setting the internal property.
Getters
std::string & getCorpus ()
Gets a reference to the text corpus.
const std::string & getcCorpus () const
Gets a constant reference to the text corpus.
Struct::TextMap & getArticleMap ()
Gets a reference to the article map of the corpus.
const Struct::TextMap & getcArticleMap () const
Gets a constant reference to the article map of the corpus.
Struct::TextMap & getDateMap ()
Gets a reference to the date map of the corpus.
const Struct::TextMap & getcDateMap () const
Gets a constant reference to the date map of the corpus.
std::string get (std::size_t index) const
Gets the article with the specified index.
std::string get (const std::string &id) const
Gets the article with the specified ID.
std::string getDate (const std::string &date) const
Gets all articles at the specified date.
std::size_t size () const
Gets the size of the text corpus in bytes.
bool empty () const
Checks whether the corpus is empty.
std::string substr (std::size_t from, std::size_t len)
Gets a substring from the corpus.
Creation
void create (std::vector< std::string > &texts, bool deleteInputData)
Creates text corpus from a vector of strings.
void create (std::vector< std::string > &texts, std::vector< std::string > &articleIds, std::vector< std::string > &dateTimes, bool deleteInputData)
Creates text corpus from parsed data, including article and date maps.
void combine (std::vector< std::string > &chunks, std::vector< Struct::TextMap > &articleMaps, std::vector< Struct::TextMap > &dateMaps, bool deleteInputData)
Creates text corpus by combining previously separated corpus chunks, as well as their article and date maps.
Copying
void copy (std::string &to) const
Copies the underlying text corpus to the given string.
void copy (std::string &to, Struct::TextMap &articleMapTo, Struct::TextMap &dateMapTo) const
Copies the underlying text corpus, as well as its article and date map.
void copyChunks (std::size_t chunkSize, std::vector< std::string > &to, std::vector< Struct::TextMap > &articleMapsTo, std::vector< Struct::TextMap > &dateMapsTo) const
Copies underlying text corpus into chunks of the given size.
Filtering
bool filterByDate (const std::string &from, const std::string &to)
Filters the corpus by the given date(s).
Cleanup
void clear ()
Clears the corpus.
Data
std::string corpus
Struct::TextMap articleMap
Struct::TextMap dateMap
Detailed Description
Class representing a text corpus.
The corpus might include article and date maps that can be sliced into smaller chunks to fit into the database.
Article and date maps are saved as text map structures, referencing a part of the text corpus and containing a describing label that indicates the ID or date associated with the referenced part of the corpus.
Note
For the filtering by date to work, all input data needs to be sorted by date, while texts without date need to be added first.
See also
Struct::TextMap
Constructor & Destructor Documentation
Corpus()
crawlservpp::Data::Corpus::Corpus (bool consistencyChecks) inline explicit
Constructor setting the internal property.
Parameters
consistencyChecks If true, consistency checks will be performed on the text corpus.
Member Function Documentation
clear()
void crawlservpp::Data::Corpus::clear () inline
Clears the corpus.
Clears the text of the corpus, as well as article and date map, if they exist.
References articleMap, corpus, and dateMap.
Referenced by combine(), create(), crawlservpp::Module::Analyzer::Database::createCorpus(), filterByDate(), and crawlservpp::Module::Analyzer::Database::getCorpus().
combine()
void crawlservpp::Data::Corpus::combine (std::vector< std::string > & chunks, std::vector< Struct::TextMap > & articleMaps, std::vector< Struct::TextMap > & dateMaps, bool deleteInputData) inline
Creates text corpus by combining previously separated corpus chunks, as well as their article and date maps.
Performs consistency checks of the provided article maps, if consistency checks have been enabled on construction.
Note
If a corpus already exists, it will be cleared.
Parameters
chunks Reference to a vector containing strings with the text of the chunks.
articleMaps Reference to a vector containing the article maps of the chunks.
dateMaps Reference to a vector containing the date maps of the chunks.
deleteInputData If true, the given texts, article and date maps will be cleared, freeing the used memory early.
Exceptions
Corpus::Exception if consistency checks are enabled and an article map does not start in the beginning of its corpus chunk.
See also
copyChunks
References articleMap, clear(), corpus, dateMap, and size().
Referenced by crawlservpp::Module::Analyzer::Database::getCorpus().
copy() [1/2]
void crawlservpp::Data::Corpus::copy (std::string & to) const inline
Copies the underlying text corpus to the given string.
Parameters
to Reference to a string to which the text corpus will be copied.
References corpus.
copy() [2/2]
void crawlservpp::Data::Corpus::copy (std::string & to, Struct::TextMap & articleMapTo, Struct::TextMap & dateMapTo) const inline
Copies the underlying text corpus, as well as its article and date map.
Parameters
to Reference to a string to which the text corpus will be copied.
articleMapTo Reference to a text map structure to which the article map will be copied.
dateMapTo Reference to a text map structure to which the date map will be copied.
References articleMap, corpus, and dateMap.
copyChunks()
void crawlservpp::Data::Corpus::copyChunks (std::size_t chunkSize, std::vector< std::string > & to, std::vector< Struct::TextMap > & articleMapsTo, std::vector< Struct::TextMap > & dateMapsTo) const inline
Copies underlying text corpus into chunks of the given size.
If the text corpus has an article and/or a date map, a corresponding article and/or date map will be created for each of the corpus slices.
If the text corpus contains UTF-8-encoded characters, they will not be split, creating the possibility of chunks with slightly different sizes.
Parameters
chunkSize The maximum chunk size in bytes.
to Reference to a vector of strings to which the texts of the corpus chunks will be appended.
articleMapsTo Reference to a vector of text map structures, to which the article maps of the chunks will be appended. The vector will not be changed if the text corpus does not possess an article map.
dateMapsTo Reference to a vector of text map structures, to which the date maps of the chunks will be appended. The vector will not be changed if the text corpus does not possess an date map.
Exceptions
Corpus::Exception if the chunk size is zero and the corpus is non-empty, or if consistency checks have been enabled on construction and
the article and the date map contradict each other
one of the chunks created is larger than the maximum chunk size given
the article map does not describe the whole corpus
the last chunk created is empty
See also
combine
References articleMap, corpus, and dateMap.
Referenced by crawlservpp::Module::Analyzer::Database::createCorpus().
create() [1/2]
void crawlservpp::Data::Corpus::create (std::vector< std::string > & texts, bool deleteInputData) inline
Creates text corpus from a vector of strings.
Concatenates all given texts and delimits them with spaces.
Note
If a corpus already exists, it will be cleared.
Parameters
texts A reference to the vector containing texts to create the corpus from.
deleteInputData If true, the given texts will be cleared, freeing the used memory early.
References clear(), and corpus.
Referenced by create(), and crawlservpp::Module::Analyzer::Database::createCorpus().
create() [2/2]
void crawlservpp::Data::Corpus::create (std::vector< std::string > & texts, std::vector< std::string > & articleIds, std::vector< std::string > & dateTimes, bool deleteInputData) inline
Creates text corpus from parsed data, including article and date maps.
Concatenates all given texts and delimits them with spaces. Saves given article IDs and date/times in article and date map.
Note
If a corpus already exists, it will be cleared.
Parameters
texts A reference to the vector containing texts to create the corpus from.
articleIds A reference to the vector containing the article IDs for the given texts.
dateTimes A refereence to the vector containing the date/times for the given texts.
deleteInputData If true, the given texts, article IDs and date/times will be cleared, freeing the used memory early.
References articleMap, clear(), corpus, create(), crawlservpp::Data::dateLength, dateMap, crawlservpp::Struct::TextMapEntry::length, and crawlservpp::Struct::TextMapEntry::value.
empty()
bool crawlservpp::Data::Corpus::empty () const inline
Checks whether the corpus is empty.
Returns
True, if the corpus is empty. False otherwise.
References corpus.
Referenced by get(), and crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit().
filterByDate()
bool crawlservpp::Data::Corpus::filterByDate (const std::string & from, const std::string & to) inline
Filters the corpus by the given date(s).
Afterwards, the corpus will only contain text marked with the given date(s), or be empty if the given date(s) do not correspond with any parts of the corpus.
If the given strings are empty, no action will be performed.
Parameters
from Constant reference to a string containing the date to be filtered from.
to Constant reference to a string containing the date to be filtered to.
Returns
True, if the corpus has been changed as result of the filtering by the given date. False, if it remains unchanged.
Exceptions
Corpus::Exception if consistency checks have been enabled on construction and the date map does not start at the beginning of the corpus, the date map and the article map contradict each other, or they contain other inconsistencies.
References articleMap, clear(), corpus, dateMap, and crawlservpp::Helper::DateTime::isISODateInRange().
Referenced by crawlservpp::Module::Analyzer::Database::getCorpus().
get() [1/2]
std::string crawlservpp::Data::Corpus::get (const std::string & id) const inline
Gets the article with the specified ID.
Parameters
id A constant reference to a string containing the ID of the article to be retrieved, as specified in the article map of the text corpus.
Returns
A copy of the article with the given ID, or an empty string if an article with this ID does not exist.
Exceptions
Corpus::Exception if no ID has been specified, i.e. id references an empty string.
References articleMap, corpus, and empty().
get() [2/2]
std::string crawlservpp::Data::Corpus::get (std::size_t index) const inline
Gets the article with the specified index.
Parameters
index The index of the article in the article map of the text corpus, starting with zero.
Returns
A copy of the article inside the text corpus with the given index.
Exceptions
Corpus::Exception if the article map of the corpus is empty or the given index is out of bounds (larger than the article map).
References articleMap, and corpus.
getArticleMap()
Struct::TextMap & crawlservpp::Data::Corpus::getArticleMap () inline
Gets a reference to the article map of the corpus.
Returns
A reference to the article map of the corpus, if specified.
References articleMap.
getcArticleMap()
const Struct::TextMap & crawlservpp::Data::Corpus::getcArticleMap () const inline
Gets a constant reference to the article map of the corpus.
Returns
A constant reference to the article map of the corpus, if specified.
References articleMap.
getcCorpus()
const std::string & crawlservpp::Data::Corpus::getcCorpus () const inline
Gets a constant reference to the text corpus.
Returns
A constant reference to the text corpus represented by the class.
References corpus.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit().
getcDateMap()
const Struct::TextMap & crawlservpp::Data::Corpus::getcDateMap () const inline
Gets a constant reference to the date map of the corpus.
Returns
A constant reference to the date map of the corpus, if specified.
References dateMap.
getCorpus()
std::string & crawlservpp::Data::Corpus::getCorpus () inline
Gets a reference to the text corpus.
Returns
A reference to the text corpus represented by the class.
References corpus.
getDate()
std::string crawlservpp::Data::Corpus::getDate (const std::string & date) const inline
Gets all articles at the specified date.
Parameters
date A constant reference to a string containing the date of the article to be retrieved, as specified in the date map of the text corpus. The string should have the format YYYY-MM-DD.
Returns
a copy of all concatenated articles at the given date, or an empty string if no articles have been found at this date.
Exceptions
Corpus::Exception if the date given has an invalid length.
References corpus, crawlservpp::Data::dateLength, and dateMap.
getDateMap()
Struct::TextMap & crawlservpp::Data::Corpus::getDateMap () inline
Gets a reference to the date map of the corpus.
Returns
A reference to the date map of the corpus, if specified.
References dateMap.
size()
std::size_t crawlservpp::Data::Corpus::size () const inline
Gets the size of the text corpus in bytes.
Note
The number of characters in the corpus may differ, as it might be UTF-8-encoded.
Returns
The size of the corpus in bytes.
References corpus.
Referenced by combine(), crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Module::Analyzer::Database::getCorpus(), and crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit().
substr()
std::string crawlservpp::Data::Corpus::substr (std::size_t from, std::size_t len) inline
Gets a substring from the corpus.
Parameters
from The zero-based index of the first byte of the substring to be retrieved.
len The length of the substring to be retreved, in bytes.
Returns
A copy of the specified substring.
Exceptions
std::out_of_range if the index or length are invalid, std::bad_alloc if the function needs to allocate storage and fails.
References corpus.
Member Data Documentation
articleMap
Struct::TextMap crawlservpp::Data::Corpus::articleMap protected
Referenced by clear(), combine(), copy(), copyChunks(), create(), filterByDate(), get(), getArticleMap(), and getcArticleMap().
corpus
std::string crawlservpp::Data::Corpus::corpus protected
Referenced by clear(), combine(), copy(), copyChunks(), create(), empty(), filterByDate(), get(), getcCorpus(), getCorpus(), getDate(), size(), and substr().
dateMap
Struct::TextMap crawlservpp::Data::Corpus::dateMap protected
Referenced by clear(), combine(), copy(), copyChunks(), create(), filterByDate(), getcDateMap(), getDate(), and getDateMap().
The documentation for this class was generated from the following file:
Data/Corpus.hpp