crawlserv++: crawlservpp::Module::Crawler::Database Class Reference
crawlservpp::Module::Crawler::Database Class Reference final
Class providing database functionality for crawler threads by implementing Wrapper::Database.
#include <Database.hpp>
Classes
class Exception
Class for crawler-specific database exceptions.
Construction
Database (Module::Database &dbThread)
Constructor setting the database connection for the thread.
Crawler-specific Setters
void setRecrawl (bool isRecrawl)
Sets whether all URLs will be recrawled.
void setUrlCaseSensitive (bool isUrlCaseSensitive)
Sets whether the current URL list is case-sensitive.
void setUrlDebug (bool isUrlDebug)
Sets whether to enable URL debugging.
void setUrlStartupCheck (bool isUrlStartupCheck)
Sets whether to check URLs on startup.
Prepared SQL Statements
void prepare ()
Prepares the SQL statements for the crawler.
URLs
std::uint64_t getUrlId (const std::string &url)
Gets the ID of a URL from the database.
IdString getNextUrl (std::uint64_t currentUrlId)
Gets the ID of the next URL to crawl from the database.
bool addUrlIfNotExists (const std::string &urlString, bool manual)
Adds a URL to the database, if it doesnt exist already.
std::size_t addUrlsIfNotExist (std::queue< std::string > &urls, bool manual)
Adds URLs to the database, if they do not exist already.
std::uint64_t getUrlPosition (std::uint64_t urlId)
Gets the position of a URL in the current URL list.
std::uint64_t getNumberOfUrls ()
Gets the number of URL in the current URL list.
URL Checking
void urlDuplicationCheck ()
Checks the current URL list for duplicates.
void urlHashCheck ()
Checks the hash values in the current URL list.
void urlEmptyCheck ()
Checks for empty URLs in the current URL list.
void urlUtf8Check ()
Checks for URLs containing invalid UTF-8 characters in the current URL list.
URL Locking
std::string getUrlLockTime (std::uint64_t urlId)
Gets the time, until which a URL has been locked.
bool isUrlCrawled (std::uint64_t urlId)
Gets whether a URL has been crawled.
std::string lockUrlIfOk (std::uint64_t urlId, const std::string &lockTime, std::uint32_t lockTimeout)
Locks a URL if it is lockable or still locked by the current thread.
void unLockUrlIfOk (std::uint64_t urlId, const std::string &lockTime)
Unlocks a URL in the database.
void setUrlFinishedIfOk (std::uint64_t urlId, const std::string &lockTime)
Sets the URL to crawled in the database, if it is still locked by the thread.
Crawling
void saveContent (std::uint64_t urlId, std::uint32_t response, const std::string &type, const std::string &content)
Saves crawled content to the database.
void saveArchivedContent (std::uint64_t urlId, const std::string &timeStamp, std::uint32_t response, const std::string &type, const std::string &content)
Saves archived content to the database.
bool isArchivedContentExists (std::uint64_t urlId, const std::string &timeStamp)
Checks whether archived content for a URL with a specific timestamp already exists in the database.
Setters
void setLogging (std::uint8_t level, std::uint8_t min, std::uint8_t verbose)
Sets the current, minimal, and verbose logging levels.
void setSleepOnError (std::uint64_t seconds)
Sets the number of seconds to sleep before trying to reconnect after connection loss.
void setTimeOut (std::uint64_t milliseconds)
Sets the maximum execution time for MySQL queries, in milliseconds.
Logging
void log (std::uint8_t level, const std::string &logEntry)
Writes a thread-specific log entry to the database.
void log (std::uint8_t level, std::queue< std::string > &logEntries)
Writes multiple thread-specific log entries to the database.
Websites
std::string getWebsiteDomain (std::uint64_t websiteId)
Gets the domain of a website from the database.
Queries
void getQueryProperties (std::uint64_t queryId, QueryProperties &queryPropertiesTo)
Gets the properties of a query from the database.
Configurations
std::string getConfiguration (std::uint64_t configId)
Gets a configuration from the database.
Target Tables
std::uint64_t addTargetTable (const TargetTableProperties &properties)
Adds a new target table or updates an existing target table in the database.
std::queue< IdString > getTargetTables (const std::string &type, std::uint64_t listId)
Gets the target tables of the specified type for a URL list from the database.
std::uint64_t getTargetTableId (const std::string &type, std::uint64_t listId, const std::string &tableName)
Gets the ID of a target table from the database.
std::string getTargetTableName (const std::string &type, std::uint64_t tableId)
Gets the name of a target table from the database.
void deleteTargetTable (const std::string &type, std::uint64_t tableId)
Deletes a target table from the database.
Locking
void beginNoLock ()
Disables database locking by starting a new SQL transaction.
void endNoLock ()
Re-enables database locking by ending the previous SQL transaction.
Tables
bool isTableEmpty (const std::string &tableName)
Checks whether a table in the database is empty.
bool isTableExists (const std::string &tableName)
Checks whether a table exists in the database.
bool isColumnExists (const std::string &tableName, const std::string &columnName)
Checks whether a table in the database contains a specific column.
std::string getColumnType (const std::string &tableName, const std::string &columnName)
Gets the type of a specific table column from the database.
Custom Data
void getCustomData (Data::GetValue &data)
Gets a custom value from one column from a table row in the database.
void getCustomData (Data::GetFields &data)
Gets custom values from multiple columns of the same type from a table row.
void getCustomData (Data::GetFieldsMixed &data)
Gets custom values from multiple columns of different types from a table row.
void getCustomData (Data::GetColumn &data)
Gets custom values from a table column in the database.
void getCustomData (Data::GetColumns &data)
Gets custom values from multiple table columns of the same type.
void getCustomData (Data::GetColumnsMixed &data)
Gets custom values from multiple table columns of different types.
void insertCustomData (const Data::InsertValue &data)
Inserts a custom value into a table row in the database.
void insertCustomData (const Data::InsertFields &data)
Inserts custom values into multiple table columns of the same type.
void insertCustomData (const Data::InsertFieldsMixed &data)
Inserts custom values into multiple table columns of different types.
void updateCustomData (const Data::UpdateValue &data)
Updates a custom value in a table row.
void updateCustomData (const Data::UpdateFields &data)
Updates custom values in multiple table columns of the same type.
void updateCustomData (const Data::UpdateFieldsMixed &data)
Updates custom values in multiple table columns of different types.
Request Counter
static std::uint64_t getRequestCounter ()
Gets the number of SQL requests performed since the start of the application.
Database Connection
Module::Database & database
Reference to the database connection for the thread.
Getters
const ModuleOptions & getOptions () const
Gets the options of the module.
const std::string & getWebsiteIdString () const
Gets the ID of the website used by the thread as string.
const std::string & getUrlListIdString () const
Gets the ID of the URL list used by the thread as string.
std::uint8_t getLoggingMin () const
Gets the minimal logging level.
std::uint8_t getLoggingVerbose () const
Gets the level for verbose logging.
std::uint64_t getMaxAllowedPacketSize () const
Gets the maximum allowed packet size for communicating with the MySQL server.
Validation
void checkConnection ()
Checks whether the connection to the database is still valid and tries to reconnect if necessary.
Helper Functions for Prepared SQL Statements
void reserveForPreparedStatements (std::size_t n)
Reserves memory for a specific number of additional prepared SQL statements.
std::size_t addPreparedStatement (const std::string &sqlQuery)
Prepares an additional SQL statement and returns its ID.
sql::PreparedStatement & getPreparedStatement (std::uint8_t id)
Gets a reference to a prepared SQL statement.
Database Helper Functions
std::uint64_t getLastInsertedId ()
Gets the last inserted ID from the database.
void createTable (const TableProperties &properties)
Adds a table to the database.
void dropTable (const std::string &tableName)
Deletes a table from the database.
void addColumn (const std::string &tableName, const TableColumn &column)
Adds a column to a table in the database.
void compressTable (const std::string &tableName)
Compresses a table in the database.
static void addDatabaseLock (const std::string &name, const IsRunningCallback &isRunningCallback)
Adds a lock to the database class, blocking execution.
static bool tryDatabaseLock (const std::string &name)
Tries to add a lock to the database class, not blocking execution.
static void removeDatabaseLock (const std::string &name)
Removes a lock from the database class.
URL List Helper Functions
void setUrlListCaseSensitive (std::uint64_t listId, bool isCaseSensitive)
Sets whether the specified URL list is case-sensitive.
Exception Helper Functions
static void sqlException (const std::string &function, const sql::SQLException &e)
Catches a SQL exception and re-throws it as a specific or a generic Database::Exception.
Helper Functions for Executing SQL Queries
static bool sqlExecute (sql::PreparedStatement &sqlPreparedStatement)
Executes a prepared SQL statement.
static sql::ResultSet * sqlExecuteQuery (sql::PreparedStatement &sqlPreparedStatement)
Executes a prepared SQL statement and returns the resulting set.
static int sqlExecuteUpdate (sql::PreparedStatement &sqlPreparedStatement)
Executes a prepared SQL statement and returns the number of affected rows.
Detailed Description
Class providing database functionality for crawler threads by implementing Wrapper::Database.
Constructor & Destructor Documentation
Database()
crawlservpp::Module::Crawler::Database::Database (Module::Database & dbThread) explicit
Constructor setting the database connection for the thread.
Parameters
dbThread Reference to the database connection used by the crawler thread.
Member Function Documentation
addColumn()
void crawlservpp::Wrapper::Database::addColumn (const std::string & tableName, const TableColumn & column) inline protected inherited
Adds a column to a table in the database.
Parameters
tableName Constant reference to a string containing the name of the table to which the column will be added.
column Constant reference to a structure containing the properties of the column to be added to the table.
Exceptions
Main::Database::Exception if no table, no column, or no column type is specified, i.e. if one of the strings containing the name of the table, the name of the column, and the type of the column is empty, or if a column reference is incomplete.
Main::Database::Exception if a MySQL error occured while adding the column to the given table in the database.
See also
Struct::TableColumn
References crawlservpp::Main::Database::addColumn(), and crawlservpp::Wrapper::Database::database.
addDatabaseLock()
void crawlservpp::Wrapper::Database::addDatabaseLock (const std::string & name, const IsRunningCallback & isRunningCallback) inline static protected inherited
Adds a lock to the database class, blocking execution.
If a lock with the same name already exists, the function will block execution until this lock has been released, or the specified callback function returns false.
Parameters
name Constant reference to a string containing the name of the lock to be waited for and added to the database class.
isRunningCallback Constant reference to a function that will be regularly called during a block, to enquire whether the thread (or application) is still running. As soon as this function returns false, execution will no longer be blocked, even if the lock could not be added.
References crawlservpp::Main::Database::addDatabaseLock().
addPreparedStatement()
std::size_t crawlservpp::Wrapper::Database::addPreparedStatement (const std::string & sqlQuery) inline protected inherited
Prepares an additional SQL statement and returns its ID.
Parameters
sqlQuery Constant reference to a string containing the SQL query for the prepared SQL statement.
Returns
A unique ID identifying the prepared SQL query in-class.
Exceptions
Main::Database::Exception if a MySQL error occured while preparing and adding the SQL statement.
References crawlservpp::Main::Database::addPreparedStatement(), and crawlservpp::Wrapper::Database::database.
Referenced by prepare(), crawlservpp::Module::Parser::Database::prepare(), crawlservpp::Module::Extractor::Database::prepare(), crawlservpp::Module::Analyzer::Database::prepare(), crawlservpp::Module::Analyzer::Database::prepareAlgo(), crawlservpp::Module::Parser::Database::unLockUrlsIfOk(), and crawlservpp::Module::Extractor::Database::unLockUrlsIfOk().
addTargetTable()
std::uint64_t crawlservpp::Wrapper::Database::addTargetTable (const TargetTableProperties & properties) inline inherited
Adds a new target table or updates an existing target table in the database.
Parameters
properties Constant reference to the properties of the new target table, or the existing target table to be updated.
Returns
If no target table with the specified type and name already exists, a unique ID identifying the new target table in the database. The ID of the new table is, however, only unique among all target tables of the same type. If a target table with the specified type and name already exists, its ID will be returned instead.
Exceptions
Main::Database::Exception if no type, website, URL list, name, or columns have been specfied in the given properties of the new target table, or if a column of the already existing target table cannot be overwritten due to incompatibilities between the respective data types.
Main::Database::Exception if a MySQL error occured while adding the new target table, or updating the existing target table in the database.
References crawlservpp::Main::Database::addTargetTable(), and crawlservpp::Wrapper::Database::database.
Referenced by crawlservpp::Module::Parser::Database::initTargetTable(), crawlservpp::Module::Analyzer::Database::initTargetTable(), and crawlservpp::Module::Extractor::Database::initTargetTables().
addUrlIfNotExists()
bool crawlservpp::Module::Crawler::Database::addUrlIfNotExists (const std::string & urlString, bool manual)
Adds a URL to the database, if it doesnt exist already.
Parameters
urlString Constant reference to a string containing the URL to be added to the current URL list in the database.
manual Specifies whether the URL is a custom URL, i.e. has been manually added.
Returns
True if the URL has been added. False, if the URL had already existed.
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, or the prepared SQL statement for adding a URL to the database is missing.
Main::Database::Exception if a MySQL error occured while adding the URL to the database.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Module::Crawler::sqlArg3, crawlservpp::Module::Crawler::sqlArg4, crawlservpp::Module::Crawler::sqlArg5, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteUpdate().
addUrlsIfNotExist()
std::size_t crawlservpp::Module::Crawler::Database::addUrlsIfNotExist (std::queue< std::string > & urls, bool manual)
Adds URLs to the database, if they do not exist already.
Adds the given URLs in batches of 1,000, 100 and 10 to the database, if possible, to considerably speed up the process.
Parameters
urls Reference to a queue containing the URLs to be added to the current URL list in the database. The queue will be cleared after a succesfull call to the function, even if some or all of the given URL have not been added, because they already existed in the database.
manual Specifies whether the URLs are custom URL, i.e. have been manually added.
Returns
The number of given URLs that did not yet exist and have been added to the database.
Exceptions
Module::Crawler::Database::Exception if one of the prepared SQL statements for adding URLs to the database is missing.
Main::Database::Exception if a MySQL error occured while adding the URLs to the database.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::nAtOnce10, crawlservpp::Module::Crawler::nAtOnce100, crawlservpp::Module::Crawler::nAtOnce1000, crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Module::Crawler::sqlArg3, crawlservpp::Module::Crawler::sqlArg4, crawlservpp::Module::Crawler::sqlArg5, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteUpdate().
beginNoLock()
void crawlservpp::Wrapper::Database::beginNoLock () inline inherited
Disables database locking by starting a new SQL transaction.
Exceptions
Main::Database::Exception if a MySQL error occured while starting a new SQL transaction in the database.
References crawlservpp::Main::Database::beginNoLock(), and crawlservpp::Wrapper::Database::database.
Referenced by getNumberOfUrls(), and getUrlPosition().
checkConnection()
void crawlservpp::Wrapper::Database::checkConnection () inline protected inherited
Checks whether the connection to the database is still valid and tries to reconnect if necessary.
Warning
Afterwards, old references to prepared SQL statements might be invalid, because the connection to the database might have been reset.
Exceptions
Main::Database::Exception if the MySQL driver is not initialized.
Main::Database::Exception if a MySQL error occured while attempting to reconnect to the database.
References crawlservpp::Main::Database::checkConnection(), and crawlservpp::Wrapper::Database::database.
Referenced by addUrlIfNotExists(), addUrlsIfNotExist(), crawlservpp::Module::Extractor::Database::checkExtractingTable(), crawlservpp::Module::Parser::Database::checkParsingTable(), crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Module::Parser::Database::fetchUrls(), crawlservpp::Module::Extractor::Database::fetchUrls(), crawlservpp::Module::Parser::Database::getAllContents(), crawlservpp::Module::Extractor::Database::getContent(), crawlservpp::Module::Parser::Database::getContentIdFromParsedId(), crawlservpp::Module::Analyzer::Database::getCorpus(), crawlservpp::Module::Parser::Database::getLatestContent(), crawlservpp::Module::Extractor::Database::getLatestParsedData(), crawlservpp::Module::Parser::Database::getLockTime(), crawlservpp::Module::Extractor::Database::getLockTime(), getNextUrl(), crawlservpp::Module::Parser::Database::getNumberOfContents(), getNumberOfUrls(), crawlservpp::Module::Parser::Database::getNumberOfUrls(), crawlservpp::Module::Extractor::Database::getNumberOfUrls(), getUrlId(), getUrlLockTime(), crawlservpp::Module::Parser::Database::getUrlLockTime(), crawlservpp::Module::Extractor::Database::getUrlLockTime(), getUrlPosition(), crawlservpp::Module::Parser::Database::getUrlPosition(), crawlservpp::Module::Extractor::Database::getUrlPosition(), isArchivedContentExists(), crawlservpp::Module::Analyzer::Database::isCorpusChanged(), isUrlCrawled(), lockUrlIfOk(), prepare(), crawlservpp::Module::Parser::Database::prepare(), crawlservpp::Module::Extractor::Database::prepare(), crawlservpp::Module::Analyzer::Database::prepare(), crawlservpp::Module::Analyzer::Database::prepareAlgo(), crawlservpp::Module::Parser::Database::renewUrlLockIfOk(), crawlservpp::Module::Extractor::Database::renewUrlLockIfOk(), saveArchivedContent(), saveContent(), setUrlFinishedIfOk(), crawlservpp::Module::Extractor::Database::setUrlsFinishedIfLockOk(), crawlservpp::Module::Parser::Database::setUrlsFinishedIfLockOk(), unLockUrlIfOk(), crawlservpp::Module::Parser::Database::unLockUrlIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlIfOk(), crawlservpp::Module::Parser::Database::unLockUrlsIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlsIfOk(), crawlservpp::Module::Extractor::Database::updateOrAddEntries(), crawlservpp::Module::Parser::Database::updateOrAddEntries(), crawlservpp::Module::Extractor::Database::updateTargetTable(), crawlservpp::Module::Parser::Database::updateTargetTable(), urlDuplicationCheck(), urlEmptyCheck(), and urlHashCheck().
compressTable()
void crawlservpp::Wrapper::Database::compressTable (const std::string & tableName) inline protected inherited
Compresses a table in the database.
The function will have no effect om the table, if the table is already compressed.
Parameters
tableName Constant reference to a string containing the name of the table to be compressed.
Exceptions
Main::Database::Exception if no table is specified, i.e. if the string containing the name of the table is empty, or if a row format could not be determined.
Main::Database::Exception if a MySQL error occured while compressing the table in the database.
References crawlservpp::Main::Database::compressTable(), and crawlservpp::Wrapper::Database::database.
createTable()
void crawlservpp::Wrapper::Database::createTable (const TableProperties & properties) inline protected inherited
Adds a table to the database.
Note
A column for the primary key named id will be created automatically.
Parameters
properties Constant reference to a structure containing the properties of the table to be created.
Exceptions
Main::Database::Exception if no name or columns are specified in the given properties structure, if one of the columns defined there is missing its name or data type, or if a column reference is incomplete.
Main::Database::Exception if a MySQL error occured while adding the table to the database.
See also
Struct::TableProperties
References crawlservpp::Main::Database::createTable(), and crawlservpp::Wrapper::Database::database.
deleteTargetTable()
void crawlservpp::Wrapper::Database::deleteTargetTable (const std::string & type, std::uint64_t tableId) inline inherited
Deletes a target table from the database.
Parameters
type Constant reference to a string containing the type of the target table to be deleted
tableId The ID of the target table to be deleted.
Exceptions
Main::Database::Exception if no target table has been specified, i.e. the string containing the type is empty or the target table ID is zero.
Main::Database::Exception if a MySQL error occured while deleting the target table from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::deleteTargetTable().
dropTable()
void crawlservpp::Wrapper::Database::dropTable (const std::string & tableName) inline protected inherited
Deletes a table from the database.
If the table does not exist in the database, the database will not be changed.
Parameters
tableName Constant reference to a string containing the name of the table to be deleted, if it exists.
Exceptions
Main::Database::Exception if no table is specified, i.e. if the string containing the name of the table is empty.
Main::Database::Exception if a MySQL error occured while removing the table from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::dropTable().
endNoLock()
void crawlservpp::Wrapper::Database::endNoLock () inline inherited
Re-enables database locking by ending the previous SQL transaction.
Exceptions
Main::Database::Exception if a MySQL error occured while ending the previous SQL transaction by committing the changes to the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::endNoLock().
Referenced by getNumberOfUrls(), and getUrlPosition().
getColumnType()
std::string crawlservpp::Wrapper::Database::getColumnType (const std::string & tableName, const std::string & columnName) inline inherited
Gets the type of a specific table column from the database.
Parameters
tableName Constant reference to a string containing the name of the table in the database from which the type of the column will be retrieved.
columnName Constant reference to a string containing the name of the column whose type will be retrieved.
Returns
A copy of the name of the given table column's data type.
Exceptions
Main::Database::Exception if no table or column name has been specified, i.e. one of the strings containing the name and the column is empty.
Main::Database::Exception if a MySQL error occured while retrieving the type of the given column, e.g. if the specified table does not exist.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getColumnType().
getConfiguration()
std::string crawlservpp::Wrapper::Database::getConfiguration (std::uint64_t configId) inline inherited
Gets a configuration from the database.
Parameters
configId The ID of the configuration to be retrieved from the database.
Returns
A copy of the configuration's JSON string as stored in the database, or an empty string if the given configuration does not exist in the database.
Exceptions
Main::Database::Exception if no configuration has been specified, i.e. the configuration ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the configuration from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getConfiguration().
Referenced by crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
getCustomData() [1/6]
void crawlservpp::Wrapper::Database::getCustomData (Data::GetColumn & data) inline inherited
Gets custom values from a table column in the database.
Parameters
data Reference to the data structure that identifies the column, and to which the result will be written.
Exceptions
Main::Database::Exception if no column or column type is specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetColumn
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getCustomData().
getCustomData() [2/6]
void crawlservpp::Wrapper::Database::getCustomData (Data::GetColumns & data) inline inherited
Gets custom values from multiple table columns of the same type.
Parameters
data Reference to the data structure that identifies the columns, and to which the result will be written.
Exceptions
Main::Database::Exception if no column or column type is specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetColumns
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getCustomData().
getCustomData() [3/6]
void crawlservpp::Wrapper::Database::getCustomData (Data::GetColumnsMixed & data) inline inherited
Gets custom values from multiple table columns of different types.
Parameters
data Reference to the data structure that identifies the columns and their types, and to which the result will be written.
Exceptions
Main::Database::Exception if no columns have been specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetColumnsMixed
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getCustomData().
getCustomData() [4/6]
void crawlservpp::Wrapper::Database::getCustomData (Data::GetFields & data) inline inherited
Gets custom values from multiple columns of the same type from a table row.
Parameters
data Reference to the data structure that identifies the columns, and to which the result will be written.
Exceptions
Main::Database::Exception if no column names or no column type are specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetFields
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getCustomData().
getCustomData() [5/6]
void crawlservpp::Wrapper::Database::getCustomData (Data::GetFieldsMixed & data) inline inherited
Gets custom values from multiple columns of different types from a table row.
Parameters
data Reference to the data structure that identifies the columns and their types, and to which the result will be written.
Exceptions
Main::Database::Exception if no columns are specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetFieldsMixed
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getCustomData().
getCustomData() [6/6]
void crawlservpp::Wrapper::Database::getCustomData (Data::GetValue & data) inline inherited
Gets a custom value from one column from a table row in the database.
Parameters
data Reference to the data structure that identifies the column, and to which the result will be written.
Exceptions
Main::Database::Exception if no column name or no column type is specified in the given data structure, or if an invalid data type has been encountered.
Main::Database::Exception if a MySQL error occured while retrieving the data.
See also
Data::GetValue
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getCustomData().
Referenced by crawlservpp::Module::Analyzer::Database::createCorpus().
getLastInsertedId()
std::uint64_t crawlservpp::Wrapper::Database::getLastInsertedId () inline protected inherited
Gets the last inserted ID from the database.
Returns
The last inserted ID from the database.
Exceptions
Main::Database::Exception if the prepared SQL statement for retrieving the last inserted ID from the database is missing.
Main::Database::Exception if a MySQL error occured while retrieving the last inserted ID from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getLastInsertedId().
Referenced by crawlservpp::Module::Analyzer::Database::createCorpus().
getLoggingMin()
std::uint8_t crawlservpp::Wrapper::Database::getLoggingMin () const inline protected inherited
Gets the minimal logging level.
Returns
The minimum logging level, in which logging is still not deactivated.
References crawlservpp::Wrapper::Database::database.
Referenced by crawlservpp::Module::Analyzer::Database::checkSource(), crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Module::Analyzer::Database::getCorpus(), saveArchivedContent(), saveContent(), and urlHashCheck().
getLoggingVerbose()
std::uint8_t crawlservpp::Wrapper::Database::getLoggingVerbose () const inline protected inherited
Gets the level for verbose logging.
Returns
The logging level, in which verbose logging is activated.
References crawlservpp::Wrapper::Database::database.
Referenced by prepare(), crawlservpp::Module::Parser::Database::prepare(), crawlservpp::Module::Extractor::Database::prepare(), crawlservpp::Module::Analyzer::Database::prepare(), and crawlservpp::Module::Analyzer::Database::prepareAlgo().
getMaxAllowedPacketSize()
std::uint64_t crawlservpp::Wrapper::Database::getMaxAllowedPacketSize () const inline protected inherited
Gets the maximum allowed packet size for communicating with the MySQL server.
Returns
The maximum allowed packet size for communicating with the MySQL server, in bytes, or zero if not connected to the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getMaxAllowedPacketSize().
Referenced by crawlservpp::Module::Analyzer::Database::createCorpus(), saveArchivedContent(), and saveContent().
getNextUrl()
Database::IdString crawlservpp::Module::Crawler::Database::getNextUrl (std::uint64_t currentUrlId)
Gets the ID of the next URL to crawl from the database.
Parameters
currentUrlId The ID of the URL that has been crawled last.
Returns
A pair of the ID and a string containing the next URL to crawl, or an empty pair if there are no more URLs to crawl.
Exceptions
Module::Crawler::Database::Exception if the prepared SQL statement for retrieving the next URL to crawl is missing.
Main::Database::Exception if a MySQL error occured while retrieving the next URL to crawl from the database.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
getNumberOfUrls()
std::uint64_t crawlservpp::Module::Crawler::Database::getNumberOfUrls ()
Gets the number of URL in the current URL list.
Returns
The total number of URLs in the current URL list.
Exceptions
Module::Crawler::Database::Exception if the prepared SQL statement for retrieving the number of URLs is missing.
Main::Database::Exception if a MySQL error occured while retrieving the number of URLs from the database.
References crawlservpp::Wrapper::Database::beginNoLock(), crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::endNoLock(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
getOptions()
const Struct::ModuleOptions & crawlservpp::Wrapper::Database::getOptions () const inline protected inherited
Gets the options of the module.
Returns
A reference to the structure containing the options for the module.
See also
Struct::ModuleOptions
References crawlservpp::Wrapper::Database::database.
Referenced by crawlservpp::Module::Parser::Database::initTargetTable(), crawlservpp::Module::Analyzer::Database::initTargetTable(), crawlservpp::Module::Extractor::Database::initTargetTables(), prepare(), crawlservpp::Module::Analyzer::Database::prepare(), and setUrlCaseSensitive().
getPreparedStatement()
sql::PreparedStatement & crawlservpp::Wrapper::Database::getPreparedStatement (std::uint8_t id) inline protected inherited
Gets a reference to a prepared SQL statement.
Warning
Do not run checkConnection while using this reference, because the references will be invalidated when reconnecting to the database!
Parameters
id The ID of the prepared SQL statement to retrieve.
Returns
A reference to the prepared SQL statement.
Exceptions
Main::Database::Exception if a MySQL error occured while retrieving the prepared SQL statement.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getPreparedStatement().
Referenced by addUrlIfNotExists(), addUrlsIfNotExist(), crawlservpp::Module::Extractor::Database::checkExtractingTable(), crawlservpp::Module::Parser::Database::checkParsingTable(), crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Module::Parser::Database::fetchUrls(), crawlservpp::Module::Extractor::Database::fetchUrls(), crawlservpp::Module::Parser::Database::getAllContents(), crawlservpp::Module::Extractor::Database::getContent(), crawlservpp::Module::Parser::Database::getContentIdFromParsedId(), crawlservpp::Module::Analyzer::Database::getCorpus(), crawlservpp::Module::Parser::Database::getLatestContent(), crawlservpp::Module::Extractor::Database::getLatestParsedData(), crawlservpp::Module::Parser::Database::getLockTime(), crawlservpp::Module::Extractor::Database::getLockTime(), getNextUrl(), crawlservpp::Module::Parser::Database::getNumberOfContents(), getNumberOfUrls(), crawlservpp::Module::Parser::Database::getNumberOfUrls(), crawlservpp::Module::Extractor::Database::getNumberOfUrls(), crawlservpp::Module::Analyzer::Database::getPreparedAlgoStatement(), getUrlId(), getUrlLockTime(), crawlservpp::Module::Parser::Database::getUrlLockTime(), crawlservpp::Module::Extractor::Database::getUrlLockTime(), getUrlPosition(), crawlservpp::Module::Parser::Database::getUrlPosition(), crawlservpp::Module::Extractor::Database::getUrlPosition(), isArchivedContentExists(), crawlservpp::Module::Analyzer::Database::isCorpusChanged(), isUrlCrawled(), lockUrlIfOk(), crawlservpp::Module::Parser::Database::renewUrlLockIfOk(), crawlservpp::Module::Extractor::Database::renewUrlLockIfOk(), saveArchivedContent(), saveContent(), setUrlFinishedIfOk(), crawlservpp::Module::Extractor::Database::setUrlsFinishedIfLockOk(), crawlservpp::Module::Parser::Database::setUrlsFinishedIfLockOk(), unLockUrlIfOk(), crawlservpp::Module::Parser::Database::unLockUrlIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlIfOk(), crawlservpp::Module::Parser::Database::unLockUrlsIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlsIfOk(), crawlservpp::Module::Extractor::Database::updateOrAddEntries(), crawlservpp::Module::Parser::Database::updateOrAddEntries(), crawlservpp::Module::Extractor::Database::updateTargetTable(), crawlservpp::Module::Parser::Database::updateTargetTable(), urlDuplicationCheck(), urlEmptyCheck(), and urlHashCheck().
getQueryProperties()
void crawlservpp::Wrapper::Database::getQueryProperties (std::uint64_t queryId, QueryProperties & queryPropertiesTo) inline inherited
Gets the properties of a query from the database.
Parameters
queryId The ID of the query for which the properties will be retrieved from the database.
queryPropertiesTo Reference to the structure to which the retrieved properties of the query will be written.
Exceptions
Main::Database::Exception if no query ID has been specfied, i.e. the query ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the properties of the given query from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getQueryProperties().
getRequestCounter()
std::uint64_t crawlservpp::Wrapper::Database::getRequestCounter () inline static inherited
Gets the number of SQL requests performed since the start of the application.
Note
By default, the request counter should be deactivated and the function always return zero.
Returns
The number of SQL requests performed since the start of the application or zero, if the request counter had not been activated on compilation.
References crawlservpp::Main::Database::getRequestCounter().
getTargetTableId()
std::uint64_t crawlservpp::Wrapper::Database::getTargetTableId (const std::string & type, std::uint64_t listId, const std::string & tableName) inline inherited
Gets the ID of a target table from the database.
Parameters
type Constant reference to a string containing the type of the target table for which to retrieve its ID.
listId The ID of the URL list associated with the target table for which to retrieve its ID.
tableName Const reference to a string containing the name of the target table for which to retrieve its ID.
Returns
The ID of the specified target table as stored in the database.
Exceptions
Main::Database::Exception if no target table or URL list has been specified, i.e. if the string containing the type is empty, or the target table or the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the ID of the target table from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getTargetTableId().
getTargetTableName()
std::string crawlservpp::Wrapper::Database::getTargetTableName (const std::string & type, std::uint64_t tableId) inline inherited
Gets the name of a target table from the database.
Parameters
type Constant reference to a string containing the type of the target table for which to retrieve its name.
tableId The ID of the target table for which to retrieve its name.
Returns
A copy of the name of the specified target table as stored in the database.
Exceptions
Main::Database::Exception if no target table has been specified, i.e. the string containing the type is empty or the target table ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the name of the target table from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getTargetTableName().
getTargetTables()
std::queue< Database::IdString > crawlservpp::Wrapper::Database::getTargetTables (const std::string & type, std::uint64_t listId) inline inherited
Gets the target tables of the specified type for a URL list from the database.
Parameters
type Constant reference to a string containing the type of the target tables to retrieve.
listId The ID of the URL list for which to retrieve the target tables.
Returns
A queue containing the IDs and names of the target tables of the given type for the specified URL list.
Exceptions
Main::Database::Exception if no target table has been specified, i.e. the string containing the type is empty or the target table ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the target tables from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getTargetTables().
getUrlId()
std::uint64_t crawlservpp::Module::Crawler::Database::getUrlId (const std::string & url)
Gets the ID of a URL from the database.
Uses a hash check for first checking the probable existence of the URL.
Parameters
url Constant reference to a string containing the URL to be checked.
Returns
The ID of the given URL, or zero if the URL does not exist in the current URL list.
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, or the prepared SQL statement for retrieving the ID of a URL is missing.
Main::Database::Exception if a MySQL error occured while retrieving the ID of the URL from the database.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
getUrlListIdString()
const std::string & crawlservpp::Wrapper::Database::getUrlListIdString () const inline protected inherited
Gets the ID of the URL list used by the thread as string.
Returns
A reference to the string containing the ID of the URL list used by the thread.
References crawlservpp::Wrapper::Database::database.
Referenced by crawlservpp::Module::Analyzer::Database::prepare().
getUrlLockTime()
std::string crawlservpp::Module::Crawler::Database::getUrlLockTime (std::uint64_t urlId)
Gets the time, until which a URL has been locked.
Parameters
urlId The ID of the URL whose lock time will be retrieved.
Returns
The time, until which the URL has been locked, in the format YYYY-MM-DD HH:MM:SS.
Exceptions
Module::Crawler::Database::Exception if the prepared SQL statement for retrieving the lock time is missing.
Main::Database::Exception if a MySQL error occured while retrieving the lock time of the URL.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
Referenced by lockUrlIfOk().
getUrlPosition()
std::uint64_t crawlservpp::Module::Crawler::Database::getUrlPosition (std::uint64_t urlId)
Gets the position of a URL in the current URL list.
Parameters
urlId ID of the URL whose position in the current URL list will be retrieved from the database.
Returns
The position of the given URL in the current URL list.
Exceptions
Module::Crawler::Database::Exception if the prepared SQL statement for retrieving the position of a URL is missing.
Main::Database::Exception if a MySQL error occured while retrieving the position of the URL from the database.
References crawlservpp::Wrapper::Database::beginNoLock(), crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::endNoLock(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
getWebsiteDomain()
std::string crawlservpp::Wrapper::Database::getWebsiteDomain (std::uint64_t websiteId) inline inherited
Gets the domain of a website from the database.
Parameters
websiteId The ID of the website for which the domain will be retrieved from the database.
Returns
A copy of the domain name of the given website.
Exceptions
Main::Database::Exception if no website has been specified, i.e. the website ID is zero.
Main::Database::Exception if a MySQL error occured while retrieving the domain name of the given website from the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::getWebsiteDomain().
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
getWebsiteIdString()
const std::string & crawlservpp::Wrapper::Database::getWebsiteIdString () const inline protected inherited
Gets the ID of the website used by the thread as string.
Returns
A reference to the string containing the ID of the website used by the thread.
References crawlservpp::Wrapper::Database::database.
Referenced by crawlservpp::Module::Analyzer::Database::prepare().
insertCustomData() [1/3]
void crawlservpp::Wrapper::Database::insertCustomData (const Data::InsertFields & data) inline inherited
Inserts custom values into multiple table columns of the same type.
Parameters
data Constant reference to a structure containing the data to be inserted.
Exceptions
Main::Database::Exception if no columns or no column type are specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while inserting the data.
See also
Data::InsertFields
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::insertCustomData().
insertCustomData() [2/3]
void crawlservpp::Wrapper::Database::insertCustomData (const Data::InsertFieldsMixed & data) inline inherited
Inserts custom values into multiple table columns of different types.
Parameters
data Constant reference to a structure containing the data to be inserted.
Exceptions
Main::Database::Exception if no columns are specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while inserting the data.
See also
Data::InsertFieldsMixed
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::insertCustomData().
insertCustomData() [3/3]
void crawlservpp::Wrapper::Database::insertCustomData (const Data::InsertValue & data) inline inherited
Inserts a custom value into a table row in the database.
Parameters
data Constant reference to a structure containing the data to be inserted.
Exceptions
Main::Database::Exception if no column name or no column type is specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while inserting the data.
See also
Data::InsertValue
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::insertCustomData().
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick().
isArchivedContentExists()
bool crawlservpp::Module::Crawler::Database::isArchivedContentExists (std::uint64_t urlId, const std::string & timeStamp)
Checks whether archived content for a URL with a specific timestamp already exists in the database.
Parameters
urlId The ID of the URL whose archived version has been crawled.
timeStamp The time stamp of the archived content, i.e. when it has been archived by the crawled archive.
Returns
True, if archived content for the specified URL with the given timestamp already exists in the database. False, if no such content has yet been saved to the database.
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, i.e. the given URL ID is zero, or if the prepared SQL statement for checking for archived content in the database is missing.
Main::Database::Exception if a MySQL error occured while checking for archived content in the database.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
isColumnExists()
bool crawlservpp::Wrapper::Database::isColumnExists (const std::string & tableName, const std::string & columnName) inline inherited
Checks whether a table in the database contains a specific column.
Parameters
tableName Constant reference to a string containing the name of the table in the database in which the existence of the column will be checked.
columnName Constant reference to a string containing the name of the column to be checked for in the given table.
Returns
True, if the given column exists in the specified table. False otherwise.
Exceptions
Main::Database::Exception if no table or column name has been specified, i.e. one of the strings containing the name and the column is empty.
Main::Database::Exception if a MySQL error occured while checking the existence of the given column, e.g. if the specified table does not exist.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::isColumnExists().
isTableEmpty()
bool crawlservpp::Wrapper::Database::isTableEmpty (const std::string & tableName) inline inherited
Checks whether a table in the database is empty.
Parameters
tableName Constant reference to a string containing the name of the table whose contents will be checked in the database.
Returns
True, if the given table is empty. False if it contains data.
Exceptions
Main::Database::Exception if no table name has been specified, i.e. the string containing the name is empty.
Main::Database::Exception if a MySQL error occured while checking the content of the given table in the database, e.g. if the table does not exist.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::isTableEmpty().
isTableExists()
bool crawlservpp::Wrapper::Database::isTableExists (const std::string & tableName) inline inherited
Checks whether a table exists in the database.
Parameters
tableName Constant reference to a string containing the name of the table whose existence in the database will be checked.
Returns
True, if the given table exists in the database. False otherwise.
Exceptions
Main::Database::Exception if no table name has been specified, i.e. the string containing the name is empty.
Main::Database::Exception if a MySQL error occured while checking the existence of the given table in the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::isTableExists().
isUrlCrawled()
bool crawlservpp::Module::Crawler::Database::isUrlCrawled (std::uint64_t urlId)
Gets whether a URL has been crawled.
Parameters
urlId The ID of the URL for which to check whether it has been crawled.
Returns
True, if the URL has been crawled. False, if the URL does not exist, or has not yet been crawled.
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, i.e. the given URL ID is zero, or if the prepared SQL statement for checking whether a URL has been crawled is missing.
Main::Database::Exception if a MySQL error occured while checking whether the URL has been crawled.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
lockUrlIfOk()
std::string crawlservpp::Module::Crawler::Database::lockUrlIfOk (std::uint64_t urlId, const std::string & lockTime, std::uint32_t lockTimeout)
Locks a URL if it is lockable or still locked by the current thread.
Parameters
urlId The ID of the URL to lock.
lockTime Constant reference to a string containing the time at which the current lock by the thread for this URL will end (or has ended). Constant reference to an empty string, if the URL has not yet been locked by the current thread.
lockTimeout The time for which to lock the URL for the current thread, in seconds.
Returns
A copy of a string containing the time until which the URL has been locked for the current thread, in the format YYYY-MM-DD HH:MM:SS. A copy of an empty string, if the URL could not be locked, or its lock could not be renewed for the current thread, e.g. because it has already been locked by another thread since the current URL lock expired.
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, i.e. the given URL ID is zero, or if one of the prepared SQL statements for locking a URL, or for renewing a URL lock is missing.
Main::Database::Exception if a MySQL error occured while locking the URL, or renewing its URL lock.
See also
getLockTime
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), getUrlLockTime(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Module::Crawler::sqlArg3, crawlservpp::Module::Crawler::sqlArg4, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteUpdate().
log() [1/2]
void crawlservpp::Wrapper::Database::log (std::uint8_t level, const std::string & logEntry) inline inherited
Writes a thread-specific log entry to the database.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entry will be written to the logging file as well.
The log entry will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entry. The entry will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntry Constant reference to a string containing the log entry.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Module::Database::log().
Referenced by crawlservpp::Module::Analyzer::Database::checkSource(), crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Module::Analyzer::Database::getCorpus(), prepare(), crawlservpp::Module::Parser::Database::prepare(), crawlservpp::Module::Extractor::Database::prepare(), crawlservpp::Module::Analyzer::Database::prepare(), crawlservpp::Module::Analyzer::Database::prepareAlgo(), saveArchivedContent(), saveContent(), and urlHashCheck().
log() [2/2]
void crawlservpp::Wrapper::Database::log (std::uint8_t level, std::queue< std::string > & logEntries) inline inherited
Writes multiple thread-specific log entries to the database.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entries will be written to the logging file as well.
The log entries will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entries. The entries will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntries Reference to a queue of strings containing the log entries to be written. It will be emptied regardless whether the log entries will be written to the database.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Module::Database::log().
prepare()
void crawlservpp::Module::Crawler::Database::prepare ()
Prepares the SQL statements for the crawler.
Note
The target table needs to be prepared first.
Exceptions
Main::Database::Exception if a MySQL error occurs during the preparation of the SQL statements.
References crawlservpp::Wrapper::Database::addPreparedStatement(), crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Module::Crawler::crawlingTableAlias, crawlservpp::Wrapper::Database::getLoggingVerbose(), crawlservpp::Wrapper::Database::getOptions(), crawlservpp::Wrapper::Database::log(), crawlservpp::Module::Crawler::nAtOnce10, crawlservpp::Module::Crawler::nAtOnce100, crawlservpp::Module::Crawler::nAtOnce1000, crawlservpp::Wrapper::Database::reserveForPreparedStatements(), crawlservpp::Struct::ModuleOptions::urlListNamespace, crawlservpp::Module::Crawler::urlListTableAlias, and crawlservpp::Struct::ModuleOptions::websiteNamespace.
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
removeDatabaseLock()
void crawlservpp::Wrapper::Database::removeDatabaseLock (const std::string & name) inline static protected inherited
Removes a lock from the database class.
Does nothing if a lock with the given name does not exist in the database class.
Parameters
name Constant reference to a string containing the name of the lock to be removed from the database class.
References crawlservpp::Main::Database::removeDatabaseLock().
reserveForPreparedStatements()
void crawlservpp::Wrapper::Database::reserveForPreparedStatements (std::size_t n) inline protected inherited
Reserves memory for a specific number of additional prepared SQL statements.
Parameters
n Number of prepared SQL statements for which memory should be reserved.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::reserveForPreparedStatements().
Referenced by prepare(), crawlservpp::Module::Parser::Database::prepare(), crawlservpp::Module::Extractor::Database::prepare(), crawlservpp::Module::Analyzer::Database::prepare(), and crawlservpp::Module::Analyzer::Database::prepareAlgo().
saveArchivedContent()
void crawlservpp::Module::Crawler::Database::saveArchivedContent (std::uint64_t urlId, const std::string & timeStamp, std::uint32_t response, const std::string & type, const std::string & content)
Saves archived content to the database.
Parameters
urlId The ID of the URL whose archived version has been crawled.
timeStamp The time stamp of the archived content, i.e. when it has been archived by the crawled archive.
response The HTTP status code that has been received together with the content, e.g. 200 for OK.
type Constant reference to a string containing the description of the content type that has been received together with the content, e.g. text/html.
content Constant reference to a string containing the crawled content to be saved to the database.
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, i.e. the given URL ID is zero, or if the prepared SQL statement for saving archived content to the database is missing.
Main::Database::Exception if a MySQL error occured while saving the archived content to the database.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getLoggingMin(), crawlservpp::Wrapper::Database::getMaxAllowedPacketSize(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Wrapper::Database::log(), crawlservpp::Module::Crawler::maxContentSize, crawlservpp::Module::Crawler::maxContentSizeString, crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Module::Crawler::sqlArg3, crawlservpp::Module::Crawler::sqlArg4, crawlservpp::Module::Crawler::sqlArg5, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecute().
saveContent()
void crawlservpp::Module::Crawler::Database::saveContent (std::uint64_t urlId, std::uint32_t response, const std::string & type, const std::string & content)
Saves crawled content to the database.
Parameters
urlId The ID of the URL that has been crawled.
response The HTTP status code that has been received together with the content, e.g. 200 for OK.
type Constant reference to a string containing the description of the content type that has been received together with the content, e.g. text/html.
content Constant reference to a string containing the crawled content to be saved to the database.
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, i.e. the given URL ID is zero, or if the prepared SQL statement for saving crawled content to the database is missing.
Main::Database::Exception if a MySQL error occured while saving the crawled content to the database.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getLoggingMin(), crawlservpp::Wrapper::Database::getMaxAllowedPacketSize(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Wrapper::Database::log(), crawlservpp::Module::Crawler::maxContentSize, crawlservpp::Module::Crawler::maxContentSizeString, crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Module::Crawler::sqlArg3, crawlservpp::Module::Crawler::sqlArg4, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecute().
setLogging()
void crawlservpp::Wrapper::Database::setLogging (std::uint8_t level, std::uint8_t min, std::uint8_t verbose) inline inherited
Sets the current, minimal, and verbose logging levels.
Initializes debug logging via logging file if necessary.
Parameters
level The current logging level.
min The minimum logging level.
verbose The verbose logging level.
Exceptions
Module::Database::Exception if the logging file could not be opened for writing.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Module::Database::setLogging().
Referenced by crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
setRecrawl()
void crawlservpp::Module::Crawler::Database::setRecrawl (bool isRecrawl)
Sets whether all URLs will be recrawled.
Note
Needs to be set before preparing the SQL statements for the crawler.
Parameters
isRecrawl Set to true, to force the re-crawling of all URLs.
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
setSleepOnError()
void crawlservpp::Wrapper::Database::setSleepOnError (std::uint64_t seconds) inline inherited
Sets the number of seconds to sleep before trying to reconnect after connection loss.
Parameters
seconds The number of seconds to wait before trying to reconnect to the MySQL server after the connection got lost.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::setSleepOnError().
Referenced by crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
setTimeOut()
void crawlservpp::Wrapper::Database::setTimeOut (std::uint64_t milliseconds) inline inherited
Sets the maximum execution time for MySQL queries, in milliseconds.
Note
The database connection needs to be estanblished before setting the time out.
Parameters
milliseconds The number of milliseconds for a MySQL query to run before it gets cancelled, or zero to disable the time-out for MySQL queries.
Exceptions
Main::Database::Exception if a MySQL error occurs while setting the execution time.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::setTimeOut().
Referenced by crawlservpp::Module::Parser::Thread::onInit().
setUrlCaseSensitive()
void crawlservpp::Module::Crawler::Database::setUrlCaseSensitive (bool isUrlCaseSensitive)
Sets whether the current URL list is case-sensitive.
Note
Needs to be set before preparing the SQL statements for the crawler.
Parameters
isUrlCaseSensitive Specifies whether the URLs in the current URL list are case-sensitive.
Warning
Changing this property of the URL list will invalidate all hashs previously created!
References crawlservpp::Wrapper::Database::getOptions(), and crawlservpp::Wrapper::Database::setUrlListCaseSensitive().
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
setUrlDebug()
void crawlservpp::Module::Crawler::Database::setUrlDebug (bool isUrlDebug)
Sets whether to enable URL debugging.
Note
Needs to be set before preparing the SQL statements for the crawler.
Parameters
isUrlDebug Specifies whether URL debugging is enabled.
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
setUrlFinishedIfOk()
void crawlservpp::Module::Crawler::Database::setUrlFinishedIfOk (std::uint64_t urlId, const std::string & lockTime)
Sets the URL to crawled in the database, if it is still locked by the thread.
Parameters
urlId The ID of the URL to set to crawled.
lockTime Constant reference to a string containing the time at which the current lock by the thread for this URL will end (or has ended).
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, i.e. the given URL ID is zero, if no lock time has been specified, i.e. it references an empty string, or if the prepared SQL statement for setting a URL to crawled is missing.
Main::Database::Exception if a MySQL error occured while setting the URL to crawled.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecute().
setUrlListCaseSensitive()
void crawlservpp::Wrapper::Database::setUrlListCaseSensitive (std::uint64_t listId, bool isCaseSensitive) inline protected inherited
Sets whether the specified URL list is case-sensitive.
Warning
The case-sensitivity should not be changed once URLs have been retrieved!
Parameters
listId The ID of the URL list whose case-sensitivity will be changed.
isCaseSensitive Specify whether URLs in the given URL list will be case-sensitive or not.
Exceptions
Main::Database::Exception if no URL list has been specified, i.e. the URL list ID is zero.
Main::Database::Exception if a MySQL error occured while setting the case-sensitivity of the URL list.
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::setUrlListCaseSensitive().
Referenced by setUrlCaseSensitive().
setUrlStartupCheck()
void crawlservpp::Module::Crawler::Database::setUrlStartupCheck (bool isUrlStartupCheck)
Sets whether to check URLs on startup.
Note
Needs to be set before preparing the SQL statements for the crawler.
Parameters
isUrlStartupCheck Specifies whether to perform a check of the URL list on startup.
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
sqlException()
void crawlservpp::Wrapper::Database::sqlException (const std::string & function, const sql::SQLException & e) inline static protected inherited
Catches a SQL exception and re-throws it as a specific or a generic Database::Exception.
Note
Always throws an exception.
Parameters
function Constant reference to a string containing the name of the function in which the exception has been thrown.
e Constant reference to the SQL exception that has been thrown.
Exceptions
Main::Database::ConnectionException
Main::Database::StorageEngineException
Main::Database::PrivilegesException
Main::Database::WrongArgumentsException
Main::Database::IncorrectPathException
Main::Database::Exception depending on the SQL exception thrown.
References crawlservpp::Main::Database::sqlException().
Referenced by addUrlIfNotExists(), addUrlsIfNotExist(), crawlservpp::Module::Extractor::Database::checkExtractingTable(), crawlservpp::Module::Parser::Database::checkParsingTable(), crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Module::Parser::Database::fetchUrls(), crawlservpp::Module::Extractor::Database::fetchUrls(), crawlservpp::Module::Parser::Database::getAllContents(), crawlservpp::Module::Extractor::Database::getContent(), crawlservpp::Module::Parser::Database::getContentIdFromParsedId(), crawlservpp::Module::Analyzer::Database::getCorpus(), crawlservpp::Module::Parser::Database::getLatestContent(), crawlservpp::Module::Extractor::Database::getLatestParsedData(), crawlservpp::Module::Parser::Database::getLockTime(), crawlservpp::Module::Extractor::Database::getLockTime(), getNextUrl(), crawlservpp::Module::Parser::Database::getNumberOfContents(), getNumberOfUrls(), crawlservpp::Module::Parser::Database::getNumberOfUrls(), crawlservpp::Module::Extractor::Database::getNumberOfUrls(), getUrlId(), getUrlLockTime(), crawlservpp::Module::Parser::Database::getUrlLockTime(), crawlservpp::Module::Extractor::Database::getUrlLockTime(), getUrlPosition(), crawlservpp::Module::Parser::Database::getUrlPosition(), crawlservpp::Module::Extractor::Database::getUrlPosition(), isArchivedContentExists(), crawlservpp::Module::Analyzer::Database::isCorpusChanged(), isUrlCrawled(), lockUrlIfOk(), crawlservpp::Module::Analyzer::Database::prepare(), crawlservpp::Module::Parser::Database::renewUrlLockIfOk(), crawlservpp::Module::Extractor::Database::renewUrlLockIfOk(), saveArchivedContent(), saveContent(), setUrlFinishedIfOk(), crawlservpp::Module::Extractor::Database::setUrlsFinishedIfLockOk(), crawlservpp::Module::Parser::Database::setUrlsFinishedIfLockOk(), unLockUrlIfOk(), crawlservpp::Module::Parser::Database::unLockUrlIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlIfOk(), crawlservpp::Module::Parser::Database::unLockUrlsIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlsIfOk(), crawlservpp::Module::Extractor::Database::updateOrAddEntries(), crawlservpp::Module::Parser::Database::updateOrAddEntries(), crawlservpp::Module::Extractor::Database::updateTargetTable(), crawlservpp::Module::Parser::Database::updateTargetTable(), urlDuplicationCheck(), urlEmptyCheck(), and urlHashCheck().
sqlExecute()
bool crawlservpp::Wrapper::Database::sqlExecute (sql::PreparedStatement & sqlPreparedStatement) inline static protected inherited
Executes a prepared SQL statement.
Parameters
sqlPreparedStatement Reference to the prepared SQL statement to be executed.
Returns
True, if the prepared SQL statement returned a result set. False, if the statement returned nothing or an update count.
References crawlservpp::Main::Database::sqlExecute().
Referenced by crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Module::Parser::Database::fetchUrls(), crawlservpp::Module::Extractor::Database::fetchUrls(), saveArchivedContent(), saveContent(), setUrlFinishedIfOk(), crawlservpp::Module::Extractor::Database::setUrlsFinishedIfLockOk(), crawlservpp::Module::Parser::Database::setUrlsFinishedIfLockOk(), unLockUrlIfOk(), crawlservpp::Module::Parser::Database::unLockUrlsIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlsIfOk(), crawlservpp::Module::Extractor::Database::updateOrAddEntries(), crawlservpp::Module::Parser::Database::updateOrAddEntries(), crawlservpp::Module::Extractor::Database::updateTargetTable(), and crawlservpp::Module::Parser::Database::updateTargetTable().
sqlExecuteQuery()
sql::ResultSet * crawlservpp::Wrapper::Database::sqlExecuteQuery (sql::PreparedStatement & sqlPreparedStatement) inline static protected inherited
Executes a prepared SQL statement and returns the resulting set.
Parameters
sqlPreparedStatement Reference to the prepared SQL statement to be executed.
Returns
A pointer to the result set retrieved by executing the prepared SQL statement.
References crawlservpp::Main::Database::sqlExecuteQuery().
Referenced by crawlservpp::Module::Parser::Database::fetchUrls(), crawlservpp::Module::Extractor::Database::fetchUrls(), crawlservpp::Module::Parser::Database::getAllContents(), crawlservpp::Module::Extractor::Database::getContent(), crawlservpp::Module::Parser::Database::getContentIdFromParsedId(), crawlservpp::Module::Analyzer::Database::getCorpus(), crawlservpp::Module::Parser::Database::getLatestContent(), crawlservpp::Module::Extractor::Database::getLatestParsedData(), crawlservpp::Module::Parser::Database::getLockTime(), crawlservpp::Module::Extractor::Database::getLockTime(), getNextUrl(), crawlservpp::Module::Parser::Database::getNumberOfContents(), getNumberOfUrls(), crawlservpp::Module::Parser::Database::getNumberOfUrls(), crawlservpp::Module::Extractor::Database::getNumberOfUrls(), getUrlId(), getUrlLockTime(), crawlservpp::Module::Parser::Database::getUrlLockTime(), crawlservpp::Module::Extractor::Database::getUrlLockTime(), getUrlPosition(), crawlservpp::Module::Parser::Database::getUrlPosition(), crawlservpp::Module::Extractor::Database::getUrlPosition(), isArchivedContentExists(), crawlservpp::Module::Analyzer::Database::isCorpusChanged(), isUrlCrawled(), urlDuplicationCheck(), urlEmptyCheck(), and urlHashCheck().
sqlExecuteUpdate()
int crawlservpp::Wrapper::Database::sqlExecuteUpdate (sql::PreparedStatement & sqlPreparedStatement) inline static protected inherited
Executes a prepared SQL statement and returns the number of affected rows.
Parameters
sqlPreparedStatement Reference to the prepared SQL statement to be executed.
Returns
The number of rows affected by the prepared SQL statement
References crawlservpp::Main::Database::sqlExecuteUpdate().
Referenced by addUrlIfNotExists(), addUrlsIfNotExist(), crawlservpp::Module::Extractor::Database::checkExtractingTable(), crawlservpp::Module::Parser::Database::checkParsingTable(), lockUrlIfOk(), crawlservpp::Module::Parser::Database::renewUrlLockIfOk(), crawlservpp::Module::Extractor::Database::renewUrlLockIfOk(), crawlservpp::Module::Parser::Database::unLockUrlIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlIfOk(), and urlHashCheck().
tryDatabaseLock()
bool crawlservpp::Wrapper::Database::tryDatabaseLock (const std::string & name) inline static protected inherited
Tries to add a lock to the database class, not blocking execution.
If a lock with the same name already exists, the function will not add a lock and return false instead.
Parameters
name Constant reference to a string containing the name of the lock to be added to the database class if a lock with the same name does not exist already.
Returns
True, if a lock with the same name did not exist already and the lock has been added. False, if a lock with the same name already exists and no lock has been added.
References crawlservpp::Main::Database::tryDatabaseLock().
unLockUrlIfOk()
void crawlservpp::Module::Crawler::Database::unLockUrlIfOk (std::uint64_t urlId, const std::string & lockTime)
Unlocks a URL in the database.
Parameters
urlId The ID of the URL to unlock.
lockTime Constant reference to a string containing the time at which the current lock by the thread for this URL will end (or has ended).
Exceptions
Module::Crawler::Database::Exception if no URL has been specified, i.e. the given URL ID is zero, if no lock time has been specified, or if the prepared SQL statement for unlocking a URL is missing.
Main::Database::Exception if a MySQL error occured while unlocking the URL.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Module::Crawler::sqlArg1, crawlservpp::Module::Crawler::sqlArg2, crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecute().
Referenced by crawlservpp::Module::Crawler::Thread::onTick().
updateCustomData() [1/3]
void crawlservpp::Wrapper::Database::updateCustomData (const Data::UpdateFields & data) inline inherited
Updates custom values in multiple table columns of the same type.
Parameters
data Constant reference to a structure containing the data to be updated.
Exceptions
Main::Database::Exception if no columns or no column type are specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while updating the data.
See also
Data::UpdateFields
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::updateCustomData().
updateCustomData() [2/3]
void crawlservpp::Wrapper::Database::updateCustomData (const Data::UpdateFieldsMixed & data) inline inherited
Updates custom values in multiple table columns of different types.
Parameters
data Constant reference to a structure containing the data to be updated.
Exceptions
Main::Database::Exception if no columns are specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while updating the data.
See also
Data::UpdateFieldsMixed
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::updateCustomData().
updateCustomData() [3/3]
void crawlservpp::Wrapper::Database::updateCustomData (const Data::UpdateValue & data) inline inherited
Updates a custom value in a table row.
Parameters
data Constant reference to a structure containing the data to be updated.
Exceptions
Main::Database::Exception if no column name or no column type is specified in the given data structure, if the given data is too large, or if an invalid data has been encountered.
Main::Database::Exception if a MySQL error occured while updating the data.
See also
Data::UpdateValue
References crawlservpp::Wrapper::Database::database, and crawlservpp::Main::Database::updateCustomData().
urlDuplicationCheck()
void crawlservpp::Module::Crawler::Database::urlDuplicationCheck ()
Checks the current URL list for duplicates.
Always throws an exception, unless no duplicates are found.
Exceptions
Module::Crawler::Database::Exception if the prepared SQL statements for checking the current URL list for duplicates is missing, or if duplicates have been found and removed.
Main::Database::Exception if a MySQL error occured while checking the URL list for duplicates.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
urlEmptyCheck()
void crawlservpp::Module::Crawler::Database::urlEmptyCheck ()
Checks for empty URLs in the current URL list.
Always throws an exception, unless no empty URLs are found.
Exceptions
Module::Crawler::Database::Exception if the prepared SQL statements for checking the current URL list for empty URLs is missing, or if empty URLs have been found.
Main::Database::Exception if a MySQL error occured while checking for empty URLs in the current URL list.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Wrapper::Database::sqlException(), and crawlservpp::Wrapper::Database::sqlExecuteQuery().
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
urlHashCheck()
void crawlservpp::Module::Crawler::Database::urlHashCheck ()
Checks the hash values in the current URL list.
Always throws an exception, unless all hash values are correct.
Exceptions
Module::Crawler::Database::Exception if the prepared SQL statements for checking the hash values in the current URL list is missing, or if invalid has values have been found and corrected.
Main::Database::Exception if a MySQL error occured while checking the hash values in the URL list.
References crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Wrapper::Database::getLoggingMin(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Wrapper::Database::log(), crawlservpp::Wrapper::Database::sqlException(), crawlservpp::Wrapper::Database::sqlExecuteQuery(), and crawlservpp::Wrapper::Database::sqlExecuteUpdate().
Referenced by crawlservpp::Module::Crawler::Thread::onInit().
urlUtf8Check()
void crawlservpp::Module::Crawler::Database::urlUtf8Check ()
Checks for URLs containing invalid UTF-8 characters in the current URL list.
Always throws an exception, unless all URLs in the current URL list contain only valid UTF-8-encoded characters.
Exceptions
Module::Crawler::Database::Exception if the prepared SQL statement for retrieving all URLs from the current URL list is missing, if a URL in the current URL list contains invalid UTF-8 characters, or if a UTF-8 error while checking the URLs in the current URL list.
Main::Database::Exception if a MySQL error occured while retrieving all URLs from the current URL list.
See also
getUrls
References crawlservpp::Helper::Utf8::isValidUtf8().
Member Data Documentation
database
Module::Database& crawlservpp::Wrapper::Database::database protected inherited
Reference to the database connection for the thread.
Referenced by crawlservpp::Wrapper::Database::addColumn(), crawlservpp::Wrapper::Database::addPreparedStatement(), crawlservpp::Wrapper::Database::addTargetTable(), crawlservpp::Wrapper::Database::beginNoLock(), crawlservpp::Wrapper::Database::checkConnection(), crawlservpp::Module::Analyzer::Database::checkSource(), crawlservpp::Wrapper::Database::compressTable(), crawlservpp::Wrapper::Database::createTable(), crawlservpp::Wrapper::Database::deleteTargetTable(), crawlservpp::Wrapper::Database::dropTable(), crawlservpp::Wrapper::Database::endNoLock(), crawlservpp::Wrapper::Database::getColumnType(), crawlservpp::Wrapper::Database::getConfiguration(), crawlservpp::Wrapper::Database::getCustomData(), crawlservpp::Wrapper::Database::getLastInsertedId(), crawlservpp::Wrapper::Database::getLoggingMin(), crawlservpp::Wrapper::Database::getLoggingVerbose(), crawlservpp::Wrapper::Database::getMaxAllowedPacketSize(), crawlservpp::Wrapper::Database::getOptions(), crawlservpp::Wrapper::Database::getPreparedStatement(), crawlservpp::Wrapper::Database::getQueryProperties(), crawlservpp::Wrapper::Database::getTargetTableId(), crawlservpp::Wrapper::Database::getTargetTableName(), crawlservpp::Wrapper::Database::getTargetTables(), crawlservpp::Wrapper::Database::getUrlListIdString(), crawlservpp::Wrapper::Database::getWebsiteDomain(), crawlservpp::Wrapper::Database::getWebsiteIdString(), crawlservpp::Wrapper::Database::insertCustomData(), crawlservpp::Wrapper::Database::isColumnExists(), crawlservpp::Wrapper::Database::isTableEmpty(), crawlservpp::Wrapper::Database::isTableExists(), crawlservpp::Wrapper::Database::log(), crawlservpp::Wrapper::Database::reserveForPreparedStatements(), crawlservpp::Wrapper::Database::setLogging(), crawlservpp::Wrapper::Database::setSleepOnError(), crawlservpp::Wrapper::Database::setTimeOut(), crawlservpp::Wrapper::Database::setUrlListCaseSensitive(), and crawlservpp::Wrapper::Database::updateCustomData().
The documentation for this class was generated from the following files:
Module/Crawler/Database.hpp
Module/Crawler/Database.cpp