crawlserv++: crawlservpp::Main::Server Class Reference
crawlservpp::Main::Server Class Reference final
The command-and-control server.
#include <Server.hpp>
Construction and Destruction
Server (const ServerSettings &serverSettings, const DatabaseSettings &databaseSettings, const NetworkSettings &networkSettings)
Constructor setting server, database, and network settings.
virtual ~Server ()
Destructor interrupting and waiting for all threads.
Getters
const std::string & getStatus () const
Gets the status of the server.
std::int64_t getUpTime () const
Gets the up-time of the server in seconds.
std::size_t getActiveThreads () const
Gets the number of active module threads.
std::size_t getActiveWorkers () const
Gets the number of active worker threads.
Server Ticks
bool tick ()
Perform a server tick.
Copy and Move
The class is neither copyable, nor movable.
Server (Server &)=delete
Deleted copy constructor.
Server & operator= (Server &)=delete
Deleted copy assignment operator.
Server (Server &&)=delete
Deleted move constructor.
Server & operator= (Server &&)=delete
Deleted move assignment operator.
Detailed Description
The command-and-control server.
Uses the Main::WebServer and the rapidJSON library to implement a HTTP server for receiving JSON-formatted commands and sending JSON-formatted replies from/to the crawlserv_frontend(s).
Also handles the threads for the different modules as well as worker threads for specific server tasks.
For more information about the rapidJSON library, see its GitHub repository.
See also
Main::WebServer
Constructor & Destructor Documentation
Server() [1/3]
crawlservpp::Main::Server::Server (const ServerSettings & serverSettings, const DatabaseSettings & databaseSettings, const NetworkSettings & networkSettings)
Constructor setting server, database, and network settings.
Parameters
serverSettings Constant reference to a structure containing the server settings.
databaseSettings Constant reference to a structure containing the database settings.
networkSettings Constant reference to a structure containing the network settings.
Exceptions
Main::Exception if the configuration could not be parsed, the configuration is invalid, or an unknown thread module is encountered.
See also
Struct::ServerSettings, Struct::DatabaseSettings, Struct::NetworkSettings
References crawlservpp::Main::cacheDir, crawlservpp::Helper::FileSystem::clearDirectory(), crawlservpp::Main::Database::connect(), crawlservpp::Main::cookieDir, crawlservpp::Struct::ServerSettings::corsOrigins, crawlservpp::Helper::FileSystem::createDirectory(), crawlservpp::Helper::FileSystem::createDirectoryIfNotExists(), crawlservpp::Struct::DatabaseSettings::debugDir, crawlservpp::Struct::DatabaseSettings::debugLogging, crawlservpp::Main::Database::getConfiguration(), crawlservpp::Main::Database::getMysqlVersion(), crawlservpp::Main::Database::getThreads(), crawlservpp::Module::Analyzer::Algo::initAlgo(), crawlservpp::Main::WebServer::initHTTP(), crawlservpp::Main::Database::initializeSql(), crawlservpp::Helper::FileSystem::isValidDirectory(), crawlservpp::Main::Database::log(), crawlservpp::Helper::DateTime::now(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::ServerSettings::port, crawlservpp::Main::Database::prepare(), crawlservpp::Main::WebServer::setAcceptCallback(), crawlservpp::Main::WebServer::setCORS(), crawlservpp::Main::WebServer::setRequestCallback(), crawlservpp::Main::Database::setSleepOnError(), crawlservpp::Main::sleepOnSqlErrorS, crawlservpp::Main::Database::update(), and crawlservpp::Main::Exception::view().
~Server()
crawlservpp::Main::Server::~Server () virtual
Destructor interrupting and waiting for all threads.
References getUpTime(), crawlservpp::Main::Database::log(), crawlservpp::Helper::DateTime::secondsToString(), and crawlservpp::Main::Exception::view().
Server() [2/3]
crawlservpp::Main::Server::Server (Server &) delete
Deleted copy constructor.
Server() [3/3]
crawlservpp::Main::Server::Server (Server &&) delete
Deleted move constructor.
Member Function Documentation
getActiveThreads()
std::size_t crawlservpp::Main::Server::getActiveThreads () const
Gets the number of active module threads.
Returns
The number of module threads currently active on the server.
getActiveWorkers()
std::size_t crawlservpp::Main::Server::getActiveWorkers () const
Gets the number of active worker threads.
Returns
The number of worker threads currently active on the server.
getStatus()
const std::string & crawlservpp::Main::Server::getStatus () const
Gets the status of the server.
Returns
Reference to the string containing the status of the server.
getUpTime()
std::int64_t crawlservpp::Main::Server::getUpTime () const
Gets the up-time of the server in seconds.
Returns
The number of seconds that have passed since the server has been started.
References crawlservpp::Helper::DateTime::now().
Referenced by ~Server().
operator=() [1/2]
Server& crawlservpp::Main::Server::operator= (Server &&) delete
Deleted move assignment operator.
operator=() [2/2]
Server& crawlservpp::Main::Server::operator= (Server &) delete
Deleted copy assignment operator.
tick()
bool crawlservpp::Main::Server::tick ()
Perform a server tick.
Polls the web server, handles database exceptions, checks for finished threads to be cleared, checks the connection to the database, gets information about the status of the server, and performs server commands received from the frontend(s).
Returns
True, if the server is still running. False otherwise.
References crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::Database::log(), crawlservpp::Main::WebServer::poll(), crawlservpp::Main::Exception::view(), and crawlservpp::Main::webServerPollTimeOutMs.
The documentation for this class was generated from the following files:
Main/Server.hpp
Main/Server.cpp