crawlserv++: crawlservpp::Module::Extractor::Thread Class Reference
crawlservpp::Module::Extractor::Thread Class Reference final
Extractor thread.
#include <Thread.hpp>
Classes
class Exception
Class for extractor exceptions.
Construction
Thread (Main::Database &dbBase, std::string_view cookieDirectory, const ThreadOptions &threadOptions, const NetworkSettings &networkSettings, const ThreadStatus &threadStatus)
Constructor initializing a previously interrupted extractor thread.
Thread (Main::Database &dbBase, std::string_view cookieDirectory, const ThreadOptions &threadOptions, const NetworkSettings &networkSettings)
Constructor initializing a new extractor thread.
Database Connection
Database database
Database connection for the extractor thread.
Networking
Network::Curl networking
Networking for the extractor thread.
Network::TorControl torControl
TOR control for the crawler thread.
Caching
std::queue< IdString > urls
Queue of URLs in the cache to still be processed, and their IDs.
std::string cacheLockTime
The time until which the URLs in the cache are locked, as string.
std::queue< DataEntry > results
Extracted data that has not yet been written to the database.
std::queue< DataEntry > linked
Linked data that has not yet been written to the database.
std::set< std::string > ids
ID cache.
std::queue< IdString > finished
Queue of URLs in the cache that have been finished.
Implemented Thread Functions
void onInit () override
Initializes the extractor.
void onTick () override
Performs an extractor tick.
void onPause () override
Pauses the extractor.
void onUnpause () override
Unpauses the extractor.
void onClear () override
Clears the extractor.
Getters
std::uint64_t getId () const
Gets the ID of the thread.
std::uint64_t getWebsite () const
Gets the ID of the website used by the thread.
std::uint64_t getUrlList () const
Gets the ID of the URL list used by the thread.
std::uint64_t getConfig () const
Gets the ID of the configuration used by the thread.
bool isShutdown () const
Checks whether the thread is shutting down or has shut down.
bool isRunning () const
Checks whether the thread is still supposed to run.
bool isFinished () const
Checks whether the shutdown of the thread has been finished.
bool isPaused () const
Checks whether the thread has been paused.
Thread Control
void end ()
Waits for the thread until shutdown is completed.
Time Travel
void warpTo (std::uint64_t target)
Jumps to the specified target ID ("time travel").
Configuration
std::string websiteNamespace
Namespace of the website used by the thread.
std::string urlListNamespace
Namespace of the URL list used by the thread.
std::string configuration
JSON string of the configuration used by the thread.
Protected Getters
bool isInterrupted () const
Checks whether the thread has been interrupted.
std::string getStatusMessage () const
Gets the current status message.
std::uint64_t getLast () const
Gets the valud of the last ID processed by the thread.
std::int64_t getWarpedOverAndReset ()
Gets the number of IDs that have been jumped over, and resets them.
Protected Setters
void setStatusMessage (const std::string &statusMessage)
Sets the status message of the thread.
void setProgress (float progress)
Sets the progress of the thread.
void setLast (std::uint64_t lastId)
Sets the last ID processed by the thread.
void incrementLast ()
Increments the last ID processed by the thread.
Protected Thread Control
void sleep (std::uint64_t ms) const
Lets the thread sleep for the specified number of milliseconds.
void allowPausing ()
Allows the thread to be paused.
void disallowPausing ()
Disallows the thread to be paused.
void pauseByThread ()
Forces the thread to pause.
Logging
bool isLogLevel (std::uint8_t level) const
Checks whether a certain logging level is enabled.
void log (std::uint8_t level, const std::string &logEntry)
Adds a thread-specific log entry to the database, if the current logging level is high enough.
void log (std::uint8_t level, std::queue< std::string > &logEntries)
Adds multiple thread-specific log entries to the database, if the current logging level is high enough.
Detailed Description
Extractor thread.
Constructor & Destructor Documentation
Thread() [1/2]
crawlservpp::Module::Extractor::Thread::Thread (Main::Database & dbBase, std::string_view cookieDirectory, const ThreadOptions & threadOptions, const NetworkSettings & networkSettings, const ThreadStatus & threadStatus)
Constructor initializing a previously interrupted extractor thread.
Parameters
dbBase Reference to the main database connection.
cookieDirectory View of a string containing the (sub-)directory for storing cookie files.
threadOptions Constant reference to a structure containing the options for the thread.
networkSettings Network settings.
threadStatus Constant reference to a structure containing the last known status of the thread.
Thread() [2/2]
crawlservpp::Module::Extractor::Thread::Thread (Main::Database & dbBase, std::string_view cookieDirectory, const ThreadOptions & threadOptions, const NetworkSettings & networkSettings)
Constructor initializing a new extractor thread.
Parameters
dbBase Reference to the main database connection.
cookieDirectory View of a string containing the (sub-)directory for storing cookie files.
threadOptions Constant reference to a structure containing the options for the thread.
networkSettings Network settings.
Member Function Documentation
allowPausing()
void crawlservpp::Module::Thread::allowPausing () protected inherited
Allows the thread to be paused.
Threads are pausable by default. Use this function if pausing has been disallowed via disallowPausing().
Thread-safe: Can be used by both the module and the main thread.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit().
disallowPausing()
void crawlservpp::Module::Thread::disallowPausing () protected inherited
Disallows the thread to be paused.
Thread-safe: Can be used by both the module and the main thread.
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::CorpusGenerator(), crawlservpp::Module::Analyzer::Algo::MarkovText::MarkovText(), and crawlservpp::Module::Analyzer::Algo::MarkovTweet::MarkovTweet().
end()
void crawlservpp::Module::Thread::end () inherited
Waits for the thread until shutdown is completed.
Note
Either stop() or interrupt() must have been called before calling this function.
Warning
May not be used by the thread itself!
References crawlservpp::Main::Database::deleteThread().
getConfig()
std::uint64_t crawlservpp::Module::Thread::getConfig () const inherited
Gets the ID of the configuration used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used configuration in the database.
References crawlservpp::Struct::ThreadOptions::config.
Referenced by crawlservpp::Module::Thread::Thread().
getId()
std::uint64_t crawlservpp::Module::Thread::getId () const inherited
Gets the ID of the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the thread in the database.
getLast()
std::uint64_t crawlservpp::Module::Thread::getLast () const protected inherited
Gets the valud of the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
Returns
The ID last processed by the thread, or zero if no ID has been processed yet.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), and onTick().
getStatusMessage()
std::string crawlservpp::Module::Thread::getStatusMessage () const protected inherited
Gets the current status message.
Thread-safe: Can be used by both the module and the main thread.
Returns
A copy of the current status message.
Referenced by crawlservpp::Module::Parser::Thread::onClear(), and onClear().
getUrlList()
std::uint64_t crawlservpp::Module::Thread::getUrlList () const inherited
Gets the ID of the URL list used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used URL list in the database.
References crawlservpp::Struct::ThreadOptions::urlList.
Referenced by crawlservpp::Module::Thread::Thread().
getWarpedOverAndReset()
std::int64_t crawlservpp::Module::Thread::getWarpedOverAndReset () protected inherited
Gets the number of IDs that have been jumped over, and resets them.
Resets the number of IDs jumped over to zero.
Warning
May only be used by the thread itself, not by the main thread!
Returns
The number of IDs that have been jumped over due to a call to warpTo(), or zero if no IDs have been jumped over, at least not since the last call to getWarpedOverAndReset(). The result might be negative, if warpTo() resulted in a jump to a previous ID.
Referenced by crawlservpp::Module::Parser::Thread::onTick(), onTick(), and crawlservpp::Module::Crawler::Thread::onTick().
getWebsite()
std::uint64_t crawlservpp::Module::Thread::getWebsite () const inherited
Gets the ID of the website used by the thread.
Thread-safe: Can be used by both the module and the main thread.
Returns
The unique ID identifying the used website in the database.
References crawlservpp::Struct::ThreadOptions::website.
Referenced by crawlservpp::Module::Crawler::Thread::onInit(), and crawlservpp::Module::Thread::Thread().
incrementLast()
void crawlservpp::Module::Thread::incrementLast () protected inherited
Increments the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
See also
setLast, Main::Database::setThreadLast
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadLast().
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), and crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick().
isFinished()
bool crawlservpp::Module::Thread::isFinished () const inherited
Checks whether the shutdown of the thread has been finished.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread has been completely shut down. False otherwise.
isInterrupted()
bool crawlservpp::Module::Thread::isInterrupted () const protected inherited
Checks whether the thread has been interrupted.
Thread-safe: Can be used by both the module and the main thread.
Returns
True if the thread has been interrupted. False otherwise.
isLogLevel()
bool crawlservpp::Module::Thread::isLogLevel (std::uint8_t level) const protected inherited
Checks whether a certain logging level is enabled.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
level The logging level to be checked for.
Returns
True, if the current logging level is at least as high as the given level. False, if the current logging level is lower than the given one.
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::isLogLevel().
Referenced by crawlservpp::Module::Parser::Thread::onInit(), onInit(), crawlservpp::Module::Parser::Thread::onTick(), onTick(), and crawlservpp::Module::Crawler::Thread::onTick().
isPaused()
bool crawlservpp::Module::Thread::isPaused () const inherited
Checks whether the thread has been paused.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread has been paused. False otherwise.
isRunning()
bool crawlservpp::Module::Thread::isRunning () const inherited
Checks whether the thread is still supposed to run.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread is has not been cancelled, even when it is paused. False, if the thread is not supposed to run any longer.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
isShutdown()
bool crawlservpp::Module::Thread::isShutdown () const inherited
Checks whether the thread is shutting down or has shut down.
Thread-safe: Can be used by both the module and the main thread.
Returns
True, if the thread is shutting down or has been shut down. False, if the thread is continuing to run.
See also
Thread::isFinished
log() [1/2]
void crawlservpp::Module::Thread::log (std::uint8_t level, const std::string & logEntry) protected inherited
Adds a thread-specific log entry to the database, if the current logging level is high enough.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entry will be written to the logging file as well.
The log entry will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entry. The entry will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntry Constant reference to a string containing the log entry.
See also
Module::Database::log(std::uint8_t, const std::string&)
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::log().
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::Empty::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onClear(), onClear(), crawlservpp::Module::Crawler::Thread::onClear(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), onInit(), crawlservpp::Module::Crawler::Thread::onInit(), crawlservpp::Module::Parser::Thread::onTick(), onTick(), and crawlservpp::Module::Crawler::Thread::onTick().
log() [2/2]
void crawlservpp::Module::Thread::log (std::uint8_t level, std::queue< std::string > & logEntries) protected inherited
Adds multiple thread-specific log entries to the database, if the current logging level is high enough.
Removes invalid UTF-8 characters if necessary.
If debug logging is active, the entries will be written to the logging file as well.
The log entries will not be written to the database, if the current logging level is lower than the specified logging level. The logging level does not affect the writing of logging entries being to the logging file when debug logging is active.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
level The logging level for the entries. The entries will only be written to the database, if the current logging level is at least the logging level for the entry.
logEntries Reference to a queue of strings containing the log entries to be written. It will be emptied regardless whether the log entries will be written to the database.
See also
Module::Database::log(std::uint8_t, std::queue<std::string>&)
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::log().
onClear()
void crawlservpp::Module::Extractor::Thread::onClear () override protected virtual
Clears the extractor.
Implements crawlservpp::Module::Thread.
References cacheLockTime, crawlservpp::Query::Container::clearQueries(), database, crawlservpp::Module::Extractor::generalLoggingDefault, crawlservpp::Module::Thread::getStatusMessage(), crawlservpp::Module::Thread::log(), crawlservpp::Helper::DateTime::now(), crawlservpp::Module::Thread::setStatusMessage(), crawlservpp::Module::Extractor::Database::unLockUrlsIfOk(), and urls.
onInit()
void crawlservpp::Module::Extractor::Thread::onInit () override protected virtual
Initializes the extractor.
Exceptions
Module::Extractor::Thread::Exception if no query for dataset or ID extraction has been specified.
Implements crawlservpp::Module::Thread.
References crawlservpp::Module::Extractor::Database::checkExtractingTable(), crawlservpp::Module::Extractor::Config::config, database, crawlservpp::Module::Extractor::Config::Entries::extractingDatasetQueries, crawlservpp::Module::Extractor::Config::Entries::extractingFieldNames, crawlservpp::Module::Extractor::Config::Entries::extractingIdQueries, crawlservpp::Module::Extractor::Config::Entries::extractingOverwrite, crawlservpp::Module::Extractor::Config::Entries::extractingRepairCData, crawlservpp::Module::Extractor::Config::Entries::extractingRepairComments, crawlservpp::Module::Extractor::Config::Entries::generalCacheSize, crawlservpp::Module::Extractor::Config::Entries::generalExtractCustom, crawlservpp::Module::Extractor::Config::Entries::generalLogging, crawlservpp::Module::Extractor::generalLoggingDefault, crawlservpp::Module::Extractor::generalLoggingExtended, crawlservpp::Module::Extractor::generalLoggingVerbose, crawlservpp::Module::Extractor::Config::Entries::generalMinimizeMemory, crawlservpp::Module::Extractor::Config::Entries::generalReExtract, crawlservpp::Module::Extractor::Config::Entries::generalSleepMySql, crawlservpp::Module::Extractor::Config::Entries::generalTargetTable, crawlservpp::Module::Extractor::Config::Entries::generalTidyWarnings, crawlservpp::Wrapper::Database::getConfiguration(), crawlservpp::Module::Extractor::Database::initTargetTables(), crawlservpp::Module::Thread::isLogLevel(), crawlservpp::Module::Thread::isRunning(), crawlservpp::Module::Extractor::Config::Entries::linkedFieldNames, crawlservpp::Module::Extractor::Config::Entries::linkedOverwrite, crawlservpp::Module::Extractor::Config::Entries::linkedTargetTable, crawlservpp::Module::Config::loadConfig(), crawlservpp::Module::Thread::log(), networking, crawlservpp::Helper::DateTime::now(), crawlservpp::Module::Extractor::Database::prepare(), crawlservpp::Network::Config::resetTorAfter, crawlservpp::Module::Extractor::Database::setCacheSize(), crawlservpp::Network::Curl::setConfigGlobal(), crawlservpp::Module::Extractor::Database::setExtractCustom(), crawlservpp::Module::Extractor::Database::setLinkedFields(), crawlservpp::Module::Extractor::Database::setLinkedTable(), crawlservpp::Wrapper::Database::setLogging(), crawlservpp::Query::Container::setMinimizeMemory(), crawlservpp::Network::TorControl::setNewIdentityMax(), crawlservpp::Module::Extractor::Database::setOverwrite(), crawlservpp::Module::Extractor::Database::setOverwriteLinked(), crawlservpp::Module::Extractor::Database::setRawContentIsSource(), crawlservpp::Module::Extractor::Database::setReExtract(), crawlservpp::Query::Container::setRepairCData(), crawlservpp::Query::Container::setRepairComments(), crawlservpp::Wrapper::Database::setSleepOnError(), crawlservpp::Module::Extractor::Database::setSources(), crawlservpp::Module::Thread::setStatusMessage(), crawlservpp::Module::Extractor::Database::setTargetFields(), crawlservpp::Module::Extractor::Database::setTargetTable(), crawlservpp::Query::Container::setTidyErrorsAndWarnings(), torControl, crawlservpp::Module::Thread::urlListNamespace, crawlservpp::Module::Extractor::Config::Entries::variablesName, crawlservpp::Module::Extractor::Config::Entries::variablesParsedColumn, crawlservpp::Module::Extractor::Config::Entries::variablesParsedTable, crawlservpp::Module::Extractor::Config::Entries::variablesSource, crawlservpp::Module::Extractor::variablesSourcesContent, crawlservpp::Module::Extractor::variablesSourcesParsed, and crawlservpp::Module::Thread::websiteNamespace.
onPause()
void crawlservpp::Module::Extractor::Thread::onPause () override protected virtual
Pauses the extractor.
Stores the current time for keeping track of the time, the extractor is paused.
Implements crawlservpp::Module::Thread.
References crawlservpp::Helper::DateTime::now().
onTick()
void crawlservpp::Module::Extractor::Thread::onTick () override protected virtual
Performs an extractor tick.
If successful, this will extract data from one URL. If not, the URL will either be skipped, or retried in the next tick.
Exceptions
Module::Extractor::Thread::Exception if the size of the URL list could not be retrieved from the database.
Implements crawlservpp::Module::Thread.
References crawlservpp::Network::TorControl::active(), cacheLockTime, crawlservpp::Module::Extractor::Config::config, database, crawlservpp::Module::Extractor::Config::Entries::extractingRemoveDuplicates, finished, crawlservpp::Module::Extractor::generalLoggingDefault, crawlservpp::Module::Extractor::generalLoggingExtended, crawlservpp::Module::Extractor::Config::Entries::generalSleepIdle, crawlservpp::Module::Extractor::Config::Entries::generalTiming, crawlservpp::Module::Thread::getLast(), crawlservpp::Module::Thread::getWarpedOverAndReset(), ids, crawlservpp::Module::Thread::isLogLevel(), crawlservpp::Module::Thread::log(), crawlservpp::Helper::DateTime::now(), crawlservpp::Module::Extractor::Database::renewUrlLockIfOk(), crawlservpp::Module::Thread::setProgress(), crawlservpp::Module::Thread::setStatusMessage(), crawlservpp::Module::Thread::sleep(), crawlservpp::Network::TorControl::tick(), crawlservpp::Timer::Simple::tickStr(), torControl, crawlservpp::Module::Extractor::Database::unLockUrlIfOk(), crawlservpp::Module::Extractor::Database::unLockUrlsIfOk(), and urls.
onUnpause()
void crawlservpp::Module::Extractor::Thread::onUnpause () override protected virtual
Unpauses the extractor.
Calculates the time, the extractor was paused.
Implements crawlservpp::Module::Thread.
References crawlservpp::Helper::DateTime::now().
pauseByThread()
void crawlservpp::Module::Thread::pauseByThread () protected inherited
Forces the thread to pause.
Warning
May only be used by the thread itself, not by the main thread!
References crawlservpp::Module::Thread::database, and crawlservpp::Main::Database::setThreadStatus().
Referenced by crawlservpp::Module::Analyzer::Thread::pause().
setLast()
void crawlservpp::Module::Thread::setLast (std::uint64_t lastId) protected inherited
Sets the last ID processed by the thread.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
lastId The last ID processed by the thread.
See also
incrementLast, Main::Database::setThreadLast
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadLast().
setProgress()
void crawlservpp::Module::Thread::setProgress (float progress) protected inherited
Sets the progress of the thread.
Warning
May only be used by the thread itself, not by the main thread!
Parameters
progress The new progress of the thread, between 0.f (0%) and 1.f (100%).
See also
Main::Database::setThreadProgress
References crawlservpp::Module::Thread::database, and crawlservpp::Module::Database::setThreadProgress().
Referenced by crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), and onTick().
setStatusMessage()
void crawlservpp::Module::Thread::setStatusMessage (const std::string & statusMessage) protected inherited
Sets the status message of the thread.
Warning
May only be used by the thread itself, not by the main thread!
Note
String views cannot be used, because they are not supported by the API for the MySQL database.
Parameters
statusMessage Constant reference to a string containing the new status message to be set.
See also
Main::Database::setThreadStatus
References crawlservpp::Module::Thread::database, and crawlservpp::Main::Database::setThreadStatus().
Referenced by crawlservpp::Module::Analyzer::Thread::finished(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoInit(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onClear(), onClear(), crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), onInit(), crawlservpp::Module::Crawler::Thread::onInit(), crawlservpp::Module::Parser::Thread::onTick(), and onTick().
sleep()
void crawlservpp::Module::Thread::sleep (std::uint64_t ms) const protected inherited
Lets the thread sleep for the specified number of milliseconds.
The sleep will be interrupted if the thread is stopped.
Thread-safe: Can be used by both the module and the main thread.
Parameters
ms The number of milliseconds for the thread to sleep, if it is not stopped.
References crawlservpp::Module::sleepMs.
Referenced by crawlservpp::Module::Analyzer::Thread::finished(), crawlservpp::Module::Analyzer::Algo::CorpusGenerator::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onTick(), onTick(), and crawlservpp::Module::Crawler::Thread::onTick().
warpTo()
void crawlservpp::Module::Thread::warpTo (std::uint64_t target) inherited
Jumps to the specified target ID ("time travel").
Skips the normal process of determining the next ID once the current ID has been processed.
Thread-safe: Can be used by both the module and the main thread.
Parameters
target The target ID that should be processed next.
Exceptions
Module::Thread::Exception if no target is specified, i.e. the target ID is zero.
See also
getWarpedOverAndReset
Member Data Documentation
cacheLockTime
std::string crawlservpp::Module::Extractor::Thread::cacheLockTime protected
The time until which the URLs in the cache are locked, as string.
In the format YYYY-MM-DD HH:MM:SS.
Referenced by onClear(), and onTick().
configuration
std::string crawlservpp::Module::Thread::configuration protected inherited
JSON string of the configuration used by the thread.
See also
Main::Database::getConfiguration
Referenced by crawlservpp::Module::Thread::Thread().
database
Database crawlservpp::Module::Extractor::Thread::database protected
Database connection for the extractor thread.
Referenced by onClear(), onInit(), and onTick().
finished
std::queue<IdString> crawlservpp::Module::Extractor::Thread::finished protected
Queue of URLs in the cache that have been finished.
Referenced by onTick().
ids
std::set<std::string> crawlservpp::Module::Extractor::Thread::ids protected
ID cache.
To be checked first, to recognize duplicate IDs in one dataset, without the need to access the database.
Referenced by onTick().
linked
std::queue<DataEntry> crawlservpp::Module::Extractor::Thread::linked protected
Linked data that has not yet been written to the database.
networking
Network::Curl crawlservpp::Module::Extractor::Thread::networking protected
Networking for the extractor thread.
Referenced by onInit().
results
std::queue<DataEntry> crawlservpp::Module::Extractor::Thread::results protected
Extracted data that has not yet been written to the database.
torControl
Network::TorControl crawlservpp::Module::Extractor::Thread::torControl protected
TOR control for the crawler thread.
Referenced by onInit(), and onTick().
urlListNamespace
std::string crawlservpp::Module::Thread::urlListNamespace protected inherited
Namespace of the URL list used by the thread.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onInit(), onInit(), crawlservpp::Module::Crawler::Thread::onInit(), and crawlservpp::Module::Thread::Thread().
urls
std::queue<IdString> crawlservpp::Module::Extractor::Thread::urls protected
Queue of URLs in the cache to still be processed, and their IDs.
Referenced by onClear(), and onTick().
websiteNamespace
std::string crawlservpp::Module::Thread::websiteNamespace protected inherited
Namespace of the website used by the thread.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::onAlgoTick(), crawlservpp::Module::Analyzer::Algo::MarkovText::onAlgoTick(), crawlservpp::Module::Parser::Thread::onInit(), onInit(), crawlservpp::Module::Crawler::Thread::onInit(), and crawlservpp::Module::Thread::Thread().
The documentation for this class was generated from the following files:
Module/Extractor/Thread.hpp
Module/Extractor/Thread.cpp