crawlserv++: crawlservpp::Module::Parser::Config Class Reference
crawlservpp::Module::Parser::Config Class Reference
Configuration for parsers.
#include <Config.hpp>
Classes
struct Entries
Configuration entries for parser threads.
class Exception
Class for parser configuration exceptions.
Protected Member Functions
void parseOption () override
Parses an parser-specific configuration option.
void checkOptions () override
Checks the parser-specific configuration options.
Configuration Loader
void loadConfig (const std::string &configJson, LogQueue &warningsTo)
Loads a configuration.
Parsing Options
enum StringParsingOption { Default = 0, SQL, SubURL, URL }
Options for parsing strings.
enum CharParsingOption { FromNumber = 0, FromString }
Options for parsing char's.
Configuration Parsing
void category (const std::string &category)
Sets the category of the subsequent configuration items to be checked for.
void option (const std::string &name, bool &target)
Checks for a configuration option of type bool.
void option (const std::string &name, std::vector< bool > &target)
Checks for a configuration option of type array of bool's.
void option (const std::string &name, char &target, CharParsingOption opt)
Checks for a configuration option of type char.
void option (const std::string &name, std::vector< char > &target, CharParsingOption opt)
Checks for a configuration option of type array of char's.
void option (const std::string &name, std::int16_t &target)
Checks for a configuration option of type 16-bit integer.
void option (const std::string &name, std::vector< std::int16_t > &target)
Checks for a configuration option of type array of 16-bit integers.
void option (const std::string &name, std::int32_t &target)
Checks for a configuration option of type 32-bit integer.
void option (const std::string &name, std::vector< std::int32_t > &target)
Checks for a configuration option of type array of 32-bit integers.
void option (const std::string &name, std::int64_t &target)
Checks for a configuration option of type 64-bit integer.
void option (const std::string &name, std::vector< std::int64_t > &target)
Checks for a configuration option of type array of 64-bit integers.
void option (const std::string &name, std::uint8_t &target)
Checks for a configuration option of type unsigned 8-bit integer.
void option (const std::string &name, std::vector< std::uint8_t > &target)
Checks for a configuration option of type array of unsigned 8-bit integers.
void option (const std::string &name, std::uint16_t &target)
Checks for a configuration option of type unsigned 16-bit integer.
void option (const std::string &name, std::vector< std::uint16_t > &target)
Checks for a configuration option of type array of unsigned 16-bit integers.
void option (const std::string &name, std::uint32_t &target)
Checks for a configuration option of type unsigned 32-bit integer.
void option (const std::string &name, std::vector< std::uint32_t > &target)
Checks for a configuration option of type array of unsigned 32-bit integers.
void option (const std::string &name, std::uint64_t &target)
Checks for a configuration option of type unsigned 64-bit integer.
void option (const std::string &name, std::vector< std::uint64_t > &target)
Checks for a configuration option of type array of unsigned 64-bit integers.
void option (const std::string &name, std::string &target, StringParsingOption opt=Default)
Checks for a configuration option of type string.
void option (const std::string &name, std::vector< std::string > &target, StringParsingOption opt=Default)
Checks for a configuration option of type array of strings.
void warning (const std::string &warning)
Adds a warning to the logging queue.
Module-specific Configuration Parsing
virtual void parseBasicOption ()
Parses a basic option.
Configuration
struct crawlservpp::Module::Parser::Config::Entries config
Configuration of the parser.
Detailed Description
Configuration for parsers.
Member Enumeration Documentation
CharParsingOption
enum crawlservpp::Module::Config::CharParsingOption protected inherited
Options for parsing char's.
Enumerator
FromNumber
Get char by its numeric value.
FromString
Get char from the beginning of a string.
Also supports certain escaped characters.
See also
Helper::Strings::getFirstOrEscapeChar
StringParsingOption
enum crawlservpp::Module::Config::StringParsingOption protected inherited
Options for parsing strings.
Enumerator
Default
Uses a string as it is.
SQL
Requires a SQL-compatible string.
SubURL
Converts a string to a sub-URL.
URL
Converts a string to a URL (without the protocol).
Member Function Documentation
category()
void crawlservpp::Module::Config::category (const std::string & category) inline protected inherited
Sets the category of the subsequent configuration items to be checked for.
Parameters
category Constant reference to a string containing the name of the category.
References crawlservpp::Struct::ConfigItem::category.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::parseAlgoOption(), crawlservpp::Module::Analyzer::Algo::MarkovText::parseAlgoOption(), crawlservpp::Network::Config::parseBasicOption(), crawlservpp::Module::Analyzer::Config::parseOption(), parseOption(), crawlservpp::Module::Crawler::Config::parseOption(), and crawlservpp::Module::Extractor::Config::parseOption().
checkOptions()
void crawlservpp::Module::Parser::Config::checkOptions () inline override protected virtual
Checks the parser-specific configuration options.
Exceptions
Module::Extractor::Config::Exception if no target table has been specified.
Implements crawlservpp::Module::Config.
References config, crawlservpp::Module::Parser::Config::Entries::generalResultTable, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeFormats, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeLocales, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeQueries, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeSources, crawlservpp::Module::Parser::Config::Entries::parsingFieldDateTimeFormats, crawlservpp::Module::Parser::Config::Entries::parsingFieldDateTimeLocales, crawlservpp::Module::Parser::Config::Entries::parsingFieldDelimiters, crawlservpp::Module::Parser::Config::Entries::parsingFieldIgnoreEmpty, crawlservpp::Module::Parser::Config::Entries::parsingFieldJSON, crawlservpp::Module::Parser::Config::Entries::parsingFieldNames, crawlservpp::Module::Parser::Config::Entries::parsingFieldQueries, crawlservpp::Module::Parser::Config::Entries::parsingFieldSources, crawlservpp::Module::Parser::Config::Entries::parsingFieldTidyTexts, crawlservpp::Module::Parser::Config::Entries::parsingFieldWarningsEmpty, crawlservpp::Module::Parser::Config::Entries::parsingIdQueries, crawlservpp::Module::Parser::Config::Entries::parsingIdSources, and crawlservpp::Module::Config::warning().
loadConfig()
void crawlservpp::Module::Config::loadConfig (const std::string & configJson, LogQueue & warningsTo) inline inherited
Loads a configuration.
Parameters
configJson Constant reference to a string containing the configuration as JSON.
warningsTo Reference to a queue to which warnings will be added that occur during the parsing of the configuration, also known as the "logging queue".
Exceptions
Module::Config::Exception if the configuration JSON cannot be parsed.
References crawlservpp::Struct::ConfigItem::category, crawlservpp::Module::Config::checkOptions(), crawlservpp::Struct::ConfigItem::name, crawlservpp::Module::Config::parseBasicOption(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::ConfigItem::str(), crawlservpp::Struct::ConfigItem::value, and crawlservpp::Main::Exception::view().
Referenced by crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
option() [1/20]
void crawlservpp::Module::Config::option (const std::string & name, bool & target) inline protected inherited
Checks for a configuration option of type bool.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a boolean variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::parseAlgoOption(), crawlservpp::Module::Analyzer::Algo::MarkovText::parseAlgoOption(), crawlservpp::Network::Config::parseBasicOption(), crawlservpp::Module::Analyzer::Config::parseOption(), parseOption(), crawlservpp::Module::Crawler::Config::parseOption(), and crawlservpp::Module::Extractor::Config::parseOption().
option() [2/20]
void crawlservpp::Module::Config::option (const std::string & name, char & target, CharParsingOption opt) inline protected inherited
Checks for a configuration option of type char.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable of the type char into which the value of the configuration entry will be written if it is encountered.
opt Parsing options used for the configuration option.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Module::Config::FromNumber, crawlservpp::Module::Config::FromString, crawlservpp::Helper::Strings::getFirstOrEscapeChar(), crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [3/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int16_t & target) inline protected inherited
Checks for a configuration option of type 16-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [4/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int32_t & target) inline protected inherited
Checks for a configuration option of type 32-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [5/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int64_t & target) inline protected inherited
Checks for a configuration option of type 64-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [6/20]
void crawlservpp::Module::Config::option (const std::string & name, std::string & target, StringParsingOption opt = Default) inline protected inherited
Checks for a configuration option of type string.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a string into which the value of the configuration entry will be stored if it is encountered.
opt Parsing option for the configuration entry.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Helper::Strings::checkSQLName(), crawlservpp::Module::Config::Default, crawlservpp::Struct::ConfigItem::name, crawlservpp::Module::Config::SQL, crawlservpp::Struct::ConfigItem::str(), crawlservpp::Module::Config::SubURL, crawlservpp::Module::Config::URL, and crawlservpp::Struct::ConfigItem::value.
option() [7/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint16_t & target) inline protected inherited
Checks for a configuration option of type unsigned 16-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [8/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint32_t & target) inline protected inherited
Checks for a configuration option of type unsigned 32-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [9/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint64_t & target) inline protected inherited
Checks for a configuration option of type unsigned 64-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [10/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint8_t & target) inline protected inherited
Checks for a configuration option of type unsigned 8-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [11/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< bool > & target) inline protected inherited
Checks for a configuration option of type array of bool's.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector of bool's into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [12/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< char > & target, CharParsingOption opt) inline protected inherited
Checks for a configuration option of type array of char's.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector of char's into which the value of the configuration entry will be written if it is encountered.
opt Parsing options used for the configuration option.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Module::Config::FromNumber, crawlservpp::Module::Config::FromString, crawlservpp::Helper::Strings::getFirstOrEscapeChar(), crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [13/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int16_t > & target) inline protected inherited
Checks for a configuration option of type array of 16-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [14/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int32_t > & target) inline protected inherited
Checks for a configuration option of type array of 32-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [15/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int64_t > & target) inline protected inherited
Checks for a configuration option of type array of 64-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [16/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::string > & target, StringParsingOption opt = Default) inline protected inherited
Checks for a configuration option of type array of strings.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
opt Parsing option for the configuration entry.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Helper::Strings::checkSQLName(), crawlservpp::Module::Config::Default, crawlservpp::Struct::ConfigItem::name, crawlservpp::Module::Config::SQL, crawlservpp::Struct::ConfigItem::str(), crawlservpp::Module::Config::SubURL, crawlservpp::Module::Config::URL, and crawlservpp::Struct::ConfigItem::value.
option() [17/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint16_t > & target) inline protected inherited
Checks for a configuration option of type array of unsigned 16-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [18/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint32_t > & target) inline protected inherited
Checks for a configuration option of type array of unsigned 32-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [19/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint64_t > & target) inline protected inherited
Checks for a configuration option of type array of unsigned 64-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [20/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint8_t > & target) inline protected inherited
Checks for a configuration option of type array of unsigned 8-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
parseBasicOption()
void crawlservpp::Module::Config::parseBasicOption () inline protected virtual inherited
Parses a basic option.
Might be overridden by child classes.
Can be used by abstract classes to add additional configuration entries without being the final implementation, as in Network::Config.
Warning
Any reimplementation needs to call parseOption() for the configuration to work properly.
See also
Network::Config::parseBasicOption
Reimplemented in crawlservpp::Network::Config.
References crawlservpp::Module::Config::parseOption().
Referenced by crawlservpp::Module::Config::loadConfig().
parseOption()
void crawlservpp::Module::Parser::Config::parseOption () inline override protected virtual
Parses an parser-specific configuration option.
Implements crawlservpp::Module::Config.
References crawlservpp::Module::Config::category(), config, crawlservpp::Module::Parser::Config::Entries::generalCacheSize, crawlservpp::Module::Parser::Config::Entries::generalDbTimeOut, crawlservpp::Module::Parser::Config::Entries::generalLogging, crawlservpp::Module::Parser::Config::Entries::generalNewestOnly, crawlservpp::Module::Parser::Config::Entries::generalParseCustom, crawlservpp::Module::Parser::Config::Entries::generalReParse, crawlservpp::Module::Parser::Config::Entries::generalResultTable, crawlservpp::Module::Parser::Config::Entries::generalSkip, crawlservpp::Module::Parser::Config::Entries::generalSleepIdle, crawlservpp::Module::Parser::Config::Entries::generalSleepMySql, crawlservpp::Module::Parser::Config::Entries::generalTiming, crawlservpp::Module::Config::option(), crawlservpp::Module::Parser::Config::Entries::parsingContentIgnoreQueries, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeFormats, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeLocales, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeQueries, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeSources, crawlservpp::Module::Parser::Config::Entries::parsingDateTimeWarningEmpty, crawlservpp::Module::Parser::Config::Entries::parsingFieldDateTimeFormats, crawlservpp::Module::Parser::Config::Entries::parsingFieldDateTimeLocales, crawlservpp::Module::Parser::Config::Entries::parsingFieldDelimiters, crawlservpp::Module::Parser::Config::Entries::parsingFieldIgnoreEmpty, crawlservpp::Module::Parser::Config::Entries::parsingFieldJSON, crawlservpp::Module::Parser::Config::Entries::parsingFieldNames, crawlservpp::Module::Parser::Config::Entries::parsingFieldQueries, crawlservpp::Module::Parser::Config::Entries::parsingFieldSources, crawlservpp::Module::Parser::Config::Entries::parsingFieldTidyTexts, crawlservpp::Module::Parser::Config::Entries::parsingFieldWarningsEmpty, crawlservpp::Module::Parser::Config::Entries::parsingIdIgnore, crawlservpp::Module::Parser::Config::Entries::parsingIdQueries, crawlservpp::Module::Parser::Config::Entries::parsingIdSources, crawlservpp::Module::Parser::Config::Entries::parsingRepairCData, crawlservpp::Module::Parser::Config::Entries::parsingRepairComments, crawlservpp::Module::Parser::Config::Entries::parsingTidyErrors, and crawlservpp::Module::Parser::Config::Entries::parsingTidyWarnings.
warning()
void crawlservpp::Module::Config::warning (const std::string & warning) inline protected inherited
Adds a warning to the logging queue.
Warning
Should not be used outside of Config::loadConfig!
Parameters
warning Constant reference to a string containing the warning.
Exceptions
Module::Config::Exception if no log queue is active.
Referenced by crawlservpp::Module::Analyzer::Config::checkOptions(), checkOptions(), crawlservpp::Module::Crawler::Config::checkOptions(), crawlservpp::Module::Extractor::Config::checkOptions(), and crawlservpp::Network::Config::parseBasicOption().
Member Data Documentation
config
struct crawlservpp::Module::Parser::Config::Entries crawlservpp::Module::Parser::Config::config
Configuration of the parser.
Referenced by checkOptions(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Parser::Thread::onTick(), and parseOption().
The documentation for this class was generated from the following file:
Module/Parser/Config.hpp