crawlserv++: crawlservpp::Wrapper::Curl Class Reference
crawlservpp::Wrapper::Curl Class Reference
RAII wrapper for handles of the libcurl API.
#include <Curl.hpp>
Construction and Destruction
Curl ()
Constructor initializing the libcurl API locally and globally, if necessary.
virtual ~Curl ()
Destructor cleaning up the libcurl API locally and globally, if necessary.
Getters
CURL * get () noexcept
Gets a pointer to the underlying libcurl handle.
CURL ** getPtr () noexcept
Gets a pointer to the pointer containing the address of the underlying libcurl handle.
bool valid () const noexcept
Checks whether the underlying libcurl handle is valid.
Initialization and Cleanup
void init ()
Initializes the underlying libcurl handle.
void clear () noexcept
Clears the underlying libcurl handle.
Copy and Move
The class is not copyable, only moveable.
Curl (Curl &)=delete
Deleted copy constructor.
Curl & operator= (Curl &)=delete
Deleted copy assignment operator.
Curl (Curl &&other) noexcept
Move constructor.
Curl & operator= (Curl &&other) noexcept
Move assignment operator.
Detailed Description
RAII wrapper for handles of the libcurl API.
Initializes the libcurl API locally and globally, if still necessary. Automatically resets the API on destruction, avoiding memory leaks.
At the moment, this class is used exclusively by Network::Curl.
For more information about the libcurl API, see its website.
Constructor & Destructor Documentation
Curl() [1/3]
crawlservpp::Wrapper::Curl::Curl () inline
Constructor initializing the libcurl API locally and globally, if necessary.
Exceptions
std::runtime_error if the initialization of the API failed.
See also
curl_global_init, curl_easy_init
References init().
~Curl()
crawlservpp::Wrapper::Curl::~Curl () inline virtual
Destructor cleaning up the libcurl API locally and globally, if necessary.
Also globally deinitializes the libcurl API if it was initialized during construction or the reponsibility for it received during move assignment.
See also
curl_global_cleanup, curl_easy_cleanup
References clear().
Curl() [2/3]
crawlservpp::Wrapper::Curl::Curl (Curl &) delete
Deleted copy constructor.
Curl() [3/3]
crawlservpp::Wrapper::Curl::Curl (Curl && other) inline noexcept
Move constructor.
Moves the libcurl handle from the specified location into this instance of the class.
Note
The other handle will be invalidated by this move.
Parameters
other The libcurl handle to move from.
See also
valid
Member Function Documentation
clear()
void crawlservpp::Wrapper::Curl::clear () inline noexcept
Clears the underlying libcurl handle.
If the handle is not initialized, the function will have no effect.
Warning
Does not clear the global initialization of the libcurl API, which will only be released on destruction or the responsibility for it transferred away during move assignment.
See also
curl_easy_cleanup
Referenced by init(), and ~Curl().
get()
CURL * crawlservpp::Wrapper::Curl::get () inline noexcept
Gets a pointer to the underlying libcurl handle.
Returns
A pointer to the underlying libcurl handle or nullptr if the initialization failed or the handle has already been cleared.
getPtr()
CURL ** crawlservpp::Wrapper::Curl::getPtr () inline noexcept
Gets a pointer to the pointer containing the address of the underlying libcurl handle.
Returns
A pointer to the pointer containing the address of the underlying libcurl handle or a pointer to a pointer containing nullptr if the initialization failed or the handle has already been cleared.
init()
void crawlservpp::Wrapper::Curl::init () inline
Initializes the underlying libcurl handle.
If the underlying handle is already initialized, it will be cleared.
See also
curl_easy_init
References clear().
Referenced by Curl().
operator=() [1/2]
Curl & crawlservpp::Wrapper::Curl::operator= (Curl && other) inline noexcept
Move assignment operator.
Moves the libcurl handle from the specified location into this instance of the class.
The responsibility to clear the libcurl API globally will be kept in this instance or transferred from the other instance if necessary.
Note
The other handle will be invalidated by this move.
Nothing will be done if used on itself.
Parameters
other The libcurl handle to move from.
Returns
A reference to the instance containing the libcurl handle after moving (i.e. *this).
See also
valid
operator=() [2/2]
Curl& crawlservpp::Wrapper::Curl::operator= (Curl &) delete
Deleted copy assignment operator.
valid()
bool crawlservpp::Wrapper::Curl::valid () const inline noexcept
Checks whether the underlying libcurl handle is valid.
Returns
true, if the handle is valid. False otherwise.
The documentation for this class was generated from the following files:
Wrapper/Curl.hpp
Wrapper/Curl.cpp