crawlserv++: crawlservpp::Wrapper::CurlList Class Reference
crawlservpp::Wrapper::CurlList Class Reference
RAII wrapper for lists used by the libcurl API.
#include <CurlList.hpp>
Construction and Destruction
CurlList ()=default
Default constructor.
virtual ~CurlList ()
Destructor resetting the list if necessary.
Getters
curl_slist * get () noexcept
Gets a pointer to the underlying list.
const curl_slist * getc () const noexcept
Gets a const pointer to the underlying list.
bool valid () const noexcept
Checks whether the underlying list is valid.
std::size_t size () const noexcept
Gets the current number of elements in the list.
bool empty () const noexcept
Checks whether the list is empty.
Manipulation and Cleanup
void append (const CurlList &other)
Appends another list to the list.
void append (const std::vector< std::string > &newElements)
Appends the elements of a vector to the list.
void append (const std::string &newElement)
Appends an element to the list.
void clear () noexcept
Resets the list and frees its memory.
Copy and Move
The class is both copyable and moveable.
CurlList (const CurlList &other)
Copy constructor.
CurlList & operator= (const CurlList &other)
Copy assignment operator.
CurlList (CurlList &&other) noexcept
Move constructor.
CurlList & operator= (CurlList &&other) noexcept
Move assignment operator.
Detailed Description
RAII wrapper for lists used by the libcurl API.
Sets the list to nullptr on construction and automatically clears it on destruction, avoiding memory leaks.
At the moment, this class is used exclusively by Network::Curl.
For more information about the libcurl API, see its website.
Note
This class does not have ownership of the underlying pointer.
Constructor & Destructor Documentation
CurlList() [1/3]
crawlservpp::Wrapper::CurlList::CurlList () default
Default constructor.
~CurlList()
crawlservpp::Wrapper::CurlList::~CurlList () inline virtual
Destructor resetting the list if necessary.
References clear().
CurlList() [2/3]
crawlservpp::Wrapper::CurlList::CurlList (const CurlList & other) inline
Copy constructor.
Creates a new list and copies all elements of the given list into it.
Note
Calling this function with an invalid list has no effect.
Parameters
other The list to copy from.
Exceptions
std::runtime_error if the new list could not be created or any of the elements could not be appended to it.
References append().
CurlList() [3/3]
crawlservpp::Wrapper::CurlList::CurlList (CurlList && other) inline noexcept
Move constructor.
Moves the list from the specified location into this instance of the class.
Note
The other list will be invalidated by this move.
Parameters
other The list to move from.
See also
valid
Member Function Documentation
append() [1/3]
void crawlservpp::Wrapper::CurlList::append (const CurlList & other) inline
Appends another list to the list.
Note
Calling this function with an invalid list or on itself has no effect.
Parameters
other A const reference to the list which elements should be appended.
Exceptions
std::runtime_error if appending to the list failed.
Referenced by append(), CurlList(), and operator=().
append() [2/3]
void crawlservpp::Wrapper::CurlList::append (const std::string & newElement) inline
Appends an element to the list.
A new list will be created if no list already exists.
Note
String views cannot be used, because the underlying API requires a null-terminated string.
Parameters
newElement A const reference to a string that should be appended at the end of the list.
Exceptions
std::runtime_error if the element could not be appended by the underlying API.
append() [3/3]
void crawlservpp::Wrapper::CurlList::append (const std::vector< std::string > & newElements) inline
Appends the elements of a vector to the list.
Parameters
newElements A const reference to the vector of strings that should be appended to the list.
Exceptions
std::runtime_error if appending to the list failed.
References append().
clear()
void crawlservpp::Wrapper::CurlList::clear () inline noexcept
Resets the list and frees its memory.
The list will be invalid and valid() will return false afterwards.
Note
Does nothing if the underlying list is not initialized.
Referenced by operator=(), and ~CurlList().
empty()
bool crawlservpp::Wrapper::CurlList::empty () const inline noexcept
Checks whether the list is empty.
Returns
True, if the list is empty or invalid. False otherwise.
See also
valid
get()
curl_slist * crawlservpp::Wrapper::CurlList::get () inline noexcept
Gets a pointer to the underlying list.
Returns
A pointer to the underlying libcurl list or nullptr if no list has been created or the list has already been resetted.
getc()
const curl_slist * crawlservpp::Wrapper::CurlList::getc () const inline noexcept
Gets a const pointer to the underlying list.
Returns
A const pointer to the underlying libcurl list or nullptr if no list has been created or the list has already been resetted.
operator=() [1/2]
CurlList & crawlservpp::Wrapper::CurlList::operator= (const CurlList & other) inline
Copy assignment operator.
Clears the existing list, creates a new one and copies all elements of the given list into it.
Note
Nothing will be done if used on itself.
Parameters
other The buffer to copy from.
Returns
A reference to the class containing the copy of the list (i.e. *this).
Exceptions
std::runtime_error if the new list could not be created or any of the elements could not be appended to it.
References append(), and clear().
operator=() [2/2]
CurlList & crawlservpp::Wrapper::CurlList::operator= (CurlList && other) inline noexcept
Move assignment operator.
Moves the list from the specified location into this instance of the class.
Note
The other list will be invalidated by this move.
Nothing will be done if used on itself.
Parameters
other The list to move from.
Returns
A reference to the instance containing the list after moving (i.e. *this).
See also
valid
size()
std::size_t crawlservpp::Wrapper::CurlList::size () const inline noexcept
Gets the current number of elements in the list.
Returns
The number of elements in the underlying list.
Note
The return value is zero if the list has not been initialized.
valid()
bool crawlservpp::Wrapper::CurlList::valid () const inline noexcept
Checks whether the underlying list is valid.
Returns
True, if a list has been created and not been resetted. False otherwise.
The documentation for this class was generated from the following file:
Wrapper/CurlList.hpp