crawlserv++: crawlservpp::Timer::Simple Class Reference
crawlservpp::Timer::Simple Class Reference
A simple timer.
#include <Simple.hpp>
Construction
Simple ()
Constructor starting the timer.
Tick control
std::uint64_t tick ()
Timer tick returning the number of milliseconds passed.
std::string tickStr ()
Timer tick returning the number of milliseconds passed as string.
Internal state
std::chrono::steady_clock::time_point timePoint
(Time) point of creation or last tick.
Detailed Description
A simple timer.
Starting from its creation, this timer counts the number of milliseconds until tick() or tickStr() is called.
The timer is restarted after each tick.
Constructor & Destructor Documentation
Simple()
crawlservpp::Timer::Simple::Simple () inline
Constructor starting the timer.
Member Function Documentation
tick()
std::uint64_t crawlservpp::Timer::Simple::tick () inline
Timer tick returning the number of milliseconds passed.
Restarts the timer.
Returns
the time since creation or last tick in milliseconds.
References crawlservpp::Helper::DateTime::now(), and timePoint.
Referenced by crawlservpp::Main::Database::checkConnection(), crawlservpp::Network::TorControl::newIdentity(), crawlservpp::Network::TorControl::setNewIdentityMax(), crawlservpp::Network::TorControl::setNewIdentityMin(), and crawlservpp::Network::TorControl::tick().
tickStr()
std::string crawlservpp::Timer::Simple::tickStr () inline
Timer tick returning the number of milliseconds passed as string.
Restarts the timer.
Returns
the time since creation or last tick as formatted string. The resolution of the result remains in milliseconds.
See also
Helper::DateTime::millisecondsToString
References crawlservpp::Helper::DateTime::millisecondsToString(), crawlservpp::Helper::DateTime::now(), and timePoint.
Referenced by crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Module::Analyzer::Database::getCorpus(), crawlservpp::Main::Database::moveWebsite(), crawlservpp::Module::Parser::Thread::onTick(), and crawlservpp::Module::Extractor::Thread::onTick().
Member Data Documentation
timePoint
std::chrono::steady_clock::time_point crawlservpp::Timer::Simple::timePoint protected
(Time) point of creation or last tick.
Referenced by tick(), and tickStr().
The documentation for this class was generated from the following file:
Timer/Simple.hpp