crawlserv++: crawlservpp::Module::Config Class Reference
crawlservpp::Module::Config Class Reference abstract
Abstract class as base for module-specific configurations.
#include <Config.hpp>
Classes
class Exception
Class for configuration exceptions.
Construction and Destruction
Config ()=default
Default constructor.
virtual ~Config ()=default
Default destructor.
Configuration Loader
void loadConfig (const std::string &configJson, LogQueue &warningsTo)
Loads a configuration.
Copy and Move
The class is neither copyable, nor movable.
Config (Config &)=delete
Deleted copy constructor.
Config & operator= (Config &)=delete
Deleted copy assignment operator.
Config (Config &&)=delete
Deleted move constructor.
Config & operator= (Config &&)=delete
Deleted move assignment operator.
Parsing Options
enum StringParsingOption { Default = 0, SQL, SubURL, URL }
Options for parsing strings.
enum CharParsingOption { FromNumber = 0, FromString }
Options for parsing char's.
Configuration Parsing
void category (const std::string &category)
Sets the category of the subsequent configuration items to be checked for.
void option (const std::string &name, bool &target)
Checks for a configuration option of type bool.
void option (const std::string &name, std::vector< bool > &target)
Checks for a configuration option of type array of bool's.
void option (const std::string &name, char &target, CharParsingOption opt)
Checks for a configuration option of type char.
void option (const std::string &name, std::vector< char > &target, CharParsingOption opt)
Checks for a configuration option of type array of char's.
void option (const std::string &name, std::int16_t &target)
Checks for a configuration option of type 16-bit integer.
void option (const std::string &name, std::vector< std::int16_t > &target)
Checks for a configuration option of type array of 16-bit integers.
void option (const std::string &name, std::int32_t &target)
Checks for a configuration option of type 32-bit integer.
void option (const std::string &name, std::vector< std::int32_t > &target)
Checks for a configuration option of type array of 32-bit integers.
void option (const std::string &name, std::int64_t &target)
Checks for a configuration option of type 64-bit integer.
void option (const std::string &name, std::vector< std::int64_t > &target)
Checks for a configuration option of type array of 64-bit integers.
void option (const std::string &name, std::uint8_t &target)
Checks for a configuration option of type unsigned 8-bit integer.
void option (const std::string &name, std::vector< std::uint8_t > &target)
Checks for a configuration option of type array of unsigned 8-bit integers.
void option (const std::string &name, std::uint16_t &target)
Checks for a configuration option of type unsigned 16-bit integer.
void option (const std::string &name, std::vector< std::uint16_t > &target)
Checks for a configuration option of type array of unsigned 16-bit integers.
void option (const std::string &name, std::uint32_t &target)
Checks for a configuration option of type unsigned 32-bit integer.
void option (const std::string &name, std::vector< std::uint32_t > &target)
Checks for a configuration option of type array of unsigned 32-bit integers.
void option (const std::string &name, std::uint64_t &target)
Checks for a configuration option of type unsigned 64-bit integer.
void option (const std::string &name, std::vector< std::uint64_t > &target)
Checks for a configuration option of type array of unsigned 64-bit integers.
void option (const std::string &name, std::string &target, StringParsingOption opt=Default)
Checks for a configuration option of type string.
void option (const std::string &name, std::vector< std::string > &target, StringParsingOption opt=Default)
Checks for a configuration option of type array of strings.
void warning (const std::string &warning)
Adds a warning to the logging queue.
Module-specific Configuration Parsing
virtual void parseBasicOption ()
Parses a basic option.
virtual void parseOption ()=0
Parses a module-specific configuration option.
virtual void checkOptions ()=0
Checks the module-specific configuration after parsing.
Detailed Description
Abstract class as base for module-specific configurations.
To add an option to a configuration, add a call to any of the option() functions (after a new call to category(), if necessary) to the local parseOption() implementation. It will be called for each configuration item to be parsed, checking whether this item contains the specified option and writing it to the specified target if it does.
Note
Once a configuration entry has been matched, it will be ignored by all subsequent option() calls, i.e. it cannot be parsed twice.
Member Enumeration Documentation
CharParsingOption
enum crawlservpp::Module::Config::CharParsingOption protected
Options for parsing char's.
Enumerator
FromNumber
Get char by its numeric value.
FromString
Get char from the beginning of a string.
Also supports certain escaped characters.
See also
Helper::Strings::getFirstOrEscapeChar
StringParsingOption
enum crawlservpp::Module::Config::StringParsingOption protected
Options for parsing strings.
Enumerator
Default
Uses a string as it is.
SQL
Requires a SQL-compatible string.
SubURL
Converts a string to a sub-URL.
URL
Converts a string to a URL (without the protocol).
Constructor & Destructor Documentation
Config() [1/3]
crawlservpp::Module::Config::Config () default
Default constructor.
~Config()
virtual crawlservpp::Module::Config::~Config () virtual default
Default destructor.
Reimplemented in crawlservpp::Module::Analyzer::Config.
Config() [2/3]
crawlservpp::Module::Config::Config (Config &) delete
Deleted copy constructor.
Config() [3/3]
crawlservpp::Module::Config::Config (Config &&) delete
Deleted move constructor.
Member Function Documentation
category()
void crawlservpp::Module::Config::category (const std::string & category) inline protected
Sets the category of the subsequent configuration items to be checked for.
Parameters
category Constant reference to a string containing the name of the category.
References crawlservpp::Struct::ConfigItem::category.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::parseAlgoOption(), crawlservpp::Module::Analyzer::Algo::MarkovText::parseAlgoOption(), crawlservpp::Network::Config::parseBasicOption(), crawlservpp::Module::Analyzer::Config::parseOption(), crawlservpp::Module::Parser::Config::parseOption(), crawlservpp::Module::Crawler::Config::parseOption(), and crawlservpp::Module::Extractor::Config::parseOption().
checkOptions()
virtual void crawlservpp::Module::Config::checkOptions () protected pure virtual
Checks the module-specific configuration after parsing.
Needs to be overridden by module-specific configuration child classes.
Implemented in crawlservpp::Module::Extractor::Config, crawlservpp::Module::Crawler::Config, crawlservpp::Module::Parser::Config, and crawlservpp::Module::Analyzer::Config.
Referenced by loadConfig().
loadConfig()
void crawlservpp::Module::Config::loadConfig (const std::string & configJson, LogQueue & warningsTo) inline
Loads a configuration.
Parameters
configJson Constant reference to a string containing the configuration as JSON.
warningsTo Reference to a queue to which warnings will be added that occur during the parsing of the configuration, also known as the "logging queue".
Exceptions
Module::Config::Exception if the configuration JSON cannot be parsed.
References crawlservpp::Struct::ConfigItem::category, checkOptions(), crawlservpp::Struct::ConfigItem::name, parseBasicOption(), crawlservpp::Helper::Json::parseRapid(), crawlservpp::Struct::ConfigItem::str(), crawlservpp::Struct::ConfigItem::value, and crawlservpp::Main::Exception::view().
Referenced by crawlservpp::Module::Analyzer::Thread::onInit(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), and crawlservpp::Module::Crawler::Thread::onInit().
operator=() [1/2]
Config& crawlservpp::Module::Config::operator= (Config &&) delete
Deleted move assignment operator.
operator=() [2/2]
Config& crawlservpp::Module::Config::operator= (Config &) delete
Deleted copy assignment operator.
option() [1/20]
void crawlservpp::Module::Config::option (const std::string & name, bool & target) inline protected
Checks for a configuration option of type bool.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a boolean variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
Referenced by crawlservpp::Module::Analyzer::Algo::MarkovTweet::parseAlgoOption(), crawlservpp::Module::Analyzer::Algo::MarkovText::parseAlgoOption(), crawlservpp::Network::Config::parseBasicOption(), crawlservpp::Module::Analyzer::Config::parseOption(), crawlservpp::Module::Parser::Config::parseOption(), crawlservpp::Module::Crawler::Config::parseOption(), and crawlservpp::Module::Extractor::Config::parseOption().
option() [2/20]
void crawlservpp::Module::Config::option (const std::string & name, char & target, CharParsingOption opt) inline protected
Checks for a configuration option of type char.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable of the type char into which the value of the configuration entry will be written if it is encountered.
opt Parsing options used for the configuration option.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References FromNumber, FromString, crawlservpp::Helper::Strings::getFirstOrEscapeChar(), crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [3/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int16_t & target) inline protected
Checks for a configuration option of type 16-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [4/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int32_t & target) inline protected
Checks for a configuration option of type 32-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [5/20]
void crawlservpp::Module::Config::option (const std::string & name, std::int64_t & target) inline protected
Checks for a configuration option of type 64-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [6/20]
void crawlservpp::Module::Config::option (const std::string & name, std::string & target, StringParsingOption opt = Default) inline protected
Checks for a configuration option of type string.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a string into which the value of the configuration entry will be stored if it is encountered.
opt Parsing option for the configuration entry.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Helper::Strings::checkSQLName(), Default, crawlservpp::Struct::ConfigItem::name, SQL, crawlservpp::Struct::ConfigItem::str(), SubURL, URL, and crawlservpp::Struct::ConfigItem::value.
option() [7/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint16_t & target) inline protected
Checks for a configuration option of type unsigned 16-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [8/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint32_t & target) inline protected
Checks for a configuration option of type unsigned 32-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [9/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint64_t & target) inline protected
Checks for a configuration option of type unsigned 64-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [10/20]
void crawlservpp::Module::Config::option (const std::string & name, std::uint8_t & target) inline protected
Checks for a configuration option of type unsigned 8-bit integer.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a variable into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [11/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< bool > & target) inline protected
Checks for a configuration option of type array of bool's.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector of bool's into which the value of the configuration entry will be written if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [12/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< char > & target, CharParsingOption opt) inline protected
Checks for a configuration option of type array of char's.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector of char's into which the value of the configuration entry will be written if it is encountered.
opt Parsing options used for the configuration option.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References FromNumber, FromString, crawlservpp::Helper::Strings::getFirstOrEscapeChar(), crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [13/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int16_t > & target) inline protected
Checks for a configuration option of type array of 16-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [14/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int32_t > & target) inline protected
Checks for a configuration option of type array of 32-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [15/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::int64_t > & target) inline protected
Checks for a configuration option of type array of 64-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [16/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::string > & target, StringParsingOption opt = Default) inline protected
Checks for a configuration option of type array of strings.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
opt Parsing option for the configuration entry.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Helper::Strings::checkSQLName(), Default, crawlservpp::Struct::ConfigItem::name, SQL, crawlservpp::Struct::ConfigItem::str(), SubURL, URL, and crawlservpp::Struct::ConfigItem::value.
option() [17/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint16_t > & target) inline protected
Checks for a configuration option of type array of unsigned 16-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [18/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint32_t > & target) inline protected
Checks for a configuration option of type array of unsigned 32-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [19/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint64_t > & target) inline protected
Checks for a configuration option of type array of unsigned 64-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
option() [20/20]
void crawlservpp::Module::Config::option (const std::string & name, std::vector< std::uint8_t > & target) inline protected
Checks for a configuration option of type array of unsigned 8-bit integers.
Ignores the option and adds a warning to the warnings queue, if the requested type does not match the data type in the configuration JSON.
Parameters
name Constant reference to a string containing the name of the option to check for.
target Reference to a vector into which the value of the configuration entry will be stored if it is encountered.
Exceptions
Module::Config::Exception if no category has been set.
See also
category
References crawlservpp::Struct::ConfigItem::name, crawlservpp::Struct::ConfigItem::str(), and crawlservpp::Struct::ConfigItem::value.
parseBasicOption()
void crawlservpp::Module::Config::parseBasicOption () inline protected virtual
Parses a basic option.
Might be overridden by child classes.
Can be used by abstract classes to add additional configuration entries without being the final implementation, as in Network::Config.
Warning
Any reimplementation needs to call parseOption() for the configuration to work properly.
See also
Network::Config::parseBasicOption
Reimplemented in crawlservpp::Network::Config.
References parseOption().
Referenced by loadConfig().
parseOption()
virtual void crawlservpp::Module::Config::parseOption () protected pure virtual
Parses a module-specific configuration option.
Needs to be overridden by module-specific configuration child classes.
Implemented in crawlservpp::Network::Config, crawlservpp::Module::Extractor::Config, crawlservpp::Module::Crawler::Config, crawlservpp::Module::Parser::Config, and crawlservpp::Module::Analyzer::Config.
Referenced by parseBasicOption().
warning()
void crawlservpp::Module::Config::warning (const std::string & warning) inline protected
Adds a warning to the logging queue.
Warning
Should not be used outside of Config::loadConfig!
Parameters
warning Constant reference to a string containing the warning.
Exceptions
Module::Config::Exception if no log queue is active.
Referenced by crawlservpp::Module::Analyzer::Config::checkOptions(), crawlservpp::Module::Parser::Config::checkOptions(), crawlservpp::Module::Crawler::Config::checkOptions(), crawlservpp::Module::Extractor::Config::checkOptions(), and crawlservpp::Network::Config::parseBasicOption().
The documentation for this class was generated from the following file:
Module/Config.hpp