crawlserv++: Setters
Setters
Functions
void crawlservpp::Module::Database::setOptions (const ModuleOptions &moduleOptions)
Sets general options for the module.
void crawlservpp::Module::Database::setThreadId (std::uint64_t id)
Sets the ID of the thread.
void crawlservpp::Module::Database::setLogging (std::uint8_t level, std::uint8_t min, std::uint8_t verbose)
Sets the current, minimal, and verbose logging levels.
Detailed Description
Function Documentation
setLogging()
void crawlservpp::Module::Database::setLogging (std::uint8_t level, std::uint8_t min, std::uint8_t verbose)
Sets the current, minimal, and verbose logging levels.
Initializes debug logging via logging file if necessary.
Parameters
level The current logging level.
min The minimum logging level.
verbose The verbose logging level.
Exceptions
Module::Database::Exception if the logging file could not be opened for writing.
References crawlservpp::Helper::FileSystem::getPathSeparator().
Referenced by crawlservpp::Wrapper::Database::setLogging().
setOptions()
void crawlservpp::Module::Database::setOptions (const ModuleOptions & moduleOptions)
Sets general options for the module.
Also converts all IDs to strings for easier usage later on.
Parameters
moduleOptions Constant reference to a structure containing the options for the current module.
See also
Struct::ModuleOptions
References crawlservpp::Struct::ModuleOptions::threadId, crawlservpp::Struct::ModuleOptions::urlListId, and crawlservpp::Struct::ModuleOptions::websiteId.
Referenced by crawlservpp::Module::Thread::Thread().
setThreadId()
void crawlservpp::Module::Database::setThreadId (std::uint64_t threadId)
Sets the ID of the thread.
Also converts it to a string for easier use later on.
Parameters
threadId Sets the ID of the thread.
Exceptions
Module::Database::Exception if no thread ID has been specified, i.e. the given thread ID is zero.
References crawlservpp::Struct::ModuleOptions::threadId.
Referenced by crawlservpp::Module::Thread::Thread().