crawlserv++: crawlservpp::Helper::DateTime Namespace Reference
crawlservpp::Helper::DateTime Namespace Reference
Namespace for global date/time helper functions.
Classes
class Exception
Class for date/time exceptions.
class LocaleException
Class for date/time locale exception.
Constants
constexpr auto longDateTime {"%a, %d %b %Y %T %Z"}
The 'long' format for date/times.
constexpr auto unixTimeFormat {"UNIX"sv}
The keyword to use a UNIX time format.
constexpr auto unixTimeFormatPlus {"UNIX+"sv}
The keyword to use a UNIX time format plus an offset.
constexpr auto unixTimeFormatMinus {"UNIX-"sv}
The keyword to use a UNIX time format minus an offset.
constexpr auto unixTimeFormatXLength {5}
The length of the keyword to use a UNIX time format with offset.
constexpr auto unixTimeFormatXOffset {4}
The position of the beginning of a UNIX time format offset.
constexpr std::array englishOrdinalSuffixes {"st"sv, "nd"sv, "rd"sv, "th"sv}
An array containing English ordinal suffixes to be stripped from numbers.
constexpr auto englishOrdinalSuffixLength {2}
The length of English ordinal suffixes to be stripped from numbers.
constexpr auto sqlTimeStamp {"%F %T"}
The date/time format used by the MySQL database.
constexpr auto sqlTimeStampLength {19}
The length of a formatted time stamp in the MySQL database.
constexpr auto frenchLocalePrefix {"fr"sv}
The prefix for French locale.
constexpr auto microsecondsPerDay {86400000000}
The number of microseconds per day used for date/time formatting.
constexpr auto millisecondsPerDay {86400000}
The number of milliseconds per day used for date/time formatting.
constexpr auto secondsPerDay {86400}
The number of seconds per day used for date/time formatting.
constexpr auto microsecondsPerHour {3600000000}
The number of microseconds per hour used for date/time formatting.
constexpr auto millisecondsPerHour {3600000}
The number of milliseconds per hour used for date/time formatting.
constexpr auto secondsPerHour {3600}
The number of seconds per hour used for date/time formatting.
constexpr auto microsecondsPerMinute {60000000}
The number of microseconds per minute used for date/time formatting.
constexpr auto millisecondsPerMinute {60000}
The number of milliseconds per minute used for date/time formatting.
constexpr auto secondsPerMinute {60}
The number of seconds per minute used for date/time formatting.
constexpr auto microsecondsPerSecond {1000000}
The number of microseconds per second used for date/time formatting.
constexpr auto millisecondsPerSecond {1000}
The number of milliseconds per second used for date/time formatting.
constexpr auto microsecondsPerMillisecond {1000}
The number of microseconds per millisecond used for date/time formatting.
constexpr auto isoDateLength {10}
The length of a date in valid ISO Format (YYYY-MM-DD)
Conversion
void convertLongDateTimeToSQLTimeStamp (std::string &dateTime)
Converts a date/time formatted in a 'long' format into the format YYYY-MM-DD HH:MM:SS.
void convertCustomDateTimeToSQLTimeStamp (std::string &dateTime, const std::string &customFormat)
Converts date/time with a custom format into the format YYYY-MM-DD HH:MM:SS.
void convertCustomDateTimeToSQLTimeStamp (std::string &dateTime, const std::string &customFormat, const std::string &locale)
Converts date/time with a custom format into the format YYYY-MM-DD HH:MM:SS.
void convertTimeStampToSQLTimeStamp (std::string &timeStamp)
Converts a timestamp in YYYYMMDDHHMMSS format to a MySQL timestamp in YYYY-MM-DD HH:MM:SS format.
void convertSQLTimeStampToTimeStamp (std::string &timeStamp)
Converts a MySQL timestamp in YYYY-MM-DD HH:MM:SS format to a timestamp in YYYYMMDDHHMMSS format.
Formatting
std::string microsecondsToString (std::uint64_t microseconds)
Converts microseconds into a well-formatted string.
std::string millisecondsToString (std::uint64_t milliseconds)
Converts milliseconds into a well-formatted string.
std::string secondsToString (std::uint64_t seconds)
Converts seconds into a well-formatted string.
std::string now ()
Formats the current date/time as string in the format YYYY-MM-DD HH:MM:SS.
Verification
bool isValidISODate (const std::string &isoDate)
Checks whether a string contains a valid date in ISO format.
Comparison
bool isISODateInRange (std::string_view isoDate, std::string_view rangeFrom, std::string_view rangeTo)
Checks whether the given ISO date is in the given range of dates.
Helpers
void removeEnglishOrdinals (std::string &strInOut)
Removes all English ordinal suffixes after numbers in the given string.
void fixFrenchMonths (std::string_view locale, std::string &strInOut)
Replaces the abbreviation "avr." for the month of april (avril) in the given string, if the locale is French.
Detailed Description
Namespace for global date/time helper functions.
Function Documentation
convertCustomDateTimeToSQLTimeStamp() [1/2]
void crawlservpp::Helper::DateTime::convertCustomDateTimeToSQLTimeStamp (std::string & dateTime, const std::string & customFormat) inline
Converts date/time with a custom format into the format YYYY-MM-DD HH:MM:SS.
Calling this function with an empty input string will have no consequences.
For more information about the format string, see Howard Hinnant's paper about his date.h library.
Alternatively, "UNIX", "UNIX+<offset>", or "UNIX<-offset>" can be used to convert from a UNIX time plus/minus the given offset.
Note
A string view cannot be used, because the underlying C function requires a null-terminated string.
Parameters
dateTime Reference to a string containing the date/time formatted in the custom format and to be converted in situ.
customFormat A const reference to the string containing the date/time format to be converted from.
Exceptions
DateTime::Exception of the custom format is invalid or empty, or if the date/time conversion fails.
References removeEnglishOrdinals(), sqlTimeStamp, sqlTimeStampLength, unixTimeFormat, unixTimeFormatMinus, unixTimeFormatPlus, unixTimeFormatXLength, and unixTimeFormatXOffset.
Referenced by convertCustomDateTimeToSQLTimeStamp(), convertLongDateTimeToSQLTimeStamp(), and convertTimeStampToSQLTimeStamp().
convertCustomDateTimeToSQLTimeStamp() [2/2]
void crawlservpp::Helper::DateTime::convertCustomDateTimeToSQLTimeStamp (std::string & dateTime, const std::string & customFormat, const std::string & locale) inline
Converts date/time with a custom format into the format YYYY-MM-DD HH:MM:SS.
Calling this function with an empty input string will have no consequences.
For more information about the format string, see Howard Hinnant's paper about his date.h library.
Note
String views cannot be used, because the underlying functions require null-terminated strings.
Parameters
dateTime A reference to the string containing the date/time formatted in the custom format and to be converted in situ.
customFormat A const reference to the string containing the date/time format to be converted from.
locale A const reference to the string containing the locale to be used during the conversion.
Exceptions
DateTime::Exception of the custom format is invalid or empty, or if the date/time conversion fails.
References convertCustomDateTimeToSQLTimeStamp(), fixFrenchMonths(), removeEnglishOrdinals(), and sqlTimeStampLength.
convertLongDateTimeToSQLTimeStamp()
void crawlservpp::Helper::DateTime::convertLongDateTimeToSQLTimeStamp (std::string & dateTime) inline
Converts a date/time formatted in a 'long' format into the format YYYY-MM-DD HH:MM:SS.
Calling this function with an empty input string will have no consequences.
Parameters
dateTime String containing the date/time formatted in a 'long' format and to be converted in situ.
Exceptions
DateTime::Exception if the conversion fails.
See also
convertCustomDateTimeToSQLTimeStamp
References convertCustomDateTimeToSQLTimeStamp(), and longDateTime.
convertSQLTimeStampToTimeStamp()
void crawlservpp::Helper::DateTime::convertSQLTimeStampToTimeStamp (std::string & timeStamp) inline
Converts a MySQL timestamp in YYYY-MM-DD HH:MM:SS format to a timestamp in YYYYMMDDHHMMSS format.
Calling this function with an empty input string will have no consequences.
Parameters
timeStamp A reference to the string containing a MySQL timestamp in the YYYY-MM-DD HH:MM:SS format to be converted in situ.
Exceptions
DateTime::Exception if the conversion fails.
See also
convertTimeStampToSQLTimeStamp
convertTimeStampToSQLTimeStamp()
void crawlservpp::Helper::DateTime::convertTimeStampToSQLTimeStamp (std::string & timeStamp) inline
Converts a timestamp in YYYYMMDDHHMMSS format to a MySQL timestamp in YYYY-MM-DD HH:MM:SS format.
Calling this function with an empty input string will have no consequences.
Parameters
timeStamp A reference to the string containing a timestamp in the YYYYMMDDHHMMSS format to be converted in situ.
Exceptions
DateTime::Exception if the conversion fails.
See also
convertCustomDateTimeToSQLTimeStamp
References convertCustomDateTimeToSQLTimeStamp().
fixFrenchMonths()
void crawlservpp::Helper::DateTime::fixFrenchMonths (std::string_view locale, std::string & strInOut) inline
Replaces the abbreviation "avr." for the month of april (avril) in the given string, if the locale is French.
If the given locale is not French, the function call will be without consequences.
Parameters
locale A string view containing the locale to be checked for French.
strInOut A reference to the string containing the date/time, in which the abbreviation will be replaced if the given locale is French.
References frenchLocalePrefix, and crawlservpp::Helper::Strings::replaceAll().
Referenced by convertCustomDateTimeToSQLTimeStamp().
isISODateInRange()
bool crawlservpp::Helper::DateTime::isISODateInRange (std::string_view isoDate, std::string_view rangeFrom, std::string_view rangeTo) inline
Checks whether the given ISO date is in the given range of dates.
Note
Only the first ten characters of the given dates will be considered.
Parameters
isoDate A string view containing the date in valid ISO format, i.e. a date in the format YYY-MM-DD.
rangeFrom A string view containing the start date of the range in valid ISO format, i.e. a date in the format YYY-MM-DD.
rangeTo A string view containing the end date of the range in valid ISO format, i.e. a date in the format YYY-MM-DD.
Returns
True, if the given date falls into the given range of dates or one of the two dates defining this range are too short. False otherwise.
References isoDateLength.
Referenced by crawlservpp::Data::Corpus::filterByDate().
isValidISODate()
bool crawlservpp::Helper::DateTime::isValidISODate (const std::string & isoDate) inline
Checks whether a string contains a valid date in ISO format.
Note
A string view is not being used, because the underlying string stream requires a copy of the string.
Parameters
isoDate A string containing the date to check.
Returns
True if the given string contains a valid date in ISO format, i.e. a date in the format YYY-MM-DD. False otherwise.
microsecondsToString()
std::string crawlservpp::Helper::DateTime::microsecondsToString (std::uint64_t microseconds) inline
Converts microseconds into a well-formatted string.
Parameters
microseconds The number of microseconds to convert.
Returns
A copy of the string containing the well-formatted output.
See also
millisecondsToString, secondsToString
References microsecondsPerDay, microsecondsPerHour, microsecondsPerMillisecond, microsecondsPerMinute, and microsecondsPerSecond.
Referenced by crawlservpp::Timer::SimpleHR::tickStr(), and crawlservpp::Timer::StartStopHR::totalStr().
millisecondsToString()
std::string crawlservpp::Helper::DateTime::millisecondsToString (std::uint64_t milliseconds) inline
Converts milliseconds into a well-formatted string.
Parameters
milliseconds The number of milliseconds to convert.
Returns
A copy of the string containing the well-formatted output.
See also
microsecondsToString, secondsToString
References millisecondsPerDay, millisecondsPerHour, millisecondsPerMinute, and millisecondsPerSecond.
Referenced by crawlservpp::Timer::Simple::tickStr(), and crawlservpp::Timer::StartStop::totalStr().
now()
std::string crawlservpp::Helper::DateTime::now () inline
Formats the current date/time as string in the format YYYY-MM-DD HH:MM:SS.
Returns
A copy of the string containing the current date/time of the system as string in the format YYYY-MM-DD HH:MM:SS.
Referenced by crawlservpp::Main::Server::getUpTime(), crawlservpp::Module::Database::log(), crawlservpp::Module::Parser::Thread::onClear(), crawlservpp::Module::Extractor::Thread::onClear(), crawlservpp::Module::Crawler::Thread::onClear(), crawlservpp::Module::Parser::Thread::onInit(), crawlservpp::Module::Extractor::Thread::onInit(), crawlservpp::Module::Crawler::Thread::onInit(), crawlservpp::Module::Parser::Thread::onPause(), crawlservpp::Module::Extractor::Thread::onPause(), crawlservpp::Module::Crawler::Thread::onPause(), crawlservpp::Module::Parser::Thread::onTick(), crawlservpp::Module::Extractor::Thread::onTick(), crawlservpp::Module::Crawler::Thread::onTick(), crawlservpp::Module::Parser::Thread::onUnpause(), crawlservpp::Module::Extractor::Thread::onUnpause(), crawlservpp::Module::Crawler::Thread::onUnpause(), crawlservpp::Network::Curl::resetConnection(), crawlservpp::Main::Server::Server(), crawlservpp::Timer::StartStop::start(), crawlservpp::Timer::StartStopHR::start(), crawlservpp::Timer::StartStop::stop(), crawlservpp::Timer::StartStopHR::stop(), crawlservpp::Timer::SimpleHR::tick(), crawlservpp::Timer::Simple::tick(), crawlservpp::Timer::SimpleHR::tickStr(), and crawlservpp::Timer::Simple::tickStr().
removeEnglishOrdinals()
void crawlservpp::Helper::DateTime::removeEnglishOrdinals (std::string & strInOut) inline
Removes all English ordinal suffixes after numbers in the given string.
Parameters
strInOut A reference to the string containing the date/time, from which the English ordinal suffixes will be removed in situ.
References englishOrdinalSuffixes, and englishOrdinalSuffixLength.
Referenced by convertCustomDateTimeToSQLTimeStamp().
secondsToString()
std::string crawlservpp::Helper::DateTime::secondsToString (std::uint64_t seconds) inline
Converts seconds into a well-formatted string.
Parameters
seconds The number of seconds to convert.
Returns
A copy of the string containing the well-formatted output.
See also
microsecondsToString, millisecondsToString
References secondsPerDay, secondsPerHour, and secondsPerMinute.
Referenced by crawlservpp::Main::Database::checkConnection(), crawlservpp::Main::App::~App(), and crawlservpp::Main::Server::~Server().
Variable Documentation
englishOrdinalSuffixes
constexpr std::array crawlservpp::Helper::DateTime::englishOrdinalSuffixes {"st"sv, "nd"sv, "rd"sv, "th"sv} constexpr
An array containing English ordinal suffixes to be stripped from numbers.
Referenced by removeEnglishOrdinals().
englishOrdinalSuffixLength
constexpr auto crawlservpp::Helper::DateTime::englishOrdinalSuffixLength {2} constexpr
The length of English ordinal suffixes to be stripped from numbers.
Referenced by removeEnglishOrdinals().
frenchLocalePrefix
constexpr auto crawlservpp::Helper::DateTime::frenchLocalePrefix {"fr"sv} constexpr
The prefix for French locale.
Referenced by fixFrenchMonths().
isoDateLength
constexpr auto crawlservpp::Helper::DateTime::isoDateLength {10} constexpr
The length of a date in valid ISO Format (YYYY-MM-DD)
Referenced by isISODateInRange().
longDateTime
constexpr auto crawlservpp::Helper::DateTime::longDateTime {"%a, %d %b %Y %T %Z"} constexpr
The 'long' format for date/times.
Referenced by convertLongDateTimeToSQLTimeStamp().
microsecondsPerDay
constexpr auto crawlservpp::Helper::DateTime::microsecondsPerDay {86400000000} constexpr
The number of microseconds per day used for date/time formatting.
Referenced by microsecondsToString().
microsecondsPerHour
constexpr auto crawlservpp::Helper::DateTime::microsecondsPerHour {3600000000} constexpr
The number of microseconds per hour used for date/time formatting.
Referenced by microsecondsToString().
microsecondsPerMillisecond
constexpr auto crawlservpp::Helper::DateTime::microsecondsPerMillisecond {1000} constexpr
The number of microseconds per millisecond used for date/time formatting.
Referenced by microsecondsToString().
microsecondsPerMinute
constexpr auto crawlservpp::Helper::DateTime::microsecondsPerMinute {60000000} constexpr
The number of microseconds per minute used for date/time formatting.
Referenced by microsecondsToString().
microsecondsPerSecond
constexpr auto crawlservpp::Helper::DateTime::microsecondsPerSecond {1000000} constexpr
The number of microseconds per second used for date/time formatting.
Referenced by microsecondsToString().
millisecondsPerDay
constexpr auto crawlservpp::Helper::DateTime::millisecondsPerDay {86400000} constexpr
The number of milliseconds per day used for date/time formatting.
Referenced by millisecondsToString().
millisecondsPerHour
constexpr auto crawlservpp::Helper::DateTime::millisecondsPerHour {3600000} constexpr
The number of milliseconds per hour used for date/time formatting.
Referenced by millisecondsToString().
millisecondsPerMinute
constexpr auto crawlservpp::Helper::DateTime::millisecondsPerMinute {60000} constexpr
The number of milliseconds per minute used for date/time formatting.
Referenced by millisecondsToString().
millisecondsPerSecond
constexpr auto crawlservpp::Helper::DateTime::millisecondsPerSecond {1000} constexpr
The number of milliseconds per second used for date/time formatting.
Referenced by millisecondsToString().
secondsPerDay
constexpr auto crawlservpp::Helper::DateTime::secondsPerDay {86400} constexpr
The number of seconds per day used for date/time formatting.
Referenced by secondsToString().
secondsPerHour
constexpr auto crawlservpp::Helper::DateTime::secondsPerHour {3600} constexpr
The number of seconds per hour used for date/time formatting.
Referenced by secondsToString().
secondsPerMinute
constexpr auto crawlservpp::Helper::DateTime::secondsPerMinute {60} constexpr
The number of seconds per minute used for date/time formatting.
Referenced by secondsToString().
sqlTimeStamp
constexpr auto crawlservpp::Helper::DateTime::sqlTimeStamp {"%F %T"} constexpr
The date/time format used by the MySQL database.
Referenced by convertCustomDateTimeToSQLTimeStamp().
sqlTimeStampLength
constexpr auto crawlservpp::Helper::DateTime::sqlTimeStampLength {19} constexpr
The length of a formatted time stamp in the MySQL database.
Referenced by convertCustomDateTimeToSQLTimeStamp().
unixTimeFormat
constexpr auto crawlservpp::Helper::DateTime::unixTimeFormat {"UNIX"sv} constexpr
The keyword to use a UNIX time format.
Referenced by convertCustomDateTimeToSQLTimeStamp().
unixTimeFormatMinus
constexpr auto crawlservpp::Helper::DateTime::unixTimeFormatMinus {"UNIX-"sv} constexpr
The keyword to use a UNIX time format minus an offset.
Referenced by convertCustomDateTimeToSQLTimeStamp().
unixTimeFormatPlus
constexpr auto crawlservpp::Helper::DateTime::unixTimeFormatPlus {"UNIX+"sv} constexpr
The keyword to use a UNIX time format plus an offset.
Referenced by convertCustomDateTimeToSQLTimeStamp().
unixTimeFormatXLength
constexpr auto crawlservpp::Helper::DateTime::unixTimeFormatXLength {5} constexpr
The length of the keyword to use a UNIX time format with offset.
Referenced by convertCustomDateTimeToSQLTimeStamp().
unixTimeFormatXOffset
constexpr auto crawlservpp::Helper::DateTime::unixTimeFormatXOffset {4} constexpr
The position of the beginning of a UNIX time format offset.
Referenced by convertCustomDateTimeToSQLTimeStamp().