crawlserv++: crawlservpp::Helper::FileSystem Namespace Reference
crawlservpp::Helper::FileSystem Namespace Reference
Namespace for global file system helper functions.
Classes
class Exception
Class for file system exceptions.
Existence and Validity
bool exists (std::string_view path)
Checks whether the specified path exists.
bool isValidDirectory (std::string_view path)
Checks whether the given path points to a valid directory.
bool isValidFile (std::string_view path)
Checks whether the given path points to a valid file.
Paths and Directories
char getPathSeparator ()
Gets the preferred separator for file paths in the current operating system.
std::vector< std::string > listFilesInPath (std::string_view pathToDir, std::string_view fileExtension)
Lists all files with the given extension in the given directory and its subdirectories.
bool contains (std::string_view pathToDir, std::string_view pathToCheck)
Checks whether the given path is located inside the given directory.
void createDirectory (std::string_view pathToDir)
Creates a directory at the given path.
void createDirectoryIfNotExists (std::string_view pathToDir)
Creates a directory at the given path, if it does not exist already.
void clearDirectory (std::string_view pathToDir)
Deletes all files and folders in the given directory.
Disk Space
std::uintmax_t getFreeSpace (std::string_view path)
Gets the available disk space at the given location in bytes.
Detailed Description
Namespace for global file system helper functions.
Function Documentation
clearDirectory()
void crawlservpp::Helper::FileSystem::clearDirectory (std::string_view pathToDir) inline
Deletes all files and folders in the given directory.
Parameters
pathToDir A string view containing a path to the directory which contents should be deleted.
Exceptions
FileSystem::Exception if the given path does not point to a valid directory or one of its contents could not be removed.
References isValidDirectory().
Referenced by crawlservpp::Main::Server::Server().
contains()
bool crawlservpp::Helper::FileSystem::contains (std::string_view pathToDir, std::string_view pathToCheck) inline
Checks whether the given path is located inside the given directory.
Parameters
pathToDir A string view containing the directory in which the given path should be located.
pathToCheck A string view containing the path which should be located inside the directory.
Returns
True, if the given path is or would be located inside the given directory, including its subdirectories. False otherwise.
Exceptions
FileSystem::Exception if the given directory does not exist, or the path to check contains an unsupported symlink.
References isValidDirectory().
Referenced by crawlservpp::Main::WebServer::sendFile(), and crawlservpp::Network::Curl::setConfigGlobal().
createDirectory()
void crawlservpp::Helper::FileSystem::createDirectory (std::string_view pathToDir) inline
Creates a directory at the given path.
Parameters
pathToDir A string view containing the path to the directory to be created.
Exceptions
FileSystem::Exception if the directory could not be created.
See also
createDirectoryIfNotExists
Referenced by createDirectoryIfNotExists(), and crawlservpp::Main::Server::Server().
createDirectoryIfNotExists()
void crawlservpp::Helper::FileSystem::createDirectoryIfNotExists (std::string_view pathToDir) inline
Creates a directory at the given path, if it does not exist already.
Parameters
pathToDir A string view containing the path to the directory to be created, if it does not exist already
Exceptions
FileSystem::Exception if the directory does not exist, but could not be created.
See also
createDirectory
References createDirectory(), and isValidDirectory().
Referenced by crawlservpp::Main::Server::Server().
exists()
bool crawlservpp::Helper::FileSystem::exists (std::string_view path) inline
Checks whether the specified path exists.
Parameters
path A string view containing the path to be checked for existence.
Returns
True if the path exists. False otherwise.
Exceptions
FileSystem::Exception if the existence of the path could not be checked.
Referenced by isValidDirectory(), isValidFile(), and listFilesInPath().
getFreeSpace()
std::uintmax_t crawlservpp::Helper::FileSystem::getFreeSpace (std::string_view path) inline
Gets the available disk space at the given location in bytes.
Parameters
path A string view containing a path to the directory for which the available disk space should be determined.
Returns
The available disk space at the given location in bytes.
Exceptions
FileSystem::Exception if the available disk space could not be dettermined at the given location.
getPathSeparator()
char crawlservpp::Helper::FileSystem::getPathSeparator () inline
Gets the preferred separator for file paths in the current operating system.
Returns
The preferred separator for file paths in the current operating system.
Referenced by crawlservpp::Main::Database::connect(), crawlservpp::Main::WebServer::sendFile(), crawlservpp::Network::Curl::setConfigGlobal(), and crawlservpp::Module::Database::setLogging().
isValidDirectory()
bool crawlservpp::Helper::FileSystem::isValidDirectory (std::string_view path) inline
Checks whether the given path points to a valid directory.
Parameters
path A string view containing the path to check.
Returns
True if the path points to a valid directory. False otherwise.
Exceptions
FileSystem::Exception if the validity of the directory could not be checked.
References exists().
Referenced by crawlservpp::Main::Database::addWebsite(), clearDirectory(), contains(), createDirectoryIfNotExists(), and crawlservpp::Main::Server::Server().
isValidFile()
bool crawlservpp::Helper::FileSystem::isValidFile (std::string_view path) inline
Checks whether the given path points to a valid file.
Parameters
path A string view containing the path to check.
Returns
True if the path points to a valid file. False otherwise.
Exceptions
FileSystem::Exception if the validity of the file could not be checked.
References exists().
listFilesInPath()
std::vector< std::string > crawlservpp::Helper::FileSystem::listFilesInPath (std::string_view pathToDir, std::string_view fileExtension) inline
Lists all files with the given extension in the given directory and its subdirectories.
Note
While the given directory (pathToDir) needs to exist, the given path to check (pathToCheck) does not.
Parameters
pathToDir A string view containing the directory to search for files.
fileExtension A string view containing the extension of the files to search for.
Returns
A vector of strings containing the paths of the files with the given extension in the given directory and its subdirectories.
Exceptions
FileSystem::Exception if the given path is invalid or does not exist, or when the iteration over all the contents of the directory has failed.
References exists().
Referenced by crawlservpp::Main::Database::initializeSql().