crawlserv++: crawlservpp::Helper::Portability Namespace Reference
crawlservpp::Helper::Portability Namespace Reference
Namespace for global portability functions.
Functions
char getch ()
Gets a character from the user via the terminal.
std::vector< std::string > enumLocales ()
Enumerates all available locale on the system.
Variables
static struct termios oldT
static struct termios newT
Detailed Description
Namespace for global portability functions.
Function Documentation
enumLocales()
std::vector<std::string> crawlservpp::Helper::Portability::enumLocales () inline
Enumerates all available locale on the system.
Returns
A vector of strings containing all available locale on the current system.
References crawlservpp::Helper::System::exec(), and crawlservpp::Helper::Strings::split().
Referenced by crawlservpp::Main::Database::update().
getch()
char crawlservpp::Helper::Portability::getch () inline
Gets a character from the user via the terminal.
Returns
The character read from the user input.
References newT, and oldT.
Variable Documentation
newT
struct termios crawlservpp::Helper::Portability::newT static
Referenced by getch().
oldT
struct termios crawlservpp::Helper::Portability::oldT static
Referenced by getch().