crawlserv++: crawlservpp::Helper::Versions Namespace Reference
crawlservpp::Helper::Versions Namespace Reference
Namespace for functions getting the versions of the different libraries used by the application.
Typedefs
using StringString = std::pair< std::string, std::string >
A pair of strings.
Constants
constexpr auto boostMajor {100000}
Divisor to retrieve the major version of the Boost library.
constexpr auto boostMinor {1000}
Divisor to retrieve the minor version of the Boost library.
constexpr auto boostPatch {100}
Divisor to retrieve the patch level of the Boost library.
constexpr auto pugixmlMajor {100}
Divisor to retrieve the major version of the pugixml library.
constexpr auto pugixmlMinor {10}
Divisor to retrieve the minor version of the pugixml library.
constexpr std::string_view utf8CppVersion {"2.1"}
The version of the UTF8-CPP library.
Getters
std::vector< StringString > getLibraryVersions ()
Gets the versions of the used libraries.
std::string getLibraryVersionsStr (const std::string &indent)
Gets the versions of the used libraries as one indented string.
Detailed Description
Namespace for functions getting the versions of the different libraries used by the application.
Typedef Documentation
StringString
using crawlservpp::Helper::Versions::StringString = typedef std::pair<std::string, std::string>
A pair of strings.
Function Documentation
getLibraryVersions()
std::vector< StringString > crawlservpp::Helper::Versions::getLibraryVersions () inline
Gets the versions of the used libraries.
Returns
The versions of the libraries as [name, version] pairs.
References boostMajor, boostMinor, boostPatch, pugixmlMajor, pugixmlMinor, and utf8CppVersion.
Referenced by getLibraryVersionsStr(), and crawlservpp::Main::Database::update().
getLibraryVersionsStr()
std::string crawlservpp::Helper::Versions::getLibraryVersionsStr (const std::string & indent) inline
Gets the versions of the used libraries as one indented string.
Parameters
indent Constant reference to a string containing the indent to be added in front of each line.
Returns
A copy of a string containing the versions of the libraries with one (indented) line for each library.
References getLibraryVersions().
Variable Documentation
boostMajor
constexpr auto crawlservpp::Helper::Versions::boostMajor {100000} constexpr
Divisor to retrieve the major version of the Boost library.
Referenced by getLibraryVersions().
boostMinor
constexpr auto crawlservpp::Helper::Versions::boostMinor {1000} constexpr
Divisor to retrieve the minor version of the Boost library.
Referenced by getLibraryVersions().
boostPatch
constexpr auto crawlservpp::Helper::Versions::boostPatch {100} constexpr
Divisor to retrieve the patch level of the Boost library.
Referenced by getLibraryVersions().
pugixmlMajor
constexpr auto crawlservpp::Helper::Versions::pugixmlMajor {100} constexpr
Divisor to retrieve the major version of the pugixml library.
Referenced by getLibraryVersions().
pugixmlMinor
constexpr auto crawlservpp::Helper::Versions::pugixmlMinor {10} constexpr
Divisor to retrieve the minor version of the pugixml library.
Referenced by getLibraryVersions().
utf8CppVersion
constexpr std::string_view crawlservpp::Helper::Versions::utf8CppVersion {"2.1"} constexpr
The version of the UTF8-CPP library.
Warning
Hard-coded version information might not be accurate!
Referenced by getLibraryVersions().