crawlserv++: crawlservpp::Helper::Strings Namespace Reference
crawlservpp::Helper::Strings Namespace Reference
Namespace for global string helper functions.
Constants
constexpr std::array utfWhitespaces
UTF-8 whitespaces used by utfTidy().
constexpr auto checkHexLength {3}
Length of a two-digit hexademical number including the preceding percentage sign.
constexpr auto randCharSet
Characters to be chosen from for random string generation performed by generateRandom().
Replacing
void replaceAll (std::string &strInOut, std::string_view needle, std::string_view replacement)
Replaces all occurences within a string with another string.
Conversion
bool stringToBool (std::string inputString)
Converts a string into a boolean value.
Number Format Checking
bool isHex (std::string_view inputString)
Checks whether a string contains only hexadecimal digits.
Trimming
void trim (std::string &stringToTrim)
Removes whitespaces around a string.
Joining
std::string join (const std::vector< std::string > &strings, char delimiter, bool ignoreEmpty)
Concatenates all elements of a vector into a single string.
std::string join (const std::vector< std::string > &strings, std::string_view delimiter, bool ignoreEmpty)
Concatenates all elements of a vector into a single string.
std::string join (std::queue< std::string > &strings, char delimiter, bool ignoreEmpty)
Concatenates all elements of a queue into a single string.
std::string join (std::queue< std::string > &strings, std::string_view delimiter, bool ignoreEmpty)
Concatenates all elements of a queue into a single string.
void join (const std::vector< std::string > &strings, char delimiter, bool ignoreEmpty, std::string &appendTo)
Concatenates all elements of a vector and appends them to a string.
void join (const std::vector< std::string > &strings, std::string_view delimiter, bool ignoreEmpty, std::string &appendTo)
Concatenates all elements of a vector and appends them to a string.
void join (std::queue< std::string > &strings, char delimiter, bool ignoreEmpty, std::string &appendTo)
Concatenates all elements of a queue into a single string.
void join (std::queue< std::string > &strings, std::string_view delimiter, bool ignoreEmpty, std::string &appendTo)
Concatenates all elements of a queue into a single string.
Splitting
std::vector< std::string > split (const std::string &str, char delimiter)
Splits a string into a vector of strings using the given delimiter.
std::vector< std::string > split (std::string_view str, std::string_view delimiter)
Splits a string into a vector of strings using the given delimiter.
std::queue< std::string > splitToQueue (std::string_view str, char delimiter, bool removeEmpty)
Splits a string into a queue of strings using the given delimiter.
std::queue< std::string > splitToQueue (std::string_view str, std::string_view delimiter, bool removeEmpty)
Splits a string into a queue of strings using the given delimiter.
Sorting
void sortAndRemoveDuplicates (std::vector< std::string > &vectorOfStrings, bool caseSensitive)
Sorts the given vector of strings and removes duplicates.
Escape Characters
char getFirstOrEscapeChar (std::string_view from)
Gets the first character or an escaped character from the beginning of the given string.
Encoding
void encodePercentage (std::string &stringToEncode)
Encodes percentage signs that are not followed by a two-digit hexadecimal number with %25.
Tidying
void utfTidy (std::string &stringToTidy)
Removes new lines and unnecessary spaces, including UTF-8 whitespaces.
Name Checking
bool checkDomainName (std::string_view name)
Checks whether the given string is a a valid domain name.
bool checkSQLName (std::string_view name)
Checks whether the given string is a valid name for MySQL tables and fields.
Random String Generation
std::string generateRandom (std::size_t length)
Generates a random alpha-numerical string of the given length.
Detailed Description
Namespace for global string helper functions.
Function Documentation
checkDomainName()
bool crawlservpp::Helper::Strings::checkDomainName (std::string_view name) inline
Checks whether the given string is a a valid domain name.
Note
Checks only for characters that would interfer with internal MySQL statements: /, \, and '.
Parameters
name View of the string to be checked for a valid domain name.
Returns
True, if the string might be used as a domain name. False otherwise.
checkSQLName()
bool crawlservpp::Helper::Strings::checkSQLName (std::string_view name) inline
Checks whether the given string is a valid name for MySQL tables and fields.
Parameters
name View of the string to be checked for a valid MySQL table or field name.
Returns
True if the string might be used as a MySQL table or field name. False otherwise.
Referenced by crawlservpp::Module::Config::option().
encodePercentage()
void crawlservpp::Helper::Strings::encodePercentage (std::string & stringToEncode) inline
Encodes percentage signs that are not followed by a two-digit hexadecimal number with %25.
Parameters
stringToEncode Reference to the string in which the percentage signs will be encoded in-situ.
References checkHexLength, and isHex().
Referenced by crawlservpp::Parsing::URI::escapeUri().
generateRandom()
std::string crawlservpp::Helper::Strings::generateRandom (std::size_t length) inline
Generates a random alpha-numerical string of the given length.
Parameters
length Length of the string to be generated.
Returns
The generated alpha-numerical string of the given length.
References randCharSet.
getFirstOrEscapeChar()
char crawlservpp::Helper::Strings::getFirstOrEscapeChar (std::string_view from) inline
Gets the first character or an escaped character from the beginning of the given string.
Escaped characters that are supported: \n, \t, and \\
Note
Only ASCII characters are supported. The returning character will be invalid, if the given string starts with a UTF-8 character.
Parameters
from A view of the string to extract the character from.
Returns
the escaped character if the first two characters of the given string equal one of the supported escape sequences. The first character of the given string otherwise.
Referenced by crawlservpp::Module::Config::option().
isHex()
bool crawlservpp::Helper::Strings::isHex (std::string_view inputString) inline
Checks whether a string contains only hexadecimal digits.
Case-insensitive.
Parameters
inputString A view into the string to check for hexadecimal digits.
Returns
True, if the string only contains hexadecimal digits (0-F) and no whitespaces. False otherwise.
Referenced by encodePercentage().
join() [1/8]
std::string crawlservpp::Helper::Strings::join (const std::vector< std::string > & strings, char delimiter, bool ignoreEmpty) inline
Concatenates all elements of a vector into a single string.
Parameters
strings Constant reference to a vector containing the strings to be concatenated.
delimiter A character to be inserted inbetween the concatenated strings.
ignoreEmpty Ignore empty strings when concatenating the given elements.
Returns
The string containing the concatenated elements, separated by the given delimiter, or an empty string if no elements have been concatenated.
Referenced by crawlservpp::Data::ImportExport::Text::exportList().
join() [2/8]
void crawlservpp::Helper::Strings::join (const std::vector< std::string > & strings, char delimiter, bool ignoreEmpty, std::string & appendTo) inline
Concatenates all elements of a vector and appends them to a string.
Parameters
strings Constant reference to a vector containing the strings to be concatenated.
delimiter A character to be inserted inbetween the concatenated strings.
ignoreEmpty Ignore empty strings when concatenating the given elements.
appendTo The string that will be appended with the concatenated elements, separated by the given delimiter. It will remain unchanged, if no elements have been concatenated.
join() [3/8]
std::string crawlservpp::Helper::Strings::join (const std::vector< std::string > & strings, std::string_view delimiter, bool ignoreEmpty) inline
Concatenates all elements of a vector into a single string.
Parameters
strings Constant reference to a vector containing the strings to be concatenated.
delimiter View of a string to be inserted inbetween the concatenated strings.
ignoreEmpty Ignore empty strings when concatenating the given elements.
Returns
The string containing the concatenated elements, separated by the given delimiter, or an empty string if no elements have been concatenated.
join() [4/8]
void crawlservpp::Helper::Strings::join (const std::vector< std::string > & strings, std::string_view delimiter, bool ignoreEmpty, std::string & appendTo) inline
Concatenates all elements of a vector and appends them to a string.
Parameters
strings Constant reference to a vector containing the strings to be concatenated.
delimiter A view of the string to be inserted inbetween the concatenated strings.
ignoreEmpty Ignore empty strings when concatenating the given elements.
appendTo The string that will be appended with the concatenated elements, separated by the given delimiter. It will remain unchanged, if no elements have been concatenated.
join() [5/8]
std::string crawlservpp::Helper::Strings::join (std::queue< std::string > & strings, char delimiter, bool ignoreEmpty) inline
Concatenates all elements of a queue into a single string.
Note
The queue will be completely emptied in the process, even if elements will be ignored.
Parameters
strings Constant reference to a vector containing the strings to be concatenated.
delimiter A character to be inserted inbetween the concatenated strings.
ignoreEmpty Ignore empty strings when concatenating the given elements.
Returns
The string containing the concatenated elements, separated by the given delimiter, or an empty string if no elements have been concatenated.
join() [6/8]
void crawlservpp::Helper::Strings::join (std::queue< std::string > & strings, char delimiter, bool ignoreEmpty, std::string & appendTo) inline
Concatenates all elements of a queue into a single string.
Note
The queue will be completely emptied in the process, even if elements will be ignored.
Parameters
strings Constant reference to a vector containing the strings to be concatenated.
delimiter A character to be inserted inbetween the concatenated strings.
ignoreEmpty Ignore empty strings when concatenating the given elements.
appendTo The string that will be appended with the concatenated elements, separated by the given delimiter. It will remain unchanged, if no elements have been concatenated.
join() [7/8]
std::string crawlservpp::Helper::Strings::join (std::queue< std::string > & strings, std::string_view delimiter, bool ignoreEmpty) inline
Concatenates all elements of a queue into a single string.
Note
The queue will be completely emptied in the process, even if elements will be ignored.
Parameters
strings Constant reference to a vector containing the strings to be concatenated.
delimiter View of a string to be inserted inbetween the concatenated strings.
ignoreEmpty Ignore empty strings when concatenating the given elements.
Returns
The string containing the concatenated elements, separated by the given delimiter, or an empty string if no elements have been concatenated.
join() [8/8]
void crawlservpp::Helper::Strings::join (std::queue< std::string > & strings, std::string_view delimiter, bool ignoreEmpty, std::string & appendTo) inline
Concatenates all elements of a queue into a single string.
Note
The queue will be completely emptied in the process, even if elements will be ignored.
Parameters
strings Constant reference to a vector containing the strings to be concatenated.
delimiter A view of the string to be inserted inbetween the concatenated strings.
ignoreEmpty Ignore empty strings when concatenating the given elements.
appendTo The string that will be appended with the concatenated elements, separated by the given delimiter. It will remain unchanged, if no elements have been concatenated.
replaceAll()
void crawlservpp::Helper::Strings::replaceAll (std::string & strInOut, std::string_view needle, std::string_view replacement) inline
Replaces all occurences within a string with another string.
Note
No recursive replacement will be performed. Use a while loop for that.
Parameters
strInOut A reference to the string in which the occurences will be replaced.
needle A string view defining the occurence to be replaced.
replacement A string view defining the replacement.
Referenced by crawlservpp::Helper::DateTime::fixFrenchMonths(), crawlservpp::Query::JsonPointer::getAll(), crawlservpp::Query::JsonPointer::getSubSets(), crawlservpp::Query::JsonPointer::JsonPointer(), and utfTidy().
sortAndRemoveDuplicates()
void crawlservpp::Helper::Strings::sortAndRemoveDuplicates (std::vector< std::string > & vectorOfStrings, bool caseSensitive) inline
Sorts the given vector of strings and removes duplicates.
Note
Only ASCII characters are supported when sorting the string. Non-ASCII characters may result in a wrong sorting order.
Parameters
vectorOfStrings Reference to the vector of strings, which will be sorted and from which duplicates will be removed in-situ.
caseSensitive True, if the removal should be performed case-sensitive. False otherwise.
split() [1/2]
std::vector< std::string > crawlservpp::Helper::Strings::split (const std::string & str, char delimiter) inline
Splits a string into a vector of strings using the given delimiter.
Parameters
str A const reference to the string to be split up.
delimiter The character around which the resulting elements will be splitted.
Returns
A new vector containing the splitted elements.
References split().
Referenced by crawlservpp::Main::Database::connect(), and crawlservpp::Helper::Portability::enumLocales().
split() [2/2]
std::vector< std::string > crawlservpp::Helper::Strings::split (std::string_view str, std::string_view delimiter) inline
Splits a string into a vector of strings using the given delimiter.
Parameters
str A const reference to the string to be split up.
delimiter A view of the string around which the resulting elements will be splitted.
Returns
A new vector containing the splitted elements.
Referenced by split(), and splitToQueue().
splitToQueue() [1/2]
std::queue< std::string > crawlservpp::Helper::Strings::splitToQueue (std::string_view str, char delimiter, bool removeEmpty) inline
Splits a string into a queue of strings using the given delimiter.
Parameters
str A const reference to the string to be split up.
delimiter The character around which the resulting elements will be splitted.
removeEmpty Set whether to ignore empty strings and not add them to the resulting queue.
Returns
A new queue containing the splitted elements.
References split().
Referenced by crawlservpp::Wrapper::TidyDoc::cleanAndRepair(), crawlservpp::Wrapper::TidyDoc::getOutput(), crawlservpp::Data::ImportExport::Text::importList(), and crawlservpp::Wrapper::TidyDoc::parse().
splitToQueue() [2/2]
std::queue< std::string > crawlservpp::Helper::Strings::splitToQueue (std::string_view str, std::string_view delimiter, bool removeEmpty) inline
Splits a string into a queue of strings using the given delimiter.
Parameters
str A const reference to the string to be split up.
delimiter A view of the string around which the resulting elements will be splitted.
removeEmpty Set whether to ignore empty strings and not add them to the resulting queue.
Returns
A new queue containing the splitted elements.
stringToBool()
bool crawlservpp::Helper::Strings::stringToBool (std::string inputString) inline
Converts a string into a boolean value.
Only case-insensitive variations of "true" will be converted into true.
Note
In order for the conversion to be case-insensitive, a copy of the given string will be made.
Parameters
inputString The string to be converted into a boolean value.
Returns
True, if the given string represents true. False otherwise.
trim()
void crawlservpp::Helper::Strings::trim (std::string & stringToTrim) inline
Removes whitespaces around a string.
Warning
Only ASCII whitespaces will be processed.
Parameters
stringToTrim Reference to the string to be trimmed in-situ.
See also
utfTidy
Referenced by crawlservpp::Main::Database::cloneTable(), crawlservpp::Main::Database::connect(), crawlservpp::Query::JsonPath::JsonPath(), crawlservpp::Query::JsonPointer::JsonPointer(), crawlservpp::Parsing::URI::parseLink(), and utfTidy().
utfTidy()
void crawlservpp::Helper::Strings::utfTidy (std::string & stringToTidy) inline
Removes new lines and unnecessary spaces, including UTF-8 whitespaces.
Parameters
stringToTidy Reference to the string from which new lines and unnecessary spaces will be removed in-situ.
References replaceAll(), trim(), and utfWhitespaces.
Variable Documentation
checkHexLength
constexpr auto crawlservpp::Helper::Strings::checkHexLength {3} constexpr
Length of a two-digit hexademical number including the preceding percentage sign.
Referenced by encodePercentage().
randCharSet
constexpr auto crawlservpp::Helper::Strings::randCharSet constexpr
Initial value:
{
        "01234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"sv
    }
Characters to be chosen from for random string generation performed by generateRandom().
Referenced by generateRandom().
utfWhitespaces
constexpr std::array crawlservpp::Helper::Strings::utfWhitespaces constexpr
Initial value:
{
        "\u0085"sv,
        "\u00a0"sv,
        "\u1680"sv,
        "\u2000"sv,
        "\u2001"sv,
        "\u2002"sv,
        "\u2003"sv,
        "\u2004"sv,
        "\u2005"sv,
        "\u2006"sv,
        "\u2007"sv,
        "\u2008"sv,
        "\u2009"sv,
        "\u200a"sv,
        "\u2028"sv,
        "\u2029"sv,
        "\u202f"sv,
        "\u205f"sv,
        "\u3000"sv,
    }
UTF-8 whitespaces used by utfTidy().
Referenced by utfTidy().