crawlserv++: crawlservpp::Helper::Utf8 Namespace Reference
crawlservpp::Helper::Utf8 Namespace Reference
Namespace for global UTF-8 encoding functions.
Classes
class Exception
Class for UTF-8 exceptions.
Functions
bool isLastCharValidUtf8 (const std::string &stringToCheck)
Checks the last character (i.e. up to four bytes at the end) of the given string for valid UTF-8.
Constants
constexpr auto utf8MemoryFactor {2}
Factor for guessing the maximum amount of memory used for UTF-8 compared to ISO-8859-1.
constexpr auto bitmaskTopBit {0x80}
Bit mask to extract the first bit of a multibyte character.
constexpr auto bitmaskTopTwoBits {0xc0}
Bit mask to extract the top two bits of a multibyte character.
constexpr auto shiftSixBits {6}
Shift six bits.
constexpr auto bitmaskLastSixBits0b000001 {0x3F}
Bit mask to check the last six bits for 0b000001.
constexpr auto oneByte {1}
One byte.
constexpr auto twoBytes {2}
Two bytes.
constexpr auto threeBytes {3}
Three bytes.
constexpr auto fourBytes {4}
Four bytes.
Conversion
std::string iso88591ToUtf8 (std::string_view strIn)
Converts a string from ISO-8859-1 to UTF-8.
Validation
bool isValidUtf8 (std::string_view stringToCheck, std::string &errTo)
Checks whether a string contains valid UTF-8.
bool isLastCharValidUtf8 (std::string_view stringToCheck)
Repair
bool repairUtf8 (std::string_view strIn, std::string &strOut)
Replaces invalid UTF-8 characters in the given string and returns whether invalid characters occured.
Detailed Description
Namespace for global UTF-8 encoding functions.
Function Documentation
isLastCharValidUtf8() [1/2]
bool crawlservpp::Helper::Utf8::isLastCharValidUtf8 (const std::string & stringToCheck) inline
Checks the last character (i.e. up to four bytes at the end) of the given string for valid UTF-8.
Uses the UTF8-CPP library for UTF-8 validation. See its GitHub repository for more information.
Parameters
stringToCheck Constant reference to the string whose last character will be checked for valid UTF-8.
Returns
True if the last character of the given string is valid UTF-8 or the given string is empty. False otherwise.
References fourBytes, oneByte, threeBytes, and twoBytes.
isLastCharValidUtf8() [2/2]
bool crawlservpp::Helper::Utf8::isLastCharValidUtf8 (std::string_view stringToCheck)
iso88591ToUtf8()
std::string crawlservpp::Helper::Utf8::iso88591ToUtf8 (std::string_view strIn) inline
Converts a string from ISO-8859-1 to UTF-8.
Parameters
strIn View of the string to be converted
Returns
A copy of the converted string.
References bitmaskLastSixBits0b000001, bitmaskTopBit, bitmaskTopTwoBits, shiftSixBits, and utf8MemoryFactor.
Referenced by crawlservpp::Network::Curl::getContent().
isValidUtf8()
bool crawlservpp::Helper::Utf8::isValidUtf8 (std::string_view stringToCheck, std::string & errTo) inline
Checks whether a string contains valid UTF-8.
Uses the UTF8-CPP library for UTF-8 validation. See its GitHub repository for more information.
Parameters
stringToCheck View of the string to check for valid UTF-8.
errTo Reference to a string to which a UTF-8 error will be written.
Returns
True if the given string contains valid UTF-8. False otherwise.
Referenced by crawlservpp::Module::Crawler::Database::urlUtf8Check().
repairUtf8()
bool crawlservpp::Helper::Utf8::repairUtf8 (std::string_view strIn, std::string & strOut) inline
Replaces invalid UTF-8 characters in the given string and returns whether invalid characters occured.
Uses the UTF8-CPP library for UTF-8 validation and replacement. See its GitHub repository for more information.
Parameters
strIn View of the string in which invalid UTF-8 characters will be replaced.
strOut Reference to a string that will be replaced with the resulting string.
Returns
True, if the given string contains invalid UTF-8 characters that have been replaced in the resulting string.
Exceptions
Utf8::Exception if invalid characters could not be replaced.
Referenced by crawlservpp::Network::Curl::getContent(), crawlservpp::Module::Database::log(), and crawlservpp::Main::Database::log().
Variable Documentation
bitmaskLastSixBits0b000001
constexpr auto crawlservpp::Helper::Utf8::bitmaskLastSixBits0b000001 {0x3F} constexpr
Bit mask to check the last six bits for 0b000001.
Referenced by iso88591ToUtf8().
bitmaskTopBit
constexpr auto crawlservpp::Helper::Utf8::bitmaskTopBit {0x80} constexpr
Bit mask to extract the first bit of a multibyte character.
Referenced by iso88591ToUtf8().
bitmaskTopTwoBits
constexpr auto crawlservpp::Helper::Utf8::bitmaskTopTwoBits {0xc0} constexpr
Bit mask to extract the top two bits of a multibyte character.
Referenced by iso88591ToUtf8().
fourBytes
constexpr auto crawlservpp::Helper::Utf8::fourBytes {4} constexpr
Four bytes.
Referenced by isLastCharValidUtf8().
oneByte
constexpr auto crawlservpp::Helper::Utf8::oneByte {1} constexpr
One byte.
Referenced by isLastCharValidUtf8().
shiftSixBits
constexpr auto crawlservpp::Helper::Utf8::shiftSixBits {6} constexpr
Shift six bits.
Referenced by iso88591ToUtf8().
threeBytes
constexpr auto crawlservpp::Helper::Utf8::threeBytes {3} constexpr
Three bytes.
Referenced by isLastCharValidUtf8().
twoBytes
constexpr auto crawlservpp::Helper::Utf8::twoBytes {2} constexpr
Two bytes.
Referenced by isLastCharValidUtf8().
utf8MemoryFactor
constexpr auto crawlservpp::Helper::Utf8::utf8MemoryFactor {2} constexpr
Factor for guessing the maximum amount of memory used for UTF-8 compared to ISO-8859-1.
Referenced by iso88591ToUtf8().