crawlserv++: crawlservpp::Helper::Json Namespace Reference
crawlservpp::Helper::Json Namespace Reference
Namespace for global JSON helper functions.
Classes
class Exception
Class for JSON exceptions.
Constants
constexpr auto unicodeEscapeLength {7}
The length of an escaped Unicode character in JSON code (including the '\u').
constexpr auto unicodeEscapeDigit1 {2}
The offset of the first Unicode character digit in JSON code (from the '\').
constexpr auto unicodeEscapeDigit2 {3}
The offset of the second Unicode character digit in JSON code (from the '\').
constexpr auto unicodeEscapeDigit3 {4}
The offset of the third Unicode character digit in JSON code (from the '\').
constexpr auto unicodeEscapeDigit4 {5}
The offset of the fourth Unicode character digit in JSON code (from the '\').
constexpr auto unicodeEscapeDigit5 {6}
The offset of the fifth Unicode character digit in JSON code (from the '\').
constexpr auto numDebugChars {25}
The number of characters to show before and behind a JSON error.
Stringification
std::string stringify (const std::vector< std::string > &vectorToStringify)
Stringifies a vector of strings into one string containing a JSON array.
std::string stringify (const std::string &stringToStringify)
Converts a string into a JSON array with the string as the only element inside it.
std::string stringify (const std::vector< std::vector< std::pair< std::string, std::string >>> &vectorToStringify)
Converts a vector of vectors of string pairs into a JSON array with corresponding objects containing [key, value] pairs.
std::string stringify (const Struct::TextMap &textMapToStringify)
Converts a text map into a JSON array with corresponding objects containing [key, value] pairs.
std::string stringify (const rapidjson::Value &value)
Stringifies a JSON value using the RapidJSON API.
std::string stringify (const jsoncons::json &json)
Stringifies a JSON value using the jsoncons API.
Parsing
std::string cleanCopy (std::string_view json)
Copies and cleans the given JSON code to prepare it for parsing.
rapidjson::Document parseRapid (std::string_view json)
Parses JSON code using the RapidJSON API.
jsoncons::json parseCons (std::string_view json)
Parses JSON code using the jsoncons API.
Struct::TextMap parseTextMapJson (std::string_view json)
Parses JSON code using the RapidJSON API and converts it into a text map.
Detailed Description
Namespace for global JSON helper functions.
Function Documentation
cleanCopy()
std::string crawlservpp::Helper::Json::cleanCopy (std::string_view json) inline
Copies and cleans the given JSON code to prepare it for parsing.
Removes control characters and corrects escape sequences in the given JSON code.
If the given JSON code is empty, an empty string will be returned.
Note
In standard JSON, allowed escape sequence names are: " \ / b f n r t, as well as u + 4 hex digits.
Parameters
json A string view containing the JSON code to be copied and cleaned.
Returns
A copy of the string containing the cleaned JSON code.
References unicodeEscapeDigit1, unicodeEscapeDigit2, unicodeEscapeDigit3, unicodeEscapeDigit4, unicodeEscapeDigit5, and unicodeEscapeLength.
Referenced by parseCons(), and parseRapid().
parseCons()
jsoncons::json crawlservpp::Helper::Json::parseCons (std::string_view json) inline
Parses JSON code using the jsoncons API.
For more information about the jsoncons API, see its GitHub repository.
Parameters
json A string view containing the JSON code to parse.
Returns
A jsoncons object containing the parsed JSON.
Exceptions
Json::Exception if an error occurs while parsing the given JSON code.
References cleanCopy().
Referenced by crawlservpp::Query::Container::addSubSetsFromQueryOnSubSet(), crawlservpp::Query::Container::getBoolFromQuery(), crawlservpp::Query::Container::getBoolFromQueryOnSubSet(), crawlservpp::Query::Container::getMultiFromQuery(), crawlservpp::Query::Container::getMultiFromQueryOnSubSet(), crawlservpp::Query::Container::getSingleFromQuery(), crawlservpp::Query::Container::getSingleFromQueryOnSubSet(), and crawlservpp::Query::Container::setSubSetsFromQuery().
parseRapid()
rapidjson::Document crawlservpp::Helper::Json::parseRapid (std::string_view json) inline
Parses JSON code using the RapidJSON API.
For more information about the RapidJSON API, see its GitHub repository.
Parameters
json A string view containing the JSON code to parse.
Returns
A RapidJSON document containing the parsed JSON.
Exceptions
Json::Exception if an error occurs while parsing the given JSON code.
References cleanCopy(), and numDebugChars.
Referenced by crawlservpp::Query::Container::addSubSetsFromQueryOnSubSet(), crawlservpp::Main::Database::duplicateWebsite(), crawlservpp::Query::Container::getBoolFromQuery(), crawlservpp::Query::Container::getBoolFromQueryOnSubSet(), crawlservpp::Query::Container::getMultiFromQuery(), crawlservpp::Query::Container::getMultiFromQueryOnSubSet(), crawlservpp::Query::Container::getSingleFromQuery(), crawlservpp::Query::Container::getSingleFromQueryOnSubSet(), crawlservpp::Module::Config::loadConfig(), parseTextMapJson(), crawlservpp::Main::Server::Server(), and crawlservpp::Query::Container::setSubSetsFromQuery().
parseTextMapJson()
Struct::TextMap crawlservpp::Helper::Json::parseTextMapJson (std::string_view json) inline
Parses JSON code using the RapidJSON API and converts it into a text map.
If the given JSON code is empty, an empty text map will be returned.
For more information about the RapidJSON API, see its GitHub repository.
Parameters
json A string view containing the JSON code to be parsed and converted into a text map.
Returns
The text map parsed from the given JSON code.
Exceptions
Json::Exception if the given string view does not contain valid JSON code or the contained JSON code does not describe a valid text map.
See also
parseRapid, Struct::TextMap
References parseRapid().
Referenced by crawlservpp::Module::Analyzer::Database::getCorpus().
stringify() [1/6]
std::string crawlservpp::Helper::Json::stringify (const jsoncons::json & json) inline
Stringifies a JSON value using the jsoncons API.
For more information about the jsoncons API, see its GitHub repository.
Parameters
json The jsoncons value to be stringified.
Returns
A copy of the string containing the representation of the given JSON value.
stringify() [2/6]
std::string crawlservpp::Helper::Json::stringify (const rapidjson::Value & value) inline
Stringifies a JSON value using the RapidJSON API.
For more information about the RapidJSON API, see its GitHub repository.
Parameters
value The RapidJSON value to be stringified.
Returns
A copy of the string containing the representation of the given JSON value.
stringify() [3/6]
std::string crawlservpp::Helper::Json::stringify (const std::string & stringToStringify) inline
Converts a string into a JSON array with the string as the only element inside it.
Uses the rapidJSON API for conversion into JSON. For more information, see its GitHub repository.
Note
A string view cannot be used, because the underlying API requires the const reference to a string.
Parameters
stringToStringify A const reference to the string to be converted into a JSON array.
Returns
The copy of a string containing valid JSON code representing an array containing the given string as its only element.
stringify() [4/6]
std::string crawlservpp::Helper::Json::stringify (const std::vector< std::string > & vectorToStringify) inline
Stringifies a vector of strings into one string containing a JSON array.
Uses the rapidJSON API for conversion into JSON. For more information, see its GitHub repository.
Parameters
vectorToStringify A const reference to the vector of strings to be combined and converted into valid JSON code.
Returns
The copy of a string containing valid JSON code representing an array contining all strings in the given vector
Referenced by crawlservpp::Module::Analyzer::Database::createCorpus(), crawlservpp::Main::Database::duplicateWebsite(), crawlservpp::Query::JsonPointer::getAll(), and crawlservpp::Query::JsonPointer::getFirst().
stringify() [5/6]
std::string crawlservpp::Helper::Json::stringify (const std::vector< std::vector< std::pair< std::string, std::string >>> & vectorToStringify) inline
Converts a vector of vectors of string pairs into a JSON array with corresponding objects containing [key, value] pairs.
Uses the rapidJSON API for conversion into JSON. For more information, see its GitHub repository.
Parameters
vectorToStringify A const reference to the vector containing vectors of string pairs, each of which represents a [key, value] pair.
Returns
The copy of a string containing valid JSON code representing an array of objects containing the given [key, value] pairs.
stringify() [6/6]
std::string crawlservpp::Helper::Json::stringify (const Struct::TextMap & textMapToStringify) inline
Converts a text map into a JSON array with corresponding objects containing [key, value] pairs.
Uses the rapidJSON API for conversion into JSON. For more information, see its GitHub repository.
Parameters
textMapToStringify A const reference to the text map to be represented as [key, value] pairs.
Returns
The copy of a string containing valid JSON code representing an array of objects containing the [key, value] pairs of the text map.
See also
Struct::TextMap, Module::Analyzer::Database::createCorpus
Variable Documentation
numDebugChars
constexpr auto crawlservpp::Helper::Json::numDebugChars {25} constexpr
The number of characters to show before and behind a JSON error.
Referenced by parseRapid().
unicodeEscapeDigit1
constexpr auto crawlservpp::Helper::Json::unicodeEscapeDigit1 {2} constexpr
The offset of the first Unicode character digit in JSON code (from the '\').
Referenced by cleanCopy().
unicodeEscapeDigit2
constexpr auto crawlservpp::Helper::Json::unicodeEscapeDigit2 {3} constexpr
The offset of the second Unicode character digit in JSON code (from the '\').
Referenced by cleanCopy().
unicodeEscapeDigit3
constexpr auto crawlservpp::Helper::Json::unicodeEscapeDigit3 {4} constexpr
The offset of the third Unicode character digit in JSON code (from the '\').
Referenced by cleanCopy().
unicodeEscapeDigit4
constexpr auto crawlservpp::Helper::Json::unicodeEscapeDigit4 {5} constexpr
The offset of the fourth Unicode character digit in JSON code (from the '\').
Referenced by cleanCopy().
unicodeEscapeDigit5
constexpr auto crawlservpp::Helper::Json::unicodeEscapeDigit5 {6} constexpr
The offset of the fifth Unicode character digit in JSON code (from the '\').
Referenced by cleanCopy().
unicodeEscapeLength
constexpr auto crawlservpp::Helper::Json::unicodeEscapeLength {7} constexpr
The length of an escaped Unicode character in JSON code (including the '\u').
Referenced by cleanCopy().