crawlserv++: crawlservpp::Struct::ServerCommandResponse Struct Reference
crawlservpp::Struct::ServerCommandResponse Struct Reference
Response from the command-and-control server.
#include <ServerCommandResponse.hpp>
Properties
bool fail {false}
Indicates whether the server command failed.
bool confirm {false}
Indicates whether the server command needs to be confirmed.
std::string text
The text of the response by the server.
std::uint64_t id {0}
Optional ID returned by the server.
Construction
ServerCommandResponse ()=default
Default constructor.
ServerCommandResponse (const std::string &response)
Constructor initializing a successful response with text.
ServerCommandResponse (const std::string &response, std::uint64_t newId)
Constructor initializing a successful response with text and ID.
ServerCommandResponse (bool failed, bool toBeConfirmed, const std::string &response)
Constructor initializing a possibly failed or possibly to be confirmed response with text.
Helpers
static ServerCommandResponse failed (const std::string &response)
Helper to initialize a "failed" response with text.
static ServerCommandResponse toBeConfirmed (const std::string &response)
Helper to initialize a "to be confirmed" response with text.
Detailed Description
Response from the command-and-control server.
Constructor & Destructor Documentation
ServerCommandResponse() [1/4]
crawlservpp::Struct::ServerCommandResponse::ServerCommandResponse () default
Default constructor.
Referenced by failed(), and toBeConfirmed().
ServerCommandResponse() [2/4]
crawlservpp::Struct::ServerCommandResponse::ServerCommandResponse (const std::string & response) inline explicit
Constructor initializing a successful response with text.
Parameters
response Constant reference to a string containing the text of the server response.
ServerCommandResponse() [3/4]
crawlservpp::Struct::ServerCommandResponse::ServerCommandResponse (const std::string & response, std::uint64_t newId) inline
Constructor initializing a successful response with text and ID.
Parameters
response Constant reference to a string containing the text of the response by the server.
newId The ID to be sent alongside the response by the server.
ServerCommandResponse() [4/4]
crawlservpp::Struct::ServerCommandResponse::ServerCommandResponse (bool failed, bool toBeConfirmed, const std::string & response) inline
Constructor initializing a possibly failed or possibly to be confirmed response with text.
Parameters
failed Set whether the server command failed.
toBeConfirmed Set whether the server command needs to be confirmed.
response Constant reference to a string containing the text of the response by the server.
Member Function Documentation
failed()
static ServerCommandResponse crawlservpp::Struct::ServerCommandResponse::failed (const std::string & response) inline static
Helper to initialize a "failed" response with text.
Parameters
response Constant reference to a string containing the text of the response by the server.
References ServerCommandResponse().
toBeConfirmed()
static ServerCommandResponse crawlservpp::Struct::ServerCommandResponse::toBeConfirmed (const std::string & response) inline static
Helper to initialize a "to be confirmed" response with text.
Parameters
response Constant reference to a string containing the text of the response by the server.
References ServerCommandResponse().
Member Data Documentation
confirm
bool crawlservpp::Struct::ServerCommandResponse::confirm {false}
Indicates whether the server command needs to be confirmed.
fail
bool crawlservpp::Struct::ServerCommandResponse::fail {false}
Indicates whether the server command failed.
id
std::uint64_t crawlservpp::Struct::ServerCommandResponse::id {0}
Optional ID returned by the server.
text
std::string crawlservpp::Struct::ServerCommandResponse::text
The text of the response by the server.
The documentation for this struct was generated from the following file:
Struct/ServerCommandResponse.hpp