language: cpp

matrix: 
 include:

 - name: "GCC7"
   os: linux
   dist: xenial
   env:
     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
   before_install:
     - eval "${MATRIX_EVAL}"
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y g++-7
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

 - name: "GCC6"
   os: linux
   dist: xenial
   env:
     - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
   before_install:
     - eval "${MATRIX_EVAL}"
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y g++-6
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

 - name: "clang7"
   os: linux
   dist: xenial
   env: 
     - MATRIX_EVAL="CC=clang && CXX=clang++"
   before_install:
     - eval "${MATRIX_EVAL}"
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y libstdc++-7-dev
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev
     
 - name: "clang6"
   os: linux
   dist: xenial
   env: 
     - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
   before_install:
     - eval "${MATRIX_EVAL}"
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y clang-6.0
     - sudo apt-get install -y libstdc++-7-dev
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev
     
 - name: "clang5"
   os: linux
   dist: xenial
   env: 
     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
   before_install:
     - eval "${MATRIX_EVAL}"
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y clang-5.0
     - sudo apt-get install -y libstdc++-7-dev
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

script:
- cd crawlserv
- mkdir build
- cd build
- cmake ..
- make VERBOSE=1
- ./crawlserv -v
