language: cpp
matrix: 
 include: 
 - name: "GCC"
   compiler: "gcc-7"
   addons: 
   apt: 
     packages: 
     - gcc-7
     - g++-7
     - cmake
     sources: 
     - ubuntu-toolchain-r-test
   env: 
   - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
   os: linux
   dist: xenial
 - name: "clang"
   compiler: "clang"
   addons: 
   apt: 
    packages:
    - cmake
    sources: 
    - ubuntu-toolchain-r-test
   env: 
   - MATRIX_EVAL="CC=clang && CXX=clang++"
   os: linux
   dist: xenial
before_install:
- eval "${MATRIX_EVAL}"
- sudo apt-get update
- sudo apt-get install -y libpthread-stubs0-dev
- sudo apt-get install -y libboost-system-dev
- sudo apt-get install -y libcurl4-openssl-dev
- sudo apt-get install -y libtidy-dev
- sudo apt-get install -y liburiparser-dev
- sudo apt-get install -y libpugixml-dev
- sudo apt-get install -y libpcre2-dev
- sudo apt-get install -y libmysqlcppconn-dev
- sudo apt-get install -y libaspell-dev
script:
- cd crawlserv
- mkdir build
- cd build
- cmake ..
- make
