language: cpp

matrix: 
 include:
 - name: "GCC9"
   os: linux
   dist: xenial
   env:
     - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
   before_install:
     - eval "${MATRIX_EVAL}"
     - echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo apt-get update -q
     - sudo apt-get install -y gcc-9
     - sudo apt-get install -y g++-9
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

 - name: "GCC8"
   os: linux
   dist: xenial
   env:
     - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"
   before_install:
     - eval "${MATRIX_EVAL}"
     - echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo apt-get update -q
     - sudo apt-get install -y gcc-8
     - sudo apt-get install -y g++-8
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

 - name: "GCC7"
   os: linux
   dist: xenial
   env:
     - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
   before_install:
     - eval "${MATRIX_EVAL}"
     - echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo apt-get update -q
     - sudo apt-get install -y gcc-7
     - sudo apt-get install -y g++-7
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

 - name: "clang9"
   os: linux
   dist: xenial
   env: 
     - MATRIX_EVAL="CC=clang-9 && CXX=clang++-9"
   before_install:
     - eval "${MATRIX_EVAL}"
     - echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
     - deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main
     - deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial main
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y clang-9
     - sudo apt-get install -y libstdc++-7-dev
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

 - name: "clang8"
   os: linux
   dist: xenial
   env: 
     - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"
   before_install:
     - eval "${MATRIX_EVAL}"
     - echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y clang-8
     - sudo apt-get install -y libstdc++-7-dev
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

 - name: "clang7"
   os: linux
   dist: xenial
   env: 
     - MATRIX_EVAL="CC=clang && CXX=clang++"
   before_install:
     - eval "${MATRIX_EVAL}"
     - echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y libstdc++-7-dev
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev
     
 - name: "clang6"
   os: linux
   dist: xenial
   env: 
     - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
   before_install:
     - eval "${MATRIX_EVAL}"
     - echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y clang-6.0
     - sudo apt-get install -y libstdc++-7-dev
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev
     
 - name: "clang5"
   os: linux
   dist: xenial
   env: 
     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
   before_install:
     - eval "${MATRIX_EVAL}"
     - echo "deb http://cz.archive.ubuntu.com/ubuntu focal main universe" | sudo tee -a  /etc/apt/sources.list
     - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
     - sudo add-apt-repository ppa:ondrej/php -y
     - sudo apt-get update -q
     - sudo apt-get install -y clang-5.0
     - sudo apt-get install -y libstdc++-7-dev
     - sudo apt-get install -y cmake
     - sudo apt-get install -y libpthread-stubs0-dev
     - sudo apt-get install -y libboost-iostreams-dev
     - sudo apt-get install -y libboost-system-dev
     - sudo apt-get install -y libcurl4-openssl-dev
     - sudo apt-get install -y libtidy-dev
     - sudo apt-get install -y liburiparser-dev
     - sudo apt-get install -y libpugixml-dev
     - sudo apt-get install -y libpcre2-dev
     - sudo apt-get install -y libmysqlcppconn-dev
     - sudo apt-get install -y libaspell-dev

script:
- cd crawlserv
- mkdir build
- cd build
- cmake ..
- make VERBOSE=1
- ./crawlserv -v
