language: cpp

compiler:
  - clang
  - gcc
 
matrix:
  include:  
- os: linux
    addons:
      apt:
        ubuntu-toolchain-r-test
        packages:
          - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      
- os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
        
before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get update
  - sudo apt-get install -y libpthread-stubs0-dev
  - sudo apt-get install -y libboost-system-dev
  - sudo apt-get install -y libcurl4-openssl-dev
  - sudo apt-get install -y libtidy-dev
  - sudo apt-get install -y liburiparser-dev
  - sudo apt-get install -y libpugixml-dev
  - sudo apt-get install -y libpcre2-dev
  - sudo apt-get install -y libmysqlcppconn-dev
  - sudo apt-get install -y libaspell-dev
